- tools/image-info
> image-info: include partition table id

- internal/weldr/api_test.go
osbuild-composer's tests can be run against lorax-composer's api in order to ensure parity with lorax. This can be accomplished by passing the environment variable LORAX=true into the tests with lorax-composer running on the api socket. Without the environment variable the tests will run as usual against osbuild-composer's api.
> test: run api tests against lorax

- internal/blueprint/ami_output.go
- internal/blueprint/blueprint.go
- internal/blueprint/disk_output.go
- internal/blueprint/ext4_output.go
- internal/blueprint/liveiso_output.go
- internal/blueprint/openstack_output.go
- internal/blueprint/qcow2_output.go
- internal/blueprint/tar_output.go
- internal/blueprint/vhd_output.go
- internal/blueprint/vmdk_output.go
- internal/weldr/api.go
- internal/weldr/store.go
Add basic infrastructure for blueprint to pipeline translations.
> Translate blueprints to pipelines

- internal/rpmmd/repository.go
> Improve error reporting when communicating with dnf-json

- internal/blueprint/pipelines/ami_empty_blueprint.json
- internal/blueprint/pipelines/disk_empty_blueprint.json
- internal/blueprint/pipelines/liveiso_empty_blueprint.json
- internal/blueprint/pipelines/openstack_empty_blueprint.json
- internal/blueprint/pipelines/qcow2_empty_blueprint.json
- internal/blueprint/pipelines/tar_empty_blueprint.json
- internal/blueprint/pipelines/vhd_empty_blueprint.json
- internal/blueprint/pipelines/vmdk_empty_blueprint.json
- internal/blueprint/qcow2_output_test.go
> Add unit tests for blueprint output types

- internal/blueprint/ami_output_test.go
- internal/blueprint/blueprint.go
- internal/blueprint/blueprint_test.go
- internal/blueprint/disk_output_test.go
- internal/blueprint/ext4_output_test.go
- internal/blueprint/liveiso_output_test.go
- internal/blueprint/openstack_output_test.go
- internal/blueprint/pipelines/ext4_empty_blueprint.json
- internal/blueprint/tar_output_test.go
- internal/blueprint/vhd_output_test.go
- internal/blueprint/vmdk_output_test.go
- internal/pipeline/assembler.go
This is a follow up to PR #38.
> More blueprint unittests

- internal/blueprint/ami_output.go
- internal/blueprint/blueprint_test.go
- internal/blueprint/pipelines/ami_empty_blueprint.json
The tests should start passing as soon as #37 lands. (`extf4` typo)
> Adjust AMI output to the Lorax one

- internal/weldr/api_test.go
Not all tests will be compatible with external APIs such as Lorax. When calling testRoute each test now declares if it can run against an external API or not. This change allows us to test against Lorax but skip the cases that will be invalid when not run against osbuild-composer's API.
> tests: specify if each test runs against external API

- internal/blueprint/blueprint.go
- internal/blueprint/customizations.go
- internal/pipeline/chrony_stage.go
- internal/pipeline/firewall_stage.go
- internal/pipeline/groups_stage.go
- internal/pipeline/hostname_stage.go
- internal/pipeline/keymap_stage.go
- internal/pipeline/stage.go
- internal/pipeline/systemd_stage.go
- internal/pipeline/timezone_stage.go
- internal/pipeline/users_stage.go
Code for simpler customizations seems to be done, we need to discuss:
- how to do customization of "initial stages" (grub stage for kernel args customizations, dnf/rpm stage for additional packages)
- how to do testing - we have n output types and m customizations, together n*m options. That's too much. Also, we need some kind of framework, current test solution would be too much messy for testing customizations imo.
> Customizations

- internal/jobqueue/api.go
- internal/jobqueue/api_test.go
- internal/store/store.go
- internal/weldr/api_test.go
Refactor current tests and add the first tests for compose status.
> Weldr tests

- golang-github-osbuild-composer.spec
The version is set to 0 as we haven't release the first version yet.
> Add spec file for building RPM package

- internal/weldr/api_test.go
The compose tests can not check for a valid id or timestamp. The added dropFields function allows specific fields to be removed from an unmarshalled json response body. This allows us to verify the compose tests response by ignoring the id and timestamps.
> Update compose tests to check for valid json response

- internal/blueprint/customizations.go
- internal/crypt/crypt.go
- internal/crypt/crypt_impl.go
- internal/crypt/crypt_test.go
Not sure if I should not just switch to use crypt_gensalt for generating salt. I had wrote my own salt generation function before I decided to embed the c code.
> Plain text passwords

- internal/blueprint/ami_output.go
- internal/blueprint/blueprint.go
- internal/blueprint/disk_output.go
- internal/blueprint/ext4_output.go
- internal/blueprint/liveiso_output.go
- internal/blueprint/openstack_output.go
- internal/blueprint/qcow2_output.go
- internal/blueprint/tar_output.go
- internal/blueprint/vhd_output.go
- internal/blueprint/vmdk_output.go
- internal/store/store.go
- internal/weldr/api.go
I've integrated the customizations with all output types. Some things are still missing that I will add in another PR. Also, I've revisited the error handling in PushCompose handler and improved it.
> Customizations integration

- internal/store/store.go
- internal/weldr/api.go
- internal/weldr/api_test.go
Users can now add their own sources alongside the base repo that osbuild-composer is initialized with. I added CRUD functionality to the store and added routes to the api that add and delete sources. I also updated the list and info routes to include the base repo as well as the user defined sources.
This PR does not use the sources to fetch the package list. The functionality added only effects the source objects.
> Add user defined sources

- LICENSE
> Fill in the license template

- Makefile
- distribution/osbuild-composer.service
- distribution/osbuild-worker@.service
- golang-github-osbuild-composer.spec
See individual commits for details.
> Update spec file to comply with fedora review

- internal/blueprint/blueprint.go
- internal/store/store.go
- internal/weldr/api.go
- internal/weldr/api_test.go
Every update to a blueprint creates a change. Each change contains a commit which is a hex string based off of an sha1 hash of the current time, a message describing the change, a revision which will usually be null, a timestamp, and the blueprint at the time of the change. Even when a blueprint is deleted the list of changes remains and will be updated if a blueprint with the same name is created again.
> Blueprint changes

- internal/store/store.go
- internal/weldr/api.go
Add a route to set a blueprint back to its state at a particular change. The route `blueprints/undo/:blueprint/:commit` requires the blueprint name and the commit hash for the change that the blueprint should be reverted too. Also, the commit message for the change created when a
blueprint is pushed is now passed from the api to the store's PushBlueprint funtion.
> Add blueprint undo route

- cmd/osbuild-composer/main.go
- internal/distro/distro.go
- internal/distro/fedora30/os.go
- internal/distro/test/distro.go
- internal/rpmmd/repository.go
- internal/store/store.go
- internal/weldr/api.go
- internal/weldr/api_test.go
Please see individual commits. I included some cleanup commits before so that my changes don't make the API handlers more complex.
> Get repositories from distro

- internal/weldr/api.go
lorax-composer recently introduced API version 1. This commit introduces
very basic support for it. This implementation tries to deduplicate code
for routes with the same behaviour as much as possible. All the differences of
v1 API are marked as TODOs for now and will be implemented in follow-ups PRs.
> api: add basic support for v1 api

- internal/distro/fedora30/helpers.go
- internal/distro/fedora30/vhd.go
- test/cases/ami_empty_blueprint.json
- test/cases/ami_local_boot.json
- test/cases/disk_empty_blueprint.json
- test/cases/disk_local_boot.json
- test/cases/ext4_empty_blueprint.json
- test/cases/ext4_local_boot.json
- test/cases/openstack_empty_blueprint.json
- test/cases/openstack_local_boot.json
- test/cases/qcow2_empty_blueprint.json
- test/cases/qcow2_local_boot.json
- test/cases/vhd_empty_blueprint.json
- test/cases/vhd_local_boot.json
- test/cases/vmdk_empty_blueprint.json
- test/cases/vmdk_local_boot.json
> Fix alignment for azure images

- .gitignore
- Makefile
- cmd/osbuild-upload-azure/main.go
- go.mod
- go.sum
- golang-github-osbuild-composer.spec
Implementation of image upload functionality for Azure. It is a separate CLI tool for now.
See commit messages for details.
> Azure image upload

- go.mod
- test/cases/ami_empty_blueprint.json
- test/cases/disk_empty_blueprint.json
- test/cases/ext4_empty_blueprint.json
- test/cases/openstack_empty_blueprint.json
- test/cases/qcow2_empty_blueprint.json
- test/cases/vhd_empty_blueprint.json
- test/cases/vmdk_empty_blueprint.json
- tools/image-info
This gets us closer to returning all the properties we support as
customizations.
> image-info: include more properties

- .packit.yaml
> packit test

- cmd/osbuild-upload-azure/main.go
- go.sum
- internal/upload/azure/azure.go
- internal/upload/azure/azure_test.go
The test is very simple, it first upload a file with random content and then downloads it back and compare hashes.
> Introduce Azure upload test

- .gitignore
- Makefile
it makes it possible to use the same workflow as with osbuild
> add makefile targets for rpm build

- internal/store/store.go
- internal/store/store_test.go
- internal/weldr/api_test.go
According to the same rules as lorax-compposer:
https://weldr.io/lorax/lorax-composer.html#blueprints
> weldr: bump blueprint version

- internal/store/store.go
- internal/weldr/api.go
> clean up blueprint getters in store & fix POST /compose behaviour regarding the workspace

- internal/weldr/api.go
- internal/weldr/api_test.go
Not everything is implemented in this route but enough to pass the tests.
> api: implement /compose/info route

- internal/weldr/api.go
- internal/weldr/api_test.go
The implementation is just a stub returning always the same tar archive.
The ability to return actual logs will be implemented in the future - osbuild
isn't currently returning any logs.
> api: implement /compose/logs route

- cmd/osbuild-pipeline/main.go
- internal/distro/distro.go
- internal/distro/distro_test.go
- internal/distro/fedora30/distro.go
- internal/distro/rhel82/distro.go
- internal/distro/test/distro.go
- internal/store/store.go
This is an additional argument on `distro.Pipeline` right now. In the
future, we probably want this per-blueprint.
> distro: insert custom sources into pipeline

- internal/distro/rhel82/distro.go
Based on #162 . 
Changes:
* Kernel parameters are according to the documentation.
* waagent is enabled
I verified that it successfully boots in Azure.
> distro/rhel-8.2: update VHD images to boot in Azure

- internal/weldr/api.go
- internal/weldr/api_test.go
This is what lorax-composer does and composer-cli expects.
> weldr: return version as string from api/status

- internal/distro/fedora30/distro.go
- test/cases/vhd_empty_blueprint.json
Replaces #158 which has a lot of merge conflicts.
> Tweak the Fedora vhd output format to boot in Azure

- README.md
fixes: #146
I included only information about how to install it, not necessarily how to use it as I think it is described in the lorax documentation in more detail.
> update readme to contain slightly more information

- README.md
- docs/osbuild-composer.svg
- internal/common/types.go
- internal/common/types_test.go
- internal/crypt/crypt_impl.go
- internal/crypt/crypt_impl_macos.go
> Documentation and new types for the internal package

- cmd/osbuild-pipeline/main.go
> osbuild-pipeline: Search also the current dir for repository configs

- internal/distro/fedora30/distro.go
- internal/distro/rhel82/distro.go
- internal/upload/awsupload/awsupload.go
- internal/upload/awsupload/awsupload_test.go
I think splitting this into individual commits doesn't add much value as these are very simple fixes. However, I don't have a strong opinion about it.
> fix ineffectual assignments found by golangci-lint

- .gitignore
- Makefile
- repositories/rhel-8.2.json
- test/cases/rhel82_ami.json
- test/cases/rhel82_ext4_filesystem.json
- test/cases/rhel82_groups.json
- test/cases/rhel82_openstack.json
- test/cases/rhel82_partitioned_disk.json
- test/cases/rhel82_qcow2.json
- test/cases/rhel82_tar.json
- test/cases/rhel82_vhd.json
- test/cases/rhel82_vmdk.json
as I dig around and try to find my way through the existing sources.
> Couple of small changes

- internal/compose/compose.go
One bad rebase and one bug fix in compose, see individual commits.
> Fix compose

- internal/distro/distro.go
- internal/jobqueue/api_test.go
- internal/mocks/distro/distro_mock.go
- internal/mocks/rpmmd/fixtures.go
- internal/rcm/api_test.go
Cherry-picked commit 0778ed288186c3835010bcf55694f6cc0b86e95e and fixed a couple remaining issues.
> Fix test failures on master

- README.md
- test/README.md
so that we know how to get started. I've documented only the integration testing portion b/c this is what I've been looking into so far. This is meant as quick start guide, not exhaustive documentation. 
@jikortus, @jrusz FYI
> Add quick README about testing

- .gitignore
- cmd/osbuild-composer/main.go
- distribution/osbuild-rcm.socket
- golang-github-osbuild-composer.spec
fixes #199 
see individual commits for details
> Rcm api socket

- cmd/osbuild-composer/main.go
- cmd/osbuild-pipeline/main.go
- internal/distro/distro.go
- internal/distro/distro_test.go
- internal/distro/fedora30/distro.go
- internal/distro/fedora30/distro_test.go
- internal/distro/fedora31/distro.go
- internal/distro/fedora31/distro_test.go
- internal/distro/fedora32/distro.go
- internal/distro/fedora32/distro_test.go
- internal/distro/rhel81/distro.go
- internal/distro/rhel81/distro_test.go
- internal/distro/rhel82/distro.go
- internal/distro/rhel82/distro_test.go
- internal/jobqueue/api_test.go
- internal/jobqueue/job.go
- internal/mocks/distro/distro_mock.go
- internal/mocks/rpmmd/fixtures.go
- internal/rcm/api_test.go
See individual commits. Tried to follow golang conventions a bit more: renaming a function, returning errors instead of panicking in a library, etc.
> Minor cleanup in distro package

- Makefile
- golang-github-osbuild-composer.spec
- internal/blueprint/blueprint.go
- internal/client/blueprints.go
- internal/client/client.go
- internal/client/client_test.go
- internal/client/json.go
- internal/client/weldr.go
- internal/weldr/api.go
- internal/weldrcheck/blueprints.go
- internal/weldrcheck/check.go
This is a rewrite of the osbuild-test code that was running composer-cli from inside Go. It includes a client library, tests for the library, and integration tests (which I called checks to prevent confusion with the unit tests in _test.go files).
It includes blueprint integration tests, 2 of which fail on osbuild-composer (I'll work on fixing them).
It doesn't currently include a test for the blueprint diff, the osbuild-composer implementation is incomplete and I am unsure how useful diff really is in practice so it currently prints 'SKIP' for it.
Output looks like this with osbuild-composer:
```
[root@composer-rawhide osbuild-composer]# go build -o osbuild-test ./cmd/osbuild-tests/ && ./osbuild-test
2020/02/26 17:55:06 Running API check on /run/weldr/api.socket
2020/02/26 17:55:06 OK: …
```
> osbuild weldr test

- internal/client/client_test.go
- internal/weldrcheck/blueprints.go
#261 was created before the introduction of the linter, therefore it wasn't
approved by it. This commit fixes all the introduced linter violations.
> fix linter errors

- test/README.md
serves as a reference and will also help less experienced folks
> [test] [docs]: Add instructions how to install build-deps in test/README

- Makefile
> Reintroduce make srpm

- .gitignore
- cmd/osbuild-rcm-tests/main.go
> Rcm integration tests

- cmd/osbuild-pipeline/main.go
A developer may want to use the output of rpmmd (build package specs, package specs, and checksums) instead of the pipeline manifest. In this case they may pass the -rpmmd flag to osbuild-pipeline. With this flag, instead of returning the pipeline, it will return the output of rpmmd. This feature is a part of #291.
> osbuild-pipeline: add rpmmd flag and output

- .github/workflows/tests.yml
- .travis.yml
- cmd/osbuild-composer/main.go
- cmd/osbuild-rcm-tests/main.go
This started out looking into fixing the source test, but as Travis is so slow, I decided to move over the tests we can.
> Move more tests from travis to github actions

- internal/distro/fedora30/distro.go
- internal/distro/fedora31/distro.go
- internal/distro/fedora32/distro.go
- internal/distro/rhel81/distro.go
- internal/distro/rhel82/distro.go
- internal/osbuild/rawfs_assembler.go
RootFilesystemUUDI -> RootFilesystemUUID
> Fix typo in RootFilesystemUUID

- internal/common/types.go
- internal/compose/compose.go
- internal/distro/fedora30/distro.go
- internal/distro/fedora30/distro_test.go
- internal/distro/fedora31/distro.go
- internal/distro/fedora31/distro_test.go
- internal/distro/fedora32/distro.go
- internal/distro/fedora32/distro_test.go
- internal/distro/fedoratest/distro.go
- internal/distro/rhel81/distro.go
- internal/distro/rhel81/distro_test.go
- internal/distro/rhel82/distro.go
- internal/distro/rhel82/distro_test.go
- internal/distro/test/distro.go
- internal/weldr/api.go
- internal/weldr/upload.go
After the recent addition of new interfaces to the distro package, drop dead code and do other mechanical cleanups.
> Distro cleanup

- cmd/osbuild-pipeline/main.go
- internal/common/types.go
- internal/distro/distro.go
- internal/distro/fedora30/distro.go
- internal/distro/fedora31/distro.go
- internal/distro/fedora32/distro.go
- internal/distro/fedoratest/distro.go
- internal/distro/rhel81/distro.go
- internal/distro/rhel82/distro.go
- internal/distro/test/distro.go
This completes the interface.
Hook it up to be used by `osbuild-pipeline`.
This is needed by #376.
> Distro: add ListArchs() method

- internal/blueprint/blueprint_test.go
I will be adding more commits to this PR. I'll be happy for any comments. This will fix https://github.com/osbuild/osbuild-composer/issues/362 once ready to merge.
> Add coverage to internal/blueprints

- internal/jobqueue/api.go
- internal/jobqueue/api_test.go
- internal/jobqueue/job.go
- internal/store/store.go
- internal/weldr/api.go
- internal/weldr/api_test.go
Some random cleanups of the store and its interaction with weldr, while I'm continuing to research towards #342.
Hope the commits are self-explanatory.
> Store cleanups

- cmd/osbuild-pipeline/main.go
- cmd/osbuild-worker/main.go
- docs/errors.md
- internal/blueprint/blueprint.go
- internal/distro/fedora30/distro.go
- internal/distro/fedora31/distro.go
- internal/distro/fedora32/distro.go
- internal/distro/rhel81/distro.go
- internal/distro/rhel82/distro.go
- internal/jobqueue/api_test.go
- internal/store/store.go
There was a long discussion about when to `panic` today. I've tried capturing the output in `docs/errors.md`. The idea is to add more rules to this document as we make them.
I've also added a couple of commits that change existing code to use these new rules.
> Document when to panic

- internal/osbuild/fix_bls_stage_test.go
> Add unit test for Fix BLS stage

- internal/osbuild/firewall_stage_test.go
> Add unit test for firewall stage

- internal/osbuild/chrony_stage_test.go
> Add unit tests for chrony stage

- internal/osbuild/fstab_stage_test.go
> Add unit tests for fstab stage

- internal/osbuild/groups_stage_test.go
> Add unit test for groups stage

- internal/osbuild/grub2_stage_test.go
> Add unit test for GRUB2 stage

- cmd/osbuild-rcm-tests/main_test.go
- internal/rcm/api.go
- internal/rcm/api_test.go
See the commits for more details.
> rcm: rework the structure of the compose requests

- internal/osbuild/hostname_stage_test.go
> Add unit test for hostname stage

- internal/osbuild/keymap_stage_test.go
> Add unit test for keymap stage

- internal/osbuild/osbuild_test.go
> Add unit tests for Pipeline struct

- internal/osbuild/locale_stage_test.go
> Add unit test for locale stage

- golang-github-osbuild-composer.spec
- osbuild-composer.spec
Explanation in the commits.
Phew.
> Fix building the tests in mock/koji

- internal/common/compose_result.go
- internal/common/compose_result_test.go
I also changed the structure definition that was there, I hope it still works the same.
Refs #419
> tests: Add coverage for compose_result

- internal/osbuild/rpm_stage_test.go
> Add unit test for RPM stage

- internal/osbuild/users_stage_test.go
> Add unit test for users stage

- internal/osbuild/script_stage_test.go
> Add unit tests for script stage

- internal/osbuild/timezone_stage_test.go
> Add unit test for timezone stage

- internal/osbuild/selinux_stage_test.go
> Add unit tests for SELinux stage

- internal/jobqueue/api_test.go
- internal/rcm/api.go
- internal/store/store.go
- internal/weldr/api.go
These fell out of work I'm doing on another branch. Makes sense to get them in separately to no make the other one too large.
> store: some random cleanups around PushCompose()

- internal/osbuild/systemd_stage_test.go
> Add unit test for systemd stage

- internal/upload/awsupload/awsupload.go
Previously the s3 object was just left on s3 after the upload had finished. However, the object is not needed anymore after an ec2 snapshot is imported from the object. I think this is wrong from the customers' perspective. I think they would not anticipate that we leave not needed s3 objects after upload.
The s3 key can be currently used using the weldr api. However, the `key` field is currently not used by cockpit-composer. When the field isn't set, osbuild-composer uses the compose id as a key. That's however not ideal, because we soon will be able to upload more images for one compose.
Let's discuss how lorax does it: Lorax does remove the s3 object after upload. Also, it doesn't the `key` object in its API, the key is always this: `{{ image_name }}-{{ image_stat['stat']['checksum'] …
> upload/aws: delete the s3 object after the snapshot is imported

- jenkins/run_tests.sh
Run the dnf integration tests with every pull request.
> 💃 Add dnf integration tests

- internal/client/source_test.go
- internal/client/unit_test.go
Between the existing sanity tests and this PR the behavior documented in #315 is covered.
> Add source tests for deleting user-defined & system wide repositories

- jenkins/run_tests.sh
> 🤏 Little bit more testing: osbuild-tests

- jenkins/run_tests.sh
> 🤏 Little bit more testing: weldr-tests

- .github/workflows/tests.yml
We added this to osbuild but it was never added to osbuild-composer.
[skip ci]
> 📦 Use prepared containers

- README.md
> 📜 Add PR gating docs

- internal/osbuild/qemu_assembler.go
> introduce support for partuuid

- jenkins/run_tests.sh
We may be able to shorten test time by running some tests
simultaneously.
> 🦥 Try running some integration tests together

- internal/client/client_test.go
I am seeing an error when executing this as an integration test but I think it is not related to the changes I made here.
With this PR I see:
```
--- FAIL: TestRequest (0.00s)
client_test.go:26: 
Error Trace:	client_test.go:26
Error:      	Received unexpected error:
unexpected end of JSON input
Test:       	TestRequest
```
with master I see
```
--- FAIL: TestRequest (0.00s)
client_test.go:35: apiError could not parse the response: unexpected end of JSON input
```
> tests: Use the require package

- cmd/osbuild-image-tests/main_test.go
This commits enables the parallelism for the image tests. However, there's a catch. Osbuild cannot be reliably run in parallel, so the code uses a mutex to ensure there's always only one osbuild instance for now. Even with this limitation, there's a significant speed-up of the tests:
Prior this commit, the image tests run in 40 minutes on Travis. After this commit, the time is reduced to 32 minutes.
The speed-up will have an even bigger effect when more cloud-upload tests are added to the test suite.
/cc @major
> tests/image: run the tests in parallel (somewhat)

- internal/distro/distro_test.go
- internal/distro/distro_test_common/distro_test_common.go
- internal/distro/fedora30/distro_test.go
Just pushing what I currently have for comments. Not sure if it's not overcomplicated (`TestImageType_Name`) or not too little inclusive (`TestImageType_Size`). But maybe I've just been staring into the code for too long :-).
Refs: #442
> Improve coverage for distro packages - F30

- jenkins/test.yml
- jenkins/test_runner_image.yml
- jenkins/vars.yml
Pass all of the image test cases directly to the test runner to speed
up the image test process.
> 🚚 Run image build test cases together

- golang-github-osbuild-composer.spec
- osbuild-composer.spec
See both commits. I tested this using a copr repo and it seems to fix all the warnings.
> Fix systemd warnings during a package removal/upgrade

- Makefile
> Random Makefile fixes releated to the release process

- cmd/osbuild-worker/main.go
- internal/target/azure_target.go
- internal/upload/azure/azure.go
- internal/weldr/upload.go
All the bits and pieces were already there, it was just needed to connect them in the worker. Also, I did some small clean-ups.
> Add a support to upload to Azure

- internal/distro/fedora30/distro_test.go
Just a small improvement to keep things consistent (as a follow-up to code review in #546).
> Use assert.NoError in F30 distro test

- internal/client/blueprints_test.go
- internal/client/compose.go
- internal/client/compose_test.go
- internal/weldr/api.go
- internal/weldr/api_test.go
> Add blueprint name validation

- cmd/osbuild-image-tests/context-managers.go
RHEL 8 doesn't have qemu-system-x86_64 in PATH. Instead, it is in `/usr/libexec/qemu-kvm`. This commit fixes that by detecting the host distro and choosing the right binary.
~I think I will do a small cleanup before the merge, I just need to test if this helps, therefore marking is a draft.~ Done
> test/images: fix running the tests on rhel

- schutzbot/Jenkinsfile
Run the base and image tests on RHEL 8.2. 🚂
> Add RHEL 8.2 testing

- .github/koji.conf
- .github/workflows/tests.yml
- cmd/osbuild-koji/main.go
- go.mod
- go.sum
- internal/upload/koji/README.md
- internal/upload/koji/koji.go
- internal/upload/koji/koji_test.go
- internal/upload/koji/run-koji-container.sh
- vendor/github.com/kolo/xmlrpc/LICENSE
- vendor/github.com/kolo/xmlrpc/README.md
- vendor/github.com/kolo/xmlrpc/client.go
- vendor/github.com/kolo/xmlrpc/decoder.go
- vendor/github.com/kolo/xmlrpc/encoder.go
- vendor/github.com/kolo/xmlrpc/request.go
- vendor/github.com/kolo/xmlrpc/response.go
- vendor/github.com/kolo/xmlrpc/test_server.rb
- vendor/modules.txt
Currently, only password auth is supported and it is hooked up to `osbuild-composer`. But the test and the container should be fully functional.
Based on #149
> Add helpers to upload to Koji

- Makefile
- NEWS.md
- golang-github-osbuild-composer.spec
- osbuild-composer.spec
Minor bits changed, see the individual commits.
> Pre release cleanups

- internal/distro/fedora32/distro.go
- internal/distro/rhel8/distro.go
- internal/distro/rhel8/distro_test.go
See commits for details.
This fixes #665.
> rhel8: add preliminary ppc64le and s390x support

- CONTRIBUTING.md
The CONTRIBUTING.MD was very useful. In this commit I'm suggesting
a couple changes that I had to make to get it to work. Hope it
helps.
> CONTRIBUTING: Tweak documentation for new contributors

- internal/upload/awsupload/awsupload.go
The AWS upload process takes a while to complete and can sometimes have
errors. By adding additional logging, users can see what has already
happened and they will have data available, such as snapshot import task
IDs, that they can use to check on status at AWS.
> Add logging for AWS upload tasks

- cmd/osbuild-tests/main_test.go
- internal/client/source.go
- internal/client/source_test.go
- internal/store/store.go
- internal/weldr/api.go
- internal/weldr/json.go
> Add API v1 support to projects/source route

- internal/test/helpers.go
- internal/weldr/api.go
- internal/weldr/api_test.go
This is needed for lorax parity. When multiple blueprints are being frozen in
toml mode, the API returns an error. This is the same behaviour as in the
/blueprints/info route.
Fixes #667
> weldr: add support for toml format in /blueprints/freeze

- schutzbot/Jenkinsfile
- schutzbot/ci_details.sh
Dump the machine specs for the system running the CI job very early
during the job run.
> Add CI details script

- internal/upload/awsupload/awsupload.go
Now that we know emojis work properly with osbuild-composer and systemd,
let's add some more.
> Add more emojis to AWS upload logs

- internal/distro/fedora31/distro.go
- internal/distro/fedora32/distro.go
- internal/distro/rhel8/distro.go
- internal/osbuild/assembler_test.go
- internal/osbuild/qemu_assembler.go
see commit messages for more info
> osbuild: update qemu assembler to match osbuild schema better

- cmd/osbuild-tests/main_test.go
This is based on #662, but rebased to pick up fixes. Added one trivial patch on top.
> Rename functions in sanity test

- schutzbot/Jenkinsfile
- schutzbot/run_base_tests.sh
Simplify the base test runner and make it easier to see the output live.
> Convert base test runner to bash

- schutzbot/Jenkinsfile
- schutzbot/run_image_tests.sh
Simplify the image tests with bash and allow the output to appear live
in the Jenkins interface.
> Convert image tests to bash

- cmd/osbuild-worker/main.go
When osbuild-composer crashed, it left temporary directories in
`/var/cache`. Use `/var/tmp` for these output directories, because
systemd will clean these up (we set PrivateTmp=true).
Also, put the store into `/var/cache/osbuild-store`. The worker does not
checkpoint anything. The store is only used as a cache for rpms. That
can be shared between multiple workers and successive runs of a single
worker.
> osbuild-worker: don't use /var/cache for temporary directories

- test/image-tests/aws.sh
- test/image-tests/qemu.sh
Perhaps my ability to copy and paste code should be taken away. 🤦🏻‍♂️
> CI: Fix copy/paste errors in log gathering

- schutzbot/deploy.sh
Reduce CI failures by trying to install osbuild-composer-tests five
times.
Fixes #784
> CI: Retry osbuild-composer-tests installation

- schutzbot/run_image_tests.sh
List the image tests that match the distro, distro version, and architecture before running image tests. That ensures we run all of the tests that are appropriate for the distro/version/arch combination.
Tests can be added or removed without changing the `run_image_tests.sh` script.
Fixes #840.
This also gets us a little closer on #834 since we select the right tests based on architecture, too.
> 🔎 Dynamically choose image test list

- cmd/osbuild-image-tests/main_test.go
Running tests in parallel is not stable under all conditions, this commit
removes it to make the tests more reliable.
This reverts commit e890e03d
> Revert "tests/image: run the tests in parallel (somewhat)"

- schutzbot/Jenkinsfile
Jenkins needs to know which node to use to send the telegram
notification.
> Fix post-build telegram notification

- schutzbot/mockbuild.sh
Allow anyone to set up a dnf repository to point to the latest build for the branch by using a repo file pointing to that build.
This would allow anyone to get the latest set of RPMs for a particular pull request or branch (especially the master branch.
> 📦 mockbuild: Create 'latest' repo for branch

- internal/store/json_test.go
Here are tests for about half the functions in json.go, will be adding more tomorrow but this PR can stand on it's own.
> Tests for store/json.go

- cmd/osbuild-worker/main.go
- cmd/osbuild-worker/osbuild.go
- internal/osbuild/result.go
- internal/osbuild/result_test.go
- internal/osbuild/rpm_stage.go
- internal/weldr/api.go
- internal/worker/client.go
- internal/worker/json.go
Parse the metadata about the RPM stage as returned from osbuild.
> osbuild: rpm metadata

- internal/kojiapi/server.go
- internal/worker/server.go
When remote worker socket was enabled, this was happening:
```
e := echo.New()
go func() {
e.Listener = listener1
e.Start("")
}()
e.Listener = listener2
e.Start("")
```
Yeah, this is a race condition. None of the echo's Start methods cannot safely
handle multiple listeners.
This commit fixes this issue by using Echo only as a router for standard
`http.Server` which handles multiple listeners in a non-racy way.
> api/worker, koji: fix race condition when using multiple listeners

- schutzbot/Jenkinsfile
- schutzbot/run_base_tests.sh
- schutzbot/run_image_tests.sh
> Start using aws creds for osbuild-image-tests

- HACKING.md
- tools/deploy/test/user-data.yml
Also add a comment to tools/deploy/test/user-data explaining where the
IP comes from.
> HACKING.md: clarify details about the spawned VM

- cmd/cloud-cleaner/main.go
- osbuild-composer.spec
- schutzbot/Jenkinsfile
- schutzbot/run_cloud_cleaner.sh
> Introduce cloud cleaner

- osbuild-composer.spec
- test/cmd/koji.sh
And use it from its installed location in test/cmd/koji.sh.
> test: install koji-compose.py

- .github/PULL_REQUEST_TEMPLATE.md
- test/README.md
Add instructions for downstream testing and notes explaining some changes to the PR process. The included PR template will look like this:
**Downstream testing notes:**
> Document downstream testing process

- osbuild-composer.spec
Trust me, it's not very useful.
> spec: remove executable bit from certificates

- cmd/osbuild-worker/main.go
- cmd/osbuild-worker/main_test.go
- internal/upload/koji/koji.go
> Assorted fixes for Koji

- NEWS.md
- osbuild-composer.spec
- schutzbot/Jenkinsfile
- schutzbot/mockbuild.sh
- test/cases/ostree.sh
I had to prepend two commits removing RHEL 8.3 pipeline from Schutzbot because it got removed from beta CDN. Otherwise, this is just another awesome release!
> Release version 23

- internal/kojiapi/api/api.gen.go
- internal/kojiapi/api/openapi.yml
- internal/kojiapi/server.go
- internal/kojiapi/server_test.go
- tools/koji-compose.py
opening draft PR for koji logs API route and new tests
> koji: add logs API route

- .github/workflows/tests.yml
- Makefile
- schutzbot/Jenkinsfile
- test/cases/image_tests.sh
I've pushed `osbuild-composer`'s main branch (exact copy of master). Once this lands, I'll switch the default branch to `main`.
> master → main

- cmd/osbuild-worker/osbuild.go
osbuild output should be always JSON-parsable. However, if a user has a weird installation of osbuild, it can return malformed JSON. In this case, it's very hard to debug what happened because the worker doesn't provide any useful information. This commit adds the non-parsable osbuild output to the error so there's at least some clue in the logs what happened.
Let me reiterate: In 99% of these cases, this shouldn't be needed. It will give us some hints in these 1% cases though.
You may want to ask if using `json.Decoder` isn't better because it doesn't buffer the input. However, it does buffer. Firstly, `json.Decoder.Decode()` buffers the whole JSON value (it contains kinda cool state machine to do it) and in the second run, it parses the buffer. Therefore, the only thing that this commit …
> worker/osbuild: print raw osbuild output if it cannot be parsed

- internal/test/helpers.go
test.API is actually just http.Handler, let's use this interface directly instead of defining our own one
> internal/test: remove redundant API interface

- cmd/osbuild-worker/jobimpl-koji-finalize.go
Previously, the checks that dependencies were successful were all over the Run() method. This led to a issue #1101 (lovely binary number btw).
This commit rewrites the Run() method to:
1) Extract dynamic args. Return an error if they cannot be unmarshalled.
2) Check if dependencies were successful. If not, call kojiFail, update the job and return.
3) Create the CGImport metadata and call kojiImport.
Fixes #1101
> worker/koji-finalize: check the dependencies early

- cmd/osbuild-upload-aws/main.go
- cmd/osbuild-worker/jobimpl-osbuild.go
- internal/boot/aws.go
- internal/cloudapi/openapi.gen.go
- internal/cloudapi/openapi.yml
- internal/cloudapi/server.go
- internal/target/aws_target.go
- internal/upload/awsupload/awsupload.go
- schutzbot/Jenkinsfile
- test/cases/api.sh
Share an ec2 snapshot and ami with other aws accounts.
> cloudapi: Share an ec2 snapshot/ami with an account

- internal/distro/rhel84/distro.go
Hybrid boot, i.e. MBR+UEFI, is only supported on X86_64, but not on aarch64, which only supports UEFI. Therefore, disable legacy, i.e. MBR, boot for aarch64 and remove the corresponding BIOS boot partition.
Since hybrid boot is always used on X86_64, the "uefi" parameter is removed completely, together with the "legacy only" option on X86_64. Thus we are left with a simple one to one mapping of architecture to qemu assembler stage options in `qemuAssembler`.
> distro/rhel84: no hybrid boot on aarch64

- Schutzfile
> schutzfile: bump koji-osbuild

- containers/osbuild-composer/Dockerfile
- containers/osbuild-composer/entrypoint.py
- osbuild-composer.spec
- schutzbot/Jenkinsfile
- schutzbot/containerbuild.sh
Build ubi8 containers in CI. This requires some preliminary changes, see individual commits for details.
> containers: add ubi8 container

- internal/weldr/api.go
- internal/weldr/api_test.go
> Test undo and fix error returned when undoing unknown commit

- internal/weldr/api.go
- internal/weldr/api_test.go
> Clear up confusing source TOML support

- .github/workflows/tests.yml
- schutzbot/send_webhook.py
> ⚡ Trigger schutzbot using github actions

- test/cases/libvirt.sh
makes it easier to find in the results log
> tests: Add info log message for UEFI boot

- test/cases/api.sh
> test: Let the composer-api testcase also boot the image in aws

- schutzbot/Jenkinsfile
> Schutzbot: ping on nightly test results

- schutzbot/Jenkinsfile
> schutzbot: add mockbuild for Fedora 34

- Schutzfile
- schutzbot/Jenkinsfile
See individual commits.
Just CI changes.
> Remove osbuild overrides & move koji-osbuild test to F33 

- internal/boot/openstacktest/openstack.go
The openstack boot test often ruins our days with:
```
Waiting for instance 63ac19be-2e19-44e2-8bef-9770d68a190c to become Active failed: A timeout occurred
```
I decided to investigate. It turns out the first boot of an image can take
up to 18 minutes. The subsequent ones are usually much faster (but don't rely
on this fact, I saw 15 minutes there).
This commit bumps the timeout to 30 minutes. This should be plenty of time
for the instance to spin up and get into the ACTIVE state.
Honestly, I'm not very happy with the solution but it should help with the
failing Schutzbot. As a follow-up, I will reach to the PSI OpenStack team
and ask them if we could somehow speed up the process (maybe by using another
flavor, ci.m1.medium.ephemeral just might be slow for some reason, I don't
know). …
> test/openstack: increase timeout for the instance to become ACTIVE

- schutzbot/mockbuild.sh
see https://github.com/rpm-software-management/mock/commit/75cd9eb52df899d40ae7d82ceb96146bf61bdc88
> schutzbot: Rename centos stream mock config

- schutzbot/mockbuild.sh
Mockbuild using systemd-nspawn currently fails on Fedora 34. The
workaround is to use "simple" isolation method - the traditional
chroot() call.
Reported as: https://bugzilla.redhat.com/show_bug.cgi?id=1931452
- This is a workaround for distribution issue on the CI system. No new tests were added.
- Not a user-visible change, therefore no documentation was added.
> schutzbot: Work around mock RHBZ#1931452 on F34

- test/cases/api.sh
Extend the Cloud API integration test for GCP to also create a Compute
Node instance using the image, boot it and ssh to it. This brings the
GCP integration testing on par with AWS testing.
Use VHD image type for GCP integration testing, because it by default
contains `cloud-init` installed, unlike the VMDK image.
- only new testing has been added
- change not visible to users
> tests: boot imported image as part of GCP cloudapi test

- cmd/osbuild-image-tests/main_test.go
Previously, the test merged stderr and stderr and treated it as json. This was
obviously wrong. osbuild's stderr only returns python exceptions that are
of course not json.
The behaviour is now different:
1) stderr and stdout are treated separately
2) json from stdout is indented to prevent long lines. If it fails the test
just prints the stdout as returned from osbuild.
3) stderr is printed as returned from osbuild
just test improvements
> test/image: improve logging of failed osbuild execution

- cmd/osbuild-worker/jobimpl-osbuild.go
- schutzbot/Jenkinsfile
> Change Azure test location to eastus & log target errors in worker

- internal/weldr/api.go
- internal/weldr/api_test.go
> Add test=X support to ostree compose, with tests.

- cmd/osbuild-composer/composer.go
- cmd/osbuild-pipeline/main.go
- internal/cloudapi/server.go
- internal/distro/distro.go
- internal/distro/distro_test.go
- internal/distro/distro_test_common/distro_test_common.go
- internal/distro/fedora32/distro_test.go
- internal/distro/fedora33/distro_test.go
- internal/distro/rhel8/distro_test.go
- internal/distro/rhel84/distro_test.go
- internal/distroregistry/distroregistry.go
- internal/distroregistry/distroregistry_test.go
- internal/kojiapi/server.go
- internal/mocks/distro/distro_mock.go
I made several changes to simplify the process of adding a new distribution, see individual commits for a deeper explanation.
> Refactor distro registry to simplify the process of adding a new distro

- Schutzfile
- schutzbot/Jenkinsfile
- test/cases/image_tests.sh
- test/data/manifests/centos_8-aarch64-ami-boot.json
Opening again to see if we get different results than in #1229 (a nightly repo file seems to be lurking around on the filesystem and is messing up everything).
> Schutzbot: Start building on aarch64 for RHEL/CentOS

- schutzbot/prepare-rhel-internal.sh
> [8.4] schutzbot: Fix wrong COMPOSE_ID URL

- schutzbot/prepare-rhel-internal.sh
> schutzbot: Fix wrong COMPOSE_ID URL

- test/cases/api.sh
- test/cases/aws.sh
> tests: install awscli from EPEL. Fix #1037

- internal/osbuild1/result.go
A result from manifest v2 contains logs from pipelines. The individual
pipelines are stored as an object, thus they have no order. Well, at least
in Go, because it doesn't guarantee one when parsing maps, see:
https://github.com/golang/go/issues/27179
Unfortunately, this makes the Result.fromV2 method return unpredictable
results because the pipeline results are processed in basically a random
order.
This caused the TestUnmarshalV2Failure test (result_test.go:124) to randomly
fail because it expects the ordering to be stable. I decided to fix this by
ordering the pipeline results by their name. When this fix is applied, the
output from Result.fromV2 is well-defined.
> osbuild1: make the conversion from v2 result stable

- cmd/osbuild-store-dump/main.go
- internal/store/compose.go
- internal/store/fixtures.go
- internal/store/json.go
- internal/store/json_test.go
- internal/store/store.go
- internal/store/store_test.go
- internal/weldr/api.go
- internal/weldr/api_test.go
> Main compose packagesets

- docs/news/unreleased/ostree-ref-handling.md
- internal/weldr/api.go
- internal/weldr/api_test.go
- test/cases/ostree-ng.sh
Cherry picked #1329 for RHEL 8.4.
Planned for z-stream. [rhbz#1951192](https://bugzilla.redhat.com/show_bug.cgi?id=1951192)
> [rhel-8.4.0] ostree url parsing

- internal/osbuild1/result.go
Cherry picked #1330 for RHEL 8.4.
Issue causes tests to fail probabilistically (albeit rarely).
We should add this to the z-stream release to avoid issues with gating.
> [rhel-8.4.0] osbuild1: make the conversion from v2 result stable

- test/README.md
because we're expecting to onboard other people as well and we need
to start keeping track of this.
@jrusz, @henrywang, @yuxisun1217 please help me define/refine your responsibilities better!
> tests: Define who's responsible for what on the team

- distribution/osbuild-composer-clouddot-template.yml
This is just an initial template, there will be some followups.
> distribution: Add OCP template for clouddot

- internal/cloud/gcp/compute.go
The GCP image import method currently use the Cloud Build API with Google's Daisy workflow. This workflow creates multiple GCE resources during its execution. Although the desired Region for the imported image is specified as a workflow argument, this has no effect on the GCE Zone used by the workflow for created resources. By default it seems to default to "us-central1-a" Zone. As a result, there are common cases of resources being exhausted in the default zone.
Add a method, which translates provided Google Storage Region to a GCE Region, which is needed mainly for multi and dual Storage Regions. Note that the status of the Region is not checked by the function as this would require a logic to handle situations when the API caller specified a Region, which is DOWN in the first place. …
> GCP: Specify and randomize GCE region used for image import

- osbuild-composer.spec
- schutzbot/Jenkinsfile
- test/cases/azure.sh
- test/data/azure/main.tf
> Enable testing of images in Azure using terraform

- test/README.md
Signed-off-by: Yuxin Sun <yuxisun@redhat.com>
> Update yuxisun responsibility

- .gitlab-ci.yml
- schutzbot/Jenkinsfile
- schutzbot/run_cloud_cleaner.sh
- test/cases/api.sh
- test/cases/aws.sh
- test/cases/azure.sh
- test/cases/image_tests.sh
- test/cases/koji.sh
- test/cases/libvirt.sh
- tools/libvirt_test.sh
> [POC] Run integration tests in gitlab ci

- distribution/osbuild-composer-clouddot-template.yml
This should become a PersistentVolumeClaim in future, but let's get the
deployment running first.
> distribution: Add state directory

- .github/workflows/tests.yml
- .gitlab-ci.yml
- test/cases/api.sh
- test/cases/vmware.sh
> GitLab CI: Add GCP &Vmware tests

- README.md
> readme: add IRC

- tools/deploy-qemu
The discussion about Bash syntax have reached the threshold where it is
necessary to rewrite the script in Python to make everyone's life
easier.
> deploy-qemu: rewrite in python

- internal/osbuild1/rpm_ostree_stage.go
Just a drive by commit while I was reading the code.
> rpm_ostree_stage: Minor fixes to comments

- test/cases/api.sh
Signed-off-by: Yuxin Sun <yuxisun@redhat.com>
> Add subscription test case and Azure boot up case

- .gitlab-ci.yml
- internal/distro/rhel84/distro_v2.go
- internal/distro/rhel85/distro.go
- internal/distro/rhel85/distro_test.go
- internal/distro/rhel85/package_sets.go
- internal/distro/rhel85/pipelines.go
- internal/distro/rhel85/stage_options.go
- internal/osbuild2/kickstart_stage.go
- internal/rpmmd/repository.go
- internal/store/json.go
- test/cases/installers.sh
- test/data/ansible/check_install.yaml
- test/data/manifests/rhel_85-x86_64-edge_commit-boot.json
- test/data/manifests/rhel_85-x86_64-edge_commit_rt-boot.json
- test/data/manifests/rhel_85-x86_64-edge_container-boot.json
- test/data/manifests/rhel_85-x86_64-tar-boot.json
Implements a `tar-installer`: an installer image that embeds an OS tarball (same as the `tar` image type) that's installed when the ISO is booted.
I had this implemented and ready for a while based on #1351.  Rebased now on #1391.  Opening now for early review but keeping as a draft until we #1391 is merged and to add tests.
> RHEL 8.5: tar installer

- internal/common/states.go
- internal/weldr/api.go
- small typo in code comments for the weldr api
- Fix unused argument in `unmarshalStateHelper` function in the `common` module
> Minor fix for common module

- .gitlab-ci.yml
- schutzbot/slack_notification.sh
- tools/define-compose-url.sh
Trying out how slack notifications about nightly pipeline execution could work.
> ci: add slack notifications

- .gitlab-ci.yml
- test/cases/azure.sh
Fixing some oversights from my previous PRs.
> Minor fixes for test/ci

- internal/cloudapi/server.go
- test/cases/api.sh
Previously a bad error code was returned, solves #1477.
> CloudAPI: Invalid package set returns 400

- internal/cloudapi/openapi.gen.go
- internal/cloudapi/openapi.yml
- internal/cloudapi/server.go
- test/cases/api.sh
> cloudapi: Add User customization

- .gitlab-ci.yml
Still WIP b/c of the many missing image types in 8.5
> CI: Enable aarch64 test runners

- internal/cloudapi/server.go
Add an echo.Binder() to simplify parsing the compose request body.
> cloudapi: create binder

- test/cases/api.sh
> Tests: Malformed JSON duplicate customization

- cmd/osbuild-image-tests/main_test.go
Previously, we just assumed that all test manifests are of version 1, or we
should export the pipeline named assembler. However, this is no longer true
in RHEL 8.5 and 9 - they are only manifest v2 and they don't have a pipeline
named assembler.
This commit introduces a new way to guess the export name - if the manifest
is of version 1, we just export the assembler. In the case v2 manifest, the
last pipeline is exported.
> test/image: fix pipeline exports for v2 manifests

- .gitlab-ci.yml
- docs/news/unreleased/rhel8.5-filesystem-support.md
- internal/disk/customizations.go
- internal/disk/disk.go
- internal/disk/disk_test.go
- internal/distro/distro.go
- internal/distro/rhel85/distro.go
- internal/distro/rhel85/distro_test.go
- internal/distro/rhel85/partition_tables.go
- internal/distro/rhel85/pipelines.go
- test/cases/filesystem.sh
- test/data/manifests/rhel_85-aarch64-qcow2-customize.json
- test/data/manifests/rhel_85-ppc64le-qcow2-customize.json
- test/data/manifests/rhel_85-s390x-qcow2-customize.json
- test/data/manifests/rhel_85-x86_64-qcow2-customize.json
- tools/test-case-generators/generate-test-cases
- implementation for file system partitions for RHEL 8.5
> Filesystem implementation

- docs/news/unreleased/rhel9.0-filesystem-support.md
- internal/distro/distro.go
- internal/distro/rhel85/distro.go
- internal/distro/rhel85/partition_tables.go
- internal/distro/rhel90/distro.go
- internal/distro/rhel90/distro_test.go
- internal/distro/rhel90/partition_tables.go
- internal/distro/rhel90/pipelines.go
- test/cases/filesystem.sh
- test/data/manifests/rhel_90-aarch64-qcow2-customize.json
- test/data/manifests/rhel_90-ppc64le-qcow2-customize.json
- test/data/manifests/rhel_90-s390x-qcow2-customize.json
- test/data/manifests/rhel_90-x86_64-qcow2-customize.json
- tools/test-case-generators/generate-test-cases
Add support for RHEL9.0 file customisations.
> RHEL9 filesystem customizations

- internal/cloudapi/server.go
Change instances of panic on error to return StatusInternalServerError
instead. Additionally change return code 200s to http.StatusOK.
Fixes #1606
> cloudapi: rework return values

- test/cases/ostree-raw-image.sh
Added test case of bios testing for edge-raw-image.
> add bios test for raw image

- internal/cloudapi/server.go
Fixes a bad formatting of the error in the cloudapi.
> cloudapi: format error string in the depsolving

- .gitlab-ci.yml
- test/cases/aws.sh
- test/cases/azure.sh
Should fix issues with aws.sh and azure.sh for RHEL-9.
> Rhel 9 aws azure updates

- .packit.yaml
This is based on the packit configuration of osbuild.
> Add support for packit

- .github/dependabot.yml
> Disable automatic rebase for Dependabot

- internal/distro/rhel85/pipelines.go
- test/data/ansible/check_ostree.yaml
This PR fixes https://github.com/osbuild/osbuild-composer/issues/1701
> internal/distro/rhel85: move systemd logs kargs to the installer image

- test/cases/vmware.sh
These changes enable the use of weldr-client with the test and also
there was a need to change the vm.create command a little bit. Without
the increased CPU and RAM RHEL-9 would not boot and a network adapter
had to be specified to use a newer one because the default one does not
work with RHEL-9.
> tests: enable vmware test on RHEL-9

- .gitlab-ci.yml
- internal/distro/rhel90/distro.go
- internal/distro/rhel90/package_sets.go
- test/cases/installers.sh
- tools/libvirt_test.sh
> rhel9: enable & fix installer test

- .gitlab-ci.yml
- cmd/osbuild-dnf-json-tests/main_test.go
- osbuild-composer.spec
- test/cases/cross-distro.sh
This is my modification of pr #1705 
> Only ship repo files for the distro being built

- NEWS.md
- internal/distro/rhel90/pipelines.go
- osbuild-composer.spec
- test/data/manifests/rhel_90-aarch64-qcow2-boot.json
- test/data/manifests/rhel_90-aarch64-qcow2-customize.json
- test/data/manifests/rhel_90-ppc64le-qcow2-boot.json
- test/data/manifests/rhel_90-ppc64le-qcow2-customize.json
- test/data/manifests/rhel_90-s390x-qcow2-boot.json
- test/data/manifests/rhel_90-s390x-qcow2-customize.json
- test/data/manifests/rhel_90-x86_64-qcow2-boot.json
- test/data/manifests/rhel_90-x86_64-qcow2-customize.json
- tools/provision.sh
Backporting:
- https://github.com/osbuild/osbuild-composer/pull/1848 for the actual bugfix
- https://github.com/osbuild/osbuild-composer/pull/1861 for one CI fix
> Backport qcow2 fix and release 33.3

- NEWS.md
- osbuild-composer.spec
> Prepare release 35

- cmd/osbuild-composer/composer.go
- cmd/osbuild-composer/main.go
- cmd/osbuild-worker/main.go
- internal/worker/server.go
> worker: use logrus for logging

- internal/cloudapi/v1/v1.go
- internal/cloudapi/v2/errors.go
- internal/cloudapi/v2/v2.go
- internal/prometheus/middleware.go
- internal/prometheus/prometheus.go
- recording composer request latency for alerting and Grafana dashboard
> Compose Latency metric

- schutzbot/scheduled_cloud_cleaner.sh
- test/cases/api.sh
- test/cases/aws.sh
Scheduled cloud cleaner only takes care of azure resources. This PR is intended to extend this functionality to AWS.
> test: cloud cleaner aws

- internal/osbuild2/authconfig_stage.go
- internal/osbuild2/authconfig_stage_test.go
- internal/osbuild2/pwquality_conf_stage.go
- internal/osbuild2/pwquality_conf_stage_test.go
- internal/osbuild2/stage.go
- internal/osbuild2/stage_test.go
- internal/osbuild2/yum_config_stage.go
- internal/osbuild2/yum_config_stage_test.go
Add support for new stages available in osbuild 41.
Replaces: #1991
Replaces: #1986
Replaces: #1984
> Multiple new stages

- internal/jobqueue/dbjobqueue/dbjobqueue.go
- internal/jobqueue/fsjobqueue/fsjobqueue.go
- internal/jobqueue/jobqueue.go
- internal/jobqueue/jobqueuetest/jobqueuetest.go
> jobqueue: add the ability to dequeue by ID

- cmd/osbuild-composer/main.go
- cmd/osbuild-worker/main.go
- internal/jobqueue/dbjobqueue/dbjobqueue.go
> Logging improvements

- internal/cloudapi/v2/v2.go
- internal/cloudapi/v2/v2_test.go
Reverts osbuild/osbuild-composer#2016
> Revert "cloudapi/v2: Use manifest-id-only job"

- test/cases/regression-composer-works-behind-satellite.sh
- test/cases/regression.sh
> test: reenable regression test for satellite

- .github/workflows/coverity_scan.yml
curl will URL encode this properly, no need to be encoded first
> ci: Update Coverity Scan name

- test/data/manifests/rhel_86-x86_64-image_installer-boot.json
> test/rhel86-manifest: re-generate

- .gitlab-ci.yml
- schutzbot/scheduled_cloud_cleaner.sh
- test/cases/api.sh
remove unused aws s3 resources.
to do so, we also make sure s3 resources originated from tests are tagged with "gitlab-ci-test"
> test: cloud cleaner aws s3

- test/README.md
> tests: Small updates to docs

- internal/osbuild2/cloud_init_stage.go
- internal/osbuild2/cloud_init_stage_test.go
Related to: https://github.com/osbuild/osbuild/pull/866/
> osbuild2: update cloud-init stage with new options

- .packit.yaml
> Use PackIt for building RPMs in COPR for PRs and commits to `main`

- test/cases/aws.sh
- test/cases/azure.sh
- test/cases/installers.sh
- test/cases/koji.sh
- test/cases/ostree-ng.sh
- test/cases/ostree-raw-image.sh
- test/cases/ostree-simplified-installer.sh
- test/cases/ostree.sh
- test/cases/vmware.sh
- test/data/koji/Return-mistakenly-dropped-option-keytab.patch
- tools/libvirt_test.sh
> tests: Fix several permission and koji failures

- internal/store/store.go
> store: set RHSM when initialising SourceConfig with a repo

- schutzbot/slack_notification.sh
> ci: CC QE in notification message

- .gitlab-ci.yml
- cmd/osbuild-composer/composer.go
- cmd/osbuild-dnf-json-tests/main_test.go
- cmd/osbuild-pipeline/main.go
- cmd/osbuild-store-dump/main.go
- cmd/osbuild-worker/jobimpl-depsolve.go
- containers/osbuild-composer/entrypoint.py
- distribution/osbuild-composer.service
- distribution/osbuild-dnf-json.service
- distribution/osbuild-dnf-json.socket
- distribution/osbuild-remote-worker@.service
- distribution/osbuild-worker@.service
- dnf-json
- internal/distro/distro_test_common/distro_test_common.go
- internal/rpmmd/repository.go
- osbuild-composer.spec
- test/cases/generation.sh
- test/cases/regression-old-worker-new-composer.sh
- tools/test-case-generators/generate-test-cases
> dnf json as a service

- cmd/osbuild-worker/jobimpl-depsolve.go
- internal/cloudapi/v2/errors.go
- internal/cloudapi/v2/openapi.v2.gen.go
- internal/cloudapi/v2/openapi.v2.yml
- internal/cloudapi/v2/v2.go
- internal/cloudapi/v2/v2_test.go
- internal/distro/distro.go
- internal/distro/fedora33/distro.go
- internal/distro/rhel8/distro.go
- internal/distro/rhel84/distro.go
- internal/distro/rhel84/distro_v2.go
- internal/distro/rhel85/distro.go
- internal/distro/rhel86/distro.go
- internal/distro/rhel90/distro.go
- internal/distro/rhel90beta/distro.go
- internal/distro/test_distro/distro.go
- internal/worker/json.go
- test/cases/api.sh
Allow 3rd-party repositories to be supported and custom packages installed.
> distro/depsolve/cloudapi: Add 3rd-party repository support.

- test/cases/generation.sh
> Tests: trim dependencies for test generation

- cmd/osbuild-composer/composer.go
- cmd/osbuild-koji/main.go
- cmd/osbuild-upload-gcp/main.go
- cmd/osbuild-worker/jobimpl-koji-finalize.go
- cmd/osbuild-worker/jobimpl-koji-init.go
- cmd/osbuild-worker/jobimpl-osbuild-koji.go
- cmd/osbuild-worker/jobimpl-osbuild.go
- internal/cloud/awscloud/awscloud.go
- internal/worker/api/errors.go
- internal/worker/server.go
log internal error details in the error handler
pass internal errors to error handler whenever possible
> cloudapi: improve logging for errors

- internal/osbuild2/tar_stage.go
Related to https://github.com/osbuild/osbuild/pull/940
> osbuild2: fix typo in tar stage option value

- dnf-json
> dnf json cache cleaner

- .gitlab-ci.yml
- osbuild-composer.spec
- test/cases/upgrade8to9.sh
- test/data/upgrade8to9/integration.xml
- test/data/upgrade8to9/upgrade_prepare.sh
- test/data/upgrade8to9/upgrade_verify.sh
> Upgrade test

- cmd/osbuild-service-maintenance/config.go
- cmd/osbuild-service-maintenance/gcp.go
- cmd/osbuild-service-maintenance/main.go
- templates/composer.yml
note that this is still dry-running so even if it's broken it's ok :)
> Maintenance enable clouds

- distribution/Dockerfile-ubi-packer
- tools/appsre-build-worker-packer.sh
Avoids the issue with artifacts that jenkins can't clean up.
> tools/appsre-build-worker-packer: Run entire workflow in container

- test/cases/api.sh
We should not fail on missing variables or errors during cleanup. The
test can fail in any stage and the cleanup should be run full each time.
Current example where this causes problem can be seen here: https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1990711774 
The test fails before the `S3_URL` is known and the cleanup function never reaches the part where background processes are killed and Gitlab CI gets stuck when there are processes running in background. This should ensure that the function is always ran in full.
> tests/api: Make cleanup best effort

- internal/distro/rhel90/stage_options.go
Add a special cases for the root user to the work-around for ssh keys in OSTree commits.
See 93e54cd8726beafc5db1427630728af277331ffa for the original, equivalent change in RHEL 8.6.
------
> distro/rhel90: special case root user for ssh keys

- internal/cloudapi/v2/errors.go
- internal/worker/api/errors.go
> worker/api: align error handler with cloudapi

- test/README.md
update testing documentation with info about 'cloud cleaner' and
'scheduled cloud cleaner'
> update testing doc with cloud cleaner info

- Schutzfile
- schutzbot/sonarqube.sh
> Sonarqube fix + Schutzfile repo rename

- image-types/rhel8/oracle-oci.md
> Add oracle-oci.md under image-types/rhel8

- cmd/osbuild-worker/jobimpl-koji-finalize.go
- cmd/osbuild-worker/jobimpl-koji-init.go
- cmd/osbuild-worker/jobimpl-osbuild-koji.go
- cmd/osbuild-worker/main.go
- internal/upload/koji/koji.go
See COMPOSER-1354 and linked tickets
> Relax TCP timeouts for koji connections

- .github/workflows/tests.yml
> github: split checks into 3 jobs

- internal/jobqueue/fsjobqueue/fsjobqueue.go
Previous implementation of fsjobqueue is amazing but it has its drawbacks:
- dequeueing can be done only based on a job type
- it's limited to 100 jobs per a job type
As we soon want to be able to dequeue also by another criteria (job channel),
we need to refactor the queue.
The new implementation is more naive but also more flexible. It basically
works like the dbjobqueue - dequeueing goroutines listen for newly added
jobs. When that happens, a signal is sent to all of them and they all inspect
all pending jobs and dequeue ones that match their needs. Ones that don't find
a suitable job, are waiting for the next signal.
This is certainly slower implementation as every time a new job is added into
the queue, all dequeueing goroutines will have to iterate over all
pending jobs. I think …
> fsjobqueue: refactor to allow dequeuing by multiple criteria

- .gitlab-ci.yml
- test/cases/upgrade8to9.sh
- test/data/upgrade8to9/upgrade_prepare.sh
> tests/upgrade: gather more logs

- internal/client/compose.go
- internal/client/compose_test.go
- internal/weldr/api.go
> Cancel waiting compose

- tools/libvirt_test.sh
This is just a simple check to verify rhbz#2004401 and rhbz#2003038
> tests/libvirt: add some regression tests

- tools/provision.sh
[bz#2057769](https://bugzilla.redhat.com/show_bug.cgi?id=2057769) blocked UEFI vm test. To make things progress, add a wrokaround to fix the issue.
> test: Add work around for bug bz#2057769

- test/cases/filesystem.sh
> Adjust filesystem tests

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/trigger-gitlab.yml
- .gitlab-ci.yml
> ci: skip CI for draft and WIP PRs 

- .github/workflows/tests.yml
- .pylintrc
- dnf-json
While working on other things, I did some cleanup of `dnf-json`.  Since it's a pretty important component of the service, I think it would be good to do a quick `pylint` run on it in the CI workflows.
> dnf-json codestyle cleanup

- test/cases/aws.sh
- test/cases/azure.sh
- test/cases/base_tests.sh
- test/cases/generation.sh
- test/cases/installers.sh
- test/cases/libvirt.sh
- test/cases/regression-composer-works-behind-satellite-fallback.sh
- test/cases/regression-composer-works-behind-satellite.sh
- test/cases/regression.sh
- test/cases/vmware.sh
- tools/libvirt_test.sh
Most test scripts don't have any documentation regarding it's purpose.
Although it can be guessed by the code, there's value in adding this
small comment.
[skip-ci]
> test: add tests purpose

- internal/upload/koji/koji.go
- internal/upload/koji/rh-logrus-adapter.go
> koji: reduce excessive logging by retryablehttp

- cmd/osbuild-worker/jobimpl-depsolve.go
These errors result in a 5xx status for the depsolve job, marked as
internal failure, it's useful to log them.
> osbuild-worker: Log unexpected dnf-json errors

- internal/jobqueue/dbjobqueue/dbjobqueue.go
See the individual commits. The first one does have a little to no effect on production but it's definitely a bug. The second is actually a non-functional change I think.
> dbjobqueue: fix race condition

- Schutzfile
> Centos pinning + Schutzfile update

- cmd/osbuild-koji/main.go
- internal/upload/koji/koji.go
- internal/upload/koji/rh-logrus-adapter.go
> Fix excessive logging and monitoring

- .gitlab-ci.yml
- Makefile
- cmd/osbuild-upload-generic-s3/main.go
- cmd/osbuild-worker/jobimpl-osbuild.go
- cmd/osbuild-worker/main.go
- internal/cloud/awscloud/awscloud.go
- internal/target/generic_s3_target.go
- internal/target/target.go
- internal/target/targetresult.go
- internal/weldr/upload.go
- osbuild-composer.spec
- test/cases/aws_s3.sh
- test/cases/generic_s3.sh
- tools/libvirt_test.sh
- tools/s3_test.sh
> Support uploading to any S3 service via the WELDR API

- test/cases/generic_s3.sh
@jrusz This addresses the issue you saw in #2412. It seems that sometimes the service takes a but longer to start so the client needs to wait and retry
> Generic S3 test - retry creating the alias in case the service is not yet up

- templates/dashboards/grafana-dashboard-image-builder-composer-general.configmap.yml
- templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
https://grafana.stage.devshift.net/d/image-builder-worker-test-2/image-builder-worker-test-2
https://grafana.stage.devshift.net/d/image-builder-composer-test-2/image-builder-composer-test-2
> Update grafana dashboards: SLO targets and visual tweaks

- internal/jobqueue/dbjobqueue/dbjobqueue.go
- internal/jobqueue/fsjobqueue/fsjobqueue.go
- internal/jobqueue/jobqueue.go
- internal/jobqueue/jobqueuetest/jobqueuetest.go
- internal/prometheus/job_metrics.go
- internal/worker/server.go
> prometheus: add tenant label

- internal/dnfjson/dnfjson.go
- internal/dnfjson/dnfjson_test.go
If dnf-json returns an error that is related to a repository, it uses the ID to identify the repository that caused the error.  Since IDs can't easily be mapped back to a configuration, appending the URL and name (if any) to the error message makes it easier to identify which repository failed.
Keeping the ID in the message is also useful for finding the cache directory of the repository if needed.
For reference, this is what an error message looks like when it has both a name and URL:
```
DNF error occurred: RepoError: There was a problem reading a repository: Failed to download metadata for repo '7a71592ff8a03486179a467c6416bf29e6a7ce46ffee9bc8aa703ff07c3b16ad' [baseos: https://0.0.0.0/baseos/repo]: Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried …
```
> dnfjson: add repository name and URL to repo-related error messages

- internal/dnfjson/dnfjson.go
The BaseSolver is an object which gets constructed when the worker
starts, and the subscriptions attached to it expire after about 3
days. By refreshing the subscriptions each time a new Solver is created,
valid subscriptions are used.
> dnfjson: Load subscriptions when creating a new solver

- cmd/osbuild-upload-gcp/main.go
> cmd/osbuild-upload-gcp: fix typo in skip-import's help string

- test/data/manifests/rhel_86-aarch64-qcow2_customize-boot.json
- test/data/manifests/rhel_86-x86_64-qcow2_customize-boot.json
Needed for https://github.com/osbuild/osbuild/pull/1051
> manifests: regenerate RHEL-8.6 qcow2 test cases

- cmd/osbuild-image-tests/main_test.go
Unconditionally ignore the UUID of the LVM container.  We don't control this value so it isn't stable and makes our image tests fail.
> osbuild-image-tests: ignore LVM UUID

- test/cases/ostree-ng.sh
Pushing container image to registry feature is ready by PR #2462, test should be update to cover this feature
> test: Update test for push container image to registry

- test/cases/ostree-ng.sh
- test/cases/ostree-raw-image.sh
- test/cases/ostree-rebase.sh
- test/cases/ostree-simplified-installer.sh
- test/cases/ostree.sh
Update test to install package `sssd` in all edge images for regression due to bug [BZ#2088459](https://bugzilla.redhat.com/show_bug.cgi?id=2088459)
> test: Install package sssd in all edge images for BZ#2088459

- templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
Add a tenant variable to the composer dashboard, with the option
to select multiple tenants. Add tenant filter to queries accordingly.
link to dashboard: https://grafana.stage.devshift.net/d/image-builder-worker-with-tenant/image-builder-worker?orgId=1
> templates: update dashboards to include tenant

- templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
Also:
- Gives tenants a nice display name.
- Makes "All" the default
---
https://grafana.stage.devshift.net/d/image-builder-worker-sanne/image-builder-worker-sanne
> templates/dashboards: Add brew tenants

- .gitlab-ci.yml
- schutzbot/prepare-rhel-internal.sh
- test/cases/regression-composer-works-behind-satellite-fallback.sh
- test/cases/regression-composer-works-behind-satellite.sh
- tools/provision.sh
> tests: Remove useless JSON file overrides

- test/cases/api/container.registry.sh
> tests: Add comment to make it more obvious what's happening

- test/cases/ostree-ng.sh
- test/cases/ostree.sh
- test/data/ansible/check_ostree.yaml
Edge test improvement for container embedding case.
Address ticket https://issues.redhat.com/browse/COMPOSER-1705
> test: Improvements for container embedding Edge test

- .gitlab-ci.yml
- test/cases/aws_s3.sh
- test/cases/gcp.sh
- test/cases/generic_s3.sh
- test/cases/koji.sh
- test/cases/oscap.sh
- test/cases/regression-bigiso.sh
- test/cases/regression-composer-works-behind-satellite-fallback.sh
- test/cases/regression-composer-works-behind-satellite.sh
- test/cases/regression-excluded-dependency.sh
- test/cases/regression-include-excluded-packages.sh
- test/cases/regression-no-explicit-rootfs-definition.sh
- test/cases/regression-old-worker-new-composer.sh
- test/cases/vmware.sh
> Disable skipped tests

- .gitlab-ci.yml
- test/cases/api/aws.sh
- test/cases/api/common/aws.sh
> test aws arm images via cloud API

- templates/packer/worker.pkr.hcl
- tools/appsre-worker-packer-container.sh
> Fix packer builds

- test/cases/api/aws.sh
The ami id of the cloned image is stored in `AMI_ID_2`.
> test/api/aws: Fix cloned image cleanup

- templates/composer.yml
> templates/composer.yml: update splunk port for splunk cloud

- internal/store/store.go
- internal/store/store_test.go
> tagging a blueprint wasn't working correctly

- cmd/osbuild-worker/jobimpl-ostree-resolve.go
- cmd/osbuild-worker/main.go
- internal/cloudapi/v2/handler.go
- internal/cloudapi/v2/server.go
- internal/cloudapi/v2/v2_test.go
- internal/ostree/ostree.go
- internal/weldr/api.go
- internal/worker/clienterrors/errors.go
- internal/worker/json.go
- internal/worker/server.go
- internal/worker/server_test.go
- test/cases/api.sh
> Ostree resolve job

- go.mod
- go.sum
- internal/weldr/api_test.go
- vendor/github.com/BurntSushi/toml/decode.go
- vendor/github.com/BurntSushi/toml/decode_go116.go
- vendor/github.com/BurntSushi/toml/doc.go
- vendor/github.com/BurntSushi/toml/encode.go
- vendor/github.com/BurntSushi/toml/error.go
- vendor/github.com/BurntSushi/toml/lex.go
- vendor/github.com/BurntSushi/toml/meta.go
- vendor/modules.txt
> Fix blueprint firewall support

- internal/client/blueprints.go
- internal/client/blueprints_test.go
- internal/store/json.go
- internal/store/json_test.go
- internal/weldr/api.go
- internal/weldr/api_test.go
> Add /blueprints/change/NAME/COMMIT route and save blueprint changes in the store

- .github/workflows/tests.yml
Update a couple of remaining checkout@v2 uses to v3
> workflows: Update to use actions/checkout@v3

- .github/workflows/tests.yml
- templates/packer/worker.pkr.hcl
- test/cases/api.sh
- test/cases/aws.sh
- test/cases/aws_s3.sh
- test/cases/azure.sh
- test/cases/gcp.sh
- test/cases/generic_s3.sh
- test/cases/regression-old-worker-new-composer.sh
- tools/generic_s3_https_test.sh
A packer build failed due to being rate limited by the aws api.
> templates/packer: increase polling delay

- tools/appsre-ansible/rpmbuild.yml
> tools/appsre-ansible: workaround missing authselect-compat

- cmd/gen-manifests/main.go
- cmd/osbuild-composer-cli-tests/main_test.go
- cmd/osbuild-pipeline/main.go
- dnf-json
- internal/client/source_test.go
- internal/cloudapi/v2/handler.go
- internal/cloudapi/v2/v2_internal_test.go
- internal/distro/distro_test_common/distro_test_common.go
- internal/dnfjson/dnfjson.go
- internal/osbuild/rpm_stage.go
- internal/rpmmd/repository.go
- internal/store/json.go
- internal/store/store.go
- internal/store/store_test.go
- internal/weldr/api_test.go
- internal/weldr/json.go
Add support for checking repomd.xml gpg signature to sources.
> Adding metadata signing check

- cmd/osbuild-dnf-json-tests/main_test.go
We only test one distro, CentOS 9, so there's no need to loop and spawn a new t.Run().
> osbuild-dnf-json-tests: remove distro loop

- test/cases/aws.sh
- test/cases/azure.sh
With the previous method, we encountered a lot of problems when sending the options via an array. Separate the options into different variables that can be set in CIV CI
> Fix CIV_OPTIONS bug

- Schutzfile
- osbuild-composer.spec
- test/cases/ostree-ng.sh
- test/cases/ostree-raw-image.sh
- test/cases/ostree-rebase-bios.sh
- test/cases/ostree-rebase-uefi.sh
- test/cases/ostree-simplified-installer.sh
- test/cases/ostree.sh
- tools/ansible-blocking-io.py
- tools/provision.sh
1. Fix bug https://github.com/osbuild/osbuild-composer/issues/3309 found in update snapshot pr.
2. Add workaround for bug https://bugzilla.redhat.com/show_bug.cgi?id=2162815
> Update rpmrepo snapshots to 20230223 (including necessary fixes and workarounds)

- test/cases/ostree-simplified-installer.sh
This pull request includes two test:
1. add usb in edge-simplified-installer test: https://github.com/osbuild/osbuild-composer/pull/3207
2. fdo onboarding create user test: https://github.com/osbuild/osbuild-composer/pull/3071
Added more test case for these two feature, so I created this new pull request with the latest test code update.
> Test/fdo: add fdo create user test case & add usb test case

- test/cases/aws.sh
- test/cases/azure.sh
Update CIV repo to use the new one. This is aimed to reduce CI time
> Change civ repo name

- test/cases/aws.sh
- test/cases/azure.sh
To do this, change how we provide parameters to CIV, we now provide a config file stored in gitlab secrets with all this parameters. This way we can also adapt the parameters in the future without modifying the script.
> Add tags to CIV instances

- containers/osbuild-composer/entrypoint.py
to avoid composer crashing and restarting when fluentd is not up
> containers/osbuild-composer: wait for fluentd in entrypoint

- pkg/jobqueue/dbjobqueue/dbjobqueue.go
We found some issues when a job is dequeued in the database (the `sqlDequeue` query succeeds), but the job is never sent to a worker. Since the logging statement at the end of `Dequeue` is never hit (we don't see anything in the logs), it's probably caused by failures of the other SQL queries. There can be multiple reasons for this, the most probable ones are random network issues or a race condition when the context passed into the function hits time-out or is cancelled before all SQL queries finish.
Let's fix this by putting all SQL queries related to one dequeuing operation into a SQL transaction. This should ensure that this operation is atomic. In order words, either all SQL operations succeed, or they are rolled back.
Some code shuffling was needed in order to achieve that, but it's …
> dbjobqueue: Make dequeuing atomic

- internal/manifest/os.go
- internal/manifest/os_test.go
- test/cases/api.sh
- test/cases/aws.sh
- test/cases/aws_s3.sh
- test/cases/azure.sh
- test/cases/container-embedding.sh
- test/cases/container-upload.sh
- test/cases/gcp.sh
- test/cases/generic_s3.sh
- test/cases/image_tests.sh
- test/cases/ostree-simplified-installer.sh
- tools/generic_s3_test.sh
- tools/libvirt_test.sh
This isn't pulled in as a dependency, and is required for services lik remediations.
> internal/manifest: install rhc-worker-playbook when using rhc

- test/cases/aws.sh
- test/cases/azure.sh
We need this env var to add a new feature into CIV
> JIRA_PAT env var

- internal/upload/koji/koji.go
- tools/run-koji-container.sh
The first two commits are just small clean-ups for the koji setup in our tests. The other two commits fix rather nasty issues that we are hitting when integrating with koji. I think that the commit messages explain them well, so please, have a look, and feel free to ask any questions. :)
> Fixes for the koji integration

- internal/client/blueprints_test.go
- internal/rpmmd/repository.go
- internal/rpmmd/repository_test.go
- internal/weldr/api.go
- internal/weldr/api_test.go
> Add tests for blueprint package name globs and fix blueprint freeze with globs

- schutzbot/mockbuild.sh
Fixes: https://github.com/osbuild/osbuild-composer/issues/3097
> Rpm build log

- test/cases/aws.sh
- test/cases/azure.sh
- test/cases/vmware.sh
> Introduce test conditions for AWS & Azure

- test/README.md
- opening this PR to check GitLab nightly pipeline scheduler. 
- explicitly opening from my personal fork to see if that will work!
> Remove Juan from the list of QE associates

- test/cases/installers.sh
- test/cases/minimal-raw.sh
- test/cases/oscap.sh
- tools/libvirt_test.sh
> Start collecting logs from virt-install

- schutzbot/slack_notification.sh
> Juan is no longer with Red Hat

- test/cases/ostree-vsphere.sh
> test edge-vsphere image

- test/cases/ostree-ami-image.sh
- test/data/ansible/check_ostree.yaml
This PR is to support edge-ami for aarch64 test. It fixed `VpcLimitExceeded` and added available instance checking before deployment.
> test: update edge-ami test to support aarch64

- test/cases/ostree-ami-image.sh
This PR adds `aws ec2 wait` commands for instance terminate, image register, and instance running to avoid hard code `sleep`. And this PR also re-formats some long shell commands shorter
> test: wait for ami image avaiable to use before tag creation

- .gitlab-ci.yml
- schutzbot/unregister.sh
> schutzbot: unregister test hosts

- test/cases/ubi-wsl.sh
Use the "Standard" public ip sku, as "Basic" produces warnings.
Spin until the vm gets assigned a valid ipv4 address.
> test/cases/ubi-wsl: public ip fixes

- test/cases/ostree-ami-image.sh
Sometime, AWS will report `Waiter SnapshotImported failed: Max attempts exceeded` error when import snapshot. `aws ec2 wait snapshot-imported` command can't be used any more but use a `manual` loop to check snapshot import status until finished.
> test: fix "Waiter SnapshotImported failed: Max attempts exceeded"

- test/cases/ubi-wsl.sh
The counter never made it past 10.
> test/cases/ubi-wsl: fix waiting for a valid ipv4

- test/cases/ostree-simplified-installer.sh
This PR is to workaround fdo package issue https://issues.redhat.com/browse/RHEL-4992
> test: workaround fdo package issue

- test/cases/ostree-iot-qcow2.sh
> Add test case for iot-qcow2-image

- .github/workflows/tests.yml
- cmd/osbuild-worker/jobimpl-osbuild.go
> lint: fix memory aliasing

- templates/dashboards/grafana-dashboard-image-builder-composer-general.configmap.yml
- templates/dashboards/grafana-dashboard-image-builder-worker-api.configmap.yml
- templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
worker api:
https://grafana.stage.devshift.net/d/pwseDuWSz/sanne-worker-api-2
composer api:
https://grafana.stage.devshift.net/d/2dWdtXZIz/image-builder-composer-copy?orgId=1
worker job stats:
https://grafana.stage.devshift.net/d/7nXfcuZIk/image-builder-worker-sanne-copy?orgId=1
> dashboard: worker api dashboard

- test/cases/ostree-simplified-installer.sh
FDO package has been fixed already, this PR is to remove workaround added by PR #3690.
> test: remove fdo package workaround from PR#3690

- pkg/splunk_logger/splunk_hook.go
- pkg/splunk_logger/splunk_logger.go
- pkg/splunk_logger/splunk_logger_test.go
> Add pkg splunk_logging

- .github/workflows/tests.yml
- cmd/osbuild-pipeline/main.go
- go.mod
- go.sum
- internal/blueprint/customizations.go
- internal/cloudapi/v2/v2_internal_test.go
- internal/store/store.go
- internal/store/store_test.go
- vendor/github.com/osbuild/images/pkg/blueprint/customizations.go
- vendor/github.com/osbuild/images/pkg/rpmmd/repository.go
- vendor/modules.txt
> Fix RHEL-16242 CheckGPG flag bug

- test/cases/ostree-simplified-installer.sh
- test/data/ansible/check_ostree.yaml
This PR fixed fdo mac address test issue which was imported by PR #3743.
> test: fix fdo mac address test issue

- .github/workflows/tests.yml
- Schutzfile
- tools/check-runners
Not sure if this should be run on PRs or not, but it should help in keeping Schutzfile cleaned up.
> Add a tool script to help check for unused runners

- DEPLOYING.md
- HACKING.md
This PR contains just small harmonizations in our usage of markdown.
> HACKING/DEPLOYING.md: Markdown syntax fixes

- go.mod
- go.sum
- vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
- vendor/github.com/aws/aws-sdk-go/aws/version.go
- vendor/github.com/containers/image/v5/docker/daemon/client.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/github.com/osbuild/images/pkg/distro/rhel9/distro.go
- vendor/modules.txt
> Update osbuild/images to v0.35.0

- internal/cloud/awscloud/secure-instance.go
The machine still needs to be able to fetch sources, so just keep the default 0.0.0.0/0 rule.
---
This rule doesn't make any sense anyway, if it still needs to contact everything.
> cloud/awscloud: remove restricting egress rule from SG

- cmd/osbuild-jobsite-builder/main.go
- internal/cloud/awscloud/secure-instance.go
This reduces network costs as transferring data between AZs is not free.
> cloud/awscloud: create secure instance in the same subnet

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
> README: Fix reference to developer guide

- .gitlab-ci.yml
- test/cases/openshift_virtualization.sh
b/c I want to expand it further
> Enable testing in OpenShift

- templates/packer/ansible/roles/common/files/worker-initialization-scripts/vector.sh
When switching to the new vector repos, the version was also bumped. The newer versions expect a yaml config.
> templates/packer: vector expects a yaml configuration now

- .github/workflows/pr_best_practices.yml
This adds our common PR best practices check action to this repository.
> ci: add a PR best practices check

- README.md
> Fixed link to developer guide

- cmd/osbuild-jobsite-builder/main.go
- cmd/osbuild-jobsite-manager/main.go
30 seconds can be a bit too little for the entire store.
> osbuild-jobsite: increase populate timeout

- templates/packer/ansible/roles/common/files/worker-initialization-scripts/get_ldap_sa_mtls_creds.sh
- templates/packer/ansible/roles/common/files/worker-initialization.service
The secret needs 3 fields, the cert, key and baseurl for the repository. The CA is optional.
> templates/packer: support ldap service account for repo mtls conf

- internal/client/unit_test.go
- internal/jobqueue/fsjobqueue/fsjobqueue.go
- internal/jobqueue/jobqueuetest/jobqueuetest.go
- internal/prometheus/worker_metrics.go
- internal/weldr/api_test.go
- internal/weldr/compose_test.go
- internal/worker/server.go
- pkg/jobqueue/dbjobqueue/dbjobqueue.go
- pkg/jobqueue/dbjobqueue/schemas/008_workers_add_channel.sql
- pkg/jobqueue/jobqueue.go
Adds an active worker gauge, increments when workers register, decrements when workers timeout. This will be useful to create an alert around (if no workers are connecting), and would be cool to have on the dashboard ($x active workers).
> Active worker gauge (COMPOSER-2215)

- templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
https://grafana.stage.devshift.net/d/cdjhlx93bxerke/image-builder-worker-job-stats-sannedeleteme
> Show worker count on grafana dashboard (COMPOSER-2215)

- go.mod
- go.sum
- vendor/github.com/aws/aws-sdk-go/aws/version.go
- vendor/github.com/osbuild/images/pkg/distro/rhel/images.go
- vendor/github.com/osbuild/images/pkg/dnfjson/dnfjson.go
- vendor/github.com/osbuild/images/pkg/manifest/os.go
- vendor/github.com/osbuild/images/pkg/manifest/raw_bootc.go
- vendor/modules.txt
Pulling in:
- https://github.com/osbuild/images/pull/650
- https://github.com/osbuild/images/pull/651
> Update osbuild/images v0.59.0 (HMS-4031)

- tools/appsre-build-fedora-worker-packer.sh
It can take a long time before packer picks up the jobs and the jobs are actually finished.
> tools/fedora-worker-packer: increase timeout further

- cmd/osbuild-worker-executor/handler_build.go
Do not use the global logger but pass instead the locally created logger. This means the test output is silent again.
Sadly using the global logger is difficult because it is a global resource so replacing it in tests means all tests (that are potentially run in parallel) will write to it which makes testing specific log output hard.
> osbuild-worker-executor: make test output silent again

- internal/osbuildexecutor/runner-impl-aws-ec2_test.go
Small followup for https://github.com/osbuild/osbuild-composer/pull/4184#discussion_r1636111501
> internal/osbuildexecutor: verify expected input from handleBuild

- cmd/osbuild-worker-executor/main_test.go
I got `error listening and serving: listen tcp 127.0.0.1:18002: bind: address already in use` during copr/packit a build.
(e.g. [this build](https://download.copr.fedorainfracloud.org/results/packit/osbuild-osbuild-composer-4103/centos-stream-10-s390x/07628035-osbuild-composer/builder-live.log.gz) )
This implementation for sure is racy but hopefully better than colliding with other concurrent tests with a fixed port for sure
> osbuild-worker-executor/main_test: use random port for tests

- internal/cloud/awscloud/secure-instance.go
When receiving the "UnfillableCapacity" error from CreateFleet, retry the request with an OnDemand instance.
> internal/awscloud: retry CreateFleet (HMS-4098)

- internal/cloud/awscloud/secure-instance.go
In case the previous executor SI belonging to the worker did not get shut down properly, attempt to do it again when starting a new one, otherwise replacing the SG or LT will not work.
> awscloud: try to terminate previous secure instance (HMS-4341)

- .gitlab-ci.yml
- tools/image-info
> fix image-info + filesystem.sh test on f40

- Schutzfile
Includes https://github.com/osbuild/osbuild/pull/1809.
> Schutzfile: update osbuild

- pkg/jobqueue/dbjobqueue/dbjobqueue.go
Preserve context.DeadlineExceeded errors through correct error wrapping. This will reduce error-level logging noise in the worker.
> dbjobqueue: correct error wrapping

- go.mod
- go.sum
- vendor/github.com/osbuild/images/pkg/blueprint/customizations.go
- vendor/github.com/osbuild/images/pkg/blueprint/filesystem_customizations.go
- vendor/github.com/osbuild/images/pkg/distro/rhel/rhel10/gce.go
- vendor/modules.txt
> Update osbuild/images to v0.82.0

- .gitlab-ci.yml
Disable the Packer test in scheduled GA pipelines.
> tests/packer: Disable Packer job in scheduled GA pipelines

- internal/cloud/awscloud/maintenance.go
> cloud/awscloud: fix another nilpointer in maintenance functions

- cmd/osbuild-worker/jobimpl-ostree-resolve.go
> worker: log proxy setting

- go.mod
- go.sum
- vendor/github.com/osbuild/images/pkg/blueprint/filesystem_customizations.go
- vendor/github.com/osbuild/images/pkg/disk/disk.go
- vendor/github.com/osbuild/images/pkg/disk/partition_table.go
- vendor/github.com/osbuild/images/pkg/distro/distro.go
- vendor/github.com/osbuild/images/pkg/distro/fedora/imagetype.go
- vendor/github.com/osbuild/images/pkg/distro/fedora/package_sets.go
- vendor/github.com/osbuild/images/pkg/distro/fedora/partition_tables.go
- vendor/github.com/osbuild/images/pkg/distro/id.go
- vendor/github.com/osbuild/images/pkg/distro/rhel/imagetype.go
- vendor/github.com/osbuild/images/pkg/distro/rhel/rhel10/partition_tables.go
- vendor/github.com/osbuild/images/pkg/distro/rhel/rhel7/ami.go
- vendor/github.com/osbuild/images/pkg/distro/rhel/rhel7/azure.go
- vendor/github.com/osbuild/images/pkg/distro/rhel/rhel7/partition_tables.go
- vendor/github.com/osbuild/images/pkg/distro/rhel/rhel8/azure.go
- vendor/github.com/osbuild/images/pkg/distro/rhel/rhel8/partition_tables.go
- vendor/github.com/osbuild/images/pkg/distro/rhel/rhel9/azure.go
- vendor/github.com/osbuild/images/pkg/distro/rhel/rhel9/edge.go
- vendor/github.com/osbuild/images/pkg/distro/rhel/rhel9/partition_tables.go
- vendor/github.com/osbuild/images/pkg/distro/test_distro/distro.go
- vendor/github.com/osbuild/images/pkg/dnfjson/dnfjson.go
- vendor/github.com/osbuild/images/pkg/osbuild/disk.go
- vendor/github.com/osbuild/images/pkg/osbuild/grub2_inst_stage.go
- vendor/github.com/osbuild/images/pkg/ostree/ostree.go
- vendor/github.com/osbuild/images/pkg/reporegistry/reporegistry.go
- vendor/github.com/osbuild/images/pkg/reporegistry/repository.go
- vendor/github.com/osbuild/images/pkg/rpmmd/repository.go
- vendor/modules.txt
SSIA
Ostree building still does not work with Pulp URLs, this should fix it.
> deps: update images to 0.99

- internal/cloud/awscloud/secure-instance.go
We still see this error sometimes:
Unable to start secure instance: Unable to create fleet: InsufficientInstanceCapacity: There is no Spot capacity available that matches your request
This is awkward because the message mentions that there is no spot capacity, even though the current code should retry on InsufficientInstanceCapacity. I also confirmed this by searching for the retries log messages: there are none in the logs.
We need a bigger hammer. Let's log everything that happens in the createFleet method in order to have better understanding why the retry logic isn't triggered. We should probably move most of the newly added logs to the debug level, but let's delay that until we have more insight into what's happening.
> awscloud: add very verbose logging to createFleet creation (COMPOSER-2407)

- go.mod
- go.sum
- vendor/github.com/osbuild/images/pkg/blueprint/ca_customizations.go
- vendor/github.com/osbuild/images/pkg/blueprint/customizations.go
- vendor/github.com/osbuild/images/pkg/blueprint/disk_customizations.go
- vendor/github.com/osbuild/images/pkg/blueprint/filesystem_customizations.go
- vendor/github.com/osbuild/images/pkg/blueprint/toml_json_bridge.go
- vendor/github.com/osbuild/images/pkg/cert/parsecerts.go
- vendor/github.com/osbuild/images/pkg/datasizes/size.go
- vendor/github.com/osbuild/images/pkg/disk/disk.go
- vendor/github.com/osbuild/images/pkg/disk/partition_table.go
- vendor/github.com/osbuild/images/pkg/distro/fedora/distro.go
- vendor/github.com/osbuild/images/pkg/distro/fedora/images.go
- vendor/github.com/osbuild/images/pkg/distro/fedora/imagetype.go
- vendor/github.com/osbuild/images/pkg/distro/rhel/images.go
- vendor/github.com/osbuild/images/pkg/manifest/os.go
- vendor/github.com/osbuild/images/pkg/osbuild/ostree_source.go
- vendor/github.com/osbuild/images/pkg/osbuild/pki_update_ca_trust_stage.go
- vendor/github.com/osbuild/images/pkg/ostree/ostree.go
- vendor/modules.txt
> deps: update images to 0.102

- cmd/osbuild-worker/jobimpl-depsolve.go
- cmd/osbuild-worker/jobimpl-search.go
- cmd/osbuild-worker/main.go
- internal/cloudapi/v2/handler.go
- internal/cloudapi/v2/openapi.v2.gen.go
- internal/cloudapi/v2/openapi.v2.yml
- internal/cloudapi/v2/search.go
- internal/cloudapi/v2/v2_koji_test.go
- internal/cloudapi/v2/v2_multi_tenancy_test.go
- internal/cloudapi/v2/v2_test.go
- internal/worker/json.go
- internal/worker/server.go
- internal/worker/server_test.go
> Add /search/packages to cloudapi

- go.mod
- go.sum
- vendor/github.com/osbuild/images/pkg/dnfjson/dnfjson.go
- vendor/github.com/osbuild/images/pkg/manifest/ostree_deployment.go
- vendor/github.com/osbuild/images/pkg/osbuild/containers_input.go
- vendor/github.com/osbuild/images/pkg/osbuild/containers_storage_source.go
- vendor/github.com/osbuild/images/pkg/osbuild/skopeo_index_source.go
- vendor/github.com/osbuild/images/pkg/osbuild/skopeo_source.go
- vendor/github.com/osbuild/images/pkg/osbuild/skopeo_stage.go
- vendor/github.com/osbuild/images/pkg/osbuild/source.go
- vendor/modules.txt
Update osbuild/images to latest release.
This is a minor update that shouldn't require any changes to osbuild-composer.
> go.mod: update to latest images@v0.112.0

- schutzbot/slack_notification.sh
Remove Alex from Slack CI notifications, add Achilleas and tag only on failures.
> CI: Update slack notifications and remove Alex

- Schutzfile
- osbuild-composer.spec
The next images update needs the updated cloud-init stage.
> Schutzfile: bump osbuild to 142

- .github/workflows/tests.yml
- go.mod
- go.sum
- osbuild-composer.spec
- vendor/github.com/golang-jwt/jwt/v4/parser.go
- vendor/github.com/golang-jwt/jwt/v5/README.md
- vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
- vendor/github.com/golang-jwt/jwt/v5/parser.go
- vendor/github.com/golang-jwt/jwt/v5/token.go
- vendor/modules.txt
> [RHEL-9.5] go.mod: update jwt-go to v4.5.2 and v5.2.2 to fix CVE-2025-30204

- .gitlab-ci.yml
> .gitlab-ci.yml: test WSL images on RHEL 10

- .github/workflows/tests.yml
- .gitlab-ci.yml
- go.mod
- go.sum
- internal/client/blueprints_test.go
- osbuild-composer.spec
- vendor/github.com/golang-jwt/jwt/v4/parser.go
- vendor/github.com/golang-jwt/jwt/v5/README.md
- vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
- vendor/github.com/golang-jwt/jwt/v5/ecdsa.go
- vendor/github.com/golang-jwt/jwt/v5/hmac.go
- vendor/github.com/golang-jwt/jwt/v5/parser.go
- vendor/github.com/golang-jwt/jwt/v5/token.go
- vendor/modules.txt
> [RHEL-9.4] go.mod: update jwt-go to v4.5.2 and v5.2.2 to fix CVE-2025-30204

- test/README.md
- test/cases/api/oci.sh
- test/cases/oci.sh
Updated documentation and CI output as well as suggested shape change in the oracle cloud.
> Improve OCI CI scripts (HMS-8591)

- Schutzfile
- tools/appsre-build-fedora-worker-packer.sh
This completes the change commited as 612a295bf6071eb6280a5dbbfdf1d97e606e9aef
> Schutzfile: Bump all osbuild hashes

- internal/auth/jwt.go
- internal/auth/jwt_test.go
- internal/auth/middleware.go
- internal/client/unit_test.go
- internal/weldr/api.go
- internal/worker/server.go
Updates various unimportant small things here and there which are reported by `staticcheck`.
> many: fix various linter warnings

- cmd/osbuild-composer-cli-tests/main_test.go
The v36.0 release of weldr-client/composer-cli will include support for cloudapi commands. This adjusts the tests so that they will work with the new version while maintaining compatibility with the previous version.
Related: RHEL-60123
> tests: Update composer-cli tests for v36.0
