osbuild/osbuild-composer

internal/distro/image_config.go
internal/distro/rhel85/pipelines.go
internal/distro/rhel86/distro.go
internal/distro/rhel86/pipelines.go
internal/distro/rhel90/distro.go
internal/distro/rhel90/pipelines.go
test/data/manifests/centos_8-aarch64-ami-boot.json
test/data/manifests/centos_8-x86_64-ami-boot.json
test/data/manifests/rhel_85-aarch64-ami-boot.json
test/data/manifests/rhel_85-aarch64-ec2-boot.json
test/data/manifests/rhel_85-x86_64-ami-boot.json
test/data/manifests/rhel_85-x86_64-ec2-boot.json
test/data/manifests/rhel_85-x86_64-ec2_ha-boot.json
test/data/manifests/rhel_86-aarch64-ami-boot.json
test/data/manifests/rhel_86-aarch64-ec2-boot.json
test/data/manifests/rhel_86-x86_64-ami-boot.json
test/data/manifests/rhel_86-x86_64-ec2-boot.json
test/data/manifests/rhel_86-x86_64-ec2_ha-boot.json
test/data/manifests/rhel_86-x86_64-ec2_sap-boot.json
test/data/manifests/rhel_90-aarch64-ami-boot.json
test/data/manifests/rhel_90-aarch64-ec2-boot.json
test/data/manifests/rhel_90-x86_64-ami-boot.json
test/data/manifests/rhel_90-x86_64-ec2-boot.json
test/data/manifests/rhel_90-x86_64-ec2_ha-boot.json
test/data/manifests/rhel_90-x86_64-ec2_sap-boot.json

Disable loging in via password authentication since this is an
official Amazon marketplace requirement:
>  Linux-based AMIs must not allow SSH password authentication.
Disable password authentication via your sshd_config file by
setting PasswordAuthentication to NO.
See section "Security policies" from https://docs.aws.amazon.com/marketplace/latest/userguide/product-and-ami-policies.html

EC2: Disable password based authentication

---

.gitlab-ci.yml

scheduled cloud cleaner is now fully functioning. This means we can
auto-cancel whole pipelines on new commits.
This PR adds the tag "interruptible" to every stage.

gitlab-ci: make every stage interruptible

---

internal/jobqueue/dbjobqueue/dbjobqueue.go
internal/prometheus/job_metrics.go
internal/worker/clienterrors/errors.go
internal/worker/server.go

- moving the metrics to the worker/server
- the ability to gather metrics on successful/unsuccessful jobs
- add the error status to job duration metrics

Workers error metrics

---

internal/worker/clienterrors/errors.go

The DNFDepsolveError and DNFMarking error should have
a `4xx` code instead of a `5xx` error code.

worker: fix error status codes

---

.gitlab-ci.yml
osbuild-composer.spec
schutzbot/deploy.sh
schutzbot/mockbuild.sh
schutzbot/prepare-rhel-internal.sh
test/cases/api.sh
test/cases/base_tests.sh
test/cases/shared_lib.sh

I had just realized that building osbuild-composer-tests rpm from main is sometimes going to result in a different NVR than we have downstream (this will be more prominent toward the end of a minor release cycle).  Because we've got 
```
Requires:   %{name} = %{version}-%{release}
```
installing this RPM inside our test systems will fail with broken dependencies. Another possibility is that this will result in silently pulling a newer osbuild-composer RPM from the S3 repos instead of pulling the RPM from the nightly tree.

Prepare CI to build -tests RPM for downstream testing from source

---

cmd/osbuild-worker/jobimpl-osbuild-koji.go
cmd/osbuild-worker/jobimpl-osbuild.go

This pull request includes adds additional checks to ensure there aren't any gaps in the
error handling for `OSBuildJob` and `KojiOSBuildJob` jobs.
The osbuild jobs were mostly fine the output is not nil from the start:
https://github.com/osbuild/osbuild-composer/blob/main/cmd/osbuild-worker/jobimpl-osbuild.go#L74-L76
But could get overridden here:
https://github.com/osbuild/osbuild-composer/blob/main/cmd/osbuild-worker/jobimpl-osbuild.go#L146
The osbuild worker now explicitly checks for nil `OsbuildOutput`.
Similarly, a function was added to validate koji build results and update the job with a job error if the worker exits
early due to an error.
The PR adds a few extra error cases too.

Worker error validation

---

test/data/manifests/rhel_85-aarch64-ami-boot.json
test/data/manifests/rhel_85-aarch64-ec2-boot.json
test/data/manifests/rhel_85-x86_64-ami-boot.json
test/data/manifests/rhel_85-x86_64-ec2-boot.json
test/data/manifests/rhel_85-x86_64-ec2_ha-boot.json
test/data/manifests/rhel_86-aarch64-ami-boot.json
test/data/manifests/rhel_86-aarch64-ec2-boot.json
test/data/manifests/rhel_86-x86_64-ami-boot.json
test/data/manifests/rhel_86-x86_64-ec2-boot.json
test/data/manifests/rhel_86-x86_64-ec2_ha-boot.json
test/data/manifests/rhel_86-x86_64-ec2_sap-boot.json

Fix missing missing `image-info` report updates after PR #2235.

test: regenerate RHEL 8.5 and 8.6 EC2 image test cases

---

templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml

Update the grafana dashboard for the workers to show information on the success rate for
osbuild and depsolve jobs.
The test dashboard can be found [here](https://grafana.stage.devshift.net/d/image-builder-worker-test/image-builder-worker-test?orgId=1&var-datasource=app-sre-stage-01-prometheus&var-interval=7d&var-stability_slo=0.95&var-latency_slo=0.9&from=now-7d&to=now)

templates/dashboards: worker error metrics

---

cmd/osbuild-service-maintenance/main.go
templates/composer.yml

Let's enable the cloud cleanup first, and then move on the db.

service-maintenance: Skip db cleanup

---

.github/workflows/trigger-gitlab.yml

Save resources and needless CI runs by skipping the trigger-gitlab job if a PR is 'draft' (can be set in the pull request page at any time) or by setting a label "WIP".
Aside from saving resources, WIP PRs that don't trigger CI are a good message to contributors to keep testing it locally and to only get the project resources after serious testing been made on their side.

Skip CI for draft PRs or WIP label

---

.github/workflows/trigger-gitlab.yml

With the quoting, we are passing an empty variable instead of no argument.
Also, if the skip is required, we are passing "-o ci.skip" instead of
"-o" "ci.skip".

github: fix gitlab trigger

---

internal/prometheus/job_metrics.go

Currently the job metrics are namespaced with the composer
subsystem, i.e. `composer_worker`. Since we plan to split
the components to their own namespaces in app interface,
the worker subsystem should be split too.

metrics: change job metrics namespace

---

templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml

- updated namespace queries for job metrics
- formatted queries for improved readability in grafana
- fallback values for empty query results, so that we don't get "No Data" 
for important panels such as the Error Budgets
This PR hasn't made any visual changes to the dashboard. The test dashboard
can be viewed [here](https://grafana.stage.devshift.net/d/image-builder-worker-test/image-builder-worker-test?orgId=1&var-datasource=app-sre-stage-01-prometheus&var-interval=12h&var-stability_slo=0.95&var-latency_slo=0.9&from=now-12h&to=now)

templates/dashboard: worker metric queries

---

test/data/manifests/fedora_34-aarch64-oci-boot.json
test/data/manifests/fedora_34-aarch64-openstack-boot.json
test/data/manifests/fedora_34-aarch64-qcow2-boot.json
test/data/manifests/fedora_34-aarch64-qcow2_customize-boot.json
test/data/manifests/fedora_34-x86_64-oci-boot.json
test/data/manifests/fedora_35-aarch64-oci-boot.json
test/data/manifests/fedora_35-aarch64-openstack-boot.json
test/data/manifests/fedora_35-aarch64-qcow2-boot.json
test/data/manifests/fedora_35-aarch64-qcow2_customize-boot.json
test/data/manifests/fedora_35-x86_64-oci-boot.json
tools/test-case-generators/distro-arch-imagetype-map.json
tools/test-case-generators/format-request-map.json

Add F34 and F35 image test cases for all remaining image types, which
were previously not tested. With this PR, image test cases are now
generated for all image types on all architectures as supported by the
Fedora distro definition.

Add missing F34 and F35 image test cases

---

test/README.md

govc cli no longer uses GOVMOMI_* enviroment variables. As the govc documentation indicates, this variables should be GOVC_*
[govc usage](https://github.com/vmware/govmomi/blob/master/govc/README.md#usage)

test: update govc env variables documentation

---

.github/workflows/trigger-gitlab.yml

I basically just copied
https://github.com/osbuild/osbuild/blob/7c9944ee188c35da7ee2ece521a4c86ac5eb2f34/.github/workflows/trigger-gitlab.yml
and:
- changed osbuild to osbuild-composer
- add a SKIP_CI mechanism

github: adapt the github trigger to work the same way as in osbuild

---

internal/distro/rhel86/pipelines.go
internal/distro/rhel90/pipelines.go
internal/osbuild2/ostree_deploy_stage.go
internal/osbuild2/ostree_pull_stage.go
test/cases/ostree-raw-image.sh
test/cases/ostree-simplified-installer.sh

I'm re-bringing this up from https://github.com/osbuild/osbuild-composer/pull/1697 as that didn't make 85 and even if we still don't have automatic updates this is pretty important for the admin workflow who's used to just serve the update and `rpm-ostree upgrade` - it should be pretty safe to land this (I don't remember what was the risk)
From the old PR:
> Preset a remote called rhel-edge with the URL that was used to fetch the commit, so it can be used to fetch updates.

Pre-define an ostree remote for RFE raw images (including created via simplified installer)

---

internal/boot/openstacktest/openstack.go

Update flavor and network ID for booting Openstack images in rhos-01
cloud.

tests: update IDs in Openstack image boot test

---

internal/mocks/rpmmd/fixtures.go
internal/store/fixtures.go
internal/store/store.go
internal/weldr/api.go
internal/weldr/api_test.go

Fix problem with undo creating empty blueprint

---

.github/workflows/trigger-gitlab.yml

By default, the API will fetch only 30 open PRs. This is enough currently
as we have 35 open ones. Bump the limit to the maximum. 100 should be enough
for some time. 🤞

github: fetch more PRs when triggering gitlab

---

.gitlab-ci.yml
schutzbot/deploy.sh
schutzbot/slack_notification.sh

Storing composer NVR in a file after it's installed and reporting on
Slack. Also reducing duplications of artifacts in .gitlab-ci.yml

ci/nightly: report composer NVR in slack

---

cmd/osbuild-worker/jobimpl-osbuild-koji.go
cmd/osbuild-worker/jobimpl-osbuild.go

This will make counting successful image builds in Splunk and Cloudwatch
much simpler and robust.

worker: Properly log successful image builds

---

test/cases/filesystem.sh

Follow up to
https://github.com/osbuild/osbuild-composer/pull/1921 and
https://bugzilla.redhat.com/show_bug.cgi?id=2023635

tests: Use human readable size for mountpoint

---

schutzbot/el9-mock-configs/templates/rhel-9.tpl

A quick and dirty solution just to see the CI green before the release.

mockbuild: temporarily pin RHEL 9 compose to an older one

---

.gitlab-ci.yml

The longer running ostree tests (all except ostree.sh) benefit from
running on large runners because of their long runtime. Changing all to
large runners.

ci: large runners for some ostree tests

---

cmd/osbuild-worker/jobimpl-osbuild.go
internal/cloud/awscloud/awscloud.go

Defaults according to https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config:
Defaults to a chain of credential providers to search for credentials in
environment variables, shared credential file, and EC2 Instance Roles.
If nothing is specified fall back to whatever instance role.

internal/cloud: Allow aws creds from defaults

---

Schutzfile

note: the rpm crash is still expected to occur, but this should fix the timezone bug issue in the released osbuild version in centos-9

Schutzfile: Pin centos-9's osbuild commit

---

tools/provision.sh

Since "ANSIBLE_STDOUT_CALLBACK=yaml" has been removed from all ostree test script, "ansible-galaxy collection install" should be removed as well.
We encountered galaxy server issue in test https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/2120498876#L2336
Let's remove it to avoid issues.

test: Remove "ansible-galaxy collection install"

---

schutzbot/el9-mock-configs/templates/rhel-9.tpl

Unpin before the compose is deleted. We should really use the same repos as define in Schutzfile at some point.

Revert "mockbuild: temporarily pin RHEL 9 compose to an older one"

---

cmd/osbuild-worker/jobimpl-osbuild-koji.go

This was causing:
Feb 21 06:08:06 ip-10-30-18-43.us-east-1.aws.redhat.com osbuild-worker[20798]: time="2022-02-21T06:08:06Z" level=warning msg="Error reporting job result: error setting job status: 404 — Token not found (IMAGE-BUILDER-WORKER-5)"

worker/osbuild-koji: fix double-reporting of osbuild-koji job status

---

templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml

The depsolve error rate had the incorrect query and was returning the error rate for the build
jobs. This has now been fixed.
Before:
After:

templates/worker: fix depsolve error rate

---

test/cases/base_tests.sh

Current version is 45.
This reverts commit 966692be1122347a2668bee8e6ae88ee8f81f39b.

COMPOSER-1343: Revert "tests: Conditionally enable osbuild-dnf-json-tests"

---

internal/cloudapi/v2/v2.go

Customizations being nil isn't the same as an empty object. The
edge-installer types require customizations equalling nil.
This partially reverts bb486bcccb5abf6b96e9e8b76c7226a693d08172.

internal/cloudapi: Allow bp.Customizations being nil

---

internal/disk/partition_table.go
internal/distro/rhel85/distro.go
internal/distro/rhel86/distro.go
internal/distro/rhel90/distro.go
internal/distro/rhel90beta/distro.go
test/cases/filesystem.sh

- enable `/tmp` mountpoint for rhel86 & rhel90
- ensure minimum size of 1GB for all file systems, except `/usr` which is set to 2GB (fixes #2347)

FS minimum size

---

internal/distro/rhel86/stage_options.go
internal/distro/rhel90/stage_options.go
test/cases/regression-bigiso.sh
test/cases/regression.sh
test/data/manifests/centos_8-x86_64-image_installer-boot.json
test/data/manifests/centos_9-x86_64-image_installer-boot.json
test/data/manifests/rhel_86-x86_64-image_installer-boot.json
test/data/manifests/rhel_90-x86_64-image_installer-boot.json

So it can contain payload bigger than 4GiB.
Related: rhbz#2056451

rhel86/90: change isolevel of image-installer to 3

---

test/data/manifests/centos_8-aarch64-image_installer-boot.json
test/data/manifests/centos_9-aarch64-image_installer-boot.json
test/data/manifests/rhel_86-aarch64-image_installer-boot.json
test/data/manifests/rhel_90-aarch64-image_installer-boot.json

The new image-installer tests were merged at the same time as the isolevel support. Adjust the test cases.

test/manifest/image-installer: fix conflicting merge

---

schutzbot/update_github_status.sh

For troubleshooting in CI, if a user is logged on to a runner, keep it alive until they are logged off.
Not sure if there is a better way to do this.  I'm open to suggestions.

schutzbot: keep runners alive when users are logged on

---

internal/disk/disk_test.go
internal/disk/partition_table.go
internal/distro/rhel86/distro.go
internal/distro/rhel86/distro_test.go
internal/distro/rhel86/partition_tables.go

Whenever we create a new mountpoint due to a user customization, ensure the layout uses LVM, i.e. convert plain layouts to it, if needed. It uses the existing lvm-ification code but enhances it so that we also create a `/boot` partition in case it does not yet exist.
Adjust the existing tests that assumed we can not create more than 4 partitions on mbr layouts, since that is now not true anymore.

rhel86: automatically convert to LVM on fs customizations

---

templates/packer/ansible/roles/common/files/worker-initialization-scripts/worker_external_creds.sh

We test if specific variables are set, and -u interferes with that.

templates/packer: Remove -u flag from creds mapping script

---

templates/composer.yml

We will be using both offline tokens (account_id) and service accounts
(rh-org-id) for now.

templates/composer: give access to Fedora org

---

test/cases/image_tests.sh

This manifest is intended only for internal use and is currently failing
in nightly pipelines. This will be moved to a different test script in
the future, see COMPOSER-1397.

🍏  test/image-tests: temporarily skip azure_rhui image testing

---

.gitlab-ci.yml

Temporarily disable Installer test case in the CI on RHEL-9 and CentOS
Stream 9 until https://bugzilla.redhat.com/show_bug.cgi?id=2059565 is
resolved. This test case is now consistently failing due to the
mentioned bug and makes it impossible for the CI to pass cleanly.

🍏  Make CI green again

---

.packit.yaml

Add srpm_build_deps key to the Packit configuration to specify the needed dependencies for SRPM build
and indicate to build SRPM in Copr.
If you are interested in the transition to building SRPMs in Copr, you can read more about it [here](https://packit.dev/posts/copr-srpms/).

Packit: build SRPMs in Copr

---

internal/reporegistry/reporegistry.go
internal/reporegistry/reporegistry_test.go
internal/store/json.go
internal/weldr/api.go

Added a new distro definition which acts as a fallback for when the host distro is not supported.  The distribution supports all known architectures, but doesn't specify any image types.  This makes osbuild-composer capable of running on unknown distros for cross-distro building.
Tested on Arch Linux:
```
❯ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo
❯ composer-cli status show
API server status:
Database version:   0
Database supported: true
Schema version:     0
API version:        1
Backend:            osbuild-composer
Build: …
```

weldr: Run on unsupported distros

---

.github/workflows/tests.yml

Flip the incorrect flip that happened in e4baddfad119f0826b22081cb68d29ec47ea5cde

github: fix job names and IDs for the tests workflow

---

distribution/Dockerfile-ubi-packer

Use app-sre packer image as base image, help to reduce packer build job running time.
https://github.com/app-sre/container-images/blob/master/packer/Dockerfile
Signed-off-by: Feng Huang <fehuang@redhat.com>

use app-sre packer image

---

go.mod
internal/jobqueue/dbjobqueue/dbjobqueue.go
internal/jobqueue/jobqueuetest/jobqueuetest.go
vendor/modules.txt

Previously, all dequeuers (goroutines waiting for a job to be dequeued) were
listening for new messages on postgres channel jobs (LISTEN jobs). This didn't
scale well as each dequeuer required to have its own DB connection and the
number of DB connections is hard-limited in the pool's config.
I changed the logic to work somewhat differently: dbjobqueue.New() now spawns
a goroutine that listens on the postgres channel. If there's a new message,
the goroutine just wakes up all dequeuers using a standard go channel.
Go channels are cheap so this should scale much better.
A test was added that confirms that 100 dequeuers are not a big deal now. This
test failed when I tried to run it on the previous commit. I tried even 1000
locally and it was still fine.
Signed-off-by: Ondřej Budai …

dbjobqueue: reduce the number of needed connections

---

cmd/osbuild-pipeline/main.go
dnf-json
internal/rpmmd/repository.go

- dnf-json: do not use reponame as repoid
- rpmmd: pass repo name to dnf-json
- dnf-json: use repository name from the request if provided
- rpmmd: rename toDNFRepoConfig() argument i -> repoID
- osbuild-pipeline: use repo name from the request if provided

Pass repo name to `dnf-json` and use it in `dnf-json`

---

dnf-json

By default `timeout` is 30 seconds, but we had it set to 5. Drop
the override and use the default.
This has two effects: it increases the time before we give up on
connecting (as it says on the tin), and it also increases the time
download has to be slow for before we give up.
Internally, we were seing failures in downlaoding metadata from ODCS
and similar issues have occurred in CI too.
The potential downside to this is in case of having several mirrors
this means it takes longer before giving up on a bad one and trying
a better one. But slow is better than broken, so for now rever to
the default behavior.

dnf-json: use the default connection timeout

---

templates/packer/ansible/roles/common/files/worker-initialization-scripts/subscription_manager.sh

We don't want to subscribe Fedora.

packer: make subscribing optional

---

templates/packer/ansible/roles/common/files/worker-initialization-scripts/get_koji_creds.sh

Oops, we should probably start testing this.

packer: fix the secret ID variable in get_koji_creds.sh

---

.github/workflows/tests.yml
.github/workflows/trigger-gitlab.yml

In 5e639cba6f0a3ea34f8db83b212e23c36674e6a3 the context of the Trigger
Gitalb CI workflow changed and the context
"github.event.pull_request.draft" is no longer available so the
condition for SKIP_CI didn't work. This can be fixed by getting the
variable in the previous workflow and passin it as artifact. Docs:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow
I've tested this quite a bit in a separate repo https://github.com/jrusz/test-actions/actions and I'm fairly confident this will work. 

github workflows: modify Gitlab CI trigger

---

test/cases/api.sh

- Do not create files in directories which don't get cleaned up.
- Make sure that the DB is dumped even if the test case fails.

`test/api.sh` cleanup

---

templates/packer/worker.pkr.hcl

packer: use unique name tag for Fedora workers

---

.github/workflows/trigger-gitlab.yml

workflows: debug Gitlab CI trigger

---

.github/workflows/trigger-gitlab.yml

Apparently Gitlab does not like single quotes. 

workflows: Fix Gitlab CI trigger + revert debug

---

.gitlab-ci.yml
schutzbot/deploy.sh

Workaround for https://bugzilla.redhat.com/show_bug.cgi?id=2065292

deploy: work around a podman bug in CS8 

---

cmd/osbuild-composer/composer.go
containers/osbuild-composer/entrypoint.py
internal/weldr/api.go
templates/composer.yml

Support graceful shutdown of composer, making sure that any pending request are handled before the container is
terminated.
In the past we risked OpenShift thinking the container was dead (because we stopped answering to liveness probes) and
killing it before pending requests (in particular long-running depsolves) had been processed.

container: graceful shutdown

---

.github/workflows/create-tag.yml

Instead of a human pushing a tag with the release notes let a bot do the work.
The bot is part of our composite action in osbuild/release-action on the create-tag branch (https://github.com/osbuild/release-action/tree/create-tag). It calculates the next subsequent release version and creates a tag based on pull request titles associated with the changes since the last release.
Finally the tag is pushed to the repository.
For a demo of what this will look like take a peek into https://github.com/ochosi/release-action-test/actions/runs/2003553167
**TODO:**

Enable scheduled upstream releases

---

test/cases/api.sh

api.sh: encrypt the DB dump artifact

---

.github/workflows/create-tag.yml

We're counting the even and odd weeks since the Unix epoch, so this
doesn't match the odd/even calendar weeks. Consequently let's switch to
odd weeks for composer.

create-tag: Fix upstream release schedule

---

.github/workflows/create-tag.yml

This PR contains two fixes for the 'create-tag (scheduled releases) action.
1. With the `'` the environment variable is not properly stored.
2. When a release is manually triggered we want to ignore whether it is odd or even week but allow the release in any case.

create-tag: Fix bash typo

---

containers/osbuild-composer/entrypoint.py
templates/composer.yml

We don't have permissions to write to /run when running on OpenShift so let's
just use /tmp and change the filename to prevent any conflicts.

container: fix liveness probe

---

internal/upload/koji/koji.go

Use properly initialized retryablehttp client
These are fixes after investigating the 3 failures from earlier last week and the log message "Koji upload failed after 0 retries" which did not make sense.

koji: fix retries when uploading chunks

---

schutzbot/slack_notification.sh

b/c we need to be able to quickly react on ostree failures when they happen.

Add Xiaofeng to notifications for nightly pipeline

---

.gitlab-ci.yml

We are running into a GitLab CI limitation:
jobs:integration:parallel:matrix config generates too many jobs (maximum is 50)
Let's split these jobs into separate ones.

gitlab: split integration tests

---

test/cases/ostree-simplified-installer.sh

There was another virt-install added recently and it was missed in
1d51c0764936902c681283a3489845ef660fef5e
@henrywang I didn't notice the new `virt-install` and this now also started getting stuck on RHEL-9.0 nightly. I had to manually unstuck this job: https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/2256353462

test/ostree-simplified-installer: destroy VM fixup

---

test/cases/ostree-simplified-installer.sh
test/data/ansible/check_ostree.yaml

1. Remove comment out code
2. Use three different IP address for different test scenarios
3. Move /boot/device-credentials file checking into playbook
4. Some shell script improvements

test: Clean up and improve ostree-simplified-installer.sh

---

.gitlab-ci.yml

tests: Run SonarQube analysis only on main branch

---

cmd/osbuild-package-sets/main.go

Add a new debugging / development tool `osbuild-package-sets` for
printing JSON object with all package sets of a specific distro x arch x
image type combination.
This is useful, since due to the way package sets are implemented in
composer, the actual package set of a vanilla image type is very
difficult to determine just by looking at the code.
Example usage:
`go run cmd/osbuild-package-sets/main.go -distro rhel-90 -arch x86_64
-image qcow2`

cmd: add `osbuild-package-sets` for printing package sets of an image

---

.gitlab-ci.yml
cmd/osbuild-worker/jobimpl-osbuild.go
internal/cloudapi/v2/v2.go
internal/distro/rhel85/package_sets.go
internal/distro/rhel86/package_sets.go
internal/distro/rhel90/package_sets.go
internal/target/target.go
test/cases/api.sh
test/data/manifests/centos_8-x86_64-vmdk-boot.json
test/data/manifests/centos_9-x86_64-vmdk-boot.json
test/data/manifests/rhel_85-x86_64-vmdk-boot.json
test/data/manifests/rhel_86-x86_64-vmdk-boot.json
test/data/manifests/rhel_90-x86_64-vmdk-boot.json

- Add `cloud-init` to the default package set of VMDK image on RHEL-85/86/90
- Extend the `api.sh` test case to test VMDK image uploaded to S3 in VSphere and run it in the CI
- Cloud API: upload stream-optimized VMDK to S3

Add `cloud-init` to VMDK image and test it in VSphere

---

tools/define-compose-url.sh

The latest nightly link for 8.6 was missing only by accident, changing
back as it's fixed already.

tools/define-compose-url: change url back to nightly

---

internal/distro/rhel85/pipelines.go
internal/distro/rhel85/stage_options.go
internal/distro/rhel86/pipelines.go
internal/distro/rhel86/stage_options.go
internal/distro/rhel90/pipelines.go
internal/distro/rhel90/stage_options.go
internal/distro/rhel90beta/pipelines.go
internal/distro/rhel90beta/stage_options.go
internal/osbuild2/rpm_stage.go

Deduplicate the `rpmStageOptions()` function implemented in every distro
`stage_options.go` to `osbuild2` package.
RHEL-8.4 and code using osbuild v1 manifests are not touched.

Move `rpmStageOptions()` from `stage_options.go` to `osbuild2`

---

cmd/osbuild-dnf-json-tests/main_test.go
internal/cloudapi/v2/v2_koji_test.go
internal/cloudapi/v2/v2_multi_tenancy_test.go
internal/cloudapi/v2/v2_test.go
internal/jobqueue/fsjobqueue/fsjobqueue_test.go
internal/jsondb/db_private_test.go
internal/jsondb/db_test.go
internal/kojiapi/server_test.go
internal/store/store_test.go
internal/weldr/api_test.go
internal/weldr/compose_test.go
internal/worker/server_test.go

A testing enhancement.
We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir

test: use `T.TempDir` to create temporary test directory

---

cmd/osbuild-composer/composer.go
internal/cloudapi/server.go
internal/cloudapi/v2/handler.go
internal/cloudapi/v2/server.go
internal/cloudapi/v2/v2_test.go

By merging https://github.com/osbuild/osbuild-composer/pull/2417 I introduced flakey tests, oh no.
`T.TempDir` basically checks whether something writes into the directory *after* the test finishes, see https://github.com/golang/go/issues/43547.
This could happen in `cloudapi` because we have the manifest generation goroutines: When a test finishes, there might be still one running and it might write something into the directory created by `T.TempDir` and the test will explode.
The underlying issue is that we don't wait for all manifest generation goroutines to finish when shutting down the cloudapi server. This is potentially dangerous because the goroutine might be interrupted in a weird, non-defined state.
This PR refactors `cloudapi` a bit and adds a synchronization mechanism that …

cloudapi: prevent dangling goroutines after the server is terminated

---

.gitlab-ci.yml
test/cases/ostree-rebase.sh

Enable CS9 test for `ostree-rebase.sh` and fix two CS8 tests for `ostree.sh`

test: Enable CS9 test for ostree-rebase and ostree

---

cmd/osbuild-worker/jobimpl-osbuild-koji.go
internal/worker/clienterrors/errors.go

Reporting that there has been an issue with a dependency job does not provide enough information about the dependency
failure. It makes more sense to bubble up the original error since this will tell us the information we need. It also has the added benefit of ensuring consistency of the status codes for metrics.

Dependency joberrors

---

test/cases/ostree-ng.sh

A user does not need to be specified in upgrade blueprint in order for
it to be present after the upgrade. Related rhbz#2060575

test/ostree-ng: remove user customization from upgrade BP

---

cmd/osbuild-worker/jobimpl-osbuild.go
internal/cloudapi/v2/server.go
internal/worker/clienterrors/errors.go
internal/worker/server.go

- empty manifest error case for osbuild jobs
- empty packagespec error case for depsolve jobs with `4xx`

Empty manifest check for osbuild jobs

---

internal/distro/rhel86/distro.go
test/data/manifests/rhel_85-x86_64-azure_rhui-boot.json
test/data/manifests/rhel_86-x86_64-azure_rhui-boot.json

We want to ensure that cloud images connect to Red Hat[1] independently of how the content was acquired (PAYG, BYOS, or marketplace).
This auto-registration feature is already enabled for AWS and this patch enables it for Azure with the same recommended settings:
Services:
rhsmcertd: Enabled (already done, so not changed in the patch)
`/etc/rhsm/rhsm.conf`:
auto_registration: enabled
auto_registration_interval: 60 (the default, so not explicitly set)
manage_repos: false
The latter value `manage_repos` is left enabled (the default) in case the user explicitly requested to have the system subscribed, i.e. the `RHSMConfigWithSubscription` code path.
Regenerate the relevant test manifests and image information.
[1] https://cloud.redhat.com
[2] …

distro/rhel86: enable auto-registration for azure

---

test/cases/api.sh

SSIA
```bash
thozza@fedora ~/devel/osbuild-composer
$ grep -r API_TEST_SUBSCRIPTION_ACTIVATION_KEY
test/cases/api.sh:  printenv API_TEST_SUBSCRIPTION_ORG_ID API_TEST_SUBSCRIPTION_ACTIVATION_KEY > /dev/null
test/cases/api.sh:      "activation_key": "${API_TEST_SUBSCRIPTION_ACTIVATION_KEY:-}",
```

CI: rotate the used RHSM activation key

---

internal/distro/rhel85/pipelines.go
internal/distro/rhel85/stage_options.go
internal/distro/rhel86/pipelines.go
internal/distro/rhel86/stage_options.go
internal/distro/rhel90/pipelines.go
internal/distro/rhel90/stage_options.go
internal/distro/rhel90beta/pipelines.go
internal/distro/rhel90beta/stage_options.go
internal/osbuild2/qemu_stage.go
internal/osbuild2/qemu_stage_test.go

- Enhance the QEMU stage implementation to allow specifying VMDK subformat.
- De-duplicate the `qemuStageOptions()` function from many distro implementations and move it to the `osbuild2` package as `NewQEMUStageOptions()`. In addition, make it more generic by not taking any format-specific arguments.
This PR is a preparation for eventually changing the VMDK image to be produced as stream-optimized, instead of being converted before uploading.

osbuild2: QEMU stage implementation enhancement and code de-duplication

---

.gitlab-ci.yml
Schutzfile
schutzbot/deploy.sh
schutzbot/mockbuild.sh

Pin fedora repositories in Schutzfile + override mock templates with rpmrepo snapshots

---

internal/cloudapi/v2/errors.go
internal/cloudapi/v2/handler.go
internal/cloudapi/v2/v2_koji_test.go
internal/cloudapi/v2/v2_test.go
internal/worker/clienterrors/errors.go
internal/worker/server.go

- empty manifest error case for osbuild jobs
- empty packagespec error case for depsolve jobs with `4xx`
- query dependencies for errors if/when a build job fails and report failed dependencies
in build job result.

Worker dependency errors

---

.gitlab-ci.yml

The jobs in finish stage are only meant to report the overall status of
the pipeline, they do not require to download the hundreds of artifacts
from the previous stages.

ci: do not download artifacts in finish stages

---

templates/packer/ansible/roles/common/files/worker-initialization-scripts/vector.sh

Vector 0.21 needs region set otherwise the healthcheck will
fail. Instead of explicitly setting the aws cloudwatch endpoint, just
set the region.

templates/packer: Rely on instance metadata to set region

---

.gitlab-ci.yml

f21e5fd1c975d08cc110409938f65906ff281456 made nightly reporting jobs not
downloading any artifacts. Unfortunately, this broke the reporting because it
depends on COMPOSE_ID and COMPOSER_NVR artifacts. Let's revert the change for
these jobs until we find a better solution.
cc @jrusz 

gitlab: fix nightly testing

---

test/cases/aws_s3.sh
test/cases/gcp.sh
test/cases/generic_s3.sh

https://coreos.slack.com/archives/C0235DZB0DT/p1650536467098679?thread_ts=1650512166.141439&cid=C0235DZB0DT

Don't run unsupported tests on 8.6 and 9.0

---

internal/disk/disk_test.go
internal/disk/partition_table.go

New function that ensures that a partition can hold the total sum of all the required sizes of specific directories on the partition.  The function sums the required directory sizes grouped by their mountpoint and then resizes the entity path of that Mountable.  
This function will be required for resizing entities in a partition table given a set of (sub)directory size requirements.  We can add min sizes for directories to image types (e.g., `/var` should be 2 GiB) and based on the filesystem customizations, we would need to resize the `/var` partition if the user requested one, otherwise we would resize `/`.

New functions for resizing partitions based on directory size requirements

---

internal/disk/disk_test.go
internal/disk/partition_table.go

[RHEL 8.6] disk: fix ensureLVM for partition tables without /boot

---

internal/disk/disk_test.go
internal/disk/partition_table.go
test/cases/generation.sh
test/data/manifests/centos_8-aarch64-qcow2_customize-boot.json
test/data/manifests/centos_8-ppc64le-qcow2_customize-boot.json
test/data/manifests/centos_8-x86_64-qcow2_customize-boot.json
test/data/manifests/centos_9-aarch64-qcow2_customize-boot.json
test/data/manifests/centos_9-ppc64le-qcow2_customize-boot.json
test/data/manifests/centos_9-s390x-qcow2-boot.json
test/data/manifests/centos_9-s390x-qcow2_customize-boot.json
test/data/manifests/centos_9-x86_64-qcow2_customize-boot.json
test/data/manifests/rhel_86-aarch64-qcow2_customize-boot.json
test/data/manifests/rhel_86-ppc64le-qcow2_customize-boot.json
test/data/manifests/rhel_86-s390x-qcow2_customize-boot.json
test/data/manifests/rhel_86-x86_64-qcow2_customize-boot.json
test/data/manifests/rhel_90-aarch64-qcow2_customize-boot.json
test/data/manifests/rhel_90-ppc64le-qcow2_customize-boot.json
test/data/manifests/rhel_90-s390x-qcow2-boot.json
test/data/manifests/rhel_90-s390x-qcow2_customize-boot.json
test/data/manifests/rhel_90-x86_64-qcow2_customize-boot.json
tools/test-case-generators/format-request-map.json

When the partition table did not have a boot partition, we created it but then _unconditionally_ returned, which meant that we did not the LVM skeleton and wrap the root partition. Properly handle this case and also re-initialize the `rootPath` in this case since the underlying `Partition[]` array in `PartitionTable` object.
Add an extra blueprint with only one customisation which exposes this bug.

disk: fix ensureLVM for partition tables without /boot

---

tools/test-case-generators/generate-all-test-cases

Add `manifests` command for generating image test cases without
`image-info` report, so only manifests.

tools/generate-all-test-cases: add `manifests` command

---

cmd/osbuild-worker/main.go
internal/worker/client.go
internal/worker/client_test.go
internal/worker/proxy_test.go
internal/worker/server_test.go

In the internal deployment, we want to talk with composer over a http/https proxy. This proxy adds new composer.proxy field to the worker config that causes the worker to connect to composer and the oauth server using a specified proxy.
NB: The proxy is not supported when connection to composer via unix sockets.
This PR also includes random improvements to the worker code but nothing major, just some things that I stumbled upon.

worker: add proxy support to worker

---

tools/image-info

Check for the rpm database in `$tree/usr/share/rpm` and explicitly also in `$tree/var/lib/rpm` and if the respective location exists pass it as argument to rpm. This should fix the situation where the default database on the host is in a different location than in the tree. Fedora < 36 and RHEL have the location in /var but Fedora starting 36 and rpm-ostree have it in /usr.

image-info: dynamically detect the rpm database

---

containers/osbuild-composer/entrypoint.py
distribution/Dockerfile-ubi

entrypoint.py
-------------
Allow the user to set the port number also for the remote worker
Allow the user to restrict the composer api or remote worker api to
localhost
Dockerfile-ubi
--------------
Allow the user to override the entrypoint parameters
Set the environment variable default value to keep current behavior

entrypoint - add parameters for socket bind address and port

---

.devcontainer/Dockerfile

The staticfiles dependency updated to support Go 1.18 generics in the
2022.1 release. This prevents the devcontainer (which has Go 1.16) from
being built. This pins to the latest release of staticfiles which builds
on 1.16.
Another option would be to bump Go to 1.18 in the devcontainer which would
allow for the dep to be installed `@latest`.
As this is a developer container I'm unsure how the checklist below
applies.

Pin the `staticfiles` Go dep in devcontainer.

---

cmd/osbuild-worker/jobimpl-osbuild.go
internal/cloudapi/v2/server.go
internal/distro/fedora33/distro.go
internal/distro/rhel8/distro.go
internal/distro/rhel84/distro.go
internal/distro/rhel85/pipelines.go
internal/distro/rhel86/pipelines.go
internal/distro/rhel90/pipelines.go
internal/distro/rhel90beta/pipelines.go
internal/osbuild1/qemu_assembler.go
internal/weldr/api.go
internal/worker/json.go
osbuild-composer.spec
test/data/manifests/centos_8-x86_64-vmdk-boot.json
test/data/manifests/centos_9-x86_64-vmdk-boot.json
test/data/manifests/fedora_34-x86_64-vmdk-boot.json
test/data/manifests/fedora_35-x86_64-vmdk-boot.json
test/data/manifests/rhel_8-x86_64-vmdk-boot.json
test/data/manifests/rhel_84-x86_64-vmdk-boot.json
test/data/manifests/rhel_85-x86_64-vmdk-boot.json
test/data/manifests/rhel_86-x86_64-vmdk-boot.json
test/data/manifests/rhel_87-x86_64-vmdk-boot.json
test/data/manifests/rhel_90-x86_64-vmdk-boot.json
test/data/manifests/rhel_90_beta-x86_64-vmdk-boot.json
test/data/manifests/rhel_91-x86_64-vmdk-boot.json

- Support specifying VMDK subformat in `osbuild1` QEMU assembler.
- Change all VMDK image pipelines to produce stream-optimized image.
- Modify Weldr and Cloud APIs to no longer set the `StreamOptimized` variable in `OSBuildJob` structure for VMDK image.

Produce VMDK images as stream-optimized

---

.github/workflows/tests.yml

Git v2.35.2 brought some security fixes which prevents interaction with
repository if it's not owned by the user who cloned it. More info here:
https://github.blog/2022-04-12-git-security-vulnerability-announced/

rpmplint: trust osbuild-composer repository

---

.gitlab-ci.yml
schutzbot/slack_notification.sh

All of the edge tests are being ran on every nightly compose inside
virt-qe Jenkins so no need to run them here as well.

Nightly testing: remove edge testing from nightly pipelines

---

templates/composer.yml

This will allow us to specify tenants in the acl per namespace.

templates/composer: Parametrize tenants in acl

---

Schutzfile

We need the latest golang-github-getkin-kin-openapi in order to unblock
https://github.com/osbuild/osbuild-composer/pull/1953

Schutzfile: update Fedora snapshots to 20220504

---

templates/composer.yml

The sidecar receives logs from the service and forwards them to Splunk
HEC

templates/composer: add fluentd sidecar

---

cmd/osbuild-composer/config.go
cmd/osbuild-composer/main.go
vendor/github.com/sirupsen/logrus/hooks/syslog/README.md
vendor/github.com/sirupsen/logrus/hooks/syslog/syslog.go
vendor/modules.txt

Which will be used on crc in the log forwarding setup
NeededBy: COMPOSER-1285

composer: add support for logrus syslog hook

---

templates/composer.yml

templates/composer: add missing fluentd-config volume

---

cmd/osbuild-worker/main.go

Before, the autoscaling group discovery is failing with error:
Error getting the Autoscaling instances: MissingRegion MissingRegion:
could not find region configuration

instances: provide the region for the ASG

---

.github/workflows/tests.yml

Fedora 36 ships pylint 2.13 that newly reports:
```
dnf-json:436:20: E0601: Using variable 'cache_state' before assignment (used-before-assignment)
```
As dnf-json is pending a big rewrite
(https://github.com/osbuild/osbuild-composer/pull/2537),
I decided to pin fedora to 35 and let the other PR decide how to proceed in
order to prevent any conflicts.

github: pin fedora:35 for the pylint check

---

tools/test-case-generators/format-request-map.json

Removed in 2beb707def18e3d2b5c3f0ac83e8958af1be9442, possibly
accidentally.
The affected manifests were not regenerated based on this change so
they all already contain the core group.

Add 'core' group back to qcow2 customize in format-request-map

---

osbuild-composer.spec

The new osbuild input schema, for which we added support in https://github.com/osbuild/osbuild-composer/pull/2578, requires osbuild v55 or newer.

spec: require osbuild v55

---

cmd/osbuild-service-maintenance/config.go
cmd/osbuild-service-maintenance/main.go
templates/composer.yml

Stage and production share the GCP account. To avoid trying to delete each GCP image twice, the maintenance script needs the ability toselectively disable certain parts based on the config.
--- 
Similar to DRY_RUN, these values should be overwritten in app-interface per namespace. At some point the maintenance specific to the CRC tenant (aws and gcp maintenance) should run in the workers namespace rather than the composer namespace. Granularity is needed for this.

Switch cleanup targets on or off in service maintenance job

---

internal/distro/image_config.go
internal/distro/rhel84/distro_backports.go
internal/distro/rhel85/pipelines.go
internal/distro/rhel86/distro.go
internal/distro/rhel86/pipelines.go
internal/distro/rhel90/pipelines.go
internal/osbuild2/udev_rules_stage.go
internal/osbuild2/udev_rules_stage_test.go
test/data/manifests/rhel_85-x86_64-azure_rhui-boot.json
test/data/manifests/rhel_86-x86_64-azure_rhui-boot.json
test/data/manifests/rhel_87-x86_64-azure_rhui-boot.json

From the corresponding comment in the rule:
```
```
Closes #2450

[rhel86] azure: add udev rule to ignore the SRIOV network interface

---

.gitlab-ci.yml

ci: run scripts in after_script regardless of failure

---

cmd/cloud-cleaner/main.go
internal/cloud/gcp/compute.go
test/cases/api.sh
test/cases/gcp.sh

We currently use a single GCP Compute region when spinning up VMs using
the imported GCE image. As a result, we are often hitting the
'IN_USE_ADDRESSES' quota limit when there are multiple CI jobs running.
Google does not allow us to increase the quota limit any more.
Change the GCP test cases to use the CI `GCP_REGION` variable to list
all GCE regions with available quota and pick a random one from the
list. The `GCP_REGION` value is used as the region name prefix when
filtering available regions. This means that if you specify an exact GCE
region, such as `us-west1`, you'll always get the same region, but if a
GCP multi-region is used, such as `us`, then a random region prefixed
with 'us' will be used.
Update `cloud-cleaner` accordingly.
Once this PR is merged, we should update the …

Improve GCP test cases to pick regions with available quota

---

schutzbot/scheduled_cloud_cleaner.sh

scheduled cloud cleaner is skipping the default storage account for a
resource group, as this images should get removed. There can be a
situation where this images are not removed and forgotten here. Remove
this skip condition so scc checks also in this storage account.

scheduled-cloud-cleaner: remove storage account skip

---

osbuild-composer.spec

[skip ci]
For some reason our release automation for creating the GitHub release and doing the post-release version bump didn't run at all. Weirdly though, the scheduled action that pushes the tag ran just fine and v52 was created.
Therefore I'm now completing the steps manually by doing the post-release version bump.

Post release version bump

---

.gitlab-ci.yml
test/cases/regression-old-worker-new-composer.sh

Use the cloud API for the `old-worker-new-composer` test.
All of the changes are bits and pieces copied from the `api.sh` script.  Most conditions are removed since we only run one test here: a guest image (`qcow2`) build uploaded to S3.  The test only really checks that the job succeeds and the image has the expected contents.  It doesn't check any fail states or image booting like the API test does.
Reasons for this change:
- Mixed versions of composer and worker aren't a realistic use-case for the weldr API (on prem) but we do run mixed versions in hosted IB, so this test is closer to real world scenarios.
- The cloud API runs depsolve jobs in the worker, whereas the weldr API runs them in composer.  By testing the cloud API we also test the backwards compatibility of the depsolve job.

Old worker - New composer test: Use Cloud API

---

internal/distro/rhel90/package_sets.go
internal/distro/rhel90/pipelines.go
test/data/manifests/rhel_90-x86_64-azure_rhui-boot.json
test/data/manifests/rhel_91-x86_64-azure_rhui-boot.json

- We need to actually set the grub2 configuration if there is one. Doh.
- Install the "NetworkManager-cloud-setup" on Azure Marketplace images.

[rhel9] Fixes for grub2 config (ImageConfig) and azure-rhui

---

test/cases/api.sh
test/cases/gcp.sh

Do not rely on the default machine type when creating a GCE instance,
but rather list the available machine types in the zone and pick from
them. Test cases will pick the smallest machine type which name matches
the `^n\d-standard-\d$` regular expression.
This should prevent CI failures like
https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/jobs/2497043942#L2930

tests/gcp: pick machine type from those available in the zone

---

test/cases/regression-old-worker-new-composer.sh

Something odd is happening with the package check and it keeps failing mysteriously even though the package is clearly in the list.  Changing the verification method to extract `passwd` and `packages` from the image info file into separate files and grepping those seems to work.
This worked in my test PR https://github.com/osbuild/osbuild-composer/pull/2688.
Hope it wasn't a one-off.

test/old-worker: change user and package verification check

---

test/cases/api.sh
test/cases/aws.sh
test/cases/aws_s3.sh
test/cases/azure.sh
test/cases/gcp.sh
test/cases/generic_s3.sh
test/cases/multi-tenancy.sh
test/cases/regression-composer-works-behind-satellite-fallback.sh
test/cases/regression-composer-works-behind-satellite.sh
test/cases/regression-old-worker-new-composer.sh
test/data/upgrade8to9/upgrade_verify.sh

When a test script fails in CI, it's often difficult to pinpoint the exact line in the log where the script failed and the cleanup() function (trapped on EXIT) begins.
Adding a prominent line (with greenprint where available) at the start of the cleanup function will make reading logs of failed jobs a lot easier.

test: add prominent message in test script cleanup functions

---

.gitlab-ci.yml
cmd/osbuild-upload-generic-s3/main.go
cmd/osbuild-worker/jobimpl-osbuild.go
internal/cloud/awscloud/awscloud.go
internal/target/generic_s3_target.go
internal/weldr/upload.go
osbuild-composer.spec
test/cases/aws_s3.sh
test/cases/generic_s3_http.sh
test/cases/generic_s3_https_insecure.sh
test/cases/generic_s3_https_secure.sh
tools/generic_s3_https_test.sh
tools/generic_s3_test.sh
tools/libvirt_test.sh
tools/s3_test.sh

API
---
Allow the user to pass the CA public certification or skip the verification
AWSCloud
--------
Restore the old version of newAwsFromCreds for access to AWS
Create a new method newAwsFromCredsWithEndpoint for Generic S3 which sets the endpoint and optionally overrides the CA Bundle or skips the SSL certificate verification
jobimpl-osbuild
---------------
Update with the new parameters
osbuild-upload-generic-s3
-------------------------
Add ca-bunlde and skip-ssl-verification flags
tests
-----
Split the tests into http, https with certificate and https skip certificate check
Create a new base test for S3 over HTTPS for secure and insecure
Move the generic S3 test to tools to reuse for secure and insecure connections
All S3 tests now use the aws cli tool
Update the libvirt test to be …

Upload to HTTPS S3 - Support self signed certificate

---

.github/workflows/tests.yml
templates/.kube-linter-config.yml
templates/composer.yml

See last few runs in https://github.com/Gundersanne/osbuild-composer/actions/workflows/tests.yml for example runs.
This will at least make sure the template can be processed and get some basic warnings/errors on the deployment.

Add kube-linter check to github tests workflow

---

templates/composer.yml

templates: add Fedora prod tenant to the ACL

---

internal/distro/rhel86/distro.go
internal/distro/rhel86/distro_test.go
internal/distro/rhel86/pipelines.go
internal/distro/rhel90/distro.go
internal/distro/rhel90/distro_test.go
internal/distro/rhel90/pipelines.go
test/data/manifests/rhel_85-x86_64-azure_rhui-boot.json
test/data/manifests/rhel_86-x86_64-azure_rhui-boot.json
test/data/manifests/rhel_87-x86_64-azure_rhui-boot.json
test/data/manifests/rhel_90-x86_64-azure_rhui-boot.json
test/data/manifests/rhel_91-x86_64-azure_rhui-boot.json

Those images are forced to be 64GiB in size but mostly consist of zeros. This makes them hard to handle, e.g. uploading to brew takes a forever. Therefore compress the RHUI artefacts.

Compress Azure RHUI artefacts

---

internal/jobqueue/dbjobqueue/schemas/003_dependencies_cascade.sql
internal/jobqueue/dbjobqueue/schemas/004_heartbeats_cascade.sql

When deleting rows from the job table, make sure the delete is cascaded
to the dependencies table.
---
We should be able to clear rows from the stage database using scheduled queries, for production we can keep stuff around for longer of course. But no point in letting the stage db grow (rds doesn't allow you to shrink after the fact).
This is independent from #2707, that PR zeros out manifests which can contain sensitive-ish data.

dbjobqueue: Alter foreign key constraints

---

internal/distro/rhel90/distro.go
test/data/manifests/rhel_90-x86_64-azure_rhui-boot.json
test/data/manifests/rhel_91-x86_64-azure_rhui-boot.json

In commit 5c1530e we disabled `skx_edac` and `intel_cstate` but after further consultation with Prarit Bhargava it was agreed that  for RHEL 9 we should indeed allow them.

distro/rhel90: remove skx_edac, intel_cstate from denylist again

---

templates/packer/ansible/roles/common/tasks/packages.yml

packer: pin the vector version

---

cmd/osbuild-composer-dbjobqueue-tests/main_test.go
cmd/osbuild-service-maintenance/db.go
internal/jobqueue/dbjobqueue/dbjobqueue.go

A few notes:
1. nulling results doesn't clear disk space without vacuum full, in fact it increases disk usage of the table
2. Vacuum analyze does free up space within the table, meaning there's room for additional inserts without disk space increasing.
---
exapmle stats: https://bpa.st/raw/X6CA

osbuild-service-maintenance:  vacuum  analyze after update

---

cmd/osbuild-worker/jobimpl-depsolve.go

This error is failing to parse correctly on the workers as a
dnfjson.Error. The old rpmmd.DNFError returned a pointer, however the
internal/dnfjson module returns the Error by value.
----
Logs:
> rpmmd error in depsolve job: DNF error occurred: MarkingErrors: Error occurred when marking packages for installation: Problems in request:\nmissing packages: packit" jobId=...
This error should be parsed as a dnfjson.Error, but is cast as a generic rpmmd error instead, which triggers alerts on our side.

osbuild-worker: Correct cast of dnfjson error in depsolve job

---

internal/distro/rhel86/distro.go
internal/distro/rhel90/distro.go
test/data/manifests/rhel_85-x86_64-azure_rhui-boot.json
test/data/manifests/rhel_86-x86_64-azure_rhui-boot.json
test/data/manifests/rhel_87-x86_64-azure_rhui-boot.json
test/data/manifests/rhel_90-x86_64-azure_rhui-boot.json
test/data/manifests/rhel_91-x86_64-azure_rhui-boot.json

The `amdgpu` module causes issues on certain GPU-enabled instances on Azure and it must not be loaded by default.
Fixes: osbuild/osbuild-composer#2711
_(I also alphabetized the list of blacklisted modules because I am weird and that bothered me. If you want me to revert to the old order, just let me know.)_ 🙃

Blacklist amdgpu module on Azure images

---

cmd/gen-manifests/main.go
internal/dnfjson/cache.go
internal/dnfjson/cache_test.go
internal/dnfjson/dnfjson.go

This PR implements size-based garbage collection for the dnf-json cache directory, based on the outline in https://github.com/osbuild/osbuild-composer/issues/2446.
The workflow is as follows:
- Update the `mtime` for a repository's cache on-disk using `touchRepo()` whenever it's used in a transaction (`Depsolve()` or `FetchMetadata()`).
- Update the internal cache information when needed by calling `updateInfo()` (see note below about the frequency of this call).
- Shrink the cache to below the configured `maxSize` by calling `shrink()`.
The most important work happens in `updateInfo()`.  It collects all the information it needs from the on-disk cache directories and organises it in a way that makes it convenient for the `shrink()` function to run efficiently.  It stores three important …

Size-based cleanup for dnf-json cache directories

---

cmd/osbuild-worker/jobimpl-osbuild.go

The return statement was forgotten when the Koji target support was
added. As a result, a Job with a failed Koji upload would be reported
as successful, while at the same time having a `JobError` set.
I found this bug while adding support for multiple upload targets.

worker/osbuild: fix forgotten return when koji upload fails

---

cmd/osbuild-worker/jobimpl-osbuild.go
internal/cloudapi/v2/server.go
internal/cloudapi/v2/v2_koji_test.go
internal/target/koji_target.go
internal/worker/server.go
internal/worker/server_test.go

When the Koji target support was added to the osbuild job, based on the osbuild-koji job, the meaning of target option values got messed up.
This PR is ensuring, that the Koji target interprets values set in target options in the same way as any other target.
In addition, ensure that the worker server returns "Bad Request" if the worker tries to upload an artifact to it, but the server is configured to not accept any artifacts from workers.
Please not that this change is backward incompatible. This was done intentionally after a discussion with @ondrejbudai, because the Koji composes via Cloud API are currently not used anywhere in production.

Consolidate Koji target options values meaning

---

distribution/Dockerfile-worker

docker-compose: fix osbuild-worker unable load libcrypt.so.1

---

cmd/osbuild-pipeline/main.go
internal/distro/fedora/pipelines.go
internal/distro/image_config.go
internal/distro/rhel7/azure.go
internal/distro/rhel7/distro.go
internal/distro/rhel7/distro_test.go
internal/distro/rhel7/package_sets.go
internal/distro/rhel7/partition_tables.go
internal/distro/rhel7/pipelines.go
internal/distro/rhel7/qcow2.go
internal/distro/rhel7/stage_options.go
internal/distro/rhel84/distro_backports.go
internal/distro/rhel85/pipelines.go
internal/distro/rhel86/pipelines.go
internal/distro/rhel90/pipelines.go
internal/distro/rhel90beta/pipelines.go
internal/distroregistry/distroregistry.go
internal/osbuild2/disk.go
internal/osbuild2/grub2_legacy_stage.go
internal/osbuild2/grub2_legacy_stage_test.go
internal/osbuild2/qemu_stage.go
internal/osbuild2/qemu_stage_test.go
internal/osbuild2/sfdisk_stage.go
internal/osbuild2/sfdisk_stage_test.go
internal/osbuild2/sgdisk_stage.go
internal/osbuild2/sgdisk_stage_test.go
test/data/manifests/rhel_7-x86_64-azure_rhui-boot.json
test/data/manifests/rhel_7-x86_64-qcow2-boot.json
test/data/manifests/rhel_7-x86_64-qcow2_customize-boot.json
tools/test-case-generators/repos.json

Based on the RHEL 8.6 pipelines, needs a special buildroot with two
extra packages: python3-iniparse and python3-PyYAML.
Only x86_64 support for now.
This is based on to of #2537

[rhel7] add initial support (qcow2, vhd, azure-rhui)

---

internal/distro/rhel7/azure.go
internal/distro/rhel7/distro.go
internal/distro/rhel7/distro_test.go

1. Broken: specifies packages that aren't available in the repositories (langpacks-en and dhcp-client).
2. Not needed.

Remove vhd image type from RHEL 7

---

.packit.yaml
Makefile
osbuild-composer.spec
schutzbot/mockbuild.sh
tools/rpm_spec_add_provides_bundle.sh

Remove all Go dependecies
Add Start and End marker comments for bundling information
Add '-k' to goprep to preserve the vendor directory
Add script to update the RPM spec file to generate the indication lines based on vendor/modules.txt
Run the new script as a post-upstream-clone hook
Run the new script on the generated spec file before generating the RPM

Fedora - Use vendor instead of rpm dependencies

---

dnf-json

When a DepsolveError exception occurs, the error message would print the packages in the request.  When the request arguments changed, the error message handling wasn't updated and would fail to produce the correct error message.
Compile a list of packages from all transactions and print them in the error message as a comma-separated list.
Before:
```
$ composer-cli blueprints show conflict
name = "conflict"
description = ""
version = "0.0.1"
modules = []
groups = []
distro = ""
[[packages]]
name = "mysql"
[[packages]]
name = "mariadb"
$ composer-cli compose start conflict qcow2
ERROR: DepsolveError: DNF error occurred: InternalError: Failed to unmarshal dnf-json error output "": unexpected end of JSON input
code
```
After:
```
$ composer-cli compose start conflict qcow2
ERROR: …
```

dnf-json: fix depsolve error handling

---

test/cases/image_tests.sh

COMPOSER-1397 temporarily skipped azure-rhui image. Now that we test on
rhel 8.7, this skip can be removed.

test/cases: remove test skip

---

test/cases/image_tests.sh

image-tests: skip azure-rhui test on rhel-86

---

cmd/osbuild-worker/jobimpl-koji-finalize.go
internal/worker/clienterrors/errors.go
internal/worker/server.go

set a job error when a heartbeat fails & fix koji-finalize job

---

internal/distro/rhel86/distro.go
test/data/manifests/rhel_85-aarch64-edge_commit-boot.json
test/data/manifests/rhel_85-aarch64-edge_container-boot.json
test/data/manifests/rhel_85-x86_64-edge_commit-boot.json
test/data/manifests/rhel_85-x86_64-edge_commit_rt-boot.json
test/data/manifests/rhel_85-x86_64-edge_container-boot.json

RHEL 8.5 doesn't have FDO and it's not installed, but we were enabling the service for it in edge.

distro: don't enable fdo-client service on RHEL 8.5

---

Schutzfile
templates/packer/worker.pkr.hcl
tools/appsre-build-worker-packer.sh

Let's stay updated!
Also, let's remove 8.4 and 8.5 from Schutzfile, I strongly believe that it's
not used anywhere.

packer: use 8.6 as a base for RHEL images

---

cmd/osbuild-playground/playground.go
internal/distro/fedora/distro.go
internal/distro/fedora/manifests.go
internal/distro/fedora/pipelines.go
internal/manifest/commit.go
internal/manifest/live.go
internal/manifest/manifest.go
internal/manifest/os.go
test/data/manifests/fedora_34-aarch64-fedora_iot_commit-boot.json
test/data/manifests/fedora_34-aarch64-fedora_iot_container-boot.json
test/data/manifests/fedora_34-x86_64-container-boot.json
test/data/manifests/fedora_34-x86_64-fedora_iot_commit-boot.json
test/data/manifests/fedora_34-x86_64-fedora_iot_commit_debug-boot.json
test/data/manifests/fedora_34-x86_64-fedora_iot_container-boot.json
test/data/manifests/fedora_35-aarch64-fedora_iot_commit-boot.json
test/data/manifests/fedora_35-aarch64-fedora_iot_container-boot.json
test/data/manifests/fedora_35-x86_64-container-boot.json
test/data/manifests/fedora_35-x86_64-fedora_iot_commit-boot.json
test/data/manifests/fedora_35-x86_64-fedora_iot_commit_debug-boot.json
test/data/manifests/fedora_35-x86_64-fedora_iot_container-boot.json
test/data/manifests/fedora_36-aarch64-fedora_iot_commit-boot.json
test/data/manifests/fedora_36-aarch64-fedora_iot_container-boot.json
test/data/manifests/fedora_36-x86_64-container-boot.json
test/data/manifests/fedora_36-x86_64-fedora_iot_commit-boot.json
test/data/manifests/fedora_36-x86_64-fedora_iot_commit_debug-boot.json
test/data/manifests/fedora_36-x86_64-fedora_iot_container-boot.json

All arguments that has reasonable defaults and where querying the package set chain as well as serialisation works without
the defaults being overridden, should be made public fields rather than arguments to the constructor.
It is the caller's responsibility not to change the parameters between querying the package set chains and serialising the
manifest, but otherwise they are free to reuse the pipeline objects and modify them freely.

manifest/os: minor refactoring to make more arguments optional

---

test/cases/filesystem.sh

There are a list of mountpoints in the [documentation](https://www.osbuild.org/guides/blueprint-reference/blueprint-reference.html#filesystem-support), but only
some of this mountpoints are tested in the test filesystem.sh. Add the
ones missing.

test/cases: add new mountpoints in filesystem.sh

---

internal/distro/fedora/distro.go
internal/distro/fedora/manifests.go
internal/distro/fedora/package_sets.go
internal/manifest/os.go
test/data/manifests/fedora_34-aarch64-ami-boot.json
test/data/manifests/fedora_34-x86_64-fedora_iot_commit-boot.json
test/data/manifests/fedora_34-x86_64-fedora_iot_commit_debug-boot.json
test/data/manifests/fedora_34-x86_64-fedora_iot_container-boot.json
test/data/manifests/fedora_35-aarch64-ami-boot.json
test/data/manifests/fedora_35-x86_64-fedora_iot_commit-boot.json
test/data/manifests/fedora_35-x86_64-fedora_iot_commit_debug-boot.json
test/data/manifests/fedora_35-x86_64-fedora_iot_container-boot.json
test/data/manifests/fedora_36-aarch64-ami-boot.json
test/data/manifests/fedora_36-x86_64-fedora_iot_commit-boot.json
test/data/manifests/fedora_36-x86_64-fedora_iot_commit_debug-boot.json
test/data/manifests/fedora_36-x86_64-fedora_iot_container-boot.json

Simplify the package sets definitions in the distribution by moving the required boot loader packages into the pipeline definitions.
Also fixes a bug, see individual patches.

manifest/os: move over bootloader packages

---

internal/distro/distro.go
internal/distro/fedora/distro.go
internal/distro/rhel7/distro.go
internal/distro/rhel8/distro.go
internal/distro/rhel90/distro.go

This is a micro pr to move the `isMountpointAllowed` function to the common distro package since this function is shared used in multiple distro packages.

distro: move isMountpointAllowed

---

distribution/Dockerfile-worker

Additional packages are required to build the docker worker. This fix updates the builder
container to install the required libraries and then create the worker binary.

Dockerfile: update worker builder

---

test/cases/diff-manifests.sh

Tests: Use unified diff format - easier to read

---

test/cases/api/common/s3.sh

tag VMs with 'gitlba-ci-test' images so they can get removed with
cloud cleaner

tag created vmare VMs

---

internal/blueprint/blueprint.go
internal/blueprint/blueprint_test.go
internal/osbuild/users_stage.go
internal/osbuild/users_stage_test.go

This commit changes blueprint behavior to always store the hash of the
password for the 'customizations.user' accounts. Note that missing or
blank passwords are not hashed and should be dealt with at a lower
layer.
Resolves: rhbz#2107358

blueprint: Hash all user passwords

---

.gitlab-ci.yml
schutzbot/ci_details.sh
schutzbot/save_journal.sh
schutzbot/upload_artifacts.sh
test/cases/api.sh
test/cases/aws.sh
test/cases/azure.sh
test/cases/container-upload.sh
test/cases/gcp.sh
test/cases/installers.sh
test/cases/manifest_tests.sh
test/cases/ostree-ng.sh
test/cases/ostree-raw-image.sh
test/cases/ostree-rebase.sh
test/cases/ostree-simplified-installer.sh
test/cases/ostree.sh
test/cases/regression-old-worker-new-composer.sh
test/cases/upgrade8to9.sh
test/cases/vmware.sh
tools/libvirt_test.sh
tools/provision.sh
tools/s3_test.sh

We want to be able to safely gather any artifacts without worrying about
any possible secrets leaking. Every artifacts that we want to upload
will now have to be placed in /tmp/artifacts which will then be uploaded
to S3 by the executor and link to the artifacts will be provided in the
logs. Only people with access to our AWS account will be able to see the artifacts.

ci/tests: Change the way artifacts are collected

---

.github/workflows/coverity_scan.yml

It was failing on:
vendor/github.com/proglottis/gpgme/data.go:4:11: fatal error: gpgme.h: No such file or directory
Let's install this package before running the check, I verified that this
fix works locally.
@atodorov This check was failing for 16 days so I presume that nobody checks it. Is it even useful if nobody checks its result?

github: fix the coverity scan action

---

.gitlab-ci.yml
schutzbot/upload_artifacts.sh
test/cases/aws.sh
test/cases/filesystem.sh

Filesystems test update

---

cmd/osbuild-worker/jobimpl-koji-finalize.go
internal/cloudapi/v2/handler.go

Fixed one error message and extended a code comment.
Followup on #2844 

Koji cloud upload fixups

---

cmd/osbuild-playground/playground.go
cmd/osbuild-worker/config.go
cmd/osbuild-worker/jobimpl-container-resolve.go
cmd/osbuild-worker/jobimpl-osbuild.go
cmd/osbuild-worker/main.go
internal/container/resolver.go
internal/osbuild/osbuild-exec.go
internal/weldr/api.go
internal/worker/clienterrors/errors.go
internal/worker/json.go
internal/worker/server.go

The osbuild worker gained a new configuration section `containers` with a new key `auth_file_path` to be able to specify a `containers-auth.conf(5)` file to be used for request. All container resolution is moved to a new worker job type so that there is only one central place that does container resolution. The containers auth file, if specified, is also forwarded to `osbuild` via the `REGISTRY_AUTH_FILE` file that is then used by `skopeo` in the `org.osbuild.skopeo` source.

Container embedding: support accessing protected resources

---

.gitlab-ci.yml
cmd/gen-manifests/main.go
cmd/gen-manifests/workerqueue.go
test/cases/diff-manifests.sh

Partially addresses issue #2767.
Changes for `gen-manifests`:
- Prints the final error summary on stderr.
- Only print progress update after receiving a message on the message queue.  This makes the command less noisy in CI where the carriage return `\r` produces a new line and constant progress updates were producing new lines.  The logic relies on the fact that each job reports when its finished with a line on the message queue, which could change, but for now is adequate.
- Support `-arches`, `-distros`, and `-images` flags.  Each supports is a comma-separated list of strings for manifest generation filtering.
- Appends the text `[failed]` to the `Finished` message for failed jobs.
Changes for `diff-manifests` test:
- Print all the output from `gen-manifests`.
- The test now fails if …

Improvements for gen-manifests tool and Manifest-diff test

---

Schutzfile
internal/container/client.go
internal/container/client_test.go
internal/distro/rhel8/distro.go
internal/distro/rhel8/pipelines.go
internal/distro/rhel90/distro.go
internal/distro/rhel90/pipelines.go
internal/osbuild/containers_storage_conf_stage.go
internal/osbuild/containers_storage_conf_stage_test.go
osbuild-composer.spec
test/cases/ostree-ng.sh
test/cases/ostree.sh
test/data/ansible/check_ostree.yaml

Add support for embedding containers in OSTree commits by storing them in `/usr/share/containers/storage`. The storage engine is configured accordingly so that this extra location is automatically taken into account by e.g. `podman`.

Embedding container in OSTree commits

---

.gitlab-ci.yml
schutzbot/upload_artifacts.sh
test/cases/diff-manifests.sh

Contents of this folder are uploaded to S3 with shutzbot/upload_artifacts.sh
Also fixing epel installation in the mentioned script.

CI: drop /tmp/artifacts upload to Gitlab

---

internal/cloudapi/v2/handler.go
internal/cloudapi/v2/server.go
internal/cloudapi/v2/v2_koji_test.go
internal/prometheus/job_metrics.go
internal/weldr/api.go
internal/weldr/compose_test.go
internal/worker/server.go
internal/worker/server_test.go

- updating the prometheus metrics to accept the `arch` label

metrics: add `arch` label to prometheus metrics

---

internal/distro/rhel90/package_sets.go
internal/distro/rhel90/pipelines.go
test/cases/diff-manifests.sh
test/data/manifests/centos_9-aarch64-edge_installer-boot.json
test/data/manifests/centos_9-aarch64-edge_installer_with_users-boot.json
test/data/manifests/centos_9-aarch64-image_installer-boot.json
test/data/manifests/centos_9-aarch64-image_installer_with_users-boot.json
test/data/manifests/centos_9-x86_64-edge_installer-boot.json
test/data/manifests/centos_9-x86_64-edge_installer_with_users-boot.json
test/data/manifests/centos_9-x86_64-image_installer-boot.json
test/data/manifests/centos_9-x86_64-image_installer_with_users-boot.json
test/data/manifests/rhel_90-aarch64-edge_installer-boot.json
test/data/manifests/rhel_90-aarch64-edge_installer_with_users-boot.json
test/data/manifests/rhel_90-aarch64-image_installer-boot.json
test/data/manifests/rhel_90-aarch64-image_installer_with_users-boot.json
test/data/manifests/rhel_90-x86_64-edge_installer-boot.json
test/data/manifests/rhel_90-x86_64-edge_installer_with_users-boot.json
test/data/manifests/rhel_90-x86_64-image_installer-boot.json
test/data/manifests/rhel_90-x86_64-image_installer_with_users-boot.json
test/data/manifests/rhel_91-aarch64-edge_installer-boot.json
test/data/manifests/rhel_91-aarch64-edge_installer_with_users-boot.json
test/data/manifests/rhel_91-aarch64-image_installer-boot.json
test/data/manifests/rhel_91-aarch64-image_installer_with_users-boot.json
test/data/manifests/rhel_91-x86_64-edge_installer-boot.json
test/data/manifests/rhel_91-x86_64-edge_installer_with_users-boot.json
test/data/manifests/rhel_91-x86_64-image_installer-boot.json
test/data/manifests/rhel_91-x86_64-image_installer_with_users-boot.json

The RHEL 9 and CS9 ISOs would fail to boot over UEFI HTTP.  Added the necessary dracut and kernel modules to support this.
The second commit adds all kernel modules that are in the official RHEL 9 ISO's initramfs and were not on ours.
See rhbz#2030730
Manifests regenerated for each commit.  Image info dropped for all updated manifests that had any.

Fix UEFI HTTP boot for RHEL 9 ISOs

---

templates/composer.yml

This causes the deployment to fail.

templates/composer: Remove non-existent secret

---

internal/distro/rhel7/azure.go
test/data/manifests/rhel_7-x86_64-azure_rhui-boot.json

This was done in RHEL 8, 9 but RHEL 7 was not yet merged so this was missed there. See e.g. 5c1530ee53fec2649eda24bd635e4a75275b12e2
See also  #2706 and #2717

distro/rhel7: blacklist skx_edac,intel_cstate kernel modules on azure

---

internal/container/client.go

This issue was found by Coverity:
```
Error: DEADCODE (CWE-561): [#def1]
osbuild-composer-58/_build/src/github.com/osbuild/osbuild-composer/internal/container/client.go:386: cond_null: Condition "err != nil", taking false branch. Now the value of "err" is "nil".
osbuild-composer-58/_build/src/github.com/osbuild/osbuild-composer/internal/container/client.go:390: null: At condition "err != nil", the value of "err" must be "nil".
osbuild-composer-58/_build/src/github.com/osbuild/osbuild-composer/internal/container/client.go:390: dead_error_condition: The condition "err != nil" cannot be true.
osbuild-composer-58/_build/src/github.com/osbuild/osbuild-composer/internal/container/client.go:391: dead_error_line: Execution cannot reach this statement: "<temporary>.$0 = container....".
389|
390| …
```

internal/container: delete leftover dead code

---

templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml

This changed in #2845, and the dashboards stopped working properly as
they were looking for `osbuild+:arch`.

templates/dashboards: Drop arch from osbuild jobtype

---

test/cases/ostree-ng.sh

Due to Edge device security reason, `edge-simplified-installer` and `edge-installer` support UEFI only.

test: Remove BIOS installation test because edge-installer supports UEFI only

---

templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml

Add the ability to filter the build job types by architecture using the `arch`
dropdown. This depends on: https://github.com/osbuild/osbuild-composer/pull/2845
Test dashboard:
https://grafana.stage.devshift.net/d/image-builder-worker-arch/image-builder-worker-arch-test?orgId=1

templates/dashboard: filter worker dashboard on `arch`

---

cmd/osbuild-worker/jobimpl-container-resolve.go
cmd/osbuild-worker/jobimpl-depsolve.go
cmd/osbuild-worker/jobimpl-koji-finalize.go
cmd/osbuild-worker/jobimpl-koji-init.go
cmd/osbuild-worker/jobimpl-osbuild.go
internal/cloudapi/v2/handler.go
internal/cloudapi/v2/server.go
internal/cloudapi/v2/v2_koji_test.go
internal/cloudapi/v2/v2_multi_tenancy_test.go
internal/cloudapi/v2/v2_test.go
internal/target/targetresult_test.go
internal/weldr/compose_test.go
internal/worker/clienterrors/errors.go
internal/worker/json_test.go
internal/worker/server.go
internal/worker/server_test.go

The alternative is keeping the ellipsis operator, but always only adding the 1st element as details to the job error.

clienterrors: Remove ellipsis operator

---

test/cases/installers.sh
test/cases/ostree-ng.sh

tests: Workaround for mkksiso options coming from newer lorax RPM

---

cmd/osbuild-worker/main.go

The worker assumes that when running on AWS an autoscale is defined. If not defined, the worker crashes.
This crash occurred when triggering a build via the Weldr API while running a local installation of osbuild-composer and osbuild-worker on an EC2 instance 

worker: fix crash if no autoscale instance is defined

---

.gitlab-ci.yml
internal/blueprint/customizations.go
internal/blueprint/customizations_test.go
internal/distro/fedora/distro.go
internal/distro/fedora/images.go
internal/distro/rhel7/distro.go
internal/distro/rhel8/distro.go
internal/distro/rhel8/pipelines.go
internal/distro/rhel90/distro.go
internal/distro/rhel90/pipelines.go
internal/manifest/os.go
internal/osbuild/oscap_remediation_stage.go
internal/osbuild/oscap_remediation_stage_test.go
internal/oscap/oscap.go
test/cases/oscap.sh

- blueprint customizations for openscap integration
- osbuild2 stage for oscap remediatoin
- validation of customization options
- add oscap stage to fedora, rhel87 and rhel91 non-rpmostree builds
Depends on:
https://github.com/osbuild/osbuild/pull/1033

oscap: implement OpenSCAP build remediation

---

cmd/osbuild-mock-openid-provider/main.go
test/cases/api.sh
test/cases/api/common/common.sh
test/cases/oscap.sh
tools/koji-compose.py

Extend the implementation of mock openid server to take the `grant_type`
into consideration for the `/token` endpoint.
In addition to the previously supported `refresh_topen`, the
implementation now supports also `client_credentials`.
This is necessary to make it possible to use the mock server in
the `koji-osbuild` CI, because the builder plugin uses
`client_credentials` to get access token.
The implementation behaves in the following way:
- For `refresh_token` grant type, it takes the `refresh_token` value
from the request and adds it to the `rh-org-id` field in the custom
claim, which is part of the returned token.
- For `client_credentials` grant type, it takes the `client_secret`
value from the request and adds it to the `rh-org-id` field in the
custom claim, which is part of the …

osbuild-mock-openid-provider: support `client_credentials` grant type

---

.gitlab-ci.yml
test/cases/ostree-ng.sh
test/cases/ostree-rebase-bios.sh
test/cases/ostree-rebase-uefi.sh

Medium runners might be enough and will give us more jobs in parallel

CI: use only medium runners on Openstack

---

internal/client/compose_test.go
internal/disk/disk.go
internal/disk/disk_test.go
internal/disk/partition_table.go
internal/disk/path_policy.go
internal/disk/path_policy_test.go
internal/disk/path_tree_test.go
internal/disk/path_trie.go
internal/distro/distro.go
internal/distro/fedora/distro.go
internal/distro/fedora/distro_test.go
internal/distro/rhel7/distro.go
internal/distro/rhel7/distro_test.go
internal/distro/rhel8/distro.go
internal/distro/rhel8/distro_test.go
internal/distro/rhel90/distro.go
internal/distro/rhel90/distro_test.go
test/cases/filesystem.sh

The interesting commit is the last one, with the commit message:
Since the LVM support was added to all distros, our disk related code is adaptive, i.e. we will set the correct BLS and grub2 prefix if there a `boot` partiton is present in the layout after all customizations happen, which includes LVMification. One thing that was not yet fully working was layouts that do not yet have a `/boot` partition but allow LVMification. In that case `NewPartitionTable` and if `/boot` was the first (or only) customization, would LVMify the partition which in turn would create the `/boot` partition; but after `newPT.ensureLVM()` the call to `newPT.createFilesystem` with `/boot` would try to create another `/boot` mountpoint. In order to deal with this situation correctly we are now using a two phase …

Allow for `/boot` to be customized

---

.gitlab-ci.yml

ci: Update runner to RHEL 9.0 to enable test in nightly pipeline

---

internal/distro/rhel9/package_sets.go
internal/distro/rhel9/pipelines.go
test/data/manifests/centos_9-aarch64-edge_installer-boot.json
test/data/manifests/centos_9-aarch64-edge_installer_with_users-boot.json
test/data/manifests/centos_9-aarch64-image_installer-boot.json
test/data/manifests/centos_9-aarch64-image_installer_with_users-boot.json
test/data/manifests/centos_9-x86_64-edge_installer-boot.json
test/data/manifests/centos_9-x86_64-edge_installer_with_users-boot.json
test/data/manifests/centos_9-x86_64-image_installer-boot.json
test/data/manifests/centos_9-x86_64-image_installer_with_users-boot.json
test/data/manifests/rhel_90-aarch64-edge_installer-boot.json
test/data/manifests/rhel_90-aarch64-edge_installer_with_users-boot.json
test/data/manifests/rhel_90-aarch64-image_installer-boot.json
test/data/manifests/rhel_90-aarch64-image_installer_with_users-boot.json
test/data/manifests/rhel_90-x86_64-edge_installer-boot.json
test/data/manifests/rhel_90-x86_64-edge_installer_with_users-boot.json
test/data/manifests/rhel_90-x86_64-image_installer-boot.json
test/data/manifests/rhel_90-x86_64-image_installer_with_users-boot.json
test/data/manifests/rhel_91-aarch64-edge_installer-boot.json
test/data/manifests/rhel_91-aarch64-edge_installer_with_users-boot.json
test/data/manifests/rhel_91-aarch64-image_installer-boot.json
test/data/manifests/rhel_91-aarch64-image_installer_with_users-boot.json
test/data/manifests/rhel_91-x86_64-edge_installer-boot.json
test/data/manifests/rhel_91-x86_64-edge_installer_with_users-boot.json
test/data/manifests/rhel_91-x86_64-image_installer-boot.json
test/data/manifests/rhel_91-x86_64-image_installer_with_users-boot.json

distro/image-installer: remove nvmf dracut module for RHEL-9.1

---

internal/distro/rhel8/distro.go
internal/distro/rhel9/distro.go
internal/manifest/os.go
test/cases/oscap.sh

Since the oscap remediation stage in osbuild runs the oscap pacakge in `chroot`, it is not possible to have
the packages in the build root. The packages are needed in the image itself.

distro: add oscap packages to image

---

cmd/osbuild-worker/jobimpl-osbuild.go
internal/common/distro.go

When running an osbuild job, we read `/etc/redhat-release` to get the host OS name to attach as metadata to the job result.
Only Fedora and RHEL ship this file, which makes the osbuild job always fail on other distributions.
The main reason to report host OS back to the worker server is due to Koji composes and the koji-finalize job, which pushes it to Koji. The motivation is to have enough information to potentially re-instantiate / identify the original builder host OS. There are no specific requirements on the string.
Modify the code to use `/etc/os-release` to determine the host OS. Fall back to using `linux` as the host OS, in case reading `os-release` fails, log the error and continue with the job. The `linux` fallback is suggested by the `os-release` spec [1]
[1] …

worker/osbuild: use `os-release` to determine host OS

---

internal/distro/rhel8/pipelines.go
internal/distro/rhel9/pipelines.go
internal/image/ostree_installer.go
test/cases/ostree-ng.sh
test/data/manifests/centos_8-x86_64-edge_installer-boot.json
test/data/manifests/centos_8-x86_64-edge_installer_with_users-boot.json
test/data/manifests/centos_9-x86_64-edge_installer-boot.json
test/data/manifests/centos_9-x86_64-edge_installer_with_users-boot.json
test/data/manifests/fedora_35-aarch64-fedora_iot_installer-boot.json
test/data/manifests/fedora_35-aarch64-fedora_iot_installer_with_users-boot.json
test/data/manifests/fedora_35-x86_64-fedora_iot_installer-boot.json
test/data/manifests/fedora_35-x86_64-fedora_iot_installer_with_users-boot.json
test/data/manifests/fedora_36-aarch64-fedora_iot_installer-boot.json
test/data/manifests/fedora_36-aarch64-fedora_iot_installer_with_users-boot.json
test/data/manifests/fedora_36-x86_64-fedora_iot_installer-boot.json
test/data/manifests/fedora_36-x86_64-fedora_iot_installer_with_users-boot.json
test/data/manifests/rhel_8-x86_64-edge_installer-boot.json
test/data/manifests/rhel_8-x86_64-edge_installer_with_users-boot.json
test/data/manifests/rhel_84-x86_64-edge_installer-boot.json
test/data/manifests/rhel_84-x86_64-edge_installer_with_users-boot.json
test/data/manifests/rhel_85-x86_64-edge_installer-boot.json
test/data/manifests/rhel_85-x86_64-edge_installer_with_users-boot.json
test/data/manifests/rhel_86-x86_64-edge_installer-boot.json
test/data/manifests/rhel_86-x86_64-edge_installer_with_users-boot.json
test/data/manifests/rhel_87-x86_64-edge_installer-boot.json
test/data/manifests/rhel_87-x86_64-edge_installer_with_users-boot.json
test/data/manifests/rhel_90-x86_64-edge_installer-boot.json
test/data/manifests/rhel_90-x86_64-edge_installer_with_users-boot.json
test/data/manifests/rhel_91-x86_64-edge_installer-boot.json
test/data/manifests/rhel_91-x86_64-edge_installer_with_users-boot.json

We supported hybrid boot for edge installers in RHEL 9.0 but we regressed when unifying the distro definitions.
From the history it seems we never supported BIOS on RHEL 8.x, but we can add it there as well.
Fixes [RHBZ#2110864](https://bugzilla.redhat.com/show_bug.cgi?id=2110864)

Support hybrid boot for edge installers

---

Schutzfile
internal/cloudapi/v2/handler.go
internal/distro/distro.go
internal/distro/rhel8/pipelines.go
internal/distro/rhel9/pipelines.go
internal/osbuild/rhsm_facts_stage.go
internal/osbuild/rhsm_facts_stage_test.go
internal/weldr/api.go
osbuild-composer.spec

Work has been ongoing to store RHSM facts into built images. This PR is part of the `osbuild-composer` side of things but has some problems to solve and/or discuss.
In this initial pull request only the `ApiType` used to request the compose is stored in the `rhsm.facts` file eventually created by `osbuild`.

Add the `rhsm.facts` stage.

---

.gitlab-ci.yml

We don't support regression-bigiso and koji tests in nightly pipelines
so don't run them.

CI: update test execution on nightly pipelines

---

cmd/gen-manifests/main.go

When the user specifies any of the distro, arch, or image type values to filter generation, invalid combinations would cause a panic, which made it hard to filter requests based just on an image type.
Instead of failing, print an error message to inform the user, but continue with the rest of the jobs.
This way, a user is informed that a certain combination is invalid if they make a mistake, but can also filter on a single image type and only get valid manifests out of the run.
This change enables running (for example):
```
go run ./cmd/gen-manifests -images edge-installer,installer
```
without worrying about distros or architectures that don't support those image types.
The error message is printed to avoid situations where typos create only invalid requests that are silently skipped.

gen-manifests: don't fail on invalid distro-arch-image combos

---

test/cases/aws.sh

For some tests, using a micro instance type is not enough. Changing to t3.medium will solve these issues.
The PR also includes conversation around CIV release process.

test/aws.sh: use bigger instance for `cloud-image-val-test`

---

test/cases/gcp.sh

All EXIT traps are cleared on line 280 so the cleanup trap is never run
and VMs are waiting for 4 hours to get cleaned by
scheduled-cloud-cleaner. Run the cleanup at the end and rely on
scheduled-cloud-cleaner only in case of failures before that.

test/gcp: Run cleanup function at the end

---

cmd/osbuild-service-maintenance/db_test.go
cmd/osbuild-worker/jobimpl-awsec2.go
cmd/osbuild-worker/main.go
internal/cloud/awscloud/awscloud.go
internal/cloudapi/v2/errors.go
internal/cloudapi/v2/handler.go
internal/cloudapi/v2/openapi.v2.gen.go
internal/cloudapi/v2/openapi.v2.yml
internal/cloudapi/v2/v2_koji_test.go
internal/cloudapi/v2/v2_test.go
internal/jobqueue/fsjobqueue/fsjobqueue.go
internal/jobqueue/jobqueuetest/jobqueuetest.go
internal/worker/json.go
internal/worker/server.go
pkg/jobqueue/dbjobqueue/dbjobqueue.go
pkg/jobqueue/jobqueue.go
test/cases/api.sh
test/cases/api/aws.sh

Create multiple aws images from a single compose

---

internal/distro/image_config.go
internal/distro/rhel8/distro.go
internal/distro/rhel8/pipelines.go
internal/distro/rhel9/distro.go
internal/distro/rhel9/pipelines.go
internal/osbuild/gcp_guest_agent_conf_stage.go
internal/osbuild/gcp_guest_agent_conf_stage_test.go
osbuild-composer.spec
test/data/manifests/centos_8-x86_64-gce-boot.json
test/data/manifests/centos_9-x86_64-gce-boot.json
test/data/manifests/rhel_8-x86_64-gce-boot.json
test/data/manifests/rhel_8-x86_64-gce_rhui-boot.json
test/data/manifests/rhel_84-x86_64-gce-boot.json
test/data/manifests/rhel_84-x86_64-gce_rhui-boot.json
test/data/manifests/rhel_85-x86_64-gce-boot.json
test/data/manifests/rhel_85-x86_64-gce_rhui-boot.json
test/data/manifests/rhel_86-x86_64-gce-boot.json
test/data/manifests/rhel_86-x86_64-gce_rhui-boot.json
test/data/manifests/rhel_87-x86_64-gce-boot.json
test/data/manifests/rhel_87-x86_64-gce_rhui-boot.json
test/data/manifests/rhel_90-x86_64-gce-boot.json
test/data/manifests/rhel_90-x86_64-gce_rhui-boot.json
test/data/manifests/rhel_91-x86_64-gce-boot.json
test/data/manifests/rhel_91-x86_64-gce_rhui-boot.json

- Add new GCP guest-agent config stage
- Add stage to RHEL8 and RHEL90 distro definitions
- Add GCPGuestAgentConf to ImageConfig
- Regenerate test cases for RHEL8 and RHEL90
- osbuild-composer.spec version bump for osbuild dependency
- Schutzfile osbuild commit hash update to include new GCP guest-agent config

Add GCP guest agent config stage

---

cmd/osbuild-composer/composer.go
internal/weldr/api.go

For each of the supported distros start a goroutine to depsolve
'filesystem' which will preload the metadata making subsequent responses
faster.
This is safe to do without limits because we only supposed a limited
number of distros, and without additional locking because this is the
the same as hitting the API with multiple depsolve requests at the same
time.
I didn't add testing for this because I'm not sure it can be tested. Ideas are welcome :)

weldr: Preload metadata at startup

---

internal/distro/rhel9/package_sets.go

In podman v4.0.0 the default network backend was switched from cni to netavark.  However, podman will choose cni if there are already containers, images, or cni networks preset on a system [1].
Starting with podman v4.2.0, containernetworking-plugins is no longer a hard requirement for podman.  So when an edge commit is built with an embedded container, podman v4.2.0+ will choose the cni network and fail with an error because the plugin isn't installed.
Adding the package explicitly alongside podman to avoid this issue with future RHEL 9.1 edge builds when they include containers.
This change does not affect test manifests.  The package is already included in manifests as a dependency of podman < v4.2.0.
See rhbz#2123210
[1] https://github.com/containers/common/blob/a083f790abf21048518f2d6 …

rhel9: explicitly add containernetworking-plugins to edge

---

.gitlab-ci.yml

tests: add aarch64 rhel-9.0 runner to API tests

---

schutzbot/update_github_status.sh

The release branch can be tracked by stage deployments to make sure
CI is green before deploying to stage.

schutzbot: Fast-forward release branch after green main run

---

cmd/osbuild-composer-dbjobqueue-tests/main_test.go
pkg/jobqueue/dbjobqueue/dbjobqueue.go

Hello,
when `Close()` is called in all cases it ends up with "Error unlistening for jobs in dequeue" because in the defer block then driver performs `Exec` call with the caller's context, it is already done.

dbjobqueue: use background context when closing listener

---

templates/packer/worker.pkr.hcl

This job is failing with "ResourceNotReady: exceeded wait attempts".
https://www.packer.io/plugins/builders/amazon#resourcenotready-error

templates/packer: Increase aws timeouts for rhel-8-aarch64

---

internal/distro/fedora/distro.go
internal/distro/fedora/images.go
internal/distro/image_config.go
internal/distro/image_config_test.go
internal/distro/rhel7/azure.go
internal/distro/rhel7/distro.go
internal/distro/rhel7/pipelines.go
internal/distro/rhel7/qcow2.go
internal/distro/rhel8/distro.go
internal/distro/rhel8/pipelines.go
internal/distro/rhel9/distro.go
internal/distro/rhel9/pipelines.go

These changes are required in order to enable unifying the `vhd` and `azure-rhui` image definitions. Detailed reasoning for each change is described in each commit message.

distro/`ImageConfig`: use pointers to simple types and reflection in `InheritFrom()`

---

templates/packer/worker.pkr.hcl

appsre: disable aarch64 AMI creation temporarily

---

test/cases/aws.sh

We were using `latest` as tag, this can be dangerous as it's the default
tag, an anyone can accidentally update it. Using `prod` is safer.
Also use dev container image if the test script is running in CIV CI.

test: change CIV tag

---

.gitlab-ci.yml
test/cases/aws.sh

Enable integration testing on aarch64

---

.gitignore
internal/common/slogger/logrus.go
internal/common/slogger/logrus_test.go
internal/common/slogger/noop.go
pkg/jobqueue/dbjobqueue/dbjobqueue.go
pkg/jobqueue/jobqueue.go

Thanks for extracting jobqueue into pkg/. Now, in order to use it in our project, we have two changes to make:
* We rely on database/sql connection pool instead of pgx.
* We do not use logrus.
This patch aims to solve the latter by creating a very simple facade via interface called `SimpleLogger` (naming things is hard bring your own suggestions). It seems the jobqueue only uses logging messages at info level and then error level, so the interface only supports these to keep things simple. It makes sense, as a user of any library you typically want to either enable or disable logging, verbosity mapping has always been problematic thing to solve.
The patch introduces a logrus implementation and a noop implementation. It will require a change in all callers of the New function, I tried my …

Introduce logging adapter for jobqueue

---

.gitlab-ci.yml
test/data/upgrade8to9/upgrade_prepare.sh

CI: Introduce x86_64 rules

---

test/cases/diff-manifests.sh

Distro version branches aren't synced to GitLab, so we will need to fetch them from GitHub directly.
This is required for any PR made against any branch other than main.

diff-manifest: fetch base branch from GitHub

---

test/cases/vmware.sh
tools/libvirt_test.sh

Specify additional package in blueprint for tests

---

pkg/jobqueue/dbjobqueue/dbjobqueue.go

Trying to reproduce and debug an issue with the db jobqueue tests.

pkg/dbjobqueue: fix dequeue constraint error

---

internal/dnfjson/cache.go
internal/dnfjson/cache_test.go
internal/dnfjson/dnfjson.go
internal/dnfjson/dnfjson_test.go

This is a proposed change, so I'm making it a Draft for now. Discussion will be in #2887
This caches the results of dnf-json for 60s, the cache is based on the Request made, so different distros, repos, search terms are considered different. It returns the results for 60s and then makes a new request to dnf-json, and it cleans up the map when CleanCache() is called so that memory use doesn't go crazy.
The result of this is that when using cockpit-composer to page through lists of packages, or explore package dependencies, it speeds things up 'a whole bunch'. The only possible drawback I see is that every 60s it takes a bit longer to get results.

Cache the results of dnf-json dump and search commands

---

templates/packer/worker.pkr.hcl

Because the rhel-8 images share the same name, and `force_deregister` is true, packer will always deregister one of them.
---
These still conform to the ` '^osbuild-composer-worker.*'` sharing regex

templates/packer: Append distro and architecture to the ami name

---

internal/distro/fedora/partition_tables.go
internal/distro/rhel7/azure.go
internal/distro/rhel7/partition_tables.go
internal/distro/rhel8/azure.go
internal/distro/rhel8/partition_tables.go
internal/distro/rhel9/azure.go
internal/distro/rhel9/partition_tables.go

Use storage capacity multiple constants in partition tables of all distro definitions.

distro: use storage capacity multiple constants in partition tables

---

test/cases/upgrade8to9.sh
test/data/upgrade8to9/upgrade_prepare.sh
test/data/upgrade8to9/upgrade_verify.sh

shared_lib.sh now contains some more helper functions and the verification script uses them. Copy it over so that we can source it. Also install all other dependencies before the actual upgrade.

tests/upgrade: copy shared_lib.sh to the test vm

---

test/cases/ostree-raw-image.sh

After osbuild-composer 64, user should be configured in raw-image blueprint. But the old versions do not support user in raw-image blueprint. This PR is to keep them both.

test: User in commit will not be supported after osbuild-composer 64

---

Schutzfile
osbuild-composer.spec

osbuild 65 got support for gpgkeypaths in the ostree.remotes stage that we need for iot-raw-image implemented recently.
See
https://github.com/osbuild/osbuild/commit/2bff83364b69f974b697e56b7094a24eeb83b37b

spec: bump osbuild dep to >= 65

---

templates/packer/README.md
templates/packer/ansible/roles/common/files/worker-initialization-scripts/client_credentials.sh
templates/packer/ansible/roles/common/files/worker-initialization-scripts/offline_token.sh

Hardcoding the token url renders the image useless if it ever needs to be changed.

templates/packer: Allow token url to be set by cloud-init vars

---

.packit.yaml

As we don't only want to get Bodhi updates for the stable releases, but also the ones still in development, we need to use 'fedora-branched'.
See https://packit.dev/docs/configuration/#aliases

packit: Enable Bodhi updates for unstable Fedoras

---

test/cases/azure.sh

CIV (Cloud-Image-Val) is an image validation tool with a big test suite.
This are basic tests. By incorporating this tool is osbuild-composer CI,
we can catch bugs in our images and our tools earlier.

test: add CIV tool to azure.sh

---

cmd/osbuild-worker/jobimpl-osbuild.go

Currently errors like clienterror 28 ("at least one target failed") have all the relevant information in the details, don't omit these details from the worker logs.

worker: log error details on job failure

---

pkg/jobqueue/dbjobqueue/dbjobqueue.go

The connection can be briefly interrupted for short periods of time, which is fine. To avoid spamming the logs with error messages, backoff for half a second.

dbjobqueue: Backoff after listener error

---

.gitlab-ci.yml
test/cases/ostree.sh

1. Fedora 35 will be EOL, it's removed from `ostree.sh` and enable __Fedora 36__ and __37__ instead.
2. Fedora 35 is removed from `ostree-ng.sh` as well.

test: Add Fedora 36 and 37 and remove 35 test for ostree.sh

---

test/cases/azure.sh

In order to run azure.sh inside CIV CI, we need to use the appropiate tag. This means getting `prod` tag when running in osbuild-composer and the pr tag when running in cloud-image-val

test: get correct CIV tag in azure.sh

---

internal/osbuild/ostree_source.go

Tested locally with `osbuild --inspect` on a throwaway manifest.

osbuild: fix gpgkeys json key in ostree source

---

schutzbot/mockbuild.sh

Running mock as root is broken, this commit can be reverted once this is fixed.
rhbz#2135203

schutzbot/mockbuild: stop running mock as root

---

test/cases/ostree-simplified-installer.sh
test/data/ansible/check_ostree.yaml

waiting for our CD to deliver aio images https://github.com/fedora-iot/fido-device-onboard-rs/pull/335 then changing the tag to something other than latest and updating the name of the image to just `aio`

Use FDO AIO server for testing

---

osbuild-composer.spec

dnf-json previously ran as a service, and the
/var/cache/osbuild-composer/rpmmd directory and files were owned by root. As a script called from osbuild-composer those directories and files need to be owned by _osbuild-composer:_osbuild-composer, otherwise it will not be able to depsolve after an upgrade from the previous implementation.
This can be worked around by removing the
/var/cache/osbuild-composer/rpmmd directory and restarting the service or rebooting.
Fixes #3079

spec: Fix ownership of the dnf-json rpmmd files

---

schutzbot/update_github_status.sh

The checkout in the working directory is a shallow clone with gitlab as a remote. As a result fast-forwarding failed due to not recognizing the remote release branch as an ancestor of $CI_COMMIT_SHA.
This clones (with `--bare`) the github remote in a separate directory. It should not be necessary to remove the release-ff-clone directory each time, simply fetch if it already exists.

schutzbot/update_github_status: fix release fast-forwarding

---

internal/cloudapi/v2/handler.go
internal/cloudapi/v2/v2_test.go
internal/distro/test_distro/distro.go
internal/weldr/api_test.go

b01792d9dd8db737369dce28addb083391d192e6 broke this behaviour. All ostree image types should have an ostree resolve job.

internal/cloudapi: add ostree options for all otree image types

---

internal/cloudapi/v2/server.go

Koji clean-up doesn't delete the top-level directories. As we named every top-level directory different, they were just cumulating on kojihub, which is obviously wrong.
This commit changes that behaviour to put all the temporary directories under a new osbuild-cg top-level one. This way, osbuild-cg won't ve ever cleaned, whereas osbuild-cg/osbuild-composer-koji-{UUID} will be, which is exactly what we want.
cc @tkopecek
Closes: https://github.com/osbuild/osbuild-composer/issues/3064

koji: put artifacts uploaded to koji under a second level directory

---

cmd/osbuild-service-maintenance/db_test.go
internal/jobqueue/fsjobqueue/fsjobqueue.go
internal/jobqueue/jobqueuetest/jobqueuetest.go
internal/worker/server.go
pkg/jobqueue/dbjobqueue/dbjobqueue.go
pkg/jobqueue/dbjobqueue/schemas/006_retry_count.sql
pkg/jobqueue/jobqueue.go
test/cases/api.sh

We are currently losing jobs if workers are restarted while building. Let's restart each job up to two times before giving up. We need to have a limit in place in case a bug in the worker causes a certain job to always fail.
In the future we could teach the workers to notify us on graceful shutdown and handle that case better, so we don't have to rely on heartbeats. In this case, the limit on the number of retries could be higher, as we know it is not a bug on our side, but just normal operation of the infrastructure.

job queue: reschedule interrupted jobs

---

cmd/osbuild-store-dump/main.go
internal/distro/test_distro/distro.go
internal/distroregistry/distroregistry.go
internal/store/fixtures.go
internal/store/json.go
internal/store/json_test.go
internal/store/store.go
internal/store/store_test.go
internal/weldr/api.go

Fixes a problem with the store load not being able to load composes for other distros when the image type isn't supported on the host distro.

Fix loading cross distro compose results

---

docker-compose.yml

This removes the not-available `--dnf-json` argument in the `docker-compose.yml` file and closes #3063.

docker-compose: remove unavailable `--dnf-json`

---

.github/workflows/tests.yml
distribution/Dockerfile-ubi
test/cases/api.sh
tools/prepare-source.sh

In go 1.18 'go install' needs to be used to install an executable. See https://go.dev/doc/go-get-install-deprecation and
https://go.dev/doc/manage-install

Use go install instead of deprecated go get

---

tools/provision.sh

Don't list specific RHEL repos which should be copied over to the repo overrides directory, but instead copy all of them, similar to how it's done for Fedora and CentOS Stream. This is less error prone when support for a new RHEL release is added to composer.
This was forgotten as part of enabling RHEL 8.8 and 9.2.

tools/provision.sh: copy RHEL repo overrides using wildcard

---

internal/distro/fedora/distro.go
internal/distro/fedora/distro_test.go

8fdd1587997dbf091dd69a426bb44ef1c9abcfd1 modified the Cloud API to resolve
ostree commits using a separate job. This change caused the API handler
to call PackageSets without any ostree options (because they are not resolved
yet).
Unfortunately, the new implementation of PackageSets initializes the manifest.
The initialization checks the options and if the type is iot-installer and
it doesn't have the fetch checksum for IoT, it just returns an error.
To work around this (we need an initialized manifest to create the chains),
this commit just gives the initialization method a dummy checksum. The ostree
options currently don't have any effect on the package sets, so this should
be fine.
In order to make this workaround at least slightly sane, a warning is printed,
there's a new test just …

Fix iot-installer build via the cloud API

---

test/cases/diff-manifests.sh

This pull request includes none of these:
Simple fix for missing redprint when diff-manifests.sh fails :)

diff-manifests.sh: Use shared_lib for greenprint and redprint

---

tools/appsre-build-worker-packer.sh

Podman doesn't work when installed from 9.1 repositories on 9.0 image.
I found that upgrading the whole system helps. Sadly, that requires removing
python-unversioned-command for some reason.

ci: fix the packer job

---

internal/disk/btrfs.go
internal/disk/disk.go
internal/disk/disk_test.go
internal/disk/lvm.go
internal/disk/partition_table.go

When the size of a logical volume is not aligned to the extent size of the volume group, LVM2 will automatically align it by rounding up (see [metadata.c](https://github.com/lvmteam/lvm2/blob/868665766491d9d42b8acedaf07cafc7118d165c/lib/metadata/metadata.c#L1072)):
Rounding up size to full physical extent 29.80 GiB
Rounding up size to full physical extent <3.82 GiB
Since we don't take that into account when we create a new volume or set the size of an existing one, the size for the whole volume group will be short by that amount and thus the creation of the last volume
will fail:
Volume group <uuid> has insufficient free space (975 extents): 977 required.
To fix this a new `AlignUp` method is added to the `MountpointCreator` creator interface. It will align a given size to the …

disk: align LVM2 volumes to the extent size 

---

internal/ostree/ostree.go
internal/ostree/ostree_test.go
internal/rhsm/secrets.go

This CA is only valid for the entitlement certificates, not the consumer certificates.
As a result resolving the ostree ref should use the system's CA cert pool.

rhsm: remove CA from consumer secrets

---

internal/blueprint/customizations.go
internal/distro/rhel8/distro.go
internal/distro/rhel8/pipelines.go
internal/distro/rhel8/stage_options.go
internal/distro/rhel9/distro.go
internal/distro/rhel9/pipelines.go
internal/distro/rhel9/stage_options.go
test/cases/ostree-simplified-installer.sh

This pull request includes changes so that:
- simplified installer iso can be build without mentioning FDO section in the blueprint.
- change done for rhel8 and rhel9 distros.
- test case added for this use case in test/case/ostree-simplified-installer.sh

simplified-installer: do not mandate FDO section in simplified provisioning

---

osbuild-composer.spec

PR#553 [1] introduced a change to the worker subpackage and replaced the systemd %preun RPM macro with a literal calls to `systemctl` due to missing functionality in systemd. However, the change omitted the fact, that the RPM macro executes commands only on package removal, not upgrade.
As a result a local or remote worker which is running on the system while the osbuild-composer-worker package is updated, gets stopped.
Fix the scriptlet and run the commands only on package removal.
[1] https://github.com/osbuild/osbuild-composer/pull/553
Signed-off-by: Tomáš Hozza <thozza@redhat.com>

SPEC: run the %preun commands in worker package only on removal

---

test/cases/shared_lib.sh

The get_build_info() function uses nvrGreaterOrEqual() to determine how to parse the output from composer-cli.  The function prints the result of the comparison but is often used in a loop when waiting for a compose to finish, which makes CI logs very annoying.
Silence the version comparison output when called form get_build_info().

tools: silence version comparison in get_build_info()

---

internal/image/image_installer.go
internal/manifest/iso_tree.go
test/data/manifests/fedora_35-aarch64-image_installer-boot.json
test/data/manifests/fedora_35-aarch64-image_installer_with_users-boot.json
test/data/manifests/fedora_35-x86_64-image_installer-boot.json
test/data/manifests/fedora_35-x86_64-image_installer_with_users-boot.json
test/data/manifests/fedora_36-aarch64-image_installer-boot.json
test/data/manifests/fedora_36-aarch64-image_installer_with_users-boot.json
test/data/manifests/fedora_36-x86_64-image_installer-boot.json
test/data/manifests/fedora_36-x86_64-image_installer_with_users-boot.json
test/data/manifests/fedora_37-aarch64-image_installer-boot.json
test/data/manifests/fedora_37-aarch64-image_installer_with_users-boot.json
test/data/manifests/fedora_37-x86_64-image_installer-boot.json
test/data/manifests/fedora_37-x86_64-image_installer_with_users-boot.json
test/data/manifests/fedora_38-aarch64-image_installer-boot.json
test/data/manifests/fedora_38-aarch64-image_installer_with_users-boot.json
test/data/manifests/fedora_38-x86_64-image_installer-boot.json
test/data/manifests/fedora_38-x86_64-image_installer_with_users-boot.json

Anaconda has support for compression on the liveimg. There is little reason not to compress the tarball using gzip.
I also want to replace the liveimg.tar in our CI for the preview images with the compressed version, it's much easier to do so when the initial liveimg is already .gz (less mksisofs)

image: image_installer, use gzip compression

---

internal/distro/rhel7/azure.go
test/data/manifests/rhel_7-x86_64-azure_rhui-boot.json

**What changed**
- Conditionally add insights-client package to azureRhuiCommonPackageSet for RHEL7.
- Regenerate test cases for RHEL 7 azure-rhui
**Why is this necessary**
QE image validation tests require the insights-client to be present in azure-rhui offers.

distro/rhel7: Add insights-client to Azure package set

---

cmd/osbuild-worker/jobimpl-ostree-resolve.go

Passing an error as details results in the details being empty after marshaling. Pass the string formatted error instead.

osbuild-worker: correctly pass ostree error details

---

internal/cloud/gcp/compute.go

At the moment we have duplicate logic here; ideally of course we consolidate (since both codebases are Go, perhaps we could create a tiny little Go library for "RHEL GCP stuff"?) but for now let's just cross-link for awareness.

gcp: Cross-reference to coreos-assembler code

---

internal/cloudapi/v2/server.go
internal/prometheus/constants.go
internal/prometheus/helpers.go
internal/prometheus/http_metrics.go
internal/prometheus/job_metrics.go
internal/prometheus/middleware.go
internal/prometheus/status_metrics.go
internal/worker/server.go
internal/worker/server_test.go

Creates a custom middleware function to record all 5xx errors for composer & worker as we
are currently only recording internal errors for the `/compose` endpoint.
The existing compose metrics can be removed in a follow up PR once the relevant alerts and dashboards
have been implemented.

Measure 5xx errors on all requests for image-builder-composer/worker

---

cmd/osbuild-worker/jobimpl-koji-finalize.go
tools/run-koji-container.sh

The result variable wasn't used at all, kojiFinalizeJobResult is what actually reports the error.
Edit: Also, I had to fix the koji test. It was actually invisibly failing the whole time.

worker: fix reporting the import error to composer

---

internal/prometheus/status_metrics.go

Openshift overrides the `service` label for all metrics in the cluster. Update the label
from `service` to `subsystem` for the status metrics query. This helps us differentiate
between requests from composer and the worker server.

metrics: update status metrics label

---

internal/osbuild/systemd_stage.go

The feature was included in the osbuild stage and was never added to composer.

osbuild: add masked services to systemd stage

---

Schutzfile
internal/blueprint/customizations.go
internal/distro/rhel8/pipelines.go
internal/distro/rhel8/stage_options.go
internal/distro/rhel9/images.go
internal/osbuild/firewall_stage.go
internal/osbuild/firewall_stage_test.go
test/cases/ostree.sh
test/data/ansible/check_ostree.yaml

~~Requires https://github.com/osbuild/osbuild/pull/1137~~ (see below)
This patch adds support to specify firewalld sources for zones
(will add tests asap)
---
osbuild-composer counterpart to osbuild/osbuild#1157.
Signed-off-by: Irene Diez <idiez@redhat.com>

Extend firewall customizations to add sources

---

internal/cloudapi/v2/handler.go

The ostree options are used during the ostree resolve job, but when generating the manifest the rhsm value comes from the image options, so it's necessary to set it on both.

cloudapi/v2: set ostree rhsm option on image options

---

internal/platform/s390x.go
test/data/manifests/centos_9-s390x-qcow2-boot.json
test/data/manifests/centos_9-s390x-qcow2_customize-boot.json
test/data/manifests/centos_9-s390x-tar-boot.json
test/data/manifests/rhel_90-s390x-qcow2-boot.json
test/data/manifests/rhel_90-s390x-qcow2_customize-boot.json
test/data/manifests/rhel_90-s390x-tar-boot.json
test/data/manifests/rhel_91-s390x-qcow2-boot.json
test/data/manifests/rhel_91-s390x-qcow2_customize-boot.json
test/data/manifests/rhel_91-s390x-tar-boot.json
test/data/manifests/rhel_92-s390x-qcow2-boot.json
test/data/manifests/rhel_92-s390x-qcow2_customize-boot.json
test/data/manifests/rhel_92-s390x-tar-boot.json

The big rewrite of rhel9 distro omitted installing `s390utils-base` into the buildroot. This caused the `org.osbuild.zipl.inst` stage to fail because of missing `/usr/sbin/zipl`.
This commit introduces `s390utils-base` back into the buildroot which fixes building of the s390x images.
I verified it by building the RHEL 9.1 qcow2 image and booting it using libvirt.

distro/rhel9: fix /usr/sbin/zipl unavailable in the buildroot

---

Schutzfile

This contains a fix to consumer secrets which are required for pulling protected ostree content.

Schutzfile: bump osbuild dependency

---

internal/distro/fedora/images.go
internal/distro/rhel8/pipelines.go
internal/distro/rhel9/images.go
internal/image/ostree_installer.go
internal/manifest/anaconda.go
internal/osbuild/anaconda_stage.go
test/data/manifests/centos_9-aarch64-edge_installer-boot.json
test/data/manifests/centos_9-x86_64-edge_installer-boot.json
test/data/manifests/fedora_38-aarch64-image_installer-boot.json
test/data/manifests/fedora_38-aarch64-image_installer_with_users-boot.json
test/data/manifests/fedora_38-x86_64-image_installer-boot.json
test/data/manifests/fedora_38-x86_64-image_installer_with_users-boot.json
test/data/manifests/rhel_90-aarch64-edge_installer-boot.json
test/data/manifests/rhel_90-x86_64-edge_installer-boot.json
test/data/manifests/rhel_91-aarch64-edge_installer-boot.json
test/data/manifests/rhel_91-x86_64-edge_installer-boot.json
test/data/manifests/rhel_92-aarch64-edge_installer-boot.json
test/data/manifests/rhel_92-x86_64-edge_installer-boot.json

In RHEL 9, for the edge installer, only enable the users module when it is required for creating a user specified in the blueprint or request.  This was the behaviour until recently.  We changed it to enable interactive user creation even when no users were defined in the request.  However this interferes with tooling for fully automated installations.
Note that the `edge_installer_with_users` manifests are unaffected.  The module is enabled in these manifests so that the user specified in the build request can be created during installation.
Also, the image installer continues to always enable the Users module.  This is required for the service, since there is no way to specify users during the request in the frontend and creating users interactively at install time is the only way to …

RHEL 9: Do not enable user module in Anaconda Edge Installer when no users are specified

---

templates/packer/worker.pkr.hcl

AMIs can take a long time to get ready.

templates/packer: triple aws polling attempts

---

internal/blueprint/customizations.go
internal/distro/rhel9/images.go
internal/distro/rhel9/imagetype.go
internal/ignition/ignition.go
internal/image/ostree_simplified_installer.go
internal/manifest/coi_iso_tree.go
internal/manifest/coreos_installer.go
internal/osbuild/ignition_stage.go
test/cases/ostree-simplified-installer.sh

This allows a user to configure the system via `edge-simplified-installer`
using an ignition configuration specified in the blueprint.
This ignition config can be embedded in the ISO as a Base64
encoded file (`ignition.embedded.data`) or as a file
containing the URL where the ignition config file is served
(`ignition.embedded.url`).
This embedded config (either data or url) ends up in the root
of the ISO.
The user can also instead specify an URL serving an ignition
config file that will passed as a karg and be fetched at first
boot (`ignition.firstboot.url`).
<hr>
depends on osbuild/osbuild-composer#3130 (that PR sets the things needed to run ignition, this PR allows the user to configure the things to pass to ignition, so this PR doesn't break anything)
<hr>

Ignition blueprint config support on rhel9

---

osbuild-composer.spec

See https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1
No code in PR
not relevant

Migrate to SPDX license

---

Schutzfile

Updating osbuild version in Schutzfile to current main (minus version bump) which includes a fix for the SELinux labels of the RHSM fact: https://github.com/osbuild/osbuild/pull/1220
The Fedora 35 config hasn't been modified to avoid conflicting with #3179.

Schutzfile: update osbuild version to current main (v75)

---

templates/dashboards/grafana-dashboard-image-builder-composer-general.configmap.yml
templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml

- update composer & worker dashboards to use the new metric queries
- add metrics for worker request & composer non-compose requests
Composer dashboard:
https://grafana.stage.devshift.net/d/image-builder-composer-update/image-builder-composer-new-queries?orgId=1
Worker dashboard:
https://grafana.stage.devshift.net/d/image-builder-worker-update/image-builder-worker-new-queries?orgId=1

Dashboard metrics update

---

internal/worker/server.go

Re-add the logging for when unresponsive heartbeats are being removed so we can verify that they
are correctly being logged as 5xx errors. As per https://github.com/osbuild/osbuild-composer/issues/3103#issuecomment-1375636679

worker/server: log unresponsive job removal

---

internal/cloudapi/v2/errors.go
internal/prometheus/http_metrics.go

We have switched how 5xx errors are being recorded internally and we are now recording all failures
for all endpoints. As a result, a dedicated metric only for compose failures is no longer required.

internal/prometheus: remove compose fail metrics

---

test/cases/ostree.sh

this pr is to fix bug https://github.com/osbuild/osbuild-composer/issues/3216 , virt-install failed to provision vm using edge commit on fedora37.

fix ostree cannot boot on fedora37

---

Schutzfile

Since composer is not updated into these distributions, it's safe to use
a newer version of osbuild on them without the risk of releasing a
composer version which would require an unreleased osbuild version.

Schutzfile: bump osbuild commit for GA RHEL

---

internal/manifest/coi_iso_tree.go
internal/manifest/commit_deployment.go
internal/manifest/iso_rootfs.go
internal/manifest/iso_tree.go
internal/osbuild/mkdir_stage.go

- rename Path struct to MkdirStagePath
- fix copy&paste error in function comment
- support `parents` stage option
- support `exist_ok` stage option (related to https://github.com/osbuild/osbuild/pull/1224)
Details are in each commit message.
This is a pre-work to support custom files and directories in `/etc` done via customizations.

osbuild/mkdir: support new stage options and small fixes

---

templates/packer/ansible/roles/common/tasks/packages.yml
tools/appsre-build-worker-packer.sh

`authselect-compat-1.2.5-2.el9_1` package is currently missing in AWS RHUI el9 AppStream repositories, which makes `dnf upgrade` fail on RHEL-9.1. This is a RHUI-specific issue, since the package is available in CDN repos.
In order to workaround the issue for now, `authselect-compat` needs to be removed as part of the upgrade in order for it to succeed. Use `--allowerasing` instead of just removing the issue, because this will ensure that `authselect-compat` will be upgraded just fine, once the issue is resolved.
Fix the issue in the CI script that builds the image using Packer, as well as the Ansible playbook used by Packer to build the image.
Signed-off-by: Tomáš Hozza <thozza@redhat.com>

Packer: workaround missing authselect-compat-1.2.5-2.el9_1 in RHUI repos

---

cmd/osbuild-service-maintenance/aws.go
cmd/osbuild-service-maintenance/main.go
internal/cloud/awscloud/awscloud.go

Since we started cloning images to different regions, the maintenance script should clean up all of these regions.

osbuild-service-maintenance: clean up all regions

---

internal/distro/fedora/distro.go
internal/distro/fedora/distro_test.go
internal/distro/fedora/package_sets.go
internal/store/json.go
test/data/manifests/fedora_36-aarch64-minimal_raw-boot.json
test/data/manifests/fedora_36-x86_64-minimal_raw-boot.json
test/data/manifests/fedora_37-aarch64-minimal_raw-boot.json
test/data/manifests/fedora_37-x86_64-minimal_raw-boot.json
test/data/manifests/fedora_38-aarch64-minimal_raw-boot.json
test/data/manifests/fedora_38-x86_64-minimal_raw-boot.json
tools/test-case-generators/format-request-map.json

Signed-off-by: Sarita Mahajan <sarmahaj@redhat.com>
New image type named 'minimal-raw' has been added to fedora.
Reference taken from https://github.com/osbuild/osbuild-composer/pull/3077 
Image is basically a minimal rpm bootable image supports aarch64 & x86
Image is tested manually.
From a RHEL PoV this will enable us to support similar devices as part of the SystemReady "Edge on Arm" initiative where the customer may not wish to run R4E or to use for development/testing/prototyping where a ostree image may not be the most straight forward way to do things.

image: add new image type "minimal-raw" for fedora

---

cmd/osbuild-worker/main.go

So that they are not changed by mistake

osbuild-worker: annotate log statements used by splunk

---

internal/distro/fedora/images.go
test/data/manifests/fedora_36-aarch64-iot_installer-boot.json
test/data/manifests/fedora_36-aarch64-iot_installer_with_users-boot.json
test/data/manifests/fedora_36-x86_64-iot_installer-boot.json
test/data/manifests/fedora_36-x86_64-iot_installer_with_users-boot.json
test/data/manifests/fedora_37-aarch64-iot_installer-boot.json
test/data/manifests/fedora_37-aarch64-iot_installer_with_users-boot.json
test/data/manifests/fedora_37-x86_64-iot_installer-boot.json
test/data/manifests/fedora_37-x86_64-iot_installer_with_users-boot.json
test/data/manifests/fedora_38-aarch64-iot_installer-boot.json
test/data/manifests/fedora_38-aarch64-iot_installer_with_users-boot.json
test/data/manifests/fedora_38-x86_64-iot_installer-boot.json
test/data/manifests/fedora_38-x86_64-iot_installer_with_users-boot.json

As noted in #3141 I've enabled extra modules for Anaconda for the `iot-installer` image type.

iot-installer: enable anaconda modules

---

internal/manifest/coi_iso_tree.go
internal/manifest/xz.go
internal/osbuild/fdo_stage.go
internal/osbuild/fdo_stage_test.go
internal/osbuild/files_input.go
internal/osbuild/files_input_test.go
internal/osbuild/ignition_stage.go
internal/osbuild/qemu_stage.go
internal/osbuild/qemu_stage_test.go
internal/osbuild/rpm_stage.go
internal/osbuild/xz_stage.go
internal/osbuild/xz_stage_test.go

This PR is a pre-work to support custom files in `/etc`, because the copy stage implementation will need to be extended to support files input with origin source. Instead of implementing 6th version of it, I decided to rework files input implementation, which we wanted to do anyway (me and @achilleas-k).
Rework files input implementation to support all reference types supported by the input schema. Also implement helper functions to generate supported reference types. In some cases, the reference supports e.g. referencing multiple pipelines in the stage inputs, but this is currently not implemented, since no pipeline in composer uses it.
Rework the stage inputs implementation of the following stages to use the common files input:
- XZ stage
- FDO stage
- QEMU stage
- RPM stage
- Ignition …

osbuild: unify implementations of files input 🧹

---

cmd/osbuild-pipeline/main.go

I use this tool quite a lot and I often want to use the CDN content, so I would very much appreciate RHSM support. :)

osbuild-pipeline: add support for RHSM when defining repos

---

.github/workflows/tests.yml

The new "latest" aka v1.51.1 started throwing unused errors during runs, blocking all the other tests, to quickly unblock that until a proper fix/rewrite is found, pin the version to the previous one.
Signed-off-by: Antonio Murdaca <antoniomurdaca@gmail.com>

.github/workflows: pin golangci-lint to v1.51.0

---

.gitlab-ci.yml
test/cases/minimal-raw.sh
test/data/ansible/check-minimal.yaml

The minimal-raw image is for Fedora only and feature merged by PR #3181.
Test only covers UEFI because the comment https://github.com/osbuild/osbuild-composer/pull/3181#issuecomment-1380029923
The minimal-raw is not ostree like file system, but "normal" RPM one. So no upgrade test, but have package installation and reboot test included.

test: Add minimal-raw image test

---

internal/upload/koji/koji.go

osbuild-worker/koji: Add logging for koji requests/responses

---

internal/cloudapi/v2/handler.go
internal/cloudapi/v2/openapi.v2.gen.go
internal/cloudapi/v2/openapi.v2.yml
internal/cloudapi/v2/v2_test.go
internal/distro/distro.go
internal/manifest/os.go
internal/manifest/os_test.go

cloudapi: Add subscription option for rhc 

---

Schutzfile
tools/image-info

From https://github.com/osbuild/manifest-db/pull/72
We still have to discuss later on how to/where to move image-info. 
The thing is, Composer needs to have access to image-info when installed as an package, Manifest-DB can't provide this.
So the better place to do it is OSBuild as its packaged, is a dependency of Composer and overall is a good place to host a utility that uses its internals to run.

Image info: Update from manifest-db

---

.gitlab-ci.yml
schutzbot/scheduled_cloud_cleaner.sh
test/README.md
test/cases/aws.sh
test/cases/azure.sh

In order to provide different options when running CIV from it's own CI, move them to the variable CIV_OPTIONS

test/cases: move CIV options into a variable

---

internal/worker/clienterrors/errors.go

This should make the logging better when errors have another error struct.
Fixes #3272

internal/worker: add String to clienterrors.Error struct

---

test/cases/ostree.sh

The current boot location of Fedora 37 in ostree.sh does not have the boot.iso file anymore. 
This PR suggests to update the boot location url.

Update boot location for Fedora 37 edge-commit

---

internal/distro/rhel8/imagetype.go
internal/distro/rhel9/imagetype.go
test/cases/ostree-simplified-installer.sh

This PR is about adding support for User customizations on `edge-simplified-installer` image types, and about giving a basic indication that user customizations on `edge-commit` and `edge-container` are deprecated and will no longer be supported in future RHEL edge versions.
Note the "basic indication" on giving the deprecation warning, currently it simply logs out the deprecation notice. I will add another PR in the near future handling the warning via weldr (working on that), this is simply so that QE can test user customizations on `edge-simplified-installer`.
--- 
Updated to also allow Group customizations and to give the same basic deprecation warning.
---

`edge-simplified-installer` allows User & Group customizations

---

cmd/gen-manifests/main.go
internal/distro/distro_test.go
internal/distro/distro_test_common/distro_test_common.go
internal/distro/fedora/distro.go
internal/distro/rhel7/distro.go
internal/distro/rhel8/imagetype.go
internal/distro/rhel9/edge.go
internal/distro/rhel9/imagetype.go
internal/distro/test_distro/distro.go
internal/image/ostree_container.go
internal/manifest/anaconda.go
internal/manifest/build.go
internal/manifest/commit_server_tree.go
internal/manifest/coreos_installer.go
internal/manifest/manifest.go
internal/manifest/os.go
internal/weldr/api.go
test/data/manifests/rhel_7-x86_64-azure_rhui-boot.json
test/data/manifests/rhel_7-x86_64-qcow2-boot.json
test/data/manifests/rhel_7-x86_64-qcow2_customize-boot.json

Assign pipeline-specific repositories to package sets before returning the package set chains.  This is a workaround for a bug where repositories with pipeline restrictions are ignored.
In the new distro definitions, repositories are assigned to pipelines while building the manifest.  The manifest then returns package set chains with repository information from the GetPackageSetChains() method.  However, the manifest is only initialised with the global repos and the package set specific repos are ignored.
~~A more correct fix for this issue would be to pass all repositories to each pipeline initialisation function (e.g., `NewBuild()`) and have each pick the repositories that matches its own name (+ any that have no restrictions).  However this would require more changes and would take …

distro: assign pipeline-specific repos to package sets

---

Schutzfile
internal/manifest/commit_deployment.go
internal/osbuild/ignition_stage.go
osbuild-composer.spec
test/data/ansible/check_ostree.yaml
test/data/manifests/centos_9-aarch64-edge_raw_image-boot.json
test/data/manifests/centos_9-aarch64-edge_simplified_installer-boot.json
test/data/manifests/centos_9-x86_64-edge_raw_image-boot.json
test/data/manifests/centos_9-x86_64-edge_simplified_installer-boot.json
test/data/manifests/rhel_92-aarch64-edge_raw_image-boot.json
test/data/manifests/rhel_92-aarch64-edge_simplified_installer-boot.json
test/data/manifests/rhel_92-x86_64-edge_raw_image-boot.json
test/data/manifests/rhel_92-x86_64-edge_simplified_installer-boot.json

This is a workaround to make the systemd believe it's firstboot when ignition runs on real firstboot.
Right now, since we ship /etc/machine-id, systemd thinks it's not firstboot and ignition depends on it to run on the real firstboot to enable services from presets. Since this only applies to artifacts with ignition and changing machineid-compat at commit creation time may have undesiderable effect, we're doing it here as a stopgap. We may revisit this in the future.
Requires https://github.com/osbuild/osbuild/pull/1249

ignition: enable systemd firstboot condition through kargs

---

templates/packer/ansible/roles/common/tasks/packages.yml
tools/appsre-ansible/rpmbuild.yml
tools/appsre-build-worker-packer.sh

We actually use rhui/cloud access images for rpmbuild as well. And the sync issue between cdn and rhui repos can cause issues when rpms are build against older packages.

tools/appsre-ansible: don't subscribe machines used for rpmbuild

---

internal/manifest/os.go

Fix the following error reported by Coverity:
```
Defect type: SUPPRESSED_ERROR
1. osbuild-composer-75/_build/src/github.com/osbuild/osbuild-composer/internal/manifest/os.go:546: suppressed_error: The error returned by the function "GetVerStrFromPackageSpecList(p.packageSpecs, "dracut-config-rescue")" is not explicitly checked.
2. osbuild-composer-75/_build/src/github.com/osbuild/osbuild-composer/internal/manifest/os.go:546: remediation: Explicitly check the return error.
544|   				}
545|
546|-> 				rescueVer, _ := rpmmd.GetVerStrFromPackageSpecList(p.packageSpecs, "dracut-config-rescue")
547|   				hasRescue := rescueVer != ""
548|   				bootloader = osbuild.NewGrub2LegacyStage(
```
Change the code to check if the called function returned an error or not. If not error is returned, then …

manifest/os: fix SUPPRESSED_ERROR issue reported by Coverity

---

internal/upload/koji/koji.go

koji: log unsuccessful requests only once

---

cmd/osbuild-worker/config.go
cmd/osbuild-worker/config_test.go
cmd/osbuild-worker/jobimpl-osbuild.go
cmd/osbuild-worker/main.go

The default number of threads (16) is OK for general use case. However, we are being asked by RH IT to lower the number of threads when uploading the image to Azure using proxy server.
Make the number of threads configurable in the worker configuration and default to the currently used value if it is not provided.

worker: allow configuring number of upload threads for Azure

---

internal/distro/fedora/package_sets.go
test/data/manifests/fedora_36-aarch64-image_installer-boot.json
test/data/manifests/fedora_36-aarch64-image_installer_with_users-boot.json
test/data/manifests/fedora_36-aarch64-iot_installer-boot.json
test/data/manifests/fedora_36-aarch64-iot_installer_with_users-boot.json
test/data/manifests/fedora_36-x86_64-image_installer-boot.json
test/data/manifests/fedora_36-x86_64-image_installer_with_users-boot.json
test/data/manifests/fedora_36-x86_64-iot_installer-boot.json
test/data/manifests/fedora_36-x86_64-iot_installer_with_users-boot.json
test/data/manifests/fedora_37-aarch64-image_installer-boot.json
test/data/manifests/fedora_37-aarch64-image_installer_with_users-boot.json
test/data/manifests/fedora_37-aarch64-iot_installer-boot.json
test/data/manifests/fedora_37-aarch64-iot_installer_with_users-boot.json
test/data/manifests/fedora_37-x86_64-image_installer-boot.json
test/data/manifests/fedora_37-x86_64-image_installer_with_users-boot.json
test/data/manifests/fedora_37-x86_64-iot_installer-boot.json
test/data/manifests/fedora_37-x86_64-iot_installer_with_users-boot.json
test/data/manifests/fedora_38-aarch64-image_installer-boot.json
test/data/manifests/fedora_38-aarch64-image_installer_with_users-boot.json
test/data/manifests/fedora_38-aarch64-iot_installer-boot.json
test/data/manifests/fedora_38-aarch64-iot_installer_with_users-boot.json
test/data/manifests/fedora_38-x86_64-image_installer-boot.json
test/data/manifests/fedora_38-x86_64-image_installer_with_users-boot.json
test/data/manifests/fedora_38-x86_64-iot_installer-boot.json
test/data/manifests/fedora_38-x86_64-iot_installer_with_users-boot.json

The new names of the packages are being added twice in two different checks, remove the redundant code.

distro: remove duplicate version checks for fonts

---

internal/distro/fedora/distro.go
internal/distro/fedora/package_sets.go

With the addition of the minimal rpm package set and image type in #3181 the previously added bare metal package set is a duplicate. It's not used elsewhere within fedora and the minimal rpm package set is officially defined.

image-installer: switch payload to minimal-rpm

---

internal/prometheus/job_metrics.go
internal/worker/server.go

Only add the arch label for osbuild job types, as the finish metrics behave similarly. Having arch labels on dequeue metrics for any other job type (but not on the finish metrics) would produce weird results.

prometheus:: add arch label to dequeue metrics

---

test/cases/api/common/vsphere.sh
test/cases/vmware.sh

Since we use streamOptimized images everywhere, we no longer need to use IDE and boot with bios. Let's test a more realistic scenario.

test/vmware: boot VMs with EFI and use SCSI as a disk controller

---

internal/distro/rhel8/edge.go
internal/distro/rhel9/edge.go
internal/image/ostree_simplified_installer.go
internal/manifest/coi_iso_tree.go
test/data/manifests/centos_8-aarch64-edge_simplified_installer-boot.json
test/data/manifests/centos_8-x86_64-edge_simplified_installer-boot.json
test/data/manifests/centos_9-aarch64-edge_simplified_installer-boot.json
test/data/manifests/centos_9-x86_64-edge_simplified_installer-boot.json
test/data/manifests/rhel_8-aarch64-edge_simplified_installer-boot.json
test/data/manifests/rhel_8-x86_64-edge_simplified_installer-boot.json
test/data/manifests/rhel_86-aarch64-edge_simplified_installer-boot.json
test/data/manifests/rhel_86-x86_64-edge_simplified_installer-boot.json
test/data/manifests/rhel_87-aarch64-edge_simplified_installer-boot.json
test/data/manifests/rhel_87-x86_64-edge_simplified_installer-boot.json
test/data/manifests/rhel_88-aarch64-edge_simplified_installer-boot.json
test/data/manifests/rhel_88-x86_64-edge_simplified_installer-boot.json
test/data/manifests/rhel_9-aarch64-edge_simplified_installer-boot.json
test/data/manifests/rhel_9-x86_64-edge_simplified_installer-boot.json
test/data/manifests/rhel_90-aarch64-edge_simplified_installer-boot.json
test/data/manifests/rhel_90-x86_64-edge_simplified_installer-boot.json
test/data/manifests/rhel_91-aarch64-edge_simplified_installer-boot.json
test/data/manifests/rhel_91-x86_64-edge_simplified_installer-boot.json
test/data/manifests/rhel_92-aarch64-edge_simplified_installer-boot.json
test/data/manifests/rhel_92-x86_64-edge_simplified_installer-boot.json

It's enabled on every other iso and certain UEFI devices aren't able to boot w/o this

simplified-installer: enable isolinux

---

cmd/osbuild-worker/jobimpl-file-resolve.go
cmd/osbuild-worker/main.go
internal/remotefile/client.go
internal/remotefile/client_test.go
internal/remotefile/resolver.go
internal/remotefile/resolver_test.go
internal/remotefile/spec.go
internal/worker/clienterrors/errors.go
internal/worker/json.go
internal/worker/server.go

- adding a file resolver to generate a checksum for the contents of a remote file.

File resolver job

---

test/cases/ostree-rebase-bios.sh
test/cases/ostree-rebase-uefi.sh
test/cases/ostree.sh

The latest boot.iso stopped working. Changing to an older version to unblock CI. RHBZ#2180024 opened with this issue.

tests/ostree: Change centos-8 BOOT_LOCATION to a working boot.iso

---

.packit.yaml

We got request for these, so let's enable them. I wonder if we should remove epel and leave only rhel in, since we don't technically need epel for anything.

packit: build RPMs also for EPEL 9 and RHEL

---

internal/boot/vmwaretest/vmware.go

Since we use streamOptimized images everywhere, we no longer need to use IDE and boot with bios. Let's test a more realistic scenario.

internal/boot: boot VMWare VMs with EFI and SCSI

---

.gitlab-ci.yml
test/cases/regression-insecure-repo.sh

COMPOSER-1936: Enable regression-insecure-repo test for nightly CI pipeline

---

test/cases/ostree-simplified-installer.sh

Test script ostree-simplified-installer.sh failed on cs9, in these two prs.
1. https://github.com/osbuild/osbuild-composer/pull/3378#issuecomment-1502633131
2. https://github.com/osbuild/osbuild-composer/pull/3379
I reproduced this failure in my local environment (it's not 100% reproducible), and found the root cause:
sometimes, when run ansible tasks with fdouser(which is created during fdo onboarding), fdouser is not created yet, caused ansible task failed. In fact, this user is created about two minutes later.
This PR added a step to verify if fdouser exist before run ansible tasks with fdouser.

Test/fix cs9 edge-simplified-installer test failure

---

test/cases/cross-distro.sh

COMPOSER-1943: Fix failure in cross-distro.sh

---

.packit.yaml

Simplify packit config

---

templates/packer/config.pkr.hcl

Version 1.2.3 made changes to how the plugin handles auto-selection of a subnet when it's not specified, see
https://github.com/hashicorp/packer-plugin-amazon/commit/f1ec287c7710e5b6284d6a637ecf092b9e248886
Sadly, the new algorithm selects us-east-1e for us that doesn't support the machine types we use (c6*.large) which causes the build to fail. I reported it here:
https://github.com/hashicorp/packer-plugin-amazon/issues/368
One workaround might be to pin a working subnet, but that's apparently also broken in 1.2.3, see
https://github.com/hashicorp/packer-plugin-amazon/issues/367
Therefore, I decided to pin the plugin to 1.2.2 for now, and see what's the recommended approach from terraform guys.

packer: pin the version of the amazon plugin to 1.2.2

---

.gitlab-ci.yml
test/cases/container-embedding.sh
test/cases/image_tests.sh

RHELSQ-4656: Conditional skip for container embedding test

---

test/cases/ostree-simplified-installer.sh

Basically pulls in https://github.com/kislyuk/yq/issues/165 to fix the installation issue

test/simplified-installer: fix yq installation on rhel8

---

schutzbot/mockbuild.sh

DNF has more elaborate locking system and can wait for other instances of itself when installing packages. Using rpm directly to install local package is causing failures in CI due to it not being able to acquire lock on `/var/lib/rpm/.rpm.lock`.
Using DNF should improve the situation, although there is no good documentation to link and support this claim for sure.

mockbuild.sh: use dnf to install local package, not rpm

---

internal/distro/rhel8/edge.go
internal/distro/rhel9/edge.go
internal/image/ostree_simplified_installer.go
internal/manifest/coi_iso_tree.go
templates/packer/config.pkr.hcl
test/data/manifests/centos_8-aarch64-edge_simplified_installer-boot.json
test/data/manifests/centos_8-x86_64-edge_simplified_installer-boot.json
test/data/manifests/centos_9-aarch64-edge_simplified_installer-boot.json
test/data/manifests/centos_9-x86_64-edge_simplified_installer-boot.json
test/data/manifests/rhel_8-aarch64-edge_simplified_installer-boot.json
test/data/manifests/rhel_8-x86_64-edge_simplified_installer-boot.json
test/data/manifests/rhel_86-aarch64-edge_simplified_installer-boot.json
test/data/manifests/rhel_86-x86_64-edge_simplified_installer-boot.json
test/data/manifests/rhel_87-aarch64-edge_simplified_installer-boot.json
test/data/manifests/rhel_87-x86_64-edge_simplified_installer-boot.json
test/data/manifests/rhel_88-aarch64-edge_simplified_installer-boot.json
test/data/manifests/rhel_88-x86_64-edge_simplified_installer-boot.json
test/data/manifests/rhel_9-aarch64-edge_simplified_installer-boot.json
test/data/manifests/rhel_9-x86_64-edge_simplified_installer-boot.json
test/data/manifests/rhel_90-aarch64-edge_simplified_installer-boot.json
test/data/manifests/rhel_90-x86_64-edge_simplified_installer-boot.json
test/data/manifests/rhel_91-aarch64-edge_simplified_installer-boot.json
test/data/manifests/rhel_91-x86_64-edge_simplified_installer-boot.json
test/data/manifests/rhel_92-aarch64-edge_simplified_installer-boot.json
test/data/manifests/rhel_92-x86_64-edge_simplified_installer-boot.json

Backport https://github.com/osbuild/osbuild-composer/pull/3327 to `rhel-9.2.0`

Backport PR#3327 to `rhel-9.2.0`

---

test/cases/custom-repos.sh

Don't execute test on osbuild-composer < 81. See #3228

---

.gitlab-ci.yml

COMPOSER-1948: Enable more regression tests for nightly pipeline

---

test/cases/ostree-ng.sh
test/cases/ostree.sh
test/data/ansible/check_ostree.yaml

This pull request includes another embedded container in edge-commit and edge-installer, just like container-embedding.sh test case.
Playbook tasks have been included to check the fedora minimal container image is embedded, and the image is not being pulled again (task fails if podman try to pull latest tag).

Test fedora minimal embedded container

---

internal/manifest/os.go
internal/manifest/os_test.go

RHC automatically connects to insights already.
---
Done with 1 rhc connect call:
---
marking as draft, as it does seem like it's doing *something*, I asked some other people for help.
---
edit2: clarified the above with the insights devs, rhc already does this. So it's not needed.

internal/manifest: remove redundant insights-client call

---

templates/packer/config.pkr.hcl
templates/packer/worker.pkr.hcl

It turns out that we might have been using the plugin improperly: `associate_public_ip_address` isn't needed if we use the default VPC (which we do). If this option isn't set, we shouldn't hit the new subnet selection algorithm introduced in https://github.com/hashicorp/packer-plugin-amazon/commit/f1ec287c7710e5b6284d6a637ecf092b9e248886 and rely on the AWS's default one, that doesn't ever select a subnet not supporting the instance type we want.
See [packer's docs](https://developer.hashicorp.com/packer/plugins/builders/amazon/ebs#run-configuration) and [this comment](https://github.com/hashicorp/packer-plugin-amazon/issues/368#issuecomment-1516975441).

Adjust packer build to work with the amazon plugin 1.2.3

---

distribution/Dockerfile-fauxauth
distribution/Dockerfile-ubi
distribution/Dockerfile-ubi-maintenance

There's no reason not to update to UBI 9.
However, the latest version of UBI 9 needs also one extra patch:
When `go install` is called, go tries to get the git commit hash and embed it
into the built binary. Internally, go just calls the git executable.
The newer go-toolset seems to be based on RHEL 9.2 that ships a newer version
of git (2.39.1). This version contains the safe directory patch that
disallows git from operating on repositories owned by different users.
Thus, we need to chown the files when copying.
See
https://git-scm.com/docs/git-config/2.35.2#Documentation/git-config.txt-safedirectory

Dockerfile*: update to ubi9 and chown the files when copying

---

internal/distro/fedora/distro.go
internal/distro/fedora/distro_test.go
internal/distro/fedora/images.go
internal/distro/rhel8/imagetype.go
internal/distro/rhel9/imagetype.go
internal/image/ostree_raw.go
internal/manifest/ostree_deployment.go
test/cases/ostree-raw-image.sh
test/cases/ostree-simplified-installer.sh
test/data/manifests/fedora_36-aarch64-iot_raw_image_customizations-boot.json
test/data/manifests/fedora_36-x86_64-iot_raw_image_customizations-boot.json
test/data/manifests/fedora_37-aarch64-iot_raw_image_customizations-boot.json
test/data/manifests/fedora_37-x86_64-iot_raw_image_customizations-boot.json
test/data/manifests/fedora_38-aarch64-iot_raw_image_customizations-boot.json
test/data/manifests/fedora_38-x86_64-iot_raw_image_customizations-boot.json
test/data/manifests/fedora_39-aarch64-iot_raw_image_customizations-boot.json
test/data/manifests/fedora_39-x86_64-iot_raw_image_customizations-boot.json
tools/test-case-generators/format-request-map.json

This is a follow-up for https://github.com/osbuild/osbuild-composer/pull/3281 adding support for the new customizations to ostree-deploy pipeline and exposing it for the Fedora `iot-raw-image`.
These customizations could be technically used also by RHEL edge image types, but the BP customization values are not passed through to the pipeline in the RHEL distro image type implementation.
Notable changes:
- Allow Files and Directories customization for Fedora `iot-raw-image` image type.
- Allow Services customization for iot-raw-image image type, to allow using the existing test case from `check_ostree.yaml`
- Restrict allowed customization for the iot/edge-raw-image, because some of them are currently just silently ignored.
Resolves …

Fedora/iot-raw-image: support custom files and directories in `/etc` (+ services customization)

---

internal/distro/fedora/package_sets.go
test/data/manifests/fedora_38-aarch64-iot_installer-boot.json
test/data/manifests/fedora_38-aarch64-iot_installer_with_users-boot.json
test/data/manifests/fedora_38-x86_64-iot_installer-boot.json
test/data/manifests/fedora_38-x86_64-iot_installer_with_users-boot.json
test/data/manifests/fedora_39-aarch64-iot_installer-boot.json
test/data/manifests/fedora_39-aarch64-iot_installer_with_users-boot.json
test/data/manifests/fedora_39-x86_64-iot_installer-boot.json
test/data/manifests/fedora_39-x86_64-iot_installer_with_users-boot.json

This adds 'fedora-release-iot' to the 'iotInstallerPackageSet' and fixes the default filesystem used for Fedora IoT Anaconda installations changing it from btrfs to LVM/ext4. 

iot: add fedora-release-iot to iot-installer

---

internal/manifest/os.go
internal/manifest/os_test.go

The post install script customises the selinux policy, but is gated on `selinuxenabled`, which will fail inside the buildroot container.
As a result it's never executed.

internal/manifest: execute rhc's post install script

---

templates/composer.yml

No separate request for memory was defined in #3472, only cpu request/limit.

templates/composer: fix fluentd requests/limits

---

internal/distro/distro_test_common/distro_test_common.go
internal/distro/fedora/distro.go
internal/distro/fedora/images.go
internal/distro/fedora/imagetype.go
internal/distro/rhel8/edge.go
internal/distro/rhel8/images.go
internal/distro/rhel9/distro.go
internal/distro/rhel9/distro_test.go
internal/distro/rhel9/edge.go
internal/distro/rhel9/images.go
internal/distro/rhel9/imagetype.go
internal/image/ostree_raw.go
test/data/manifests/centos_9-aarch64-edge_ami-boot.json
test/data/manifests/centos_9-x86_64-edge_ami-boot.json
test/data/manifests/rhel_9-aarch64-edge_ami-boot.json
test/data/manifests/rhel_9-x86_64-edge_ami-boot.json
test/data/manifests/rhel_90-aarch64-edge_ami-boot.json
test/data/manifests/rhel_90-x86_64-edge_ami-boot.json
test/data/manifests/rhel_91-aarch64-edge_ami-boot.json
test/data/manifests/rhel_91-x86_64-edge_ami-boot.json
test/data/manifests/rhel_92-aarch64-edge_ami-boot.json
test/data/manifests/rhel_92-x86_64-edge_ami-boot.json
test/data/manifests/rhel_93-aarch64-edge_ami-boot.json
test/data/manifests/rhel_93-x86_64-edge_ami-boot.json
tools/test-case-generators/format-request-map.json

This PR allows to create an 'edge-ami' image type, which generates an uncompressed raw image (x86_64,
aarch64) ready to upload to AWS EC2 based on an edge OSTree commit.
This edge-ami image type has Ignition support.

Add the 'edge-ami' image type based on edge-raw-image

---

cmd/osbuild-composer/composer.go
cmd/osbuild-composer/main.go
distribution/osbuild-composer-api.socket
distribution/osbuild-composer-prometheus.socket
osbuild-composer.spec
templates/composer.yml
test/cases/api.sh

Listening on another port, while keeping the existing endpoint

internal/cloudapi: new prometheus listener

---

internal/osbuild/result.go
internal/osbuild/result_test.go
internal/osbuild/result_test_data.go

osbuild can return a json object with details about manifest validation errors. This adds support for saving those, and printing them when the Write function is called. eg. when using composer-cli compose log UUID
Includes tests for new behavior.

osbuild: Add validation error logging

---

test/cases/ostree-simplified-installer.sh
test/data/ansible/check_ostree.yaml

1. Checking FDO user created before running ansible playbook
2. Wait 10 seconds before and after VM rebooting to make VM stable

test: Some enhancements to make test stable

---

test/cases/ostree-ignition.sh
test/cases/ostree-raw-image.sh
test/cases/ostree-simplified-installer.sh

Simplifed installer test takes too much time and its test script code is over 1500 lines. Moving ignition test out of simplified installer test will make test faster and code shorter. It's time to use a new test job for ignition test. This PR includes:
1. Remove ignition test from simplified installer test and raw image test
2. Use a new test job for ignition test
3. Add ignition test for raw image

test: Move ignition test out of simplified installer test

---

internal/distro/rhel8/azure.go
test/data/manifests/rhel_8-x86_64-azure_eap7_rhui-boot.json
test/data/manifests/rhel_86-x86_64-azure_eap7_rhui-boot.json
test/data/manifests/rhel_87-x86_64-azure_eap7_rhui-boot.json
test/data/manifests/rhel_88-x86_64-azure_eap7_rhui-boot.json
test/data/manifests/rhel_89-x86_64-azure_eap7_rhui-boot.json

PR#3421 [1] unintentionally removed the `rhui-azure-rhel8` package from the Azure EAP7 RHUI image base package set. As a result, the image manifest can't be built successfully. The reason is that the removed package installs a RPM GPG key, which is hard-coded in the image manifest to be imported as part of the image build.
Add the package back to the image base package set and regenerate all affected test manifests.
[1] https://github.com/osbuild/osbuild-composer/pull/3421

distro/rhel8: fix Azure EAP7 RHUI image definition

---

test/data/upgrade8to9/upgrade_prepare.sh
test/data/upgrade8to9/upgrade_verify.sh

Upstream leapp no longer uses separate channels for obtaining its data and instead packages them into the RPM. See
https://redhat-internal.slack.com/archives/C04JP91FB8X/p1687428000886329

Remove redundant script in upgrade8to9 test

---

test/cases/ostree-raw-image.sh
test/cases/ostree-simplified-installer.sh

Don't need dedicated rebase test workflow, move rebase test into other test script. That will save runner and reduce running time.
1. Add BIOS rebase test in ostree-raw-image.sh
2. Add UEFI rebase test in ostree-simplified-installer.sh
Removing ostree-rebase-bios.sh, ostree-rebase-uefi.sh and rebase test CI workflow will be in another PR to make CI result all green.

test: Move rebase test into ostree-raw-image.sh and ostree-simplified-installer.sh

---

.gitlab-ci.yml
test/cases/libvirt.sh
test/cases/minimal-raw.sh
test/cases/ostree-ng.sh
test/cases/ostree.sh
test/data/ansible/check_ostree.yaml
tools/libvirt_test.sh

This PR:
- updates the Fedora 38 runners to the GA version
- makes some adjustments to the testing suite so it supports all Fedora versions - we no longer need to change anything in the test scripts in order to enable CI for a new version
- enables CI on Fedora 38
- enables running even more tests on Fedora 38 (libvirt and installer) - some adjustments were needed

Enable CI for Fedora 38 & a few cleanups

---

internal/distro/distro_test.go
internal/manifest/os_test.go
internal/osbuild/copy_stage_test.go
internal/osbuild/fdo_stage.go
internal/osbuild/files_input.go
internal/osbuild/files_input_test.go
internal/osbuild/fsnode.go
internal/osbuild/fsnode_test.go
internal/osbuild/ignition_stage.go
internal/osbuild/rpm_stage.go
internal/osbuild/rpm_stage_test.go

Helper functions that create stage input objects with references always hard-coded `sha256:` as a prefix/algorithm for the checksum.  This prevents the functions from being used in cases where other algorithms are use, like sha1, which is possible with (perhaps older) RPM repositories.  The inputs in osbuild a number of hashing algorithms and we should be able to generate stages with other prefixes when necessary.
This PR removes the `sha256:` prefix in the helper functions and assumes all arguments to these functions provide the correct prefix.
Fixes rhbz#2215043 (RHELPLAN-159871).

Allow any hashing algorithm in osbuild stage inputs

---

.github/workflows/tests.yml

GitHub will automatically disable scheduled actions defined on repositories which don't receive much activity. In particular such scheduled jobs will be disabled after 60 days of repo inactivity.
This CI job sanity checks the current status and reports back to every PR so we can manually re-enable cloud-cleaner if necessary.

Sanity check if cloud-cleaner workflow is enabled

---

internal/auth/middleware.go
internal/cloudapi/v2/errors.go
internal/cloudapi/v2/middleware.go
internal/cloudapi/v2/server.go
internal/cloudapi/v2/v2_multi_tenancy_test.go
internal/prometheus/http_metrics.go
internal/prometheus/middleware.go
internal/prometheus/status_metrics.go
internal/worker/server.go
test/cases/api.sh

Adds the tenant field to the status and request duration metrics, and uses the the latter in the worker api as well.
---
Once we update the dashboards we can move the total_requests and total_compose_requests counters.

Set the tenant in the request context, reuse it for the status and request duration metrics

---

containers/osbuild-composer/entrypoint.py
distribution/Dockerfile-ubi

containers/osbuild-composer: add prometheus port parameter

---

internal/cloudapi/v2/server.go
internal/worker/server.go

The duration middleware should come after the tenant channel mw. The status mw can come before because it queries the request context right before sending the response, but the duration metric needs the tenant set in the request context as it creates the timer timing the request.

reorder middlewares in worker and cloud apis

---

.github/workflows/trigger-gitlab.yml
schutzbot/slack_notification.sh
schutzbot/update_github_status.sh

- don't report to Slack if SLACK_WEBHOOK_URL is not defined
- report GitHub statuses separately for regular pipeline & nightly pipeline
Same as #3541 but PR opened from a branch, not a fork.

Schedule a nightly CI pipeline against each PR

---

.github/workflows/trigger-gitlab.yml
schutzbot/slack_notification.sh

Fix for possibly undefined variable in CI script

---

tools/rpm_spec_add_provides_bundle.sh
tools/rpm_spec_vendor2provides

Replace the generator for the spec file "Provides:" list with the one from the current go-rpm-macros [1].  The new generator can handle 'replace' commands in vendor/modules.txt, which makes it possible to build RPMs with temporarily modified dependencies.  This enables making scratch builds against forks or branches of the new osbuild/images repository for development and testing.
In the (distant) future, we can use the packaged version of the script, but this isn't yet available in all supported distros (EL8).
Made some minor modifications to the original script to prepend each dependency with "Provides:" and read input files as arguments instead of lines from stdin.
https://pagure.io/go-rpm-macros/blob/c32fbbd25bbcedee8c0b898d3653255b18a0d30e/f/rpm/go_mod_vendor.prov
@supakeen @bcl I've …

tools: replace spec Provides generator

---

cmd/osbuild-composer/composer.go
test/cases/api.sh

remove old prometheus listener

---

test/cases/ostree-ami-image.sh

Now that osbuild-composer is able to generate an edge AMI that can be uploaded and deployed on AWS, it would be useful to include a dedicated test script for automation.
ostree-ami-image.sh uses osbuild-composer to build edge-ami image type, then upload it to a S3 bucket and deploy an EC2 instance using that image.

Include test for edge-ami image type

---

.golangci.yml

Use the linter to make sure go.mod doesn't include a replace directive.

lint: Enable check for replace in go.mod

---

internal/cloudapi/v2/handler.go

This was missing to enable `live-installer` in the CloudAPI.

cloudapi: add `live-installer`

---

test/README.md

Add instructions for how to test an updated osbuild/images repo against osbuild-composer and update test manifest generation instructions.

test/README: describe vendoring modified images repo

---

.github/workflows/trigger-gitlab.yml

There were two issues:
- ${{ }} converts the expression to a string, and strings are apparently always truthy
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif
- There was a typo in pr_data
Therefore, the check didn't work properly.

ci: fix the gitlab trigger

---

Schutzfile
osbuild-composer.spec

The recently merged `live-installer` image type depends on osbuild >= 89, see the following commit in osbuild:
https://github.com/osbuild/osbuild/commit/c90b587dccf5f82e5732b7a264866c3535c066c2

spec: require osbuild >= 89

---

.github/workflows/tests.yml
README.md
cmd/osbuild-composer/config.go
cmd/osbuild-worker/jobimpl-osbuild.go
go.mod
internal/blueprint/customizations_test.go
internal/client/client.go
internal/client/compose_test.go
internal/client/projects.go
internal/cloud/gcp/storage.go
internal/dnfjson/dnfjson.go
internal/jobqueue/fsjobqueue/fsjobqueue.go
internal/upload/koji/koji.go
tools/prepare-source.sh

UBI and the oldest support Fedora (37) now all have go 1.19, so we are cleared to switch.
gofmt now reformats comments in certain cases, so that explains the formatting changes in this commit.
See https://go.dev/doc/go1.19#go-doc

update to go 1.19

---

test/cases/installers.sh
test/cases/minimal-raw.sh
test/cases/oscap.sh
test/cases/ostree-ignition.sh
test/cases/ostree-ng.sh
test/cases/ostree-raw-image.sh
test/cases/ostree-simplified-installer.sh
test/cases/ostree.sh
tools/libvirt_test.sh

All RHEL for Edge test on RHEL 9.3 failed due to bug https://bugzilla.redhat.com/show_bug.cgi?id=2225667 which would be related with systemd bug https://bugzilla.redhat.com/show_bug.cgi?id=2213660.
This PR is just a workaround, it'll be removed when issue fixed.

test: Add workaround for BZ#2213660 and #2225667

---

.github/workflows/tests.yml
tools/check-snapshots

This pulls the list of snapshots from the rpmrepo API, greps the codebase for all uses of rpmrepo.osbuild.org that look like a snapshot name, and then checks to make sure they are still valid.

tests: Add a check for valid snapshot urls

---

test/cases/aws.sh
test/cases/azure.sh
test/cases/base_tests.sh
test/cases/filesystem.sh
test/cases/image_tests.sh
test/cases/installers.sh
test/cases/minimal-raw.sh
test/cases/oscap.sh
test/cases/ostree-ami-image.sh
test/cases/ostree-ignition.sh
test/cases/ostree-ng.sh
test/cases/ostree-raw-image.sh
test/cases/ostree-simplified-installer.sh
test/cases/ostree.sh
test/cases/upgrade8to9.sh

We were using greenprint for failures, which makes it hard to quickly find where the tests failed. This switches errors to use redprint, and adds it to places that were simply using echo before doing an exit 1.

test: Make log errors easier to find

---

test/cases/api/common/common.sh

We had no end-to-end test for the facts we submit to `subscription-manager`.
This PR adds a very simple test for it.

test/cases/api: add check for subscription-manager facts

---

cmd/osbuild-koji-tests/main_test.go
cmd/osbuild-koji/main.go
cmd/osbuild-worker/jobimpl-koji-finalize.go
cmd/osbuild-worker/jobimpl-osbuild.go
internal/cloudapi/v2/server.go
internal/upload/koji/koji.go
internal/weldr/api.go
internal/worker/json.go
test/cases/koji.sh

The main goal of this PR is to expose the image boot mode in the Koji Build Extra metadata field.
Notable changes:
- Refactor Koji structures to be more consistent with their JSON representation and to what's used in Koji documentation. The changes make data structures more generic, which will be later helpful for the consolidation of information attached to Koji builds.
- Expose the image output extra metadata also in the build extra metadata under the image filename. The same data structure is now used for these two situations.
- Add the image boot mode to the `OSBuildJob` options and `OSBuildJobResult` options and copy the value in worker from job options to the result. Unfortunately, there is no better way (see discussion in this PR) to enable `KojiFinalize` job to access the data.
- …

Koji: expose image metadata in build extra metadata, including boot mode

---

internal/blueprint/blueprint.go
internal/blueprint/blueprint_convert_test.go

Previously, nil values in the conversion source were in some cases converted to empty arrays or empty objects. This is undesirable, because it can be in certain cases changing the semantics of the blueprint. See e.g. https://github.com/osbuild/images/blob/f317064da574a8475d438972e9c54bc67ffa1dfb/pkg/distro/rhel7/imagetype.go#L239C7-L239C7
This commit modifies the conversion process so nil values are converted without any changes. Also, the `Convert` function was covered with a unit test.

COMPOSER-2016: blueprint: make Convert respect nils

---

test/cases/ostree-ignition.sh
test/cases/ostree-ng.sh
test/cases/ostree-raw-image.sh
test/cases/ostree-vsphere.sh
test/data/ansible/check_ostree.yaml

Do not need to run greenboot rollback case on all tests to save time.
ostree.sh covered rollback on kvm, ostree-ami-image.sh covered rollback on AWS ec2, and ostree-vsphere.sh covered rollback on ESXi.

test: run greenboot rollback test on ostree.sh, ostree-ami-image.sh and ostree-vsphere.sh

---

internal/cloud/gcp/compute.go

See: https://github.com/coreos/coreos-assembler/pull/3547
See: https://cloud.google.com/blog/products/identity-security/rsa-snp-vm-more-confidential
See: https://issues.redhat.com/browse/COS-2343
---

internal/cloud/gcp/compute: Add SEV_SNP_CAPABLE Guest OS Feature

---

templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml

The worker dashboard contains slow queries, running these on 28 days of data take a very long time (and they often time out).

dashboards/worker: default to showing the past 6 hours

---

.github/dependabot.yml

Imho, this is much saner than having so many PRs for all individual dependencies. Taken from osbuild/images.

dependabot: group go package updates

---

test/cases/installers.sh

should trigger a kernel trace instead of only warnings
I've been trying this locally but so far didn't have any luck triggering the kernel issue. 
Before adding this cli argument I managed to reproduce the issue once on a beaker machine :-(.

Tests: Add softlockup_all_cpu_backtrace=1 boot argument

---

test/cases/ostree.sh

Test `edge-commit-cs9` failure is caused by bug https://bugzilla.redhat.com/show_bug.cgi?id=2234390. This PR adds workaround for this bug.

test: add workaround for bug BZ#2234390

---

test/cases/installers.sh
test/cases/oscap.sh
test/cases/ostree-ignition.sh
test/cases/ostree-ng.sh
test/cases/ostree-raw-image.sh
test/cases/ostree-simplified-installer.sh
test/cases/ostree.sh
test/cases/ubi-wsl.sh

test logs print:
[2023-08-22T10:18:14-04:00] 💿 Install image via installer(ISO) on VM WARNING  --os-type is deprecated and does nothing. Please stop using it.

Tests: Remove deprecated --os-type cli argument

---

cmd/osbuild-worker/jobimpl-osbuild.go
internal/upload/oci/upload.go
internal/worker/clienterrors/errors.go

Two fixes related to each other:
1. When an osbuild job panics, but `osbuild` actually succeeded and no `JobError` was set, we currently report success back to composer. That's wrong. I added a `recover()` to set an error state.
2. Passing wrong credentials when uploading to OCI causes a panic. Seems like the OCI SDK doesn't handle this well. I worked around this by doing more checking when the error is returned.

Handle panics in the osbuild job & fix panic when OCI authentication fails

---

.github/workflows/stale-cleanup.yml

Actions: add workflow for marking and closing stale issues and PRs

---

test/cases/ubi-wsl.sh

Solves `invalid usage for storage profile: attach existing managed OS disk`.

test/cases/ubi-wsl: set --os-type when creating vm

---

test/cases/ostree.sh

Bug BZ#2234390 has been fixed, workaround (by PR https://github.com/osbuild/osbuild-composer/pull/3663) should be removed.

test: remove workaround for bug BZ#2234390

---

.github/workflows/tests.yml
go.mod
go.sum
test/cases/ostree-simplified-installer.sh
vendor/github.com/osbuild/images/pkg/disk/partition_table.go
vendor/github.com/osbuild/images/pkg/distro/fedora/distro.go
vendor/github.com/osbuild/images/pkg/distro/fedora/images.go
vendor/github.com/osbuild/images/pkg/distro/fedora/package_sets.go
vendor/github.com/osbuild/images/pkg/distro/fedora/partition_tables.go
vendor/github.com/osbuild/images/pkg/distro/image_config.go
vendor/github.com/osbuild/images/pkg/distro/rhel7/images.go
vendor/github.com/osbuild/images/pkg/distro/rhel8/edge.go
vendor/github.com/osbuild/images/pkg/distro/rhel8/images.go
vendor/github.com/osbuild/images/pkg/distro/rhel8/package_sets.go
vendor/github.com/osbuild/images/pkg/distro/rhel9/edge.go
vendor/github.com/osbuild/images/pkg/distro/rhel9/images.go
vendor/github.com/osbuild/images/pkg/distro/rhel9/package_sets.go
vendor/github.com/osbuild/images/pkg/platform/aarch64.go
vendor/modules.txt

Update images dependency to pull in change to minimal raw images [1] for release into RHEL 9.3.0.
Includes fix for Azure image kernel options [2].
[1] https://github.com/osbuild/images/pull/163
[2] https://github.com/osbuild/images/pull/166

[RHEL 9.3.0] deps: update osbuild/images to v0.3.0-r9.3.2

---

internal/client/blueprints_test.go

Package version parsing fails on minor releases (88.1).
I plan to add this as a downstream patch on top of v88.1 to get through RHEL CI.

test: remove package version check

---

templates/composer.yml

The job won't run if it doesn't get scheduled within 30 minutes. This prevents the job running multiple times in a row if it didn't get scheduled, for instance due to resource limits.

templates/compose: add startingDeadlineSeconds to maintenance job

---

templates/packer/ansible/roles/common/tasks/subscribe.yml
tools/appsre-ansible/rpmbuild.yml

tools/appsre-ansible/rpmbuild: retry all tasks

---

tools/provision.sh

This was hit in c9s CI:
https://gitlab.com/redhat/centos-stream/rpms/osbuild-composer/-/merge_requests/88 https://artifacts.dev.testing-farm.io/658332f8-8705-4727-84d3-f27b57775037/
```
/usr/libexec/osbuild-composer-test/provision.sh: line 141: OCI_SECRETS: unbound variable
```

tools/provision.sh: fix unbound variable bug if no OCI secrets are set

---

cmd/osbuild-koji-tests/main_test.go
cmd/osbuild-koji/main.go
cmd/osbuild-worker/jobimpl-koji-finalize.go
cmd/osbuild-worker/jobimpl-osbuild.go
internal/cloudapi/v2/server.go
internal/cloudapi/v2/v2_koji_test.go
internal/cloudapi/v2/v2_test.go
internal/common/dependencies.go
internal/target/aws_target.go
internal/target/azure_image_target.go
internal/target/azure_target.go
internal/target/container_target.go
internal/target/gcp_target.go
internal/target/koji_target.go
internal/target/koji_target_test.go
internal/target/oci_target.go
internal/target/targetresult.go
internal/target/targetresult_test.go
internal/target/vmware_target.go
internal/target/worker_server_target.go
internal/upload/koji/koji.go
internal/worker/json.go
internal/worker/json_test.go
osbuild-composer.spec
test/cases/koji.sh

This PR is related to [COMPOSER-1801](https://issues.redhat.com/browse/COMPOSER-1801).
The main intention of this PR is to enhance osbuild-composer as a Koji Content Generator, to import all of the most important artifacts to the Koji build, with additional metadata. The goal is to ensure that these additional files and data are preserved for the lifetime of the image in a Koji build.
Previously, some files such as OSBuild logs and manifests were uploaded only to the Koji task by the `koji-osbuild` builder plugin. This resulted in an undesirable situation of them being garbage collected after some time, thus making it extremely difficult (close to impossible) to reproduce the same image build using OSBuild if needed.
With this PR, all the information needed to reproduce an image build are …

Consolidation & extension of information imported to Koji builds

---

test/cases/ostree-vsphere.sh

fix ostree vmdk test timeout

---

cmd/osbuild-worker/jobimpl-osbuild.go

Two small fixes as a follow-up for PR #3599:
- indent the uploaded manifest to make it nicer to read
- fix typo in error message

Small fixes for Koji data consolidation PR#3599

---

distribution/Dockerfile-ubi
schutzbot/containerbuild.sh
tools/appsre-build-deploy.sh

When the container with osbuild-composer gets built in our CI or by AppSRE, we do not set the composer version to any value (as we do when we built RPMs). As a result, the version reported by composer is always "devel". This is not useful for debugging and determining the used version of composer. In addition, this information now gets exposed in Koji builds, therefore it makes sense to make it useful.

Container: set the composer git revision during the build

---

.gitlab-ci.yml

previously added in 1eb51b7bab93da89602d29c2e893074af522e0fb but was later removed for some reason. See COMPOSER-1796.

Enable Azure testing on HyperV Gen2

---

internal/cloudapi/v2/compose.go
internal/cloudapi/v2/compose_test.go

There is a lot of repeated checks for bp.Customization != nil, this simplifies that by creating an empty blueprint.Customizations at the top, and checking to see if it is still empty at the bottom and setting it back to nil.
Includes a new test for calling with an empty (not nil) v2.Customizations set on the request.

cloudapi: Simplify the bp.Customizations code

---

go.mod
go.sum
vendor/github.com/osbuild/images/pkg/distro/rhel9/azure.go
vendor/github.com/osbuild/images/pkg/distro/rhel9/edge.go
vendor/github.com/osbuild/images/pkg/distro/rhel9/imagetype.go
vendor/github.com/osbuild/images/pkg/distro/rhel9/partition_tables.go
vendor/modules.txt

Update images dependency to pull in change to partition tables for RHEL 9.3 images.
https://github.com/osbuild/images/pull/221

deps: update osbuild/images to v0.3.0-r9.3.3

---

test/README.md

Add a small paragraph with the instruction to run the go tests when pulling in a new version of images as a guide for making sure that osbuild-composer builds and runs successfully, before moving on to integration tests.
As a side note: This part of the document might be more appropriate in the HACKING document than the testing README but I'm not sure.  Or maybe somewhere else?  I'm not sure.
----

test/README: run go tests when updating images

---

.github/workflows/tests.yml
.packit.yaml

- Configure Packit to handle only release tags without a "dot".
- Fix deprecated option in the Packit config.
- Validate Packit config as part of CI.

:package: Packit configuration enhancements

---

internal/store/store.go
internal/store/store_test.go

The SourceConfig pointer may be a loop variable that gets reused. This results in unexpected behavior when the value pointed to is overwritten by the loop calling this function.
So, DO NOT point to unsafe variables. Make a new pointer using common.ToPtr where it is passed by value and returns a pointer to that new value.
NOTE: This is NOT caught by golangci-lint, there are likely other places this is happening.

store: Fix RepoConfig

---

test/cases/azure.sh

This will allow us to define which HyperV generation to use when creating the image on the fly.
Related PRs:
* https://github.com/osbuild/cloud-image-val/pull/282
* https://github.com/osbuild/osbuild-composer/pull/3679

Added hyper_v_generation metadata to the instance used by CIV.

---

internal/store/store_test.go

Forgot the #1 rule of map iteration. Don't depend on the order. This uses a slice instead, which should be just as good for testing the loop variable alias behavior.

store: Fix test for CheckGPG

---

templates/packer/ansible/roles/common/files/worker-initialization-scripts/get_pulp_creds.sh
templates/packer/ansible/roles/common/files/worker-initialization.service

Configure pulp credentials on worker startup.

templates/packer: configure pulp creds on startup

---

internal/blueprint/customizations_test.go
internal/blueprint/filesystem_customizations.go
internal/blueprint/filesystem_customizations_test.go

Due to an oversight, the toml and json tags for the `MinSize`field had different keywords. This commit fixes this by creating
a `minsize` toml tag and ensuring backwards compatability by checking the old `size` tag.
If both `minsize` & `size` are set in the toml block, the custom unmarshal function validates the input for inconsistencies.
Guides PR: https://github.com/osbuild/guides/pull/152

Blueprints: Fix TOML filesystem `minsize` keyword

---

test/cases/ubi-wsl.sh

`vm list-ip-addresses` has proven to be quite unreliable.

test/cases/ubi-wsl: query Windows VM ip address via vm show

---

test/cases/filesystem.sh

SSIA
Related to https://issues.redhat.com/browse/COMPOSER-2030

:lock: Update `filesystem.sh` test case to reflect update mountpoint policy

---

test/cases/oscap.sh

The `oscap` remediation is failing due to an issue with remediating the
firewall loopback traffic. The remediation fails and bails out early
resulting in a lower score and causing a regression in the test. This
will need to be fixed on the OpenSCAP side, so as a workaround, we can
remove this rule from the remediation.

Fix rhel9 oscap test

---

containers/osbuild-composer/entrypoint.py

This reverts commit b4cf032239e4d8ebe17934439d14a492f158e158. No longer needed after removing sidecar COMPOSER-2051

Revert "containers/osbuild-composer: wait for fluentd in entrypoint"

---

README.md

After documentation refactoring "developer guide" link was pointing to non existing page. This commit updates the link to point to the latest upstream developer guide page.

Readme: Fix broken link

---

Makefile

Just some minor typo in makefile

Makefile: Fix typo in printed project name

---

cmd/osbuild-service-maintenance/db_test.go
internal/cloudapi/v2/v2_koji_test.go
internal/cloudapi/v2/v2_test.go
internal/jobqueue/fsjobqueue/fsjobqueue.go
internal/jobqueue/jobqueuetest/jobqueuetest.go
internal/test/helpers.go
internal/weldr/compose_test.go
internal/worker/api/api.gen.go
internal/worker/api/errors.go
internal/worker/api/openapi.yml
internal/worker/client.go
internal/worker/client_test.go
internal/worker/server.go
internal/worker/server_test.go
pkg/jobqueue/dbjobqueue/dbjobqueue.go
pkg/jobqueue/dbjobqueue/schemas/007_create_table_workers.sql
pkg/jobqueue/jobqueue.go

Unresponsive workers (>=1 hour of no status update) are cleaned up.
Several things are enabled by keeping track of workers, in future the
worker server could:
- keep track of how many workers are active
- see if a worker for a specific architecture is available

Worker status heartbeat

---

test/data/ansible/check-minimal.yaml

Persistent log is not related with minimal raw image itself and it is not stable. After discuss with team, remove this test.

test: remove persistent log checking on minimal raw test

---

.gitlab-ci.yml

cherry-picked from #3820. [Here's](https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/pipelines/1102949161) a mostly successfull execution on 9.4 nightly!

.gitlab-ci.yml: upgade neetle early to workaround RHEL-17890

---

test/data/ansible/check_ostree.yaml

Today, Edge tests in RHEL 8 and RHEL 9 are running into an ansible error `conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}` https://github.com/osbuild/rhel-edge-ci/actions/runs/7166929082/job/19511985610#step:6:4065.
This error should be imported by ansible-core upgrade from 2.14.9 to 2.14.12.
This PR addresses this error to not include templating delimiters such as {{ }} or {% %}` in conditional statements.

test: fix ansible playbook conditional statements error

---

Schutzfile

osbuild dependency commit for RHEL 9.4 is not updated. This PR updated commit value.
@achilleas-k @mmartinv FIPS test needs this PR to have correct osbuild dependence for RHEL 9.4.

test: update osbuild dependency commit for RHEL 9.4

---

go.mod
go.sum
internal/blueprint/blueprint.go
internal/client/unit_test.go
internal/jobqueue/fsjobqueue/fsjobqueue.go
internal/store/fixtures.go
internal/weldr/api.go
internal/weldr/api_test.go
internal/weldr/compose_test.go
internal/worker/server.go
pkg/jobqueue/dbjobqueue/dbjobqueue.go
pkg/jobqueue/jobqueue.go
test/cases/cross-distro.sh
vendor/modules.txt

This is useful in environments with multi-arch remote workers. Defaults to the host architecture.
---
Wondering if we should test the cross arch in weldr api, since it queries the state of the remote worker socket now :/ 
---

internal/weldr: specify architecture of compose

---

test/cases/cross-distro.sh

Will make cross-distro.sh test work on nightlies.

Adjust expected response based on osbuild-composer version

---

tools/image-info

In the osbuild PR#1501 [0] a new paramter "partition" for
mounts.Mount() was added.
This commit updates the code that it deals cleanly with the new
and the old API for `mount.Mount`.
[0] https://github.com/osbuild/osbuild/pull/1501

image-info: update for new "partition" option in mounts.Mount

---

test/cases/filesystem.sh

the conditionals have been introduced in
https://github.com/osbuild/osbuild-composer/commit/8960a51d2f10a9b50e7e8d296c6b9598ad181ca8 which states (emphasys mine):
> The new partition rules are **in** osbuild-composer v94 and higher.
but the condition was "not v94 or higher" and as a result it fails on 8.10 nightly with osbuild-composer v92 with:
failed to initialize osbuild manifest: The following custom mountpoints are not supported [\"/boot/firmware\" \"/foobar\"]
see https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/jobs/5905865402

Invert wrong boolean condition in filesystem test

---

cmd/osbuild-composer/main.go
distribution/osbuild-composer.socket
internal/cloudapi/v2/compose.go
internal/cloudapi/v2/compose_test.go
internal/cloudapi/v2/errors.go
internal/cloudapi/v2/handler.go
internal/cloudapi/v2/openapi.v2.gen.go
internal/cloudapi/v2/openapi.v2.yml

The basic idea here is to start by adding blueprint support to cloudapi, the discussion for this can be found [here](https://github.com/orgs/osbuild/discussions/2).
This is a really rough poc, but it does actually work, you can submit compose requests to a local socket and it will use the "blueprint" to create it. I only implemented the customizations schema that were the same as a starting point.
Some things to answer:
* Should blueprint and cloudapi customizations be exclusive and return an error if both are present?
* If not, how to handle merging them. eg. handling duplicate entries like both trying to setup the same user.
* Should the cloudapi schema be changed to match the blueprint customization schema?
Schema notes:
Things the same:
- Kernel
- SSHKey
- Timezone
- Locale
- Services …

COMPOSER-2096: Add blueprint support to cloudapi & local access to cloudapi service

---

tools/build-rpms.py

osbuild/osbuild-composer#3614 removed the rhel-8.6, the centos-stream-9 entry should be there for a while at least.

tools/build-rpms: fix getting the osbuild commit from Schutzfile

---

test/cases/oscap.sh

b/c https://github.com/ComplianceAsCode/content/issues/11275 has been fixed. This reverts commit c77b73a8881a5d82ec50642e2747ab7ede061c94.

Remove oscap.sh firewalld rules workaround

---

tools/appsre-build-fedora-worker-packer.sh

It should only build fedora, not everything except fedora.

tools/fedora-worker-packer: fix packer only/except

---

templates/packer/ansible/roles/common/files/worker-initialization-scripts/client_credentials.sh
templates/packer/ansible/roles/common/files/worker-initialization-scripts/get_aws_creds.sh
templates/packer/ansible/roles/common/files/worker-initialization-scripts/get_azure_creds.sh
templates/packer/ansible/roles/common/files/worker-initialization-scripts/get_gcp_creds.sh
templates/packer/ansible/roles/common/files/worker-initialization-scripts/get_koji_creds.sh
templates/packer/ansible/roles/common/files/worker-initialization-scripts/get_oci_creds.sh
templates/packer/ansible/roles/common/files/worker-initialization-scripts/get_pulp_creds.sh
templates/packer/ansible/roles/common/files/worker-initialization-scripts/offline_token.sh
templates/packer/ansible/roles/common/files/worker-initialization-scripts/subscription_manager.sh

Don't allow unbound variables, but for the variables that are used to determine whether or not that part of the setup should continue, default to false.

templates/packer: deal with unbound variables

---

.gitlab-ci.yml
Schutzfile
test/cases/regression-old-worker-new-composer.sh

Move testing to RHEL 8.9 and 9.3 runners.

tests/CI: Add RHEL 9.3 and 8.9 GA to pipeline

---

pkg/jobqueue/dbjobqueue/dbjobqueue.go

The workers table should be updated, not the heartbeats. Currently every worker is reregisterig every minute.

pkg/jobqueue: fix worker status update query

---

DEPLOYING.md
HACKING.md

The footnote or endnote style links sometimes don't work well with DocuSaurus, i.e. they're not resolved correctly and lead to build errors.
https://github.com/osbuild/osbuild.github.io/actions/runs/7776075785/job/21202788034?pr=36
For reference, this is the PR this is blocking: https://github.com/osbuild/osbuild.github.io/pull/36

DEPLOYING/HACKING.md: Consistently use inline refs

---

tools/provision.sh

- Two bugs have been fixed, workarounds are not needed anymore.
- The version comparison looks not work. Here's the log from https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/jobs/6105842327#L3137
```
++ echo 8.10
++ awk '{print $1 >= 8.6}'
+ ge86=0
+ echo -n 'rhel=8.10 '
rhel=8.10 + [[ rhel == \r\h\e\l ]]
+ ((  ge86  ))
+ sudo dnf install -y ansible koji
```
This PR fixed this issue. Only RHEL 8.4 needs `ansible`, but RHEL 8.9 and 8.10 need `ansible-core`. And CI doesn't have any other RHEL 8 distros.

test: remove workarounds for fixed bugs

---

cmd/osbuild-jobsite-builder/main.go
cmd/osbuild-jobsite-manager/main.go
osbuild-composer.spec

WIP, commit messages are not yet complete; TODO below.
Has to be done:
Can be followup:
This PR implements a new concept in `osbuild-composer`: the `jobsite`. The `jobsite` is an isolated set of services to run builds in. They can be separated from the rest of the system through network segmentation or other means. The `jobsite` and what's in it are only available to things inside it. One `jobsite` is used for each build, after which all resources used in it are removed again.
In the case of `osbuild-composer` the worker can set up a network, start a separate virtual machine containing the `builder` and then spawn the `manager` to point at it.
This implements the `jobsite-manager` and `jobsite-builder`. The `builder` is a thin wrapper around `osbuild` itself, it takes in a manifest; build …

jobsite: `manager` and `builder`

---

cmd/osbuild-composer/main.go
vendor/github.com/getsentry/sentry-go/logrus/logrusentry.go
vendor/modules.txt

Send error-level (and higher) log messages to sentry, this should log include HTTP 500 errors since we use log them as errors.
Follow up to https://github.com/osbuild/osbuild-composer/pull/3907

errors-level logs to glitchtip

---

internal/cloud/awscloud/secure-instance.go
templates/packer/ansible/roles/common/files/worker-initialization-scripts/worker_executor.sh
templates/packer/ansible/roles/common/files/worker-initialization.service
templates/packer/ansible/roles/common/tasks/worker-initialization-service.yml

cloud/awscloud: specify subnets when creating secure instance
For non-default VPCs, AWS needs the subnets it can launch the instance
in, otherwise it will try to launch the instance in the default VPC,
even if the supplied security groups are attached to a non-default VPC.
Furthermore there can only be 1 subnet specified per availability zone,
so query the subnets in the VPC of the host (as the instance needs to be
launched in the same network), and pick 1 of the VPC's subnets per AZ.

worker-executor followups: fix oneshot service and secure instance for non-default vpcs

---

internal/cloud/awscloud/secure-instance.go

```
InvalidParameterValue: Your request contains more than the maximum allowed number of InstanceRequirements (4)
```

cloud/awscloud: max 4 overrides are allowed when creating a fleet

---

templates/packer/ansible/roles/common/files/worker-initialization-scripts/worker_executor.sh

The builder uses `/run/osbuild` as a default path for this argument. Yet this directory doesn't exist when the builder writes the manifest. But osbuild should own this directory, not the builder.
Furthermore `/run` is a tmpfs, so the executor might run into memory issues if we use `/run` as the store and output directory (on the "host" workers these are in `/var/cache`).
While `/tmp` might seem like a good candidate on RHEL, it's a tmpfs on Fedora, so it's also to be avoided.

templates/packer: set -builder-path to /var/cache/osbuild-builder

---

cmd/osbuild-jobsite-builder/main.go
cmd/osbuild-jobsite-manager/main.go

Write osbuild's stdout in the progress step. The manager can just copy it to stdout and the executor will be able to parse the output into an osbuild result.

cmd/osbuild-jobsite: capture osbuild's stdout

---

cmd/osbuild-jobsite-manager/main.go

Be a bit more friendly and actually create the export directory instead of assuming it exists.

jobsite/manager: create export directory

---

cmd/osbuild-jobsite-builder/main.go

The buffer needs to be assigned to the process' stdout for the buffer to fill up.

cmd/osbuild-jobsite-builder: actually assign the stdout buffer

---

templates/packer/ansible/roles/common/files/worker-initialization-scripts/worker_executor.sh

In app-interface the output resource names need to be unique, and the log group name is already shared with the role.

templates/packer: rename executor log group

---

internal/cloud/awscloud/secure-instance.go

Using the group names option only works for the default VPC, the workers are not running in the default VPC. For non-default VPCs filters should be used.
---
See https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#DescribeSecurityGroupsInput

cloud/awscloud: describe security groups using filters

---

cmd/osbuild-composer/config.go
cmd/osbuild-composer/config_test.go
templates/composer.yml

SSIA, check commit messages for more details.
Also added unit tests for the functionality.

Support configuring distro aliases via ENV and set aliases in the composer template.

---

.gitignore
Makefile
README.md
internal/blueprint/blueprint.go
internal/client/blueprints_test.go
rpmlint.config

Improves the error message if a name or (name and version) is missing.
Also introduces a test for this.
- [✔] adequate testing for the new functionality or fixed issue
- [✔] adequate documentation informing people about the change such as
- [✔] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/
https://issues.redhat.com/browse/RHEL-16006

RHEL-16006: improve error on missing package name

---

internal/cloud/gcp/compute.go

SEV-SNP capable kernels containing commit ac3f9c9f are compatible. SEV_LIVE_MIGRATABLE indicated compatibility with an older version of SEV live migration, without ac3f9c9f. See: https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=ac3f9c9f1b37edaa7d1a9b908bc79d843955a1a2

Tag rhel 9.2+ with SEV_LIVE_MIGRATABLE_V2

---

tools/appsre-build-fedora-worker-packer.sh

The fedora build script should wait until the rpms are released upstream before starting the build, otherwise the rpms will come from the fedora repos.

tools/appsre-build-fedora: wait until rpms are built upstream

---

test/data/ansible/check_ostree.yaml

The remount of /var and /sysroot mount points fails in edge-commit CS9 due to bug https://issues.redhat.com/browse/RHEL-25249 
This is causing several workflow jobs to fail and affects several PRs.
We suggest to skip the playbook task that makes sure mentioned folders are remounted, until we find out the root cause of the issue.

ci: skip ostree-remount check in CS9 due to bug RHEL-25249

---

test/cases/installers.sh
test/cases/minimal-raw.sh
test/cases/oscap.sh
test/cases/ostree-ignition.sh
test/cases/ostree-ng.sh
test/cases/ostree-pulp.sh
test/cases/ostree-raw-image.sh
test/cases/ostree-simplified-installer.sh
test/cases/ostree.sh
tools/libvirt_test.sh

test: remove libvirt workaround

---

templates/packer/ansible/roles/common/files/osbuild-worker.toml
templates/packer/ansible/roles/common/files/worker-initialization-scripts/worker_config.sh
templates/packer/ansible/roles/common/files/worker-initialization-scripts/worker_executor.sh
templates/packer/ansible/roles/common/files/worker-initialization.service

We need to use custom IAM policy name used by the worker for osbuild-executor on Fedora workers (in prod vs. stage). And we have the same requirement for the CloudWatch log group used by the osbuild-executor.
Modify the Ansible playbook used by Packer to use the values from /tmp/cloud_init_vars if set and defaulting to the current values if not set.
Related to https://github.com/osbuild/image-builder-terraform/pull/436

Packer: make osbuild-executor worker config more configurable (HMS-3727)

---

.gitlab-ci.yml
test/cases/api.sh
test/cases/api/aws.sh
test/cases/api/azure.sh
test/cases/api/common/common.sh
test/cases/api/common/s3.sh
test/cases/api/container.registry.sh
test/cases/api/gcp.sh
test/cases/api/oci.sh

This reverts commit 2fe5e01d4d421d4d41e31f217c9b952d2e644aff.
This functionality is covered by unit tests in osbuild/images: https://github.com/osbuild/images/blob/aaa53adc3c1570bb54e65b15b9aa090991e74afb/pkg/distrofactory/distrofactory_test.go#L9

Drop distro aliases and dot-notation tests (HMS-3710)

---

templates/packer/ansible/roles/common/files/worker-initialization-scripts/worker_executor.sh

The /tmp/cloud_init_vars is not created on the worker executor, so sourcing it will make the script fail. Comment the line out, until we change the worker implementation to inject this file into the worker executor using cloud-init.

Packer: don't source non-existing file in worker_executor.sh

---

.gitlab-ci.yml

Test `koji.sh` with cloud upload on the latest RHEL-8.9 and RHEL9.3 GA releases, which we use on our Brew workers.
Test the `koji.sh` only on the latest RHEL-8.9, RHEL-9.3 and Fedora releases, which we use on our Brew and Koji workers.
There's no value in testing this case on CentOS Stream, RHEL EUS releases or nightly composes.

Test/Koji: test only combinations that we run in the service (HMS-3710)

---

cmd/osbuild-worker/jobimpl-osbuild.go

Without this you get an array of bytes in the logs. Convert the raw json output from osbuild to a string so there is some hope that it is readable.

osbuild-worker: Convert osbuild raw json error to a string for logging

---

cmd/osbuild-worker/config.go
cmd/osbuild-worker/config_test.go
cmd/osbuild-worker/jobimpl-osbuild.go
cmd/osbuild-worker/main.go
internal/cloud/awscloud/secure-instance.go
internal/cloud/awscloud/secure-instance_test.go
internal/osbuildexecutor/runner-impl-aws-ec2.go
templates/packer/ansible/roles/common/files/worker-initialization-scripts/worker_config.sh
templates/packer/ansible/roles/common/files/worker-initialization-scripts/worker_executor.sh

We need the ability to use different CloudWatch group for the osbuild-executor on Fedora workers in staging and production environment.
Extend the worker confguration to allow configuring the CloudWatch group name used by the osbuild-executor. Extend the secure instance code to instruct cloud-init via user data to create /tmp/cloud_init_vars file with the CloudWatch group name in the osbuild-executor instance, to make it possible for the executor to configure its logging differently based on the value.
Cover new changes by unit tests.

Worker: allow configuring executor CloudWatch group (HMS-3727)

---

cmd/osbuild-composer/composer.go
cmd/osbuild-composer/main.go
internal/cloudapi/server.go
internal/cloudapi/v2/compose.go
internal/cloudapi/v2/compose_test.go
internal/cloudapi/v2/handler.go
internal/cloudapi/v2/server.go
internal/cloudapi/v2/v2_test.go
internal/weldr/api.go

Use distro repos in cloudapi

---

templates/composer.yml

We now have a proper rhel-10.0 distribution, and this alias is clashing
with it, so we are seeing the following message in production:
failed to configure distro aliases: invalid aliases: ["alias 'rhel-10.0' masks an existing distro"]
Let's fix it by removing the alias, it's obviously not needed anymore.

Remove rhel-10.0 alias from the openshift template

---

Makefile
cmd/osbuild-jobsite-builder/main.go
cmd/osbuild-jobsite-manager/main.go
internal/cloud/awscloud/secure-instance.go
internal/osbuildexecutor/runner-impl-aws-ec2.go
templates/packer/ansible/roles/common/files/worker-initialization-scripts/worker_executor.sh
test/cases/worker-executor.sh

osbuild-jobsite: push sources to executor (HMS-3633)

---

cmd/osbuild-jobsite-manager/main.go

osbuild-jobsite-manager: close writer before sending the store

---

cmd/osbuild-jobsite-builder/main.go

Let's just rely on the timeouts surrounding the whole step.

osbuild-jobsite-builder: disable http.Server timeouts

---

.gitlab-ci.yml

reduce the number of overall test executions b/c resources in this environment are severely limited.

Execute OpenShift Virtualization tests only on RHEL 9.x nightly

---

templates/packer/ansible/roles/common/files/worker-initialization-scripts/worker_service.sh

The snapshotted repositories on stage are behind a VPN + a proxy.

templates/packer: set http(s)_proxy environment variable in unit HMS-3798

---

.github/workflows/tests.yml
README.md
go.mod
internal/weldr/api_test.go
pkg/splunk_logger/go.mod
tools/prepare-source.sh

Go 1.20 is included in all currently supported distro versions.
Newer versions of a lot of our dependencies now require go 1.20, which is making dependabot PRs fail.

go.mod: update to go v1.20

---

cmd/osbuild-worker/config.go
cmd/osbuild-worker/jobimpl-depsolve.go
cmd/osbuild-worker/jobimpl-osbuild.go
cmd/osbuild-worker/main.go
templates/packer/ansible/roles/common/files/worker-initialization-scripts/get_ldap_sa_mtls_creds.sh
templates/packer/ansible/roles/common/files/worker-initialization-scripts/worker_service.sh

The AWS sdk fails to get the instance identity document when the proxy
is configured. The proxy will need to be configured explicitly for the
depsolve job and osbuild (sources) job.

worker: support http proxy for depsolve and osbuild sources job HMS-3798

---

internal/osbuildexecutor/runner-impl-aws-ec2.go

The extra env only contains paths to secrets which are needed to pull sources. Since the sources don't get pulled on the executor, don't pass the env along to the executor.

osbuildexecutor/ec2: pass extraEnv only to sources invocation

---

.gitlab-ci.yml
test/cases/aws.sh

This one is 1 vCPU + 4GiB RAM, the older one is 2 vCPU, same RAM

Update Arm EC2 instance to a newer one

---

cmd/osbuild-worker/jobimpl-depsolve.go

Yesterday in an effort to get the snapshotting to work quickly, I ignored the results of the api tests, turns out that was a bad idea.

osbuild-worker: fix nil pointer in depsolve job

---

Makefile

Following up from #4068, this PR removes the dnf-json related line from the install target in the Makefile.

Makefile: remove installation of dnf-json

---

.github/workflows/tests.yml
test/cases/aws.sh
test/cases/azure.sh
test/cases/container-embedding.sh
test/cases/container-upload.sh
test/cases/filesystem.sh
test/cases/gcp.sh
test/cases/generic_s3.sh
test/cases/installers.sh
test/cases/minimal-raw.sh
test/cases/openshift_virtualization.sh
test/cases/ostree-ami-image.sh
test/cases/ostree-ignition.sh
test/cases/ostree-iot-qcow2.sh
test/cases/ostree-ng.sh
test/cases/ostree-pulp.sh
test/cases/ostree-raw-image.sh
test/cases/ostree-simplified-installer.sh
test/cases/ostree-vsphere.sh
test/cases/ostree.sh
test/cases/vmware.sh

see for example this change:
https://github.com/osbuild/osbuild-composer/pull/3681/commits/13a3ca24ceef05164a77db1c71b929e262098f41

Add CI job to detect possible problematic usage of `trap`

---

test/data/upgrade8to9/upgrade_prepare.sh

They changed the group and branch.

tests: Fix leapp repo url

---

templates/packer/ansible/roles/common/files/worker-initialization-scripts/get_ldap_sa_mtls_creds.sh

"null" as proxy isn't valid, which is the value proxy gets in case jq can't find the proxy defined in the secret.

templates/packer: fix proxy config in ldap service account init

---

test/cases/regression-old-worker-new-composer.sh

Image-info is installed via the latest test rpms, which need a newer osbuild version.

test/old-worker-new-composer: reset osbuild repo for image-info

---

.github/workflows/tests.yml
templates/openshift/maintenance.yml

We could deploy this job for both composer and each tenant's workers that's present in app-intf. Then we can remove the maintenance bits from the composer template.

templates/openshift: make the maintenance template generic

---

.github/workflows/tests.yml

The script hangs while pinging codecov for a url to upload the results to.

.github/workflows/tests: disable codecov until further notice

---

templates/openshift/maintenance.yml

Current runs fail because the ssl mode isn't set, and the service account is missing (in the workers-stage ns).

templates/openshift/maintenance: service account & parameter fixes

---

templates/packer/ansible/roles/common/files/worker-initialization-scripts/on_exit.sh
templates/packer/ansible/roles/common/files/worker-initialization.service

In case the service failed, set the instance to unhealthy.

templates/packer: add failure script

---

templates/dashboards/grafana-dashboard-image-builder-worker-api.configmap.yml
templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml

A space is necessary before and after the colon separating the key and the value.
[skip ci]

templates/dashboards: fix community-stage tenant variable

---

.github/workflows/tests.yml
codecov.yml

Same as https://github.com/osbuild/osbuild-composer/pull/4118 but opened from a branch so I have access to `secrets.CODECOV_TOKEN`. 

Reenable codecov via action

---

internal/cloudapi/v2/handler.go
internal/cloudapi/v2/openapi.v2.gen.go
internal/cloudapi/v2/openapi.v2.yml

This allows the compose status to reflect that it was saved locally, not uploaded to a remote service. Without this it returns an error of 'Compose has unknown upload target'

cloudapi: Add UploadTypesLocal for local_save status reports

---

test/cases/ostree-ng.sh
test/cases/ostree-raw-image.sh
test/cases/ostree-simplified-installer.sh

In order to align with PR [distro/rhel: unify osname for edge deployments](https://github.com/osbuild/images/pull/650), it is suggested to update edge-installer, edge-simplified-installer, and edge-raw-image tests with the corresponding osname value.

test: update osname for edge deployments

---

templates/packer/ansible/roles/common/tasks/main.yml
templates/packer/ansible/roles/common/tasks/packages.yml
templates/packer/ansible/roles/common/tasks/subscribe.yml
templates/packer/ansible/roles/common/tasks/unregister.yml
templates/packer/ansible/roles/common/tasks/worker-config.yml
templates/packer/ansible/roles/common/tasks/worker-initialization-service.yml
templates/packer/variables.pkr.hcl
templates/packer/worker.pkr.hcl
tools/appsre-build-fedora-worker-packer.sh
tools/appsre-build-worker-packer.sh
tools/ci-build-worker-packer.sh

With the rpmcopy or rpmrepo_osbuild tags, the `Install worker rpm` stage got skipped on RHEL and CI. Invert the tag logic and use `--tags` instead of `--skip-tags`.
---
CI
---
```
ansible-playbook  ./templates/packer/ansible/playbook.yml --tags ci --list-tasks
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
playbook: ./templates/packer/ansible/playbook.yml
play #1 (all): all	TAGS: []
tasks:
include_tasks	TAGS: [always]
include_tasks	TAGS: [always]
include_tasks	TAGS: [always]
include_tasks	TAGS: [always]
include_tasks	TAGS: [always]
common : Add osbuild-composer repository	TAGS: [ci]
common : Add osbuild repository	TAGS: [ci, fedora]
common : …
```

templates/packer: invert tag logic

---

internal/blueprint/customizations_test.go

Extend user customizations to include an expiration date. This allows users to be configured to require password change on first login.

Minor user customization test improvements

---

test/data/ansible/check_ostree.yaml

We have seen edge-commit-f39 and edge-installer-f39 failing in CI due to `"dmesg: read kernel buffer failed: Operation not permitted"`
```
TASK [check dmesg output] ******************************************************
fatal: [192.168.100.50]: FAILED! => {"changed": true, "cmd": ["dmesg"], "delta": "0:00:00.004286", "end": "2024-04-19 15:07:24.268256", "msg": "non-zero return code", "rc": 1, "start": "2024-04-19 15:07:24.263970", "stderr": "dmesg: read kernel buffer failed: Operation not permitted", "stderr_lines": ["dmesg: read kernel buffer failed: Operation not permitted"], "stdout": "", "stdout_lines": []}
```
This PR suggests to execute dmesg playbook task as privileged user.

test: execute dmesg task as privileged user

---

.gitlab-ci.yml
test/cases/ubi-wsl.sh

I updated wsl in the snapshot & switched to an absolute path to wsl. Apparently there are multiple wsl executables, some of which cannot be accessed in the ssh session, and some of which can.

test/cases/ubi-wsl: test rhel9 ga (HMS-4207)

---

.github/workflows/tests.yml
distribution/Dockerfile-config
distribution/Dockerfile-worker
tools/koji-compose.py

Fedora 37 has been EOL for some time.

GH actions / containerfiles: update F37 to F40

---

templates/packer/ansible/roles/common/tasks/main.yml
templates/packer/ansible/roles/common/tasks/packages.yml
templates/packer/worker.pkr.hcl
tools/appsre-build-worker-packer.sh

The tags don't get inherited through the dynamic `include_tasks` command. Use `import_tasks` to preserve the tags.
---
```
ansible-playbook  ./templates/packer/ansible/playbook.yml --tags rhel  --list-tasks
playbook: ./templates/packer/ansible/playbook.yml
play #1 (all): all	TAGS: []
tasks:
common : Subscribe	TAGS: [rhel]
common : Enable repo mgmt through subman	TAGS: [rhel]
common : Enable cdn repos	TAGS: [rhel]
common : Upgrade all packages	TAGS: [always]
common : Add Vector repo	TAGS: [always]
common : Install required packages	TAGS: [always]
common : Download AWS CLI installer	TAGS: [always]
common : Unpack AWS CLI installer	TAGS: [always]
common : Run AWS installer	TAGS: [always]
common : Cleanup AWS installer	TAGS: [always]
common : Create rpmbuild directory	TAGS: [rhel]
common : …
```

templates/packer: use import_tasks instead of include_tasks

---

test/data/ansible/check_ostree.yaml

We suggest to skip ostree-remount playbook task due to issue https://issues.redhat.com/browse/RHEL-25249 also detected recently in RHEL-9.4 
https://github.com/osbuild/rhel-edge-ci/actions/runs/8889962119/job/24409179382 
https://github.com/osbuild/rhel-edge-ci/actions/runs/8889962119/job/24409179480

test: skip ostree-remount due to issue RHEL-25249

---

.github/workflows/tests.yml
tools/provision.sh

Fix condition in `tools/provision.sh` for el10 and re-enable snapshot URL validation

---

cmd/osbuild-worker-executor/export_test.go
cmd/osbuild-worker-executor/main.go
cmd/osbuild-worker-executor/main_test.go

Pass the mock logger directly to `run()` instead of mocking `logrus.New`. Doing the later leads to a data race when multiple parallel tests modify the (global) `var logrusNew logrus.New`.
Thanks to Tomas Hozza for reporting.

main: rework the way the mock logger is passed

---

cmd/osbuild-worker/jobimpl-depsolve.go
cmd/osbuild-worker/jobimpl-osbuild.go

This is an alternative/complementary fix for https://github.com/osbuild/osbuild-composer/pull/4137. It is very simple so should be uncontroversial.
It fixes an issue that @schuellerf discovered, i.e. that when an error interface is passed into clienterrors.Error.Details the details get lost because the json.Marshaler will not know how to handler an error interface.
To find the problematic uses of `error` a custom vet checker was build in https://github.com/mvo5/osbuild-cvet. With that the result is:
```
$ go run github.com/mvo5/osbuild-cvet@latest ./...
/home/mvogt/devel/osbuild/osbuild-composer/cmd/osbuild-worker/jobimpl-depsolve.go:93:26: do not pass 'error' to WorkerClientError() details, use error.Error() instead
/home/mvogt/devel/osbuild/osbuild-composer/cmd/osbuild-worker/jobimpl-osb …
```

osbuild-worker: do not use `error` in clienterror.Error.Details

---

cmd/osbuild-worker-executor/handler_build_test.go
cmd/osbuild-worker-executor/handler_result_test.go
cmd/osbuild-worker-executor/handler_root_test.go

The `assert.Equal()` expects that the "expected" value is put first. Which is not what I'm used to. It's also slightly inconsistent because `assert.EqualError()` expects the "actual" err first and then the expected string. But this commit is not about ranting :)
This commit fixes the order in the tests assert.Equal() so that mismatches actually are displayed correctly.

osbuild-worker-executor: fix order of `assert.Equal()` in tests

---

go.mod
go.sum
vendor/github.com/osbuild/images/internal/common/helpers.go
vendor/github.com/osbuild/images/pkg/distro/fedora/distro.go
vendor/github.com/osbuild/images/pkg/distro/fedora/package_sets.go
vendor/github.com/osbuild/images/pkg/distro/fedora/partition_tables.go
vendor/github.com/osbuild/images/pkg/distro/rhel/rhel8/azure.go
vendor/github.com/osbuild/images/pkg/dnfjson/dnfjson.go
vendor/github.com/osbuild/images/pkg/manifest/ostree_deployment.go
vendor/github.com/osbuild/images/pkg/osbuild/systemd_unit_create_stage.go
vendor/github.com/osbuild/images/pkg/policies/policies.go
vendor/modules.txt

Relevant PRs included in this update:
* dnfjson: enable loading of optional metadata when needed (https://github.com/osbuild/images/pull/702)
* Author: Achilleas Koutsou, Reviewers: Brian C. Lane, Tomáš Hozza
* Fedora: Change AArch64 iot-simplified-installer to gpt (https://github.com/osbuild/images/pull/735)
* Author: Paul Whalen, Reviewers: Achilleas Koutsou
* Remove support for Fedora 38 (https://github.com/osbuild/images/pull/728)
* Author: Achilleas Koutsou, Reviewers: Simon de Vlieger
* Set the chunk size for S3 upload to 64MB (https://github.com/osbuild/images/pull/717)
* Author: Brad P. Crochet, Reviewers: Achilleas Koutsou
* distro/rhel8: update RHUI client RPM for Azure SAP 8.10 images (COMPOSER-2254) (https://github.com/osbuild/images/pull/707)
* Author: Achilleas Koutsou, …

go.mod: bump osbuild/images to v0.65.0

---

cmd/osbuild-worker/export_test.go
cmd/osbuild-worker/jobimpl-depsolve.go
cmd/osbuild-worker/jobimpl-depsolve_test.go

Tiny commit to extract a helper from DepsolveJobImpl.Run() that can then be unit tested.
This should help with https://github.com/osbuild/images/issues/727

obuild-worker: extract workerClientErrorFrom() helper and add tests

---

internal/osbuildexecutor/runner-impl-aws-ec2.go
internal/osbuildexecutor/runner-impl-aws-ec2_test.go

We need to allow files of type `tar.TypeGNUSparse` in the result that we get from the osbuild-worker-executor too.

osbuildexecutor: allow file type `tar.TypeGNUSparse` too

---

cmd/osbuild-worker-executor/export_test.go
cmd/osbuild-worker-executor/handler_build.go
cmd/osbuild-worker-executor/handler_build_test.go
cmd/osbuild-worker-executor/main_test.go
cmd/osbuild-worker/jobimpl-osbuild.go
internal/osbuildexecutor/osbuild-executor.go
internal/osbuildexecutor/runner-impl-aws-ec2.go
internal/osbuildexecutor/runner-impl-aws-ec2_test.go
internal/osbuildexecutor/runner-impl-host.go

This commit adds support to set the hostname to the job-id that is part of the control.json.
This is the first part, the second part will actually set this in the `internal/osbuildexecutor/runner-impl-aws-ec2.go`

osbuild-worker-executor: `job-id` in control.json as hostname

---

.gitlab-ci.yml

Remove rhel-8.10 jobs from test matrix

---

.golangci.yml

`images` also calls this linter but with `path-prefix`.
This should fix PR tests in the `images` repo

golangci: fix integration tests for images

---

cmd/osbuild-worker-executor/export_test.go
cmd/osbuild-worker-executor/handler_build.go
cmd/osbuild-worker-executor/handler_build_test.go
cmd/osbuild-worker-executor/main_test.go
cmd/osbuild-worker/jobimpl-osbuild.go
internal/cloud/awscloud/secure-instance.go
internal/cloud/awscloud/secure-instance_test.go
internal/osbuildexecutor/osbuild-executor.go
internal/osbuildexecutor/runner-impl-aws-ec2.go
internal/osbuildexecutor/runner-impl-aws-ec2_test.go
templates/packer/ansible/roles/common/files/worker-executor.service
templates/packer/ansible/roles/common/files/worker-initialization-scripts/set_executor_hostname.sh

This way much more of the journal will be captured under the new hostname.

Set executor hostname via cloud-init

---

.gitignore
HACKING.md
cmd/osbuild-composer/config.go
cmd/osbuild-composer/config_test.go
cmd/osbuild-composer/main.go
internal/cloudapi/v2/server.go
internal/common/context_hook.go
internal/common/echo_logrus.go
internal/common/external_id.go
internal/common/journal_hook.go
internal/common/journal_hook_test.go
internal/common/logger_middleware.go
internal/common/operation_id.go
vendor/github.com/coreos/go-systemd/journal/journal.go
vendor/modules.txt

This patch adds native journald support through logrus which enables to work with structured logs. It uses a dependency that is already in the project (`coreos/systemd-go`) which is a pure Go implementation. New log type is introduced named "journal" and it is now the default with fallback to "text" if journald is not present on the system.
Structured logging enabled me to work with logrus fields that can help with correlating log records on standalone or hosted deployments. Already existing "operation_id" field (random string) is now fully propagated via echo context logger and new logrus hook extracts it from Go standard context.
A new field called "external_id" is extracted from HTTP header `X-External-Id` when present. The idea is to set this to X-Edge-Request-Id on hosted image …

main: journald support with external correlation

---

internal/cloudapi/v2/errors.go
internal/cloudapi/v2/errors_test.go
internal/cloudapi/v2/handler.go
internal/cloudapi/v2/server.go
internal/cloudapi/v2/v2_koji_test.go

Also adds a few tests for the errorhandler.

cloudapi: more details for non-service errors

---

test/cases/aws.sh

Added spot_instance = true for CIV deployments in AWS.

---

templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml

Also makes the default 40m, which is the new slo target for osbuild jobs.
---
Now that #4242 is in, let's update the dashboards.

templates/dashboards: human readable job duration targets

---

.github/workflows/tests.yml
.gitignore
Containerfile_golangci_lint
Makefile
tools/apt-install-deps.sh

trying to reproduce `golangci-lint` errors with the new `make lint` and fix them

Introduce make lint

---

Makefile

followup of PR #4241
golint version should match golang version
this fixes `make lint` and implicitly fixes the github actions

Makefile: bump golint version

---

cmd/osbuild-worker/export_test.go
cmd/osbuild-worker/jobimpl-depsolve.go
cmd/osbuild-worker/jobimpl-depsolve_test.go
cmd/osbuild-worker/jobimpl-osbuild.go
cmd/osbuild-worker/jobimpl-osbuild_test.go

This should improve the error in the frontend from
to
There is no test framework to test changes like this, right?

osbuild-worker: improve error "reason" in case of stage failures (HMS-1442)

---

cmd/osbuild-worker/jobimpl-osbuild.go
cmd/osbuild-worker/jobimpl-osbuild_test.go

Small followup for
https://github.com/osbuild/osbuild-composer/pull/4113#discussion_r1670063775
Given that the failed stage is a relatively short string the `\n` seems unneccessary and quotes are enough.

osbuild-worker: tweak error to not include a \n for a failed stage

---

.gitlab-ci.yml
schutzbot/slack_notification.sh

Separate RHEL GA/EUS releases testing to nightly pipeline from the pipeline ran on every PR.

Create a nightly pipeline for GA/EUS releases

---

cmd/osbuild-composer/config.go
cmd/osbuild-composer/config_test.go
templates/openshift/composer.yml

Composer can load configuration values defined as map from ENV. Previously, when loading the configuration from ENV, the whole map would get overridden, not just values defined in the ENV. This is however not intended and not consistent with how loading configuration from file works.
Adjust the configuration loading from ENV and adjust the unit test accordingly.

Fix distro alias loading from ENV

---

schutzbot/slack_notification.sh

The `COMPOSE_ID` and `COMPOSER_NVR` variables were causing the GA pipeline's slack notification jobs to fail due to them being undefined when the script was invoked by those two jobs. Fixing that by moving their definition into the condition.
Run where the job failed: https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/jobs/7401301891

Fix slack GA pipeline notification job failure

---

test/cases/api.sh

When cleaning up api tests, the build job results are dumped from the database to store in build-result.txt and are printed to the runner log at the same time.  This makes it very difficult to read results as the database dump prints very long lines that flood the job log.  The result isn't really readable (or useful) unless the file is downloaded separately.
Silence the `tee` command so that the file is created but no output is printed from the db dump.
See for example [this job log](https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/jobs/7433608651) which starts with the last line of the database dump.  To see previous lines, you need to switch to the complete raw form.

test/api: silent dump_db()

---

cmd/osbuild-worker/jobimpl-awsec2.go
cmd/osbuild-worker/jobimpl-container-resolve.go
cmd/osbuild-worker/jobimpl-depsolve.go
cmd/osbuild-worker/jobimpl-file-resolve.go
cmd/osbuild-worker/jobimpl-koji-finalize.go
cmd/osbuild-worker/jobimpl-koji-init.go
cmd/osbuild-worker/jobimpl-osbuild.go
cmd/osbuild-worker/jobimpl-ostree-resolve.go
internal/cloudapi/v2/server.go
internal/cloudapi/v2/v2_koji_test.go
internal/cloudapi/v2/v2_test.go
internal/remotefile/resolver.go
internal/target/targetresult_test.go
internal/weldr/compose_test.go
internal/worker/clienterrors/errors.go
internal/worker/json.go
internal/worker/json_test.go
internal/worker/server.go
internal/worker/server_test.go

The usual convention to create new object is to prefix `New*` so this commit renames the `WorkerClientError`. Initially I thought it would be `NewWorkerClientError()` but looking at the package prefix it seems unneeded, i.e. `clienterrors.New()` already provides enough context it seems and it's the only error we construct.
We could consider renaming it to `clienterror` (singular) too but that could be a followup.
I would also like to make `clienterror.Error` implement the `error` interface but that should be a followup to make this (mechanical) rename trivial to review.
[this was https://github.com/osbuild/osbuild-composer/pull/4143 but for some reason I couldn't reopen it]

clienterrors: rename `WorkerClientError` to `clienterrors.New`

---

templates/openshift/composer.yml

This is to be inline with `image-builder` and to
enable decoding in splunk
@croissanne I'm still somewhat in the dark with the deployment setup :-/ is this the correct place to change the logs, going to splunk, to be json? (to support `|spath input=message` which works for `image-builder`)

Change log_format for the service to json

---

internal/cloud/awscloud/secure-instance.go

When the cleanup function gets called, there's a chance the Instnace field isn't populated yet, so store the instance ID separately and wait for it to be terminated in case it's present.
The error would produce the following trace:
```
goroutine 1 [running]:
...
main.(*OSBuildJobImpl).Run.func1()
osbuild/osbuild-composer/cmd/osbuild-worker/jobimpl-osbuild.go:404 +0xc5
panic({0x55e2a76a1e40?, 0x55e2a906d2f0?})
/usr/lib/golang/src/runtime/panic.go:920 +0x270
github.com/osbuild/osbuild-composer/internal/cloud/awscloud.(*AWS).deleteFleetIfExists(0xc000faa840, 0xc0012718c0)
osbuild/osbuild-composer/internal/cloud/awscloud/secure-instance.go:441 +0x175
github.com/osbuild/osbuild-composer/internal/cloud/awscloud.(*AWS).TerminateSecureInstance(0x55e2a90825e0?, 0x2?) …
```

cloud/awscloud: fix nil pointer dereference

---

cmd/osbuild-worker/jobimpl-depsolve.go
cmd/osbuild-worker/jobimpl-depsolve_test.go

The workerClientErrorFrom() was returning an `*clienterrors.Error` and an `error` (if something with the conversation goes wrong.
But the calling code was expecting that even if an `error` is returned the `*clienterrors.Error` is still valid. The caller would then just log the error. As returning a valid `value` even when there is an `error` is an unexpected pattern this commit changes the code to always return a `*clienterrors.Error` and log any issue via the logger.

osbuild-worker: rework the `workerClientErrorFrom()` error

---

.github/workflows/tests.yml
.gitignore
Makefile

I just wanted to check #4102 locally.
maybe that's helpful for someone

Makefile for templates/openshift

---

internal/osbuildexecutor/runner-impl-aws-ec2.go
internal/osbuildexecutor/runner-impl-aws-ec2_test.go

This is a short term workaround to get better visibility why the osbuild executor sometimes sends non-json data. When reading the result from the executor the entire output is now read and if the json parsing goes wrong it will use the entire body in the error message for better debug visibility.

osbuildexecutor: show full osbuild exector on json decode errors

---

cmd/osbuild-composer/config.go
cmd/osbuild-composer/main.go
internal/common/environment_hook.go
internal/common/environment_hook_test.go
templates/openshift/composer.yml

As far as I saw in the openshift deployment, the parameter `"CHANNEL"` is already set implicitly by the environment (`…/environments/stage.yml` or `…/environments/production.yml`)
If something like this worked, this would be awesome for filtering logs

logrus: add deployment channel as field to the logs

---

cmd/osbuild-composer/main.go

followup of PR #4285 
the "deployment channel" does not seem to be ending up in splunk.
@croissanne is it possible that it does not work just due to the order of logrus hooks being executed?

osbuild-composer: activate deployment-channel reporting for splunk

---

pkg/splunk_logger/environment_hook.go
pkg/splunk_logger/environment_hook_test.go

this has to be in two steps:
- duplicate `environment_hook` to `splunk_logger` first
- change and use the reference from within `go.mod` and the main code
so this PR just duplicates the code to `pkg/splunk_logger` to be able to reference it from there after being on `main` (from composer as well as image-builder later on)
or can this be done in one go? (...in one "go" 😁 🙄 )

splunk_logger: move environment hook to splunk_logger pt1

---

test/cases/minimal-raw.sh
test/data/ansible/check_ostree.yaml
tmt/plans/edge-test.fmf

This PR fixed test failures on fedora40 and centos-stream9.
1. disabled edge-commit and edge-installed test on fedora40 due to bug https://bugzilla.redhat.com/show_bug.cgi?id=2294897
2. disabled minimal-raw test on fedora40 due to bug https://github.com/virt-s1/rhel-edge/issues/3531 (this error only happens in upstream, need to use latest snapshot repo)
3. disabled ostree-remount test case on cs9 due to bug https://issues.redhat.com/browse/RHEL-25249
4. fixed some test case errors.
Those disabled cases will be added back after the bugs are fixed.

ci: fix edge test failures in cs9 and fedora40

---

tools/appsre-ansible/rpmbuild.yml

Also unsubscribe after the build is done.
---
Packer builds are failing with
```
10:18:52 TASK [Subscribe] ***************************************************************
10:19:18 fatal: [44.203.59.246]: FAILED! => {"changed": false, "cmd": "/sbin/subscription-manager register --org **** --activationkey VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "msg": "Remote server error. Please check the connection details, or see /var/log/rhsm/rhsm.log for more information.", "rc": 70, "stderr": "Remote server error. Please check the connection details, or see /var/log/rhsm/rhsm.log for more information.\n", "stderr_lines": ["Remote server error. Please check the connection details, or see /var/log/rhsm/rhsm.log for more information."], "stdout": "", "stdout_lines": []}
```
sometimes. Let's just retry like …

tools/appsre-ansible: retry subscribing rpmbuild machines

---

osbuild-composer.spec

Use an exact version dependency on the `osbuild-dnf-json-api` to ensure incompatible json protocol changes cannot break composer.
See also https://github.com/osbuild/osbuild/pull/1849

osbuild-composer: add `Requires: osbuild-dnf-json-api = 7`

---

tools/appsre-ansible/rpmbuild.yml

The community redhat_subscription module calls `subscription-manager unsusbscribe`, which doesn't exist. Use shell for now.
---
```
11:01:06 fatal: [54.91.239.48]: FAILED! => {"attempts": 5, "changed": false, "cmd": "/sbin/subscription-manager unsubscribe --all", "msg": "", "rc": 1, "stderr": "", "stderr_lines": [], "stdout": "Usage: subscription-manager MODULE-NAME [MODULE-OPTIONS] [--help]\n\r\nPrimary Modules: \n\n  attach         Attach a specified subscription to the registered system, when system does not use Simple Content Access mode\n  list           List subscription and product information for this system\n  refresh        Pull the latest subscription data from the server\n  register       Register this system to the Customer Portal or another subscription management service\n …
```

tools/appsre-ansible: fix unregister

---

internal/worker/client.go

The current name `Client.server` feels a bit misleading as it is unclear if this is an abstraction for a "server" object or an URL. This rename makes this unambiguous.
There are some more opportunities to tweak the code here, I can do some followups if desired but this is an extremely low-hanging fruit.

worker: rename `server` -> `serverURL`

---

internal/worker/client.go

There is no actual payload when posting the worker status so let's just post `nil` instead of an empty `bytes.Buffer` to make this explicit.

worker: simplify the `POST` in workerHeartbeat()

---

internal/worker/client.go

I find it slightly eaiser to read this code when
`api.BasePath = conf.BasePath` is right at the top as it's unrelated to the parsing code below.
Note that the code itself is problematic:
- api.BasePath is global but client is not, this means that multiple client with different configs will result in api.BasePath being potentially wrong
- api.BasePath is set in a non-thread safe manner
Changing is a bigger job but we might consider it (IMHO).

worker: move `api.BasePath` setup to the start of the funcs

---

cmd/osbuild-worker/jobimpl-osbuild.go
internal/cloudapi/v2/imagerequest.go
internal/target/gcp_target.go
internal/weldr/upload.go
test/cases/api/gcp.sh
test/cases/gcp.sh

Previously, the worker was determining the GCE image guest OS Features on its own, based on the OS name. This caused problems, in case the osbuild-composer was of a newer version than the worker.
Example:
osbuild-composer contained support for c10s GCE image type and its implementation also contained the proper guest OS Features list for it. However, when the worker got the osbuild job, it built it and tried to fetch the guest OS Features for the distro. Since its implementation was too old, it didn't contain the code that added the actual support for c10s GCE images and got no guest OS features list (which is the default for unsupported distros). The image was successfully uploaded and shared, but it does not boot in GCP, because it does not know that it should use UEFI to boot it.
This …

Worker: move GCE image guest OS features to upload target options

---

tools/build-rpms.py

Mockbuilds are currently timing out after #4287, maybe due to memory constraints.

tools/build-rpms: increase size of instances

---

cmd/osbuild-worker/jobimpl-depsolve.go
cmd/osbuild-worker/jobimpl-depsolve_test.go

osbuild/images#751 wrapped the errors in the images/dnfjson package to provide more details, the depsolve job should take this into account to map the dnfjson error to the correct worker client error.
This caused user input errors errors to be misclassified as internal errors, triggering depsolve job failure alerts.

osbuild-worker: handle error wrapping from dnfjson package

---

internal/worker/client.go

Just refactor the usage of the mutex to remove code duplication

internal/worker/client.go: refactor reading worker ID

---

internal/upload/azure/azure.go

When creating a storage account we're currently allowing public blob access, users might have compliance policies active on their azure accounts which forbid this.
---
Even though the default should be false, we're still getting
```
Storage account Allow Blob Public Access should be disallowed
```
so let's just do it explicitly.

upload/azure: turn off public access on storage accounts

---

internal/worker/client.go
internal/worker/client_test.go

When the osbuild worker cannot register itself with the server on startup the worker will "crash". This is inconsistent with the existing behavior in `workerHeartbeat()` which deals with connectivity or other server issue gracefully and retries periodically.
To unify the behavior this commit changes the behavior and only issues a `logrus.Warnf` instead of the previous `Falalf` when the registration fails.
---
This is an alternative version of https://github.com/osbuild/osbuild-composer/pull/4320 that contains the minimal change to achieve the goal with a test. I feel quite rude to open this PR and I'm sorry for this. I'm mostly doing this as I feel after 51 discussion comments in the other PR it might be easier/more illustrative to offer an alternative version instead of keeping the …

osbuild-worker: fix "crashing" on worker registration issues

---

tools/build-rpms.py

The instance created for rpm builds is running out of space on the default 10G disk, let's double it.

tools/build-rpms: increase rpm builder instance disk size

---

tools/build-rpms.py

Fixes:
```
Error: Create EC2 instances  failed: 'ec2.ServiceResource' object has no attribute 'describe_images'
Traceback (most recent call last):
File "/osbuild-composer/tools/build-rpms.py", line 218, in <module>
stage_generate_rpms(cleanup_actions, args)
File "/osbuild-composer/tools/build-rpms.py", line 175, in stage_generate_rpms
create_ec2_instances, cleanup_actions, args, keyname)
File "/osbuild-composer/tools/build-rpms.py", line 66, in stage
ret = fun(*args)
File "/osbuild-composer/tools/build-rpms.py", line 109, in create_ec2_instances
img = ec2.describe_images(ImageIds=[arch_info[a]["ImageId"]])
AttributeError: 'ec2.ServiceResource' object has no attribute 'describe_images'
```
---
I didn't realise the difference between boto resources and boto clients. Rather confusing imo.

tools/build-rpms: fix ec2 client initialisation

---

test/cases/api/common/common.sh

tests: fix api.sh gcp ssh connection timeout

---

cmd/osbuild-composer/composer.go
tools/provision.sh

The `reporegistry.New()` has been enhanced to return an error, in case there were no repositories loaded. This was to fix the situation in many unit tests, which were previously not loading any repositories and silently not running any tests.
This however broke our SaaS deployment, where we actually do not configure any repositories on the filesystem. As a result, osbuild-composer started to fail on it.
Workaround this situation in osbuild-composer by reverting to the old behavior by loading the repo configs separately and then using the loaded repos (which could be empty map) to initialize the RepoRegistry.
Also update the `tools/provision.sh` to delete all repositories in the Service scenario.

composer: don't create RepoRegistry using reporegistry.New()

---

.gitlab-ci.yml
test/cases/api.sh
test/cases/api/common/common.sh

test/cases: Use openscap customization + enable oci api test on RHEL-10 

---

internal/cloud/awscloud/mocks_test.go
internal/cloud/awscloud/secure-instance.go

While I was investigating a customer report I noticed this small typo which could actually cause the fallback not to work at all. The correct terms are linked from AWS Go library:
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html
Related issue: https://issues.redhat.com/browse/HMS-4676

cloud: fixed typo UnfulfillableCapacity (HMS-4676)

---

.gitlab-ci.yml

Just making it more clear and scheduling aws.sh on RHEL-10 and GA runners.

CI: integration test rules fixup

---

.gitlab-ci.yml
templates/openshift/composer.yml
templates/openshift/maintenance.yml
test/cases/regression-composer-works-behind-satellite-fallback.sh
test/cases/regression-composer-works-behind-satellite.sh

When generating x509 v3 certs we need to explicitely set "CA:TRUE" otherwise they're not trusted to be used.

tests/regression: Add config for v3 certificates

---

test/cases/filesystem.sh

The test started failing on 8.10 GA. It seems that something changed in the system repos and the size we had originally set was not enough.

tests/filesystem: increase /usr size

---

internal/cloud/awscloud/secure-instance.go
internal/cloud/awscloud/secure-instance_test.go

In case the on demand option failed as well, retry one more time across availability zones. This significantly increases the pool of available instances, but increases network related costs, as transferring data between AZs is not free.

cloud/aws: add a third secure instance fallback across AZs

---

test/data/ansible/check_ostree.yaml

Since /sysroot is being mounted as ro and /var as rw, ostree-remount.service will not remount those mountpoints. The test is no longer necessary. 
Thus, this PR suggests to delete the task as a workaround for the reported Jira [edge-commit CS9 failure: ostree-remount.service fails to remount /sysroot and /var mountpoints](https://issues.redhat.com/browse/RHEL-25249)

test: disable ostree-remount service checking since /sysroot is ro and /var rw already

---

internal/cloud/awscloud/secure-instance.go
internal/cloud/awscloud/secure-instance_test.go

The errors returned by create fleet are not entirely clear. It seems it also returns `InsufficientInstanceCapacity` in addition to `UnfulfillableCapacity`. Let's just retry three times regardless of the create fleet error, that way there's no need to chase error codes which aren't clearly defined.

cloud/awscloud: retry CreateFleet regardless of the error code

---

templates/packer/worker.pkr.hcl

Imagine this scenario: the packer job is ran, an AMI gets created.
We configure our deployment to use this AMI. Then, someone retries the
packer job. Since we have force_deregister=true, this will not only
create a new AMI, but also remove the old one (because it has the same
name). Thus, our deployment will get broken, because the source AMI
no longer exists. This means that the ASG cannot replace any broken
instances, and the secure instance feature gets absolutely broken
because it cannot spawn new secure instances (they "inherit" the AMI
ID from their parents).
Let's remove force_deregister=true, so the AMI never gets replaced.
This might cause some pipelines to start failing because they are
rerunning the packer job for same commit (the GA pipeline currently).
Let's fix those then, …

packer: don't deregister old AMIs (COMPOSER-2376)

---

internal/blueprint/blueprint.go
internal/blueprint/blueprint_convert_test.go
internal/blueprint/installer_customizatios.go

**blueprint: enable the anaconda modules customization**
This has been available since v0.74.0 of osbuild/images but was never
connected to the frontend blueprint.
See https://github.com/osbuild/images/pull/799
---
**blueprint: add kickstart contents to conversion test**
The option was added in f5c6cdd9cfc6d38a375b2f38d868d520399b668d but a
value was never added to the conversion test.
---

Enable the anaconda modules customization

---

cmd/osbuild-service-maintenance/aws.go
cmd/osbuild-service-maintenance/aws_test.go
cmd/osbuild-service-maintenance/export_test.go
internal/cloud/awscloud/awscloud.go
internal/cloud/awscloud/awscloud_test.go
internal/cloud/awscloud/maintenance.go
internal/cloud/awscloud/maintenance_test.go

Now and then there are leftover secure instances, probably when worker instances get terminated during builds, this is possible in ASGs. 2 hours as a cutoff should be enough, since the build times out after 60 minutes, and fetching the output archive after 30 minutes, so that leaves 30 minutes for booting and connection.

Remove leftover secure instances in service maintenance

---

internal/cloud/awscloud/export_test.go
internal/cloud/awscloud/secure-instance.go
internal/cloud/awscloud/secure-instance_test.go

The current path sometimes launches two instances, which is problematic because the rest of the secure instance code expects exactly one instance. A security group could be attached to both instances and would block the worker from launching any more SIs as it tries to delete the old security group first, which is still held by one of the surplus SIs which didn't get terminated.
Only retry if:
- there are "UnfulfillableCapacity" or "InsufficientInstanceCapacity" error codes;
- there wasn't an instance launched anyway.
If either of these checks fail, do not try to launch another one, and just fail the job.

cloud/awscloud: rework create fleet retry logic

---

schutzbot/slack_notification.sh

We are on a quest to reduce clutter on our Slack channels. Thus,
I decided to simplify the daily CI notifications:
- the link to the edge pipelines got removed, it's now in bookmarks
- several words were removed to make the message shorter
- the link to the pipeline is now a hyperlink
- the whole message should be a one liner
- less text is now bold
I've also simplified the format in which we send the message. I think
that the block format used before makes redundant line-breaks.
Unfortunately, the mentions need to be done using user IDs instead
of user names. If you ever need to find them, go to the user's profile,
click on the three dots and select "Copy member ID".
Before:
After:
(I've also removed the bold style from the COMPOSE_ID and the NVR, this is not shown in the screenshot.)

schutzbot: shorten the slack notification

---

cmd/osbuild-worker/jobimpl-osbuild.go

This looks like a copy and paste error.
The variable name was not correct:
https://github.com/osbuild/osbuild/blob/4b4b5cea950910ed9e1bc9d2fc1c618e0596b2b7/sources/org.osbuild.curl#L14

worker: fix OSBUILD_SOURCES_CURL_SSL_CA_CERT variable

---

internal/cloud/awscloud/maintenance.go

The maintenance pod is crashing when describing the images by tag, most likely something else is failing.

cloud/awscloud: fix nil pointer dereference in maintenance fns

---

osbuild-composer.spec

I just created a release for the backport tagged v101.1: https://github.com/osbuild/osbuild-composer/releases/tag/v101.1
and made a copr build successfully for the affected user, but quickly realised I hadn't updated the version in the spec file.

spec: update version to 101.2

---

internal/cloud/awscloud/secure-instance.go

Set the correct target capacity specification type, just setting the spot options to nil doesn't result in an on demand instance.

cloud/awscloud: fix retrying to create secure instances

---

templates/packer/ansible/roles/common/files/worker-initialization-scripts/worker_config.sh

Currently the worker images always have to use aws.ec2, this way we can use the host executor for fedora.

templates/packer: allow setting executor type in worker config

---

cmd/osbuild-service-maintenance/aws.go

Respect dry run when terminating leftover SIs.
---
Forgot about this when adding #4420. This isn't urgent, currently dryrun isn't enabled anywhere.

cmd/osbuild-service-maintenance: respect dry run

---

templates/packer/worker.pkr.hcl

templates/packer: fix fedora 40 aarch64 base image

---

internal/cloud/awscloud/secure-instance.go

The current spot price could be limiting the available instance pool significantly. ARM instances specifically are experiencing a lot of capacity errors.

cloud/awscloud: don't specify max spot price

---

Makefile

This is a followup of #4435.
To speedup `make lint` we use a local cache.
It seems that there is no sane way to check and just update the cache, so we'll just provide an option to wipe it.
Using the cache does reduce the time of `make lint` from 1 minute 15sec to 1 sec on my PC. So for consecutive runs, the cache still makes sense.
Thanks @mvo5 for the tests in #4435

Makefile: clean golangci-lint cache on `make clean`

---

cmd/osbuild-composer/composer.go
cmd/osbuild-composer/config.go
go.mod
go.sum
templates/openshift/composer.yml
test/cases/api.sh
test/cases/regression-old-worker-new-composer.sh
test/data/composer/osbuild-composer-jwt.toml
test/data/composer/osbuild-composer-tls.toml
tools/provision.sh
vendor/github.com/osbuild/images/pkg/reporegistry/error.go
vendor/github.com/osbuild/images/pkg/reporegistry/reporegistry.go
vendor/github.com/osbuild/images/pkg/reporegistry/repository.go
vendor/modules.txt

This is a small update that only includes one PR from osbuild/images: https://github.com/osbuild/images/pull/946
The second and third commits change the behaviour of osbuild-composer's startup when no repositories are configured.
Weldr (running on-prem) requires local repository configurations, while the API (SaaS) doesn't.  However, at the time during startup when reporegistry.LoadAllRepositories() is called, it is still not known whether the Weldr API will be initialised.
Since lack of repository configurations is no longer a stop condition for osbuild-composer's startup, the Weldr API will now return with an error when no repositories are configured during its initialisation.

go.mod: update osbuild/images to v0.95.0

---

templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml

Adds the charts "Pending Jobs Max" and "Pending Jobs"
both "by type".
To see how many jobs are pending and where we might need more workers.
Note that the second commit to enable crosshair is just convenience and could be removed from this PR or split off if needed.

Introduce grafana number of pending jobs

---

.github/workflows/tests.yml
Makefile
cmd/osbuild-composer-dbjobqueue-tests/main_test.go
cmd/osbuild-service-maintenance/db_test.go
internal/jobqueue/jobqueuetest/jobqueuetest.go
tools/dbtest-entrypoint.sh
tools/dbtest-prepare-env.sh
tools/dbtest-run-migrations.sh

This PR implements `make db-tests` and extends `make clean`
The tests which are run locally until now used the `fsjobqueue` and the postgres DB tests were only run in github.
For now this just implements running the tests. More improvements to the tests them selves will be handled in subsequent PRs.

Implement running db tests locally

---

cmd/osbuild-koji-tests/main_test.go
cmd/osbuild-koji/main.go
cmd/osbuild-worker/jobimpl-osbuild.go
cmd/osbuild-worker/jobimpl-ostree-resolve.go
cmd/osbuild-worker/main.go
go.mod
go.sum
internal/cloudapi/v2/imagerequest.go
internal/cloudapi/v2/server.go
internal/weldr/api.go
internal/weldr/upload.go
vendor/github.com/osbuild/images/pkg/disk/disk.go
vendor/github.com/osbuild/images/pkg/disk/lvm.go
vendor/github.com/osbuild/images/pkg/disk/partition_table.go
vendor/github.com/osbuild/images/pkg/distro/distro.go
vendor/github.com/osbuild/images/pkg/distro/fedora/imagetype.go
vendor/github.com/osbuild/images/pkg/distro/rhel/imagetype.go
vendor/github.com/osbuild/images/pkg/distro/rhel/rhel8/azure.go
vendor/github.com/osbuild/images/pkg/distro/test_distro/distro.go
vendor/github.com/osbuild/images/pkg/image/bootc_disk.go
vendor/github.com/osbuild/images/pkg/image/disk.go
vendor/github.com/osbuild/images/pkg/image/gce.go
vendor/github.com/osbuild/images/pkg/manifest/build.go
vendor/github.com/osbuild/images/pkg/osbuild/container_deploy_stage.go
vendor/github.com/osbuild/images/pkg/ostree/ostree.go
vendor/github.com/osbuild/images/pkg/platform/bootmode.go
vendor/modules.txt

For Edge Pulp migration we need the very same thing as repositories (curl) but for ostree input.

osbuild-worker: use the new ostree resolver API

---

cmd/osbuild-worker/jobimpl-ostree-resolve.go

My MTLS patch was not correctly checking MTLS config - it is currently missing and all builds are failing.
https://issues.redhat.com/browse/HMS-4975

worker: check MTLS config for ostree

---

cmd/osbuild-worker/jobimpl-ostree-resolve.go

Ostree builds are ending up with "connection refused"
```
"details": "error sending request to ostree repository \"https://mtls.xxxxx.redhat.com/api/pulp-content/edge-integration-test-2/lzap-rhel9/refs/heads/rhel/9/x86_64/edge\": Get \"https://mtls.xxxxx.redhat.com/api/pulp-content/edge-integration-test-2/lzap-rhel9/refs/heads/rhel/9/x86_64/edge\": proxyconnect tcp: dial tcp :0: connect: connection refused"
```
this patch ensures the proxy configuration parses fine, it should be set to `squid.xxxxxxx.redhat.com:3128` which parses fine via `url.Parse` so not sure why it does not work.
Well at least I found this, but need to dig deeper.

worker: check MTLS proxy for nil

---

.github/workflows/tests.yml
Makefile
internal/cloudapi/v2/server.go
internal/jobqueue/fsjobqueue/fsjobqueue.go
internal/jobqueue/jobqueuetest/jobqueuetest.go
internal/worker/clienterrors/errors.go
internal/worker/server.go
pkg/jobqueue/dbjobqueue/dbjobqueue.go
pkg/jobqueue/jobqueue.go

Fixes the special case that if no worker is available and we generate an internal timeout and cancel the depsolve, including all followup jobs, no error was propagated.
For details, see https://issues.redhat.com/browse/HMS-2989
Now all jobs (in the DB) are set to "failed":
* All `jobs` entries get a "job_error" in the `result` as well as
* `started_at` and `failed_at` are set to "now" and
* `token` is set to a random UUID to comply with the DB schema
This is set to draft for now until:
* I get feedback that this approach is ok
* tests are implemented
* we decided on if we should "create a separate metrics" (see comment in the code)

internal/worker/server: return an error on depsolve timeout (HMS-2989)

---

internal/cloud/awscloud/secure-instance.go

We'll log as direct URL to the console for easier tracing
@croissanne would this work (especially `identity.Region`) and do you think this is useful or too much 😁

awscloud/secure-instance: enrich logging with secure instance id

---

internal/cloud/awscloud/secure-instance.go

Terminated waiter sometimes responded
with `waiter state transitioned to Failure`
where we want to retry waiting for the termination

awscloud/secure-instance: retry on error in terminated waiter

---

Schutzfile

Newer osbuild uses dnf 4 on Fedora 41, as we've seen Fedora 41 in combination with dnf 5 (and SBOMs) failing.

Schutzfile: update osbuild commit (COMPOSER-2406)

---

cmd/osbuild-worker/export_test.go
cmd/osbuild-worker/main.go
cmd/osbuild-worker/main_test.go

This is a bit of an RFC commit, I noticed that when we discussed a crash from the worker we lookged at individual message from syslog/journald for the stacktrace deatils. I was wondering if having a more direct crash report would be more useful? We can of course also add more logrus features to flag those with tags like "crash" or something (I did not do that in this PR, I don't know much about the operational side, sorry).
Feel free to close if we already have similar means to get the comprehensive stacktrace, I looked into how we deploy this but it seems we run the worker directly via a systemd unit so this might be still useful.

worker: report cashes directly to logrus

---

templates/openshift/composer.yml

templates/composer: bump rhel-9 distro alias

---

internal/cloud/awscloud/secure-instance.go

By surfacing the output even in case of an error, the fleet ID and
instance ID can be extracted if present. Thus the instance can be
terminated before its dependencies are deleted.
---
We're seeing some behaviour where create fleet is not retried and subsequently the SI cleanup fails due to the security group already being tied to an existing instance. There is no error that an instance was launched anyway.

awscloud/secure-instance: fix cleaning up fleets with creation errors

---

cmd/osbuild-worker/jobimpl-osbuild.go

It looks like extra env is not passed correctly for ostree builds, this should verify it. There are no secrets, certs and keys are passed via filenames, so this should be safe.

cmd: extra env logging for osbuild worker

---

schutzbot/slack_notification.sh

Removing myself from the slack notifications as I'm no longer a QE member.

CI: remove jrusz from notifications

---

internal/cloud/awscloud/secure-instance.go

That way you can just enter the parent instance id into the search bar and get both the worker and its executor.

cloud/awscloud: give secure instances a name

---

internal/cloudapi/v2/server.go

Implement logic to carry the MTLS secret for ostree URLs, enhancing compatibility with HTTPS schemes. This change also maintains backwards compatibility for older workers.

cloudapi: carry ostree MTLS secret over

---

internal/cloud/awscloud/secure-instance.go

Even in case of errors, as long as create fleet returns an instance,
attempt to use it.
In some cases AWS returns `InsufficientInstanceCapacity` but still
creates an instance:
```
msg="Won't retry CreateFleet with OnDemand instance, retry: false, errors: InsufficientInstanceCapacity: There is no Spot capacity available that matches your request.; Already launched instance ([i-...]), aborting create fleet"
msg="doCreateFleetRetry: returning retry: false, msg: [InsufficientInstanceCapacity: There is no Spot capacity available that matches your request. Already launched instance ([i-...]), aborting create fleet]"
msg="doCreateFleetRetry: cancelling retry, instance already exists: [i-...]"
msg="doCreateFleetRetry: setting retry to true"
msg="Checking to retry fleet create on error …
```

cloud/awscloud: use any instance create fleet returns

---

tools/define-compose-url.sh

Update a RHEL 10 compose URL to point to nightly instead of public beta. This PR should fix a failing RHEL10 nightly pipeline as the url will point now to correct repositories.

tools/tests: Update rhel10 compose url

---

Makefile
cmd/osbuild-service-maintenance/aws.go
cmd/osbuild-service-maintenance/aws_test.go
cmd/osbuild-service-maintenance/export_test.go
internal/cloud/awscloud/maintenance.go

Implement removal of orphaned items as described in https://issues.redhat.com/browse/HMS-3632
removal of launch templates is not yet implemented (that's why it's a draft for now)

Clean up orphaned instances and security groups (HMS-3632)

---

.golangci.yml

Prevent linting processes from running on the vendor directory to improve efficiency.

Exclude vendor directory ci: do not perform linting on vendor/from linting

---

cmd/osbuild-composer/main.go
cmd/osbuild-worker-executor/handler_build.go
internal/auth/jwt_auth_handler.go

Newer versions of the go compiler (1.24 in this case) fail when running go test during a mock rebuild of the srpm created by 'make srpm' on Fedora 42.
Even though we currently don't support go1.24, fix these so they don't become an issue when we do.

Fix non-constant log strings

---

go.mod
go.sum
vendor/github.com/golang/glog/glog.go
vendor/github.com/golang/glog/glog_file.go
vendor/github.com/golang/glog/glog_file_nonwindows.go
vendor/github.com/golang/glog/glog_file_windows.go
vendor/modules.txt

github.com/golang/glog 1.2.2 is reported to be potentially vulnerable, so we'll upgrade to 1.2.4.

go.mod: upgrade glog

---

cmd/osbuild-composer/composer.go

This commit changes cmd/composer to use the `reporegistry.New` call again. This is a preparation for
https://github.com/osbuild/images/pull/1179
And undoes parts of https://github.com/osbuild/osbuild-composer/pull/4378 but that is no longer necessary because in
https://github.com/osbuild/images/pull/946 the error is now passed on from `reporegistry.New()` in the same way as from `LoadRepositories()`.

composer: use `reporegistry.New()` again (see PR#4378)

---

go.mod
internal/cloudapi/v2/handler.go
internal/cloudapi/v2/openapi.v2.gen.go
internal/cloudapi/v2/openapi.v2.yml
internal/cloudapi/v2/v2_test.go

cloudapi: Add /distributions/ to cloudapi

---

cmd/osbuild-composer/config.go
cmd/osbuild-composer/config_test.go
osbuild-composer.spec

I noticed a few issues that should land in RHEL-9.6 and RHEL-10:
- SPEC: unconditionally undefine gomodulesmode
- osbuild-composer: bump rhel-9 distro alias to rhel-9.6

ITM26 last-minute fixes

---

.github/workflows/coverity_scan.yml
.github/workflows/create-tag.yml
.github/workflows/pr_best_practices.yml
.github/workflows/release.yml
.github/workflows/stale-cleanup.yml
.github/workflows/tests.yml
.github/workflows/trigger-gitlab.yml

Changes the github workflows to use ubuntu-22.04 everywhere.

Switch github workflows to ubuntu 22.04

---

test/README.md

The repository of the "backend" aka "middleware" was renamed
from `image-builder` to `image-builder-crc`.

test/README: image-builder repo was renamed to image-builder-crc

---

tools/prepare-source.sh

Repeat of 8554d6202dff0f887d0f8bec838f15c24af02e8d.
This is a much nicer (and newer) way of handling the Go version for the
project.  The issue that caused the previous revert was that the toolbox
version was being set to 1.22.0, which is older than what some
dependencies require, specifically osbuild/images, so the 'go mod tidy'
would downgrade images to match the required toolbox version.
Setting the go and toolbox version to 1.22.6 should make it all work as
expected.
This reverts commit 7e87d1e124c1bbd49f7a0afcd732fd83357f4e57.
Co-authored-by: Lukáš Zapletal <lukas@zapletalovi.com>

tools: use go toolbox instead of installing a binary

---

.golangci.yml
Makefile
cmd/gen-manifests/main.go
cmd/gen-manifests/workerqueue.go
cmd/osbuild-worker-executor/handler_build.go
cmd/osbuild-worker/config.go
cmd/osbuild-worker/jobimpl-file-resolve.go
cmd/osbuild-worker/jobimpl-koji-finalize.go
cmd/osbuild-worker/main.go
internal/blueprint/fsnode_customizations.go
internal/boot/netns.go
internal/cloudapi/v2/handler.go
internal/upload/koji/koji.go

Currently a draft because I am not sure how to handle:
```
internal/cloudapi/v2/handler.go:467:17: G115: integer overflow conversion uint64 -> int (gosec)
buildID := int(initResult.BuildID)
^
cmd/osbuild-worker/jobimpl-koji-finalize.go:314:19: G115: integer overflow conversion uint64 -> int64 (gosec)
StartTime: int64(args.StartTime),
^
cmd/osbuild-worker/jobimpl-koji-finalize.go:105:40: G115: integer overflow conversion uint64 -> int (gosec)
err = impl.kojiFail(args.Server, int(initArgs.BuildID), initArgs.Token)
```
Ideally these would just use the proper type from the start, but I don't know exactly how this interacts with koji, what values it expects or returns.

Use golangci-lint v1.60 and cleanup the errors it returns

---

internal/cloudapi/v2/compose_test.go

This will make it easier to update next time the distribution version needs to be bumped.

cloudapi: Use constants for distro in compose_test.go

---

internal/cloud/gcp/compute.go

Latest RHEL images (from 9.6 on) should fully support running as TDX guests, as well as latest CentOS images.
See: https://issues.redhat.com/browse/COS-3111
See: https://github.com/coreos/coreos-assembler/pull/4006
See: https://gitlab.com/redhat/centos-stream/src/kernel/centos-stream-9/-/merge_requests/5979
I couldn't find anything relevant to be changed to address the points above.

internal/cloud/gcp/compute: Add TDX_CAPABLE guest OS feature

---

.github/CODEOWNERS

Setting people for `/templates` codeowners: @croissanne @kingsleyzissou @thozza (and myself)
@kingsleyzissou do you want to be part of `/templates` or only `/templates/dashboards`
Did I miss someone?

CODEOWNERS: set people for `/templates`

---

.gitlab-ci.yml

Disable installer test because it will keep failing due to the fix for dracut missing ifcfg won't make RHEL 10 nightly composes.

tests/CI: Disable installer test for RHEL 10.0 nightly

---

templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml

minor change: Increase timespan readability
Also introduces "50min." as we use this now for alerting and
shorten/update some titles to see which charts _are affected_ by the `target_duration`.

templates/dashboards: increase timespan readability

---

internal/cloudapi/v2/v2_internal_test.go

This commit discards the logrus output when the tests are run. That might be a controversial change but the amount of redundant output that drowns the actual failures makes it very hard to work with these tests.
I want to paste the output here in full but github won't let me because it's too long for the limits that the body can have!
It is 1135 lines and exceeds the 65536 bytes limit of GH.

cloudapi: silence logrus in tests

---

test/cases/openshift_virtualization.sh

The old one is going to be decommissioned. I only changed:
- extracted the storage class to a variable
- adjusted the openshift yaml file to what I was given in the UI
- most importantly, we now use an instancetype to specify the
resource requirements instead of doing it manually
- the network is called default, instead of nic0 on this cluster
- we are downloading the oc and virtctl clients from the new cluster
so the versions match
+ I removed wget, and introduced retries to help with flakiness.

test: migrate the openshift virt test to a new cluster (COMPOSER-2458)

---

.github/workflows/tests.yml

Add a check which leverages the osbuild/images@check-spec-deps-action action to check that the SPEC files requires at least the minimum versions for dependencies specified by the `osbuild/images`.

GH Action: check the SPEC osbuild/images deps minimum version

---

.github/workflows/create-tag.yml
internal/client/blueprints_test.go
osbuild-composer.spec

Also add the option to specify version for the "create tag" action for the first "dot" release on the branch.

[RHEL-9.5.0] SPEC: bump the version to the next to release

---

.github/workflows/create-tag.yml
internal/client/blueprints_test.go
osbuild-composer.spec

Also add the option to specify version for the "create tag" action for the first "dot" release on the branch.

[RHEL-9.6.0] SPEC: bump the version to the next to release

---

internal/client/blueprints_test.go

The version check is failing on the "dot" version, while trying to convert "118.1" to an integer. Delete the condition for skipping the test, because it will never be running on anything older than v83 anyway.

client/blueprints_test.go: delete condition for composer version < 83

---

.gitlab-ci.yml
test/cases/api/aws.s3.sh
test/cases/api/generic.s3.sh

**test: disable verification step for vsphere builds**
The vsphere verification is failing consistently with the following
error message from govc:
A component of the virtual machine is not accessible on the host.
Disabling it until we have time to look into it further.
---
**gitlab: disable vmware tests**
The vmware tests are consistently failing.  While the build succeeds,
the upload step fails with:
Unable to protect host, if the host isn't running as part of an
autoscaling group, this can safely be ignored: operation error Auto
Scaling: DescribeAutoScalingInstances, get identity: get credentials:
failed to refresh cached credentials, no EC2 IMDS role found,
operation error ec2imds: GetMetadata, http response error StatusCode:
404, request to EC2 IMDS failed
Disabling the test until we …

Disable vmware tests and verification step in vsphere builds

---

.github/workflows/tests.yml

The `packit validate-config` command was replaced with `packit config validate` as per [packit changelog](https://github.com/packit/packit/blob/main/CHANGELOG.md?plain=1#L8) in version 1.6.0
ATM, due to packit config lint failire, it blocks my [PR#4613](https://github.com/osbuild/osbuild-composer/pull/4613)

update packit validate-config command

---

.github/workflows/tests.yml
go.mod
go.sum
osbuild-composer.spec
vendor/github.com/golang-jwt/jwt/v4/parser.go
vendor/github.com/golang-jwt/jwt/v5/README.md
vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
vendor/github.com/golang-jwt/jwt/v5/parser.go
vendor/github.com/golang-jwt/jwt/v5/token.go
vendor/modules.txt

[RHEL-9.6] go.mod: update jwt-go to v4.5.2 and v5.2.2 to fix CVE-2025-30204

---

go.mod
go.sum
vendor/github.com/osbuild/images/pkg/distro/defs/rhel-10/distro.yaml
vendor/github.com/osbuild/images/pkg/distro/defs/rhel-9/distro.yaml
vendor/github.com/osbuild/images/pkg/distro/fedora/images.go
vendor/github.com/osbuild/images/pkg/distro/image_config.go
vendor/github.com/osbuild/images/pkg/distro/rhel/images.go
vendor/github.com/osbuild/images/pkg/distro/rhel/rhel9/azure.go
vendor/github.com/osbuild/images/pkg/manifest/os.go
vendor/github.com/osbuild/images/pkg/osbuild/nm_conf_stage.go
vendor/modules.txt

Includes
tag v0.134.0
Tagger: imagebuilder-bot <imagebuilder-bots+imagebuilder-bot@redhat.com>
Changes with 0.134.0
----------------
* Distro/el10/ec2/modprobe: blacklist 'i2c_piix4' (RHEL-71926) (osbuild/images#1395)
* Author: Tomáš Hozza, Reviewers: Achilleas Koutsou, Michael Vogt
* Update osbuild dependency commit ID to latest (osbuild/images#1391)
* Author: SchutzBot, Reviewers: Achilleas Koutsou, Tomáš Hozza
* distro/rhel9/azure: blacklist more modules on 9.6+ (RHEL-79065) (osbuild/images#1394)
* Author: Achilleas Koutsou, Reviewers: Michael Vogt, Simon de Vlieger
* distro/rhel9/azure: exclude microcode_ctl on 9.6+ (RHEL-79065) (osbuild/images#1405)
* Author: Achilleas Koutsou, Reviewers: Michael Vogt, Tomáš Hozza
* test: add configs for Azure that match official builds …

go.mod: update osbuild/images to v0.137.0

---

test/cases/aws.sh
test/cases/azure.sh

In CloudX, we'd like to start testing on RHEL10 and CentOS10. Therefore, we'd like to see what tests are applicable and failing for these runners if any. For the start, please see the fix for [CLOUDX-994](https://issues.redhat.com/browse/CLOUDX-994) as [PR364](https://github.com/osbuild/cloud-image-val/pull/364). Thus, this PR removes a workaround for [CLOUDX-994](https://issues.redhat.com/browse/CLOUDX-994) which skips RHEL10/CentOS10 runners.

remove workaround for CLOUDX-994

---

.github/workflows/tests.yml

GH actions: move from soon to be EOL F40 to F42

---

test/cases/cross-distro.sh

Test/cross-distro: fix processing of repo configs 
Previously, the code would remove everything after the first dot in the
repo config filename. So 'rhel-10.0.json' -> 'rhel-10'. This means that
there was just a bunch of 'rhel-X' repo config names to compare. This is
probably a leftover from the days before we introduced dot-notation for
distro names.
Modify the test to effectivelly strip only the filename extension (the
part after the last dot, including the dot).
-----------------------------------------------------------------------------
Test/cross-distro: take the images version used to compile composer 
After the move of the repo configs to `osbuild/images`, we changed the
way to determine the all available distro repo configs by taking the
last release of 'images'. This turns out …

Test/cross-distro: fix one issue and make the test more robust on "ZStream" branches

---

internal/cloudapi/v2/compose.go
internal/cloudapi/v2/imagerequest.go
internal/cloudapi/v2/imagerequest_test.go

This method is not particularly useful anymore.  Its purpose was to initialise the ImageOptions from an ImageRequest with the appropriate size and partitioning mode.  However, the partitioning mode was also being set later using request.GetPartitioningMode().  More importantly, setting the size on the ImageOptions caused issues with the interaction between filesystem and partitioning customizations as well as the image request size (see #4705).  The correct thing to do here is to map the ImageRequest.Size directly onto ImageOptions.Size, without taking into account ImageType or the Blueprint Customizations.  The rest are considered when generating the manifest in images, either when preparing the Manifest() call or when generating the partition table.  This makes it easier to trace and …

cloudapi: drop ImageRequest.GetImageOptions() method

---

test/cases/cross-distro.sh

The issue has been fixed in 9.6 0day ZStream in v132.1, so running the test against anything older will make the test fail. This is currently the case for RHEL-9-nightly pipeline.
Let's solve this annoyance.

Test/cross-distro: add version check for cross-building el8 on el9

---

go.mod
go.sum
vendor/github.com/osbuild/images/pkg/customizations/fsnode/dir.go
vendor/github.com/osbuild/images/pkg/customizations/fsnode/file.go
vendor/github.com/osbuild/images/pkg/customizations/fsnode/fsnode.go
vendor/github.com/osbuild/images/pkg/distro/defs/loader.go
vendor/github.com/osbuild/images/pkg/distro/rhel/images.go
vendor/github.com/osbuild/images/pkg/distro/rhel/rhel10/ami.go
vendor/github.com/osbuild/images/pkg/manifest/os.go
vendor/github.com/osbuild/images/pkg/olog/package.go
vendor/github.com/osbuild/images/pkg/olog/proxy.go
vendor/github.com/osbuild/images/pkg/olog/var.go
vendor/github.com/osbuild/images/pkg/osbuild/insights_client_config_stage.go
vendor/github.com/osbuild/images/pkg/reporegistry/repository.go
vendor/github.com/osbuild/images/pkg/rhsm/secrets.go
vendor/modules.txt

tag v0.144.0
Tagger: imagebuilder-bot <imagebuilder-bots+imagebuilder-bot@redhat.com>
Changes with 0.144.0
----------------
* customizations: drop `FsNode` interface as it is not used (#1490)
* Author: Michael Vogt, Reviewers: Brian C. Lane, Simon de Vlieger
* distro/rhel10/ami: unset authselect in ImageConfig (COMPOSER-2517) (#1469)
* Author: Achilleas Koutsou, Reviewers: Brian C. Lane, Michael Vogt
* manifest/os: immediately create directories (HMS-6043) (#1502)
* Author: Simon de Vlieger, Reviewers: Achilleas Koutsou, Michael Vogt
* osbuild: Add config to InsightsClientConfigStageOptions (#1503)
* Author: rverdile, Reviewers: Michael Vogt, Sanne Raymaekers
* refactor: replace logrus with stdlib log package (#1481)
* Author: Lukáš Zapletal, Reviewers: Michael Vogt, Simon de Vlieger
— …

go.mod: bump images to v0.144.0

---

internal/cloudapi/v2/server.go

It looks like this got lost in a refactor back in commit 6e4efabf246561673fc7334c0e4fcb6157c48d1b when it used to populate the Specs list in a loop.

cloudapi: Fix missing specs for koji ContainerResolve

---

templates/packer/ansible/roles/common/files/worker-executor.service
templates/packer/ansible/roles/common/files/worker-initialization.service

The `cloud-init.target` in 9.6 has `After=multi-user.target` in its unit config. The worker initialization service was set to run before `multi-user.target`, but after `cloud-final.service`. This created an impossible situation and systemd just disabling the initialization service.
So this changes:
`multi-user.target -> worker-*.service -> cloud-final.service -> multi-user.target`
to
`cloud-init.target -> worker-*.service -> cloud-final.service -> multi-user.target`.
Thus resolving the loop.
---
on the graph you can see the worker-initialization -> cloud-final -> multi target -> worker-initialization loop.
---
fixed loop

templates/packer: set wanted-by to cloud-init.target

---

.github/workflows/trigger-gitlab.yml

Add RHEL 10 nightly pipeline to PRs as well to avoid test breaking changes being introduced into main.

CI: Run RHEL 10 nightly pipeline on PRs

---

.gitlab-ci.yml

The problem with the test infrastructure should be resolved.
This reverts commit d0e805e8be5d37e9aee13aa81be0752ddd269577.

gitlab: enable OCI tests

---

.github/workflows/create-tag.yml

Modify the action to allow passing the version when run manually. This will be useful in the future once we branch-off a `rhel-x.y` branch to backport a fix and will be doing the first "dot" release from such branch.
Depends on https://github.com/osbuild/release-action/pull/29

GH Action/create-tag: allow passing the version when run manually

---

templates/packer/ansible/roles/common/tasks/packages.yml

There are now 2 colons present, one in the package name, one before the comment.

templates/packer: fix installing rpms from copr

---

.github/workflows/gobump.yml

Since gobump proven to be useful in `images`, I am proposing it for composer as well. We would drop other dependency bots and only use gobump. It bumps weekly.
This can only be tested after GHA exists and then it can be triggered against `upstream` branch manually to fine-tune it. It is the exact copy from `images` job: https://github.com/osbuild/images/blob/main/.github/workflows/gobump.yml

ci: introduce gobump gha

---

.packit.yaml
go.mod
go.sum
vendor/github.com/osbuild/images/pkg/image/anaconda_ostree_installer.go
vendor/modules.txt

Fixes the size of the ISO rootfs to fit the anaconda tree for the edge-installer.
See osbuild/images#1594

[RHEL 8.10] go.mod: bump osbuild/images to v0.40.1 [RHEL-95416]

---

internal/cloudapi/v2/errors.go
internal/cloudapi/v2/handler.go

The most common one is going to be trying to delete a compose before it is finished, and that is certainly not worthy of a 500 server error since it is a temporary state.

cloudapi: Use error 400 for cloudapi delete errors

---

cmd/osbuild-dnf-json-tests/main_test.go

The test was importing `distro/rhel/rhel9` directly instead of using the `distrofactory`. This is problematic as the go module for `rhel9` is going away. This commit fixes this by going via the `distrofactory` which will keep working.
Needed for  https://github.com/osbuild/images/pull/1645

osbuild-dnf-json-tests: use `distrofactory` to get `centos-9`

---

templates/packer/ansible/roles/common/files/worker-initialization.service

When the worker executor starts up, many error messages and warnings are shown in the system logs, `worker-initialization.service` should actually not run at all (if I understood correctly!). The service crashes and functionally that's fine, but it just messes up the log, raises questions and can be avoided by just not running it.
@croissanne is this valid? Would this remove the errors I saw?

templates/packer: avoid errors in worker-executor startup

---

internal/cloudapi/v2/imagerequest_test.go

Same as in 57813199cf6298a8f78222dad6e75163b63aade7.
The test was importing `distro/rhel/rhel9`, which is going away, instead of using the distrofactory.

cloudapi: use distrofactory to get rhel-9.3

---

.github/workflows/gobump.yml

The newly added gobump was using the default token but this one is not configured with all required permissions for this repo. This was causing tests not being executed on github.
---
Tested in CRC, seems to help: https://github.com/osbuild/image-builder-crc/pull/1656
Will fix gobump PR where tests are not being triggered: https://github.com/osbuild/osbuild-composer/pull/4793

workflows: use correct token for gobump

---

templates/packer/config.pkr.hcl

The 1.3.10 release has some issues and fails when used by Packer. See https://github.com/hashicorp/packer-plugin-amazon/issues/586 for more information.

Packer: skip packer-plugin-amazon version 1.3.10 due to missing checksum

---

test/cases/regression-old-worker-new-composer.sh

The test case is testing that old version of osbuild-composer worker
still works with the current version of the osbuild-composer under test.
This is to ensure that we do not break backward compatibility of the
worker API.
The test case first installs the version of osbuild-composer under test,
to determine its version. It uses GH to determine the upstream commit
SHA of an osbuild-composer version older by three releases than the
current version under test. The installed osbuild-composer* RPMs are
then removed.
In the next phase, the test case sets up RPM repo for the "old" composer
version from CI S3 cache and installs the osbuild-composer-worker
package from it. Lastly, the current version of osbuild-composer under
test is pulled as a container, which is built by a previous job within …

Test/regression-old-worker-new-composer: make the test case more robust

---

test/cases/rhel-upgrade.sh

Anaconda dracut hook was running out of space on 3G.

test/cases/rhel-upgrade: increase virt-install memory

---

internal/blueprint/blueprint.go
internal/blueprint/blueprint_convert_test.go

The blueprint convert function was missing the json tailoring case. This meant that if the json tailoring customization was provided in the blueprint, the customization would get ignored and the tailoring profile would not be applied to the image.

[9.6.0] internal/blueprint: add JSON tailoring to bp conversion (HMS-9303)

---

internal/cloud/awscloud/secure-instance.go
internal/cloud/awscloud/secure-instance_test.go
templates/packer/ansible/roles/common/files/worker-initialization-scripts/vector.sh
templates/packer/ansible/roles/common/files/worker-initialization-scripts/worker_executor.sh

This is a requirement to remove internet access from the executors entirely, yet keep logging.
Mind that this is just the first step, removing internet access would need to be done after the forwarding has been shown to work properly.

worker & executor: use vector to forward logs from executor to worker (HMS-9304)

---

templates/packer/ansible/roles/common/files/worker-initialization-scripts/vector.sh

Names have to be unique across sources and sinks.
Fixes the following error:
```
Failed to load ["/etc/vector/vector.yaml"]
x More than one component with name "executor" (source, sink).
x Input "executor" for sink "executor" doesn't match any components.
```

templates/packer: handle vector error

---

internal/common/echo_logrus.go

This is a backport of 1cde7e3. The original patch was not separated into individual commits unfortunately, therefore only the relevant line is being brought in. The original analysis:
---
It looks like both CloudAPI and WeldrAPI consume memory, process can go up to several gigabytes pretty quickly just by running a simple script.
while sleep 0.001; do
curl --unix-socket /run/weldr/api.socket -XGET http://localhost/api/
curl --unix-socket /run/cloudapi/api.socket -XGET http://localhost/api/
done
There is a logrus logger method called Write and WriteLevel which create a new logging entry, create a PIPE and spawn a goroutine that is reading from that PIPE. The caller is expected to close the PIPE writer which was not done.

common: fix unclosed logrus logging pipes

---

internal/cloudapi/v2/server.go

Certain code paths result in a panic from images. While this should be avoided in images, let's make the manifest generation job slightly more robust by recovering from these panics. Currently these panics crash the container and force a restart, this could impact other manifest jobs on the same pod.

cloudapi/v2: recover from panics in serializeManifest (HMS-9379)

---

Makefile
cmd/osbuild-worker/config.go
cmd/osbuild-worker/config_test.go
cmd/osbuild-worker/jobimpl-osbuild.go
cmd/osbuild-worker/main.go
internal/cloud/awscloud/secure-instance.go
internal/cloud/awscloud/secure-instance_test.go
internal/osbuildexecutor/runner-impl-aws-ec2.go
templates/packer/ansible/roles/common/files/worker-initialization-scripts/vector.sh
templates/packer/ansible/roles/common/files/worker-initialization-scripts/worker_config.sh
templates/packer/ansible/roles/common/files/worker-initialization-scripts/worker_executor.sh

This drops cloudwatch logging from the executor:
```
worker: remove cloudwatch group option from aws.ec2 executor
Logs should be forwarded from the executor to the worker.
This facilitates isolating the executor from the internet. Cloudwatch
doesn't have a well-defined IP range, so it's tricky to update the
executor's security group in such a way to allow only cloudwatch
traffic. By forwarding any log traffic from the executor via the worker,
this problem is eliminated.
Note that this just prepares for the needed security group changes which
would isolate the executor from the internet.
```
See  #4858.

worker/executor: drop cloudwatch logging from executor (HMS-9304)

---

cmd/osbuild-store-dump/main.go
internal/client/modules.go
internal/client/projects.go
internal/store/compose.go
internal/store/fixtures.go
internal/store/json.go
internal/store/json_test.go
internal/store/store.go
internal/store/store_test.go
internal/weldr/api.go
internal/weldr/api_test.go
internal/weldr/compose.go
internal/weldr/json.go
internal/weldrtypes/compose.go
internal/weldrtypes/imagebuild.go
internal/weldrtypes/package.go

Weldr API endpoints and the JSON store, used only by Weldr API, directly use `rpmmd` data structures representing packages for serialization. This means that any changes to the data structures in `osbuild/images` affect Weldr API endpoint responses and the store. This PR decouples Weldr API endpoints and store from `rpmmd` structures.
Note that the `rpmmd.RepoConfig` is still used for serialization. It may make sense to decouple it in the future as well, but I omitted it at this point because it does not block the refactoring I plan to do in `osbuild/images` as part of the SBOM rearchitecture.
/jira-epic HMS-8910
JIRA: [HMS-9376](https://issues.redhat.com/browse/HMS-9376)

Weldr API endpoints & store: don't use `rpmmd` package structs for serialization (HMS-9376)

---

internal/common/echo_logrus.go

This is a backport of 1cde7e3. The original patch was not separated into individual commits unfortunately, there fore only the relevant line is being brought in. The original analysis:
It looks like both CloudAPI and WeldrAPI consume memory, process can go up to several gigabytes pretty quickly just by running a simple script.
while sleep 0.001; do
curl --unix-socket /run/weldr/api.socket -XGET http://localhost/api/
curl --unix-socket /run/cloudapi/api.socket -XGET http://localhost/api/
done
There is a logrus logger method called Write and WriteLevel which create a new logging entry, create a PIPE and spawn a goroutine that is reading from that PIPE. The caller is expected to close the PIPE writer which was not done.
(cherry picked from commit 0f97a1c1668827086dfa335c9fb427cbb28782b2)

common: fix unclosed logrus logging pipes (RHEL-10.0)

---

go.mod
go.sum
vendor/github.com/osbuild/images/data/distrodefs/distros.yaml
vendor/github.com/osbuild/images/pkg/distro/generic/options.go
vendor/modules.txt

tag v0.198.0
Tagger: imagebuilder-bot <imagebuilder-bots+imagebuilder-bot@redhat.com>
Changes with 0.198.0
----------------
- defs/centos: cross-arch for s390x, ppc64le (osbuild/images#1905)
- Author: Simon de Vlieger, Reviewers: Achilleas Koutsou, Michael Vogt
- distro: turn all errors from distro.ValidateConfig() into warnings (osbuild/images#1904)
- Author: Achilleas Koutsou, Reviewers: Michael Vogt, Sanne Raymaekers, Simon de Vlieger
- test/configs: add jq to all test configs that require it (osbuild/images#1899)
- Author: Achilleas Koutsou, Reviewers: Lukáš Zapletal, Simon de Vlieger
— Somewhere on the Internet, 2025-09-29
---

go.mod: update osbuild/images to v0.198.0 (HMS-9444)

---

internal/cloud/awscloud/client-interfaces.go
internal/cloud/awscloud/mocks_test.go
internal/cloud/awscloud/secure-instance.go
internal/cloud/awscloud/secure-instance_test.go
test/cases/worker-executor.sh

cloud/awscloud: revoke internet access from executor
After the vector forwarding (#4858), it should be safe to remove
internet access from executors again.
By default security groups are created with internet access (egress to
0.0.0.0/0) being allowed. First remove all egress rules in the
executor's security group, then add a rule which allows egress to the
worker host

executor: remove internet access entirely (HMS-9304)

---

internal/cloudapi/v2/export_test.go
internal/cloudapi/v2/handler.go
internal/cloudapi/v2/server.go
internal/cloudapi/v2/v2_koji_test.go
internal/cloudapi/v2/v2_multi_tenancy_test.go
internal/cloudapi/v2/v2_test.go
internal/test/apicall.go

While porting https://github.com/osbuild/images/pull/1907 to osbuild-composer, I ran into the problem that the CloudAPI endpoint for compose manifests was not checking manifest generation job results and would return a 'nil' value instead of an error if the manifest generation failed.
Moreover, the mock data used by unit tests for depsolved packages was not complete and was lacking basic properties, such as the remote location URL, which is needed to generate an osbuild manifest.
This PR addresses the issues mentioned above, it also adds a unit test for compose manifests Cloud API endpoint and improves unit tests where failure debugging was previously unnecessarily complicated.
/jira-epic HMS-8910
JIRA: [HMS-9501](https://issues.redhat.com/browse/HMS-9501)

CloudAPI: fix `/compose/{id}/manifests` endpoint behavior on manifest generation errors (HMS-9501)
