osbuild/osbuild-composer

- internal/weldr/api.go
If a package had version "*" its name-version would be "name-*". This would match all packages containing "name" in their name. Instead the name-version is "name-*-*" so it matches any version of the package.
> Fix package name-version for wildcard version

- .travis.yml
- internal/weldr/api.go
- internal/weldr/api_test.go
- internal/weldr/store.go
The list of changes between the committed blueprint and its workspace are returned when a user requests the diff. Each change includes the new(added) or the old(removed) package.
> Add blueprint workspace diff

- internal/job/job.go
- internal/job/store.go
- internal/jobqueue/api.go
- internal/jobqueue/api_test.go
- internal/pipeline/pipeline.go
- internal/target/target.go
- internal/weldr/api.go
- internal/weldr/api_test.go
- internal/weldr/store.go
For now we will hardcode the org.osbuild.local target, so we might
as well fix this up front.
We do not yet support any target types, but for testing purposes we
claim to support 'tar', and we pass a noop tar pipeline to the worker.
This makes introspecting the job-queu api using curl a bit more
pleasant.
> job-queue: pass a well-formed job object to the worker

- tools/image-info
Rough draft of image-info, a tool that extracts high-level information
about an os image. It prints this information in JSON form on stdout.
Run it like this:
$ tools/image-info <image>
It supports all images that qemu-ndb supports.
> tools: add image-info

- tools/image-info
Use qemu-img to query the image format and include that in the report.
> image-info: include the image format

- tools/image-info
This shows the changes an image has relative to what its rpm database
thinks is installed. Output is:
"rpm-verify": {
"missing": [ <missing files> ],
"changed": { <map from filename to rpm attribute octet > }
}
Alas, this makes running image-info slower.
> image-info: include output from `rpm --verify`

- internal/rpmmd/repository.go
- internal/weldr/api.go
- internal/weldr/api_test.go
- internal/weldr/store.go
Add parameters to the api responses that while not displayed by cockpit-composer are used in props validation or blueprint updates. These updates bring osbuild-composer's api closer to lorax-composer's.
> Update api and store for parity with lorax

- tools/image-info
The order doesn't matter, but should be the same between different runs
of image-info.
> image-info: sort bootmenu entries

- distribution/osbuild-composer.service
This directory is currently only used for unix-domain sockets but they are created by systemd with the socket unit and therefore this line is redundant and maybe even causes problems.
We want the sockets to live even when the service is down (either because of error or intentional suspension) and it seems that setting the RuntimeDirectory to the directories that contain the sockets makes systemd remove both directories and unlink the sockets when the service fails and that is exactly what we don't want.
> Remove RuntimeDirectory

- cmd/osbuild-composer/main.go
- cmd/osbuild-worker/job.go
- go.mod
- internal/blueprint/ami_output.go
- internal/blueprint/blueprint.go
- internal/blueprint/disk_output.go
- internal/blueprint/ext4_output.go
- internal/blueprint/liveiso_output.go
- internal/blueprint/openstack_output.go
- internal/blueprint/qcow2_output.go
- internal/blueprint/tar_output.go
- internal/blueprint/vhd_output.go
- internal/blueprint/vmdk_output.go
- internal/jobqueue/api.go
- internal/jobqueue/api_test.go
- internal/store/store.go
- internal/weldr/api.go
- internal/weldr/api_test.go
**Make sure to pull this PR and test if it's not breaking your workflow!**
This should be the best practice according to other popular go projects:
- https://github.com/prometheus/prometheus
- https://github.com/syncthing/syncthing
- https://github.com/drone/drone
- https://github.com/hashicorp/terraform
Also, this change fixes go get command (it currently fails due to bad package
name).
> osbuild-composer: Rename module to github.com/osbuild/osbuild-composer

- cmd/osbuild-pipeline/main.go
- internal/blueprint/f30_helpers.go
We've merged some stuff with old module name used in imports. This
commit fixes it.
> osbuild-composer: Fix imports broken by new module name

- internal/weldr/api_test.go
At the end of each set of tests the blueprint created is deleted. This tests the delete route as well as removing blueprints created while testing external apis such as lorax.
> tests: delete blueprints after tests

- dnf-json
When osbuild-composer is run as systemd service, we don't want to write
anything into working directory. Currently, we write dnf cache into it.
Instead, use absolute path to /var/cache as dnf cache.
> dnf-json: Use /var/cache as dnf cachedir

- internal/blueprint/qcow2_output_test.go
Use the autogenerated test framework from VSCode (with minor fixes to
make them compile).
As we do not yet support customizations in blueprint, all the tests are
trivial.
I was not entirely sure about the best way to encode the wanted pipeline
output. I currently represent it as a JSON string and unmarshal it into
the object to compare with.
> blueprint/output/qcow2: add unit tests

- .gitignore
- Makefile
- internal/blueprint/f30_helpers.go
- internal/blueprint/pipelines/ami_empty_blueprint.json
- internal/blueprint/pipelines/disk_empty_blueprint.json
- internal/blueprint/pipelines/openstack_empty_blueprint.json
- internal/blueprint/pipelines/qcow2_empty_blueprint.json
- internal/blueprint/pipelines/vhd_empty_blueprint.json
- internal/blueprint/pipelines/vmdk_empty_blueprint.json
- internal/blueprint/qcow2_output.go
- internal/pipeline/dnf_stage.go
Adjust the qcow2 output to the official Fedora image and add a test for it. It uses the public `blueprint.ToPipeline` API.
> QCOW2 image generation and output test

- internal/weldr/api.go
- internal/weldr/api_test.go
API error responses include the error message as well as an id and optional status code. The error messages are equivalent to those provided by lorax. There are a couple of messages that are not quite equivalent:
- Any GET request that takes url params does not throw the proper error when not provided with params or a closing / i.e. `/source/info`
- A GET request for blueprints or sources currently returns an error with a status code of 400 but it should return an empty list and the error with a status code of 200
> api: update api error responses to equal lorax's

- internal/store/store.go
- internal/weldr/api.go
As part of the effort to reach parity with lorax-composer I added some missing compose status info. Each compose now includes the blueprint version it is based off of, its compose type, and the finished compose's file size (0 if the compose isn't finished).
> Compose status updates

- cmd/osbuild-worker/main.go
- internal/jobqueue/api.go
- internal/jobqueue/job.go
The main purpose of this is to share the structs between the server
and the client, and let the compiler ensure that our marshaling and
unmarshaling matches.
In the future we also want to make it easier to write unittests for
this code.
> worker: move Job type to the jobqueue package

- cmd/osbuild-composer/main.go
- dnf-json
- internal/rpmmd/repository.go
- internal/weldr/api.go
We used to hard-code fedora 30 in there. Change the way dnf-json receives its arguments (JSON on stdin) and pass repository information through that.
This makes it possible to fetch information from multiple repositories. I haven't tested that yet, though.
> dnf-json: get repository information from osbuild-composer

- dnf-json
When argument passing was switched from command line to stdin in cae1fdd,
depsolve command was broken. This commit fixes it.
> dnf-json: fix depsolve command

- internal/weldr/api.go
The delete source handler now removes the leading "/" from the parameters passed to it. Not removing the "/" caused sources to not be deleted from the store since they could not be found when their name contained a "/" as the first character.
> api: fix delete source route

- internal/rpmmd/repository.go
When dnf-json dumps the packages from the repos passed to it, it does not sort the packages. In order to properly list and search the packages, the package list is now sorted before being returned by the FetchPackageList function.
> Sort fetched package list

- cmd/osbuild-composer/main.go
- dnf-json
- internal/mocks/rpmmd/fixtures.go
- internal/mocks/rpmmd/rpmmd_mock.go
- internal/rpmmd/repository.go
- internal/weldr/api.go
- internal/weldr/api_test.go
This PR introduces support for mocking dnf-json, adds error reporting to dnf-json and implements one missing route for projects.
I've renamed rpmmd to dnfadapter. I don't like the name rpmmd - it isn't very descriptive and it was hard to work with it when I introduced the mocking part. I'm not sure if dnfadapter is the right name. Maybe dnfwrapper?
> Projects API improvements & dnf mocking

- internal/weldr/api_test.go
After this change one can immediately see all the differences when developing
or running the tests.
> api/tests: print all differences between expected and actual values

- internal/weldr/api_test.go
I changed the API of weldr.New in 495f5b55 and Jacob added a new call of
that function in 9970150e, which created conflicting state.
> tests: fix failing tests due to a bad merge

- cmd/osbuild-composer/main.go
- internal/rpmmd/repository.go
- internal/weldr/api.go
- internal/weldr/api_test.go
When users add their own sources they are now able to fetch packages from these sources. The package list is generated from the base repo and the user-defined repos. This allows users to add packages not found in the base repo to their blueprints.
> Fetch packages from user sources

- internal/weldr/api.go
- internal/weldr/api_test.go
The blueprint freeze route `/blueprints/freeze/<names>` returns the blueprint info but each
package will be the package selected by depsolving. So, instead of the version being the version number with optional wildcards as /blueprints/info would provide, the version is of the form
`Version-Release.Arch`.
> Add blueprints freeze route

- internal/weldr/api_test.go
The blueprints freeze test now creates the blueprint with the package dep-package1 which is mocked and will properly depsolve when the blueprint is frozen. This test can no longer run externally against
lorax-composer.
> api/tests: fix blueprints freeze test

- LICENSE
This reverts commit ce6854d781cab65b0eedfeb564f8fbf09db8403c as I
understood the license text in a wrong way.
> Revert "Fill in the license template"

- internal/jobqueue/job.go
- internal/store/store.go
- internal/target/aws_target.go
- internal/target/azure_target.go
- internal/target/local_target.go
- internal/target/target.go
These are not currently implemented in the backend, but shows how
the API will look like.
> targets: add dummy azure and aws targets

- cmd/osbuild-upload-aws/main.go
- go.mod
- go.sum
- golang-github-osbuild-composer.spec
- internal/awsupload/awsupload.go
- internal/distro/fedora30/os.go
- internal/jobqueue/job.go
This commandline tools uploads a file to S3, as a proof of concept.
All options are mandatory. Credentials are only read from the
commandline and not from the environment or configuration files.
The tool will be refactored into a package that will be used both
by our tests and by the worker.
The next step is to add support for importing from S3 to EC2,
currently the images we produce cannot be imported as-is, so this
requires more research.
To try this out: create an S3 bucket, get your credentials and
call the tool, passing any value as `key`. Note that if the key
already exists, it will be overwritten.
> upload/aws: add a sample AWS upload client

- internal/jobqueue/api_test.go
- internal/mocks/rpmmd/fixtures.go
- internal/mocks/rpmmd/rpmmd_mock.go
- internal/test/helpers.go
- internal/weldr/api_test.go
This PR is somewhat connected with #101. While developing upload API I needed two things:
- support for DropFields in jobqueue tests. Therefore I extract common helpers to a new package.
- support for better way to describe initial store state. Therefore I added store fixtures.
> Tests improvement

- golang-github-osbuild-composer.spec
this is a small helper to enable easy switch between backends
in the existing test suite where we reference everything by name.
The current working variant is:
yum install $BACKEND
systemctl enable $BACKEND.socket
where BACKEND is either lorax-composer or osbuild-composer!
> Provides: osbuild-composer in .spec

- internal/weldr/api.go
- internal/weldr/api_test.go
Cockpit-composer really doesn't like that
> api: fix compose routes returning null instead of empty array

- tools/image-info
Quick hack to make `image-info` work with UEFI images.
If we detect a ESP (via its type UUID) remember it and mount it at any filesystem that has a /boot/efi (there should in theory be only one). This is needed so grubenv can be read, which is likely
a link from `/boot/grub2/grubenv` to `../efi/EFI/$vendor/grubenv`.
Additionally this will make rpm verify not report that all the efi binaries are missing, e.g.:
```
"missing": [
"/boot/efi/EFI",
"/boot/efi/EFI/BOOT",
"/boot/efi/EFI/BOOT/BOOTIA32.EFI",
"/boot/efi/EFI/BOOT/BOOTX64.EFI",
"/boot/efi/EFI/BOOT/fbia32.efi",
"/boot/efi/EFI/BOOT/fbx64.efi",
"/boot/efi/EFI/fedora",
"/boot/efi/EFI/fedora",
...
```
> image-info: mount ESP at /boot/efi if found

- .travis.yml
- Makefile
- cmd/osbuild-composer/main.go
- cmd/osbuild-pipeline/main.go
- cmd/osbuild-worker/main.go
- distribution/osbuild-composer.service
- distribution/osbuild-composer.socket
- distribution/osbuild-worker@.service
- golang-github-osbuild-composer.spec
- internal/distro/distro.go
- internal/distro/distro_test.go
- internal/distro/fedora30/distro.go
- internal/distro/rhel82/distro.go
- internal/distro/test/distro.go
- internal/jobqueue/api_test.go
- internal/jobqueue/job.go
- internal/store/store.go
- internal/weldr/api.go
- internal/weldr/api_test.go
The pipeline generation now takes the architecture as an argument.
Currently only x86_64 is supported. The architecture is detected
at start-up, and passed down to each pipeline translation.
For osbuild-pipeline we now requrie the architecture to be passed
in.
> composer: add provisional multi-arch support

- dnf-json
- internal/rpmmd/repository.go
- internal/store/store.go
This is the opposite of dnf.conf's `sslverify`, because go's default for
booleans is always false. This is error prone: we'd like to default to
true.
> rpmmd: add IgnoreSSL key to RepoConfig

- internal/jobqueue/job.go
d55abdfd75450dcfc27913e71f16dee2ea3346d7 disabled caching the osbuild
store by moving it to /var/tmp. Fix the directory we're copying the
outputs from as well.
> jobqueue: copy outputs from the right location

- distribution/osbuild-worker@.service
Image generation is very much a batch job, latency is not important
and because it is so CPU and IO intensive, it really affects the
overall responsiveness of the system if left on the default settings.
Set scheduling to idle/batched for the worker. The composer service
is still left in the normal scheduling classes as its latency is
important for the UI.
> service: adjust the IO and CPU scheduling classes

- internal/distro/rhel82/distro.go
- test/cases/rhel82_ami.json
- test/cases/rhel82_ext4_filesystem.json
- test/cases/rhel82_openstack.json
- test/cases/rhel82_partitioned_disk.json
- test/cases/rhel82_qcow2.json
- test/cases/rhel82_tar.json
- test/cases/rhel82_vhd.json
- test/cases/rhel82_vmdk.json
- test/run
These tests are dependent on access to the RHEL repositories, so can only be triggered manually, rather than as part of CI.
> tests: add tests and minor cleanups for RHEL-8.2

- golang-github-osbuild-composer.spec
Commit 04012641 broke the rpm build by introducing bad package name
to be build. This commit fixes it.
> spec: fix build

- internal/blueprint/blueprint.go
- test/cases/groups_blueprint.json
- test/cases/rhel82_groups.json
When group names are passed on to dnf, they must be prefixed with an
ampersand, or they are treated as a regular package, potentially
causing the build to fail.
Add a testcase to verify this behavior.
This resolves rhbz#1784035.
> blueprints: fix group handling

- internal/store/store.go
- internal/weldr/api_test.go
When restarting composer, we were not handling the compose states
correctly.
This resolves that as follows:
* any running composes are marked as failed,
* any waiting composes are put back in the pending jobs queue
As a consequence of needing the ability to reinitialize the job
queue, we must include the depsolved pipeline in the compose object.
This is the correct thing to do, as the semantics we currently
adhere to is that pipelines are depsolved when the compose is
started (and restarting composer should not affect this by for
instance re-depsolve the pipeline).
Resolves rhbz#1784062.
> store: fix compose state handling on restart

- cmd/osbuild-pipeline/main.go
- dnf-json
- internal/mocks/rpmmd/rpmmd_mock.go
- internal/rpmmd/repository.go
- internal/weldr/api.go
dnf-json relies on dnf's ability to cache repository metadata. This is
important, because the API calls it quite often to serve requests for
package lists and depsolves.
However, osbuild's dnf stage always fetches new metadata, because it
doesn't have access to the host's cache. Since metadata is valid for
some time, even after a repository changed, the checksum we put in
the pipeline might be old.
Force a new metadata download when producing the pipeline. This is still
not perfect, but greatly reduces the probability of putting stale
metadata into the pipeline.
> weldr: ensure a fresh dnf cache when making a new compose

- cmd/osbuild-composer/main.go
Osbuild-composer expects two or three listeners and fails if there is an unexpected number of listening sockets. Checking if there are not two or if there are not three listeners always returns true even if there are the desired number of listeners. Therefore, osbuild-composer always crashes. The check now only crashes if there are a number of listeners other than 2 or 3.
> osbuild-composer: fix number of listeners check

- cmd/osbuild-pipeline/main.go
- internal/distro/distro.go
- internal/distro/distro_test.go
- internal/distro/fedora30/distro.go
- internal/distro/rhel82/distro.go
- internal/distro/test/distro.go
- internal/jobqueue/api_test.go
- internal/pipeline/tar_assembler.go
- internal/rcm/api.go
- internal/store/store.go
- internal/weldr/api.go
- test/cases/ami_empty_blueprint.json
- test/cases/disk_empty_blueprint.json
- test/cases/disk_local_boot.json
- test/cases/ext4_empty_blueprint.json
- test/cases/ext4_local_boot.json
- test/cases/openstack_empty_blueprint.json
- test/cases/openstack_local_boot.json
- test/cases/qcow2_empty_blueprint.json
- test/cases/qcow2_local_boot.json
- test/cases/rhel82_ext4_filesystem.json
- test/cases/rhel82_openstack.json
- test/cases/rhel82_partitioned_disk.json
- test/cases/rhel82_qcow2.json
- test/cases/rhel82_vhd.json
- test/cases/rhel82_vmdk.json
- test/cases/vhd_empty_blueprint.json
- test/cases/vhd_local_boot.json
- test/cases/vmdk_empty_blueprint.json
- test/cases/vmdk_local_boot.json
When starting a compose users can pass in an image size. The resulting image will then be of this size. If no image size is passed a default size will be used.
> Allow for user defined image size

- cmd/osbuild-pipeline/main.go
- internal/common/types.go
In the current state, osbuild-pipeline exits with random golang error, such as goroutine failed, which is not at all helpful. This PR introduces CLI arguments validation and helful error messages that use the newly introduced types so that we don't waste time guessing what was the right way to invoke this tool.
note about image types:
Image type validation is not in place because we want to rethink the names and the newly created types are different from what we currently use in `distro` package
> osbuild-pipeline: improve CLI interface

- internal/jobqueue/job.go
Otherwise if there is an error creating result.json or if the Run
command failed it will remain owned by root.root and cannot be deleted
via the API.
Closes #204
> Change ownership of the output directory immediately

- internal/store/store.go
- internal/store/store_test.go
Generating a SHA-1 based on time is not safe. A collision can easily be
generated, and if parallel operations are used they will eventually
collide. This reads random bytes and uses them for the SHA-1 hash. It
will return an error if the rand.Read() fails.
> Switch blueprint commit to use a random SHA-1

- cmd/osbuild-worker/main.go
- internal/common/compose_result.go
- internal/jobqueue/api.go
- internal/jobqueue/job.go
- internal/store/store.go
- internal/weldr/api.go
This is needed in order to implement remote workers.
> Transfer logs from worker to composer using API instead of filesystem

- internal/weldr/api.go
- internal/weldr/api_test.go
composer-cli pushes blueprints to the workspace using TOML not JSON.
This also adds a test.
> api: Add TOML support for workspace POST

- internal/distro/distro.go
- internal/distro/distro_test.go
- internal/distro/fedora30/distro.go
- internal/distro/rhel82/distro.go
- internal/distro/test/distro.go
- internal/store/store.go
- internal/weldr/api.go
- internal/weldr/compose.go
Currently, osbuild-composer returns the file size of an image in its compose status/info response. We should instead return the image size that is defined either by the user when creating the compose or is the default value if the user does not define a size. The user defined size is passed to the store when the compose is created but the default image size is only stored in the pipeline's assembler options. So, in order to access the image size even if a user does not define one, I added a function to the assembler options' interface which will return the size specified for the assembler.
> Store virtual image size

- internal/jobqueue/api.go
Prior this commit these errors would just disappear.
> api/jobqueue: return 500 error when updating job unexpectedly failed

- cmd/osbuild-worker/main.go
- internal/compose/compose.go
- internal/jobqueue/api.go
- internal/jobqueue/api_test.go
- internal/jobqueue/job.go
- internal/jobqueue/local_target_uploader.go
- internal/mocks/rpmmd/fixtures.go
- internal/store/store.go
- internal/target/local_target.go
- internal/weldr/api.go
- internal/weldr/compose.go
This PR grew bigger than I originally though but honestly, **I love it**. Things changed:
1) Images from worker to composer are now transported using jobqueue API. This enables us to implement remote workers (should be just fairly simple rebase of my existing PR).
2) `LocalTarget.Location` field is no more. The store is now responsible for managing all the build artifacts and keeping track of their locations. The LocalTarget's now only denoting if there's an image for an image build.
3) `Compose.Image` is no more. We can calculate its values when they are needed, no need to store them redundantly.
4) osbuild results and images are now stored per image build instead of per compose. This was TODO from #221 and it made sense to me to implement it in this PR.
> Upload images from worker to compose using jobqueue API

- internal/jobqueue/job.go
In jobqueue/job internal/compose was imported. This imported is unused and osbuild-composer fails to build. The import is now removed.
> jobqueue: remove unused compose import

- internal/distro/distro.go
- internal/distro/fedora31/distro.go
- internal/distro/fedora31/distro_test.go
- repositories/fedora-31.json
Images can be built for fedora 31. The pipeline generation and distro tests are based off of the fedora 30 ones. Repository information has also been added for the fedora 31 repos.
> distro: add fedora 31 support

- cmd/osbuild-pipeline/main.go
When creating a pipeline with the default image size, the size should no longer be set to 0. Instead, the size is fetched using the distro function GetSizeForOutputType which can return the default image size
for a given image type. This size can then be passed into the pipeline.
> Fix osbuild-pipeline creating pipelines with an image size of 0

- .gitignore
- Makefile
- cmd/osbuild-composer/main.go
- cmd/osbuild-dnf-json-tests/main.go
- golang-github-osbuild-composer.spec
- internal/common/types.go
- internal/common/types_test.go
- internal/mocks/rpmmd/rpmmd_mock.go
- internal/rcm/api.go
- internal/rcm/api_test.go
- internal/rpmmd/repository.go
- internal/store/store.go
- internal/weldr/api.go
> RCM API: use the new PushComposeRequest method

- Makefile
- cmd/osbuild-composer/main.go
- cmd/osbuild-worker/main.go
- distribution/osbuild-remote-worker.socket
- distribution/osbuild-remote-worker@.service
- distribution/osbuild-worker@.service
- golang-github-osbuild-composer.spec
Several decision I made which we might discuss:
- configuration is passed in composer and worker as command line arguments. This is the easiest options but there might be some security concerns.
- socket activation is used even with tcp (systemd supports it). I'm not sure if that's what we want.
TODO:
- tests - we need some kind of integration tests for worker/composer.
- disabling local target in the case of a remote worker
> Add tcp and tls support to worker API

- distribution/osbuild-composer.service
- distribution/osbuild-worker@.service
- dnf-json
- internal/rpmmd/repository.go
dnf does not behave well when we don't specify a cache directory. Use /var/cache/osbuild-composer/rpmmd, as we did at one point in the past. Let systemd create the cache directory and set up the right user/group permissions for us.
This should avoid lots of stale cache directories around as reported by @msehnout.
I cherry-picked a patch from #198, to (hopefully) avoid a merge conflict.
> dnf-json: always specify a cache directory

- golang-github-osbuild-composer.spec
There needs to be a space, otherwise it does not work
```
[root@6440f5c897a2 osbuild-composer]# rpm -q osbuild
osbuild-7-1.fc31.noarch
[root@6440f5c897a2 osbuild-composer]# dnf install output/x86_64/*.rpm
Last metadata expiration check: 2:36:56 ago on Thu Feb 20 11:46:09 2020.
Error:
Problem 1: conflicting requests
- nothing provides osbuild>=7 needed by golang-github-osbuild-composer-5-1.fc31.x86_64
Problem 2: package golang-github-osbuild-composer-tests-5-1.fc31.x86_64 requires osbuild-composer, but none of the providers can be installed
- conflicting requests
- nothing provides osbuild>=7 needed by golang-github-osbuild-composer-5-1.fc31.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```
> spec: fix osbuild version dependency

- internal/rpmmd/repository.go
The LoadRepositories function interates over a list of paths and expects
to find a distro configuration in one of them. The case when no path
with valid configuration is found was not handled. This patch introduces
the check.
> rpmmd: fix LoadRepositories in case no valid path is provided

- cmd/osbuild-tests/main.go
comparing to lorax-composer test suite only ext4-filesystem and partitioned-disk are built without asserting anything other than the build succeeds. For the rest of the images we usually try to
boot them and verify the resulting VM works somehow.
@teg I've tried this locally and it works for me although it makes the entire test suite take longer. Please review.
> tests: Build all available image types during integration test

- internal/rpmmd/repository.go
This can happen when CacheDirectory= is missing from the service file.
That's unlikely to happen, but it's hard to figure out what caused the
failure when it does. Be explicit and panic.
> rpmmd: panic when CACHE_DIRECTORY is not set

- internal/weldr/api.go
If no packages are included in a blueprint, the slice remains `nil`,
which translates to `null` in json. Always initialize the slice by
pointing it to an empty array.
> weldr: ensure passing valid `package-specs` to dnf-json

- cmd/osbuild-composer/main.go
- cmd/osbuild-image-tests/osbuild-image-tests.go
- golang-github-osbuild-composer.spec
- internal/common/helpers.go
- internal/distro/distro.go
Image info tests are running, therefore I think it's time for reviewing. Please note that this is meant to be a part of the integration test suite (therefore run on a pristine Fedora VM, not on Travis CI).
Changes from the Python version:
1) osbuild is called from `PATH`, not from the submodule.
2) `--arches` argument is gone. Instead only the tests for the current arch are run.
Go's `flag` package doesn't support arguments with multiple values, therefore I just dropped it for now. We can revisit this later.
3) `--distros` argument is gone. Instead only the tests for the host distro are run.
The same reason as the previous point, we can also revisit this later.
4) `--cases` argument is now a positional argument. (`osbuild-image-tests CASES... `), when no `CASES` are given, all the tests …
> First part of the porting the current ./test/run test suite to Go

- internal/common/types.go
- internal/distro/distro.go
- internal/distro/rhel81/distro.go
- internal/distro/rhel81/distro_test.go
- repositories/rhel-8.1.json
Images can be built for rhel 8.1. The pipeline generation and distro tests are based off of the rhel 8.2 ones. Repository information as been added for rhel 8.1. The repo urls are internal ones and will only work if the user is on the Red Hat VPN. This PR is dependent on https://github.com/osbuild/osbuild/pull/245
> distro: add rhel-8.1 support

- .github/workflows/lint.yml
- .golangci.yml
- cmd/osbuild-composer/main.go
- cmd/osbuild-tests/main.go
- cmd/osbuild-worker/main.go
- internal/blueprint/blueprint_test.go
- internal/common/compose_result.go
- internal/common/helpers.go
- internal/common/types.go
- internal/jobqueue/api.go
- internal/jobqueue/job.go
- internal/osbuild/source_test.go
- internal/osbuild/stage_test.go
- internal/store/store.go
- internal/upload/awsupload/awsupload_test.go
- internal/upload/azure/azure.go
- internal/upload/azure/azure_test.go
- internal/weldr/api.go
- internal/weldr/api_test.go
I would like to introduce linting of our Go code in the project. I think this could help us to detect some errors before the merge button is pressed. I chose golangci-lint as our linter as it's a popular project used by many big projects (podman, openshift), and it aggregates multiple Go linters so more errors can be caught. To demonstrate its functionality, I run it on the current master. Then, I chose one example for each error type. The results are here:
```
errcheck in cmd/osbuild-tests/main.go:
Error return value of `cmd.Start` is not checked:
cmd.Start()
```
There are 45 cases of unchecked errors in our code. It's surely annoying to do the check every time (in some cases god bless exceptions) but without any checking of errors we will never know about them. I think we should always …
> Add a linter to this project

- golang-github-osbuild-composer.spec
Prior this commit installing the worker sub-packages shows the following
warning:
Failed to preset unit: Unit file osbuild-worker@.service does not exist.
Moving the unit file to the sub-package fixes it.
> spec: move worker-related service units to worker sub-package

- cmd/osbuild-composer/main.go
I broke it in d7cbc22d, there shouldn't be a goroutine.
> fix composer immediately exiting

- cmd/osbuild-composer/main.go
- cmd/osbuild-dnf-json-tests/main.go
- cmd/osbuild-pipeline/main.go
- internal/rpmmd/repository.go
rpmmd looked at the CACHE_DIRECTORY environment variable to set a path
for the dnf repository cache.  Aside from being a smelly thing to do
from a library, this breaks osbuild-pipeline and osbuild-dnf-json-tests,
which don't run as systemd services and thus don't have CACHE_DIRECTORY
set.
Explicitly pass the cache directory to rpmmd. Keep using a path based on
CACHE_DIRECTORY for osbuild-composer. Use the user's `.cache` directory
for osbuild-pipeline and a temporary directory for the tests.
> rpmmd: pass in cache directory explicitly

- distribution/osbuild-composer.service
systemd >= 240 sets this variable to `/var/cache/` + the value of
CacheDirectory. osbuild-composer must run on earlier versions though
(specifically RHEL 8.2).
> distribution: set CACHE_DIRECTORY in the .service file

- cmd/osbuild-pipeline/main.go
- internal/common/types.go
- internal/distro/distro.go
- internal/distro/distro_test.go
We were verifying two things: if the passed distroArg exists in the
distribution mapping in common/types.go and if the it is an actually
registered distro. Since you cannot have distros registered that don't
correspond to a type, the first test is unnecessary.
Merge the two tests by moving the (much better) error message down into
the second test. This makes DistributionExists redundant, because
Registry.GetDistro() checks this implicitly.
Also, move ListDistributions() to the Registry object, because we want
to show distributions that are actually registered.
Add a test which checks that Registry.List() works and that all included
distributions register correctly.
> osbuild-pipeline: validate distro when fetching it

- cmd/osbuild-pipeline/main.go
- internal/compose/compose.go
- internal/distro/distro.go
- internal/distro/fedora30/distro.go
- internal/distro/fedora31/distro.go
- internal/distro/fedora32/distro.go
- internal/distro/fedoratest/distro.go
- internal/distro/rhel81/distro.go
- internal/distro/rhel82/distro.go
- internal/distro/test/distro.go
- internal/jobqueue/api.go
- internal/jobqueue/api_test.go
- internal/jobqueue/job.go
- internal/osbuild/osbuild.go
- internal/store/store.go
- internal/weldr/api_test.go
This allows sources to be passed together with pipelines directly to osbuild on stdin, rather than having to pass sources as a separate file.
For now empty sources are passed, but a follow-up PR will switch from dnf- to rpm-based pipelines, which requires sources to be passed separately.
> osbuild: introduce `manifest` objects

- internal/blueprint/blueprint.go
- internal/blueprint/blueprint_test.go
- internal/weldr/api_test.go
If the user creates a new blueprint with no version specified, the blueprint struct uses "0.0.0" as the default version. Blueprint tests for a blueprint with an empty version now expect no error.
> blueprint: add default version

- .gitignore
- Makefile
Prior to this patch, `make rpm` would produce rpms that have the latest
tag as their versions. This was confusing, because one could never know
which contents are in a locally built rpm.
Change this so that the is version always based on the commit hash of
HEAD. This is easy: the golang macros read a `%commit` macro when it
exists and do this for us.
To simplify more, only define `%_topdir` to ./rpmbuild and use
rpmbuild's known directory structure (SPEC, SOURCES, RPMS, ...)
otherwise, to make it easier to find build results.
Build the specfile, tarball, source rpms, and rpms with `make rpm`,
without separate sub-targets. We can reintroduce them if they're needed
somewhere.
Also remove the `check-working-directory` target. It should be clear
from the output that only the …
> Makefile: simplify `make rpm`

- golang-github-osbuild-composer.spec
We're not fully compatible with lorax-composer's API yet, and we don't
provide lorax-composer's systemd unit files.
As a result, cockpit-composer's integration tests fail, because `dnf
install lorax-composer` on Fedora can result in installing
osbuild-composer in some cases.
> spec: remove lorax-composer provide

- golang-github-osbuild-composer.spec
Since the recent commit (04db4fa) we are no longer provider
of lorax-composer. This was needed because when installing cockpit-composer,
which depends on lorax-composer, dnf chose us as the lorax-composer provider
instead of the original lorax-composer package. As we are not yet ready to
fully replace lorax-composer, this broke the cockpit-composer tests.
This commit is the first part of long term fix. Osbuild-composer is now
a provider of weldr. Soon, lorax-composer will also be a provider of
weldr. After that, cockpit-composer will be switched to be depending
on weldr. Also, it will suggest lorax-composer, which will force dnf
to use lorax-composer as the default weldr backend. If someone wants
to experiment with osbuild-composer, it will be possible, because
it will also be a provider …
> spec: add weldr provide

- .github/workflows/tests.yml
Now that `make rpm` does what we need, let's simplify GitHub Actions workflows and use that instead. 
Also, let's add emojis. *Why?* Don't ask why. **Just love the emojis.** 🥰
> 🐣 Use new 'make rpm' in GitHub Actions

- Makefile
The spec file in the current working directory might have changes. When
building rpms with the commit hash in the version, they ought to be
built with the spec file from that hash as well.
> Makefile: use spec file from HEAD to make rpm

- cmd/osbuild-tests/main.go
Some `composer-cli` commands operate on the current directory, for
example saving blueprints or images. Add the `TemporaryWorkDir` type,
which helps changing to a temporary working directory and cleaning
everything up after.
The alternative would have been to pass a working directory to all calls
of `runComposerCLI`, but that seemed like it would require a lot of
change, which I didn't deem worth for testing code.
> osbuild-tests: run compose tests in a temporary directory

- Makefile
- cmd/osbuild-rcm-tests/main.go
It is an equivalent to what we already have for Weldr API but this one
is for the RCM API. It should test the expected use cases:
* submit a compose
* get a status
> tests: introduce RCM API testing executable

- cmd/osbuild-tests/main.go
For every image built we download it via `composer-cli compose image` then delete the file using globs to match only on the UUID. 
Globbing doesn't seem t produce errors so maybe I'm not using it correctly.
> Download images inside osbuild-tests

- cmd/osbuild-weldr-tests/main.go
- internal/client/blueprints.go
- internal/client/client.go
- internal/client/client_test.go
- internal/client/weldr.go
- internal/weldrcheck/blueprints.go
- internal/weldrcheck/check.go
This converts the client and weldrcheck functions to use http.Client for
connections instead of passing around the socket path and opening it for
each test.
> client: Use http.Client instead of a string for the socket

- internal/store/store.go
- internal/weldr/api.go
In the process of adding tests I discovered that the tag route was unimplemented, and that the blueprint commits were un-ordered. This PR builds on my test PR #261 and should not be merged until that one is.
> Fix blueprint commit ordering and add blueprint tag support

- .gitignore
- Makefile
- cmd/osbuild-dnf-json-tests/main_test.go
- golang-github-osbuild-composer.spec
This is based on @atodorov's https://github.com/osbuild/osbuild-composer/pull/282. It contains the same commits, but changes the spec file to not use the `gotest` macro for building the binary. It also squashes the last two commits, because the intermediate state doesn't work.
> tests: use go's test framework in osbuild-dnf-json-tests

- cmd/osbuild-dnf-json-tests/main_test.go
- go.mod
- test/README.md
- vendor/modules.txt
@msehnout the asserts part should be straight forward but can you pay attention to the test docs? Is this what you meant in your commment here https://github.com/osbuild/osbuild-composer/issues/309#issuecomment-598589328
> Convert osbuild-dnf-json-tests to using asserts + test docs

- cmd/osbuild-image-tests/context-managers.go
- cmd/osbuild-image-tests/helpers.go
- cmd/osbuild-image-tests/netns.go
- cmd/osbuild-image-tests/osbuild-image-tests.go
- go.mod
- golang-github-osbuild-composer.spec
- vendor/modules.txt
This PR makes the osbuild-image-tests binary doing the same set of tests
like the old test/run script.
Changes from test/run:
- qemu/nspawn are now killed gracefully. Firstly, SIGTERM is sent. If the process doesn't exit till the timeout, SIGKILL is sent. I changed this because nspawn leaves some artifacts behind when killed by SIGKILL.
- the unsharing of network namespace now works differently because of systemd/systemd#15079
> Finish rewriting the image tests to Go

- cmd/osbuild-composer/main.go
- distribution/osbuild-composer.service
Use $STATE_DIRECTORY environment variable which is set by systemd
because we use: StateDirectory=osbuild-composer in the service unit.
_Note: I haven't yet had time to run integration tests on this => draft._
> osbuild-composer: don't use hardcoded state directory

- .golangci.yml
In the current PRs (#325 and #335) we have an issue with the linter failing on a dead code in integration tests. The linter isn't failing on main_test.go file because it somehow ignores the integration tag. However, it fails on other files which main_test.go depends on and which have the integration tag.
This commit tells golangci-lint to always use the integration tag while doing the inspection.
I think there shouldn't be any false negatives resulting from this change. However, I may be wrong, feel free to correct me.
Another solution is to turn off the `deadcode` linter in the affected files, however I think that this PR solves this issue more elegantly.
Note: This commit doesn't have any effect on our current codebase.
> ci/lint: add integration tag

- cmd/osbuild-composer/main.go
- internal/jobqueue/api_test.go
- internal/mocks/rpmmd/fixtures.go
- internal/rcm/api.go
- internal/rcm/api_test.go
- internal/store/store.go
- internal/weldr/api.go
See individual commits. Lots of cleanup-type commits leading up to be able to merge these two functions.
@msehnout I wonder about the benefit of the common types. There's lots of code to convert between them and strings, all of which can return an error.
> rcm: merge the two PushCompose functions

- golang-github-osbuild-composer.spec
Fedora packaging guidelines require that we use scriptlets when shipping
unit files:
https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_systemd
the rcm subpackage needs to use these as well as the main package.
> spec: add systemd scriptlets for the rcm subpackage

- internal/jobqueue/api.go
- internal/jobqueue/api_test.go
- internal/jobqueue/job.go
- internal/store/store.go
A job's purpose is to build an osbuild manifest and upload the results
somewhere. It should not know about which distro was used to generate
the pipeline.
Workers depended on the distro package in two ways:
1. To set an osbuild `--build-env`. This is not necessary anymore in new
versions of osbuild. More importantly, it was wrong: it passed the
runner from the distro that is being built, instead of one that
matches the host.
This patch simply removes that logic.
2. To fetch the output filename with `Distro.FilenameFromType()`. While
that is useful, I don't think it warrants the dependency.
This patch uses the fact that all current pipelines output exactly
one file and uploads that. This should probably be extended in the
future to upload all output files, or to name them explicitly in the …
> store/jobqueue: remove `distro` field from jobs

- golang-github-osbuild-composer.spec
The changelog is distribution-specific, therefore it doesn't make sense to have it upstream.
The removal also makes the releasing of new version to Fedora easier (We don't have to sync the changelogs).
However, I could be wrong, feel free to tell me why to keep the changelog in the repository.
> spec: remove the changelog

- Makefile
- cmd/osbuild-rcm-tests/main_test.go
- golang-github-osbuild-composer.spec
This is my attempt at rewriting the current rcm test using the testify assert and require packages. I'm not sure if this will behave in the same way, I might have removed too much.
> tests: rewrite RCM tests to use go test framework

- cmd/osbuild-composer/main.go
- cmd/osbuild-pipeline/main.go
- internal/client/client_test.go
- internal/distro/distro.go
- internal/distro/distro_test.go
- internal/distro/fedora30/distro.go
- internal/distro/fedora30/distro_test.go
- internal/distro/fedora31/distro.go
- internal/distro/fedora31/distro_test.go
- internal/distro/fedora32/distro.go
- internal/distro/fedora32/distro_test.go
- internal/distro/fedoratest/distro.go
- internal/distro/rhel81/distro.go
- internal/distro/rhel81/distro_test.go
- internal/distro/rhel82/distro.go
- internal/distro/rhel82/distro_test.go
- internal/distro/test/distro.go
- internal/weldr/api.go
- internal/weldr/api_test.go
Mixing the way to build a distribution with where to get the source
packages from is wrong: it breaks pre-release repos, local mirrors, and
other use cases. To accommodate those, we introduced
`/etc/osbuild-composer/repositories`.
However, that doesn't work for the RCM API, which receives repository
URLs to use from outside requests. This API has been wrongly using the
`additionalRepos` parameter to inject those repos. That's broken,
because the resulting manifests contained both the installed repos and
the repos from the request.
To fix this, stop exposing repositories from the distros, but require
passing them on every call to `Manifest()`. This makes `additionalRepos`
redundant.
Fixes #341
> distro: don't expose repositories in distro objects

- .travis.yml
- Makefile
- cmd/osbuild-image-tests/context-managers.go
- cmd/osbuild-image-tests/helpers.go
- cmd/osbuild-image-tests/main_test.go
- cmd/osbuild-image-tests/netns.go
- golang-github-osbuild-composer.spec
I decided not to use the testing framework in functions which are not directly tight to testing (booting images, running osbuild). I think it's reasonable to use classic error handling there and propagate the errors to places directly tight to testing and then use the testing library. This enables us to reuse the code in different part of projects if needed.
Other changes:
- I removed the hack which assumed that every fedora is Fedora 30. We currently do have tests for other Fedora versions, therefore it's not needed anymore.
- The testing VM has now only 1GB of memory, now it should be able to run in [teg/testvm](https://github.com/teg/test-vm/).
This PR is depending on #336, before it gets merged, the CI will be failing.
> tests/image: rewrite to go testing framework

- internal/jobqueue/api_test.go
- internal/rcm/api.go
- internal/store/store.go
- internal/weldr/api.go
Repositories were not passed down into `Distro.Manifest()`. This makes
all builds fail, because these repositories are use to access gpgkeys.
> store: pass repos to PushCompose

- cmd/osbuild-image-tests/constants.go
- cmd/osbuild-image-tests/context-managers.go
- cmd/osbuild-image-tests/helpers.go
- cmd/osbuild-image-tests/netns.go
Build constraints must be added to every file. We only want to build
this package when the `integration` tag is set.
Without this, every build prints this warning:
runtime.main_main·f: function main is undeclared in the main package
> osbuild-image-tests: add missing build constraints

- cmd/osbuild-composer/main.go
- internal/compose/compose.go
- internal/jobqueue/api_test.go
- internal/jobqueue/job.go
- internal/mocks/rpmmd/fixtures.go
- internal/rcm/api_test.go
- internal/store/store.go
- internal/target/aws_target.go
- internal/target/azure_target.go
- internal/target/local_target.go
- internal/weldr/api.go
- internal/weldr/api_test.go
- internal/weldr/compose.go
- internal/weldr/upload.go
Drop any assumptions about the name or number of output files that osbuild produces from the worker.
Inspired by #370, fixes #348.
> Specify image filenames in upload targets

- cmd/osbuild-composer/main.go
- cmd/osbuild-pipeline/main.go
- internal/client/client_test.go
- internal/distro/distro.go
- internal/distro/distro_test.go
- internal/distro/fedora30/distro.go
- internal/distro/fedora30/distro_test.go
- internal/distro/fedora31/distro.go
- internal/distro/fedora31/distro_test.go
- internal/distro/fedora32/distro.go
- internal/distro/fedora32/distro_test.go
- internal/distro/fedoratest/distro.go
- internal/distro/rhel81/distro.go
- internal/distro/rhel81/distro_test.go
- internal/distro/rhel82/distro.go
- internal/distro/rhel82/distro_test.go
- internal/distro/test/distro.go
- internal/jobqueue/api_test.go
- internal/rcm/api.go
- internal/store/store.go
- internal/weldr/api.go
- internal/weldr/api_test.go
- internal/weldr/upload.go
Introduce new interfaces to represent a distro at a given architecture, and each image type for a architecture/distro pair. Methods on the ImageType object are used rather than passing in architecture and image type to methods on the distro objects, simplifying the code and making the need for much of the `common` package redundant.
As discussed with @msehnout and @larskarlitski .
> Distro interfaces

- test/README.md
just makes it easier to navigate to the coverage report
> Add coverage notes and link to Coveralls in docs

- cmd/osbuild-dnf-json-tests/main_test.go
- cmd/osbuild-pipeline/main.go
- dnf-json
- internal/distro/fedora30/distro.go
- internal/distro/fedora31/distro.go
- internal/distro/fedora32/distro.go
- internal/distro/rhel81/distro.go
- internal/distro/rhel82/distro.go
- internal/mocks/rpmmd/rpmmd_mock.go
- internal/rcm/api.go
- internal/rpmmd/repository.go
- internal/weldr/api.go
The depsolving currently does not work cross-arch. Also when passing repos with multiple architectures it does not work but we already have the information about required architecture, so we can just pass it to dnf.
See individual commits for further explanation.
> Request specific architecture from dnf

- cmd/osbuild-worker/main.go
- distribution/osbuild-remote-worker@.service
- distribution/osbuild-worker@.service
- internal/jobqueue/client.go
See individual commits.
More is coming for `jobqueue.Client` if people think this it the right direction. This is a good first chunk that's ready for review.
It changes how `osbuild-worker`'s command line arguments. I don't think we treat those as stable API, right?
> worker: move ComposerClient to jobqueue and defaults to unit files

- cmd/osbuild-tests/main_test.go
by loading repositories configuration first and then running `composer-cli sources info <repo>` on the first repository found.
@teg I took a different approach for this. Please review.
> tests: Make TestSources distro independent. Refs #315

- internal/blueprint/blueprint_test.go
- internal/osbuild/locale_stage.go
- internal/osbuild/tar_assembler.go
The helper functions were never used, we should aim to use the
osbuild types just as regular structs for serialization purposes.
> osbuild: remove dead code

- image-types/README.md
- image-types/rhel8/README.md
- image-types/rhel8/amazon-ec2.md
- image-types/rhel8/openstack.md
This is the start to document the image types that osbuild-composer
produces on a higher level than the code in the `distro` package.
The idea is to document the purpose for each of the image types as well
as the reasons why deviating from a standard install is necessary.
This is a draft. Want to get feedback if this is generally going in the right direction before fleshing it out further. That's why I requested reviews from *all the people* :tada:
> image-types: start describing image types

- internal/osbuild/assembler_test.go
This improves coverage of assembler.go, the other related _assembler.go files still remaining to cover. I'd be glad for any comments, especially I wonder it there is any elegant way to better format the long lines with json strings.
> Add coverage for *assembler.go

- internal/distro/distro.go
- internal/distro/fedora30/distro.go
- internal/distro/fedora30/distro_test.go
- internal/distro/fedora31/distro.go
- internal/distro/fedora31/distro_test.go
- internal/distro/fedora32/distro.go
- internal/distro/fedora32/distro_test.go
- internal/distro/fedoratest/distro.go
- internal/distro/rhel81/distro.go
- internal/distro/rhel81/distro_test.go
- internal/distro/rhel82/distro.go
- internal/distro/rhel82/distro_test.go
- internal/weldr/api.go
Certain image types are not supported on certain architectures. For
example VMWare works only on x86_64, so it is not possible nor necessary
to produce vmdk images for any other architecture. The same goes to
cloud-provider specific images, we only support architectures they
support, e.g. AWS: x86_64 and aarch64, but not ppc64le or s390x.
This patch move the imageTypes dictionary to the appropriate place which
is in the architecture specific structure. It also merges the two "arch"
structures because it wasn't clear which one to use for this purpose.
It does the same for the imageType structures.
Only Fedora distros are covered in this PR.
> distro: define valid image types for the arches

- cmd/osbuild-dnf-json-tests/main_test.go
- cmd/osbuild-pipeline/main.go
- internal/distro/distro.go
- internal/distro/fedora30/distro.go
- internal/distro/fedora30/distro_test.go
- internal/distro/fedora31/distro.go
- internal/distro/fedora31/distro_test.go
- internal/distro/fedora32/distro.go
- internal/distro/fedora32/distro_test.go
- internal/distro/fedoratest/distro.go
- internal/distro/rhel81/distro.go
- internal/distro/rhel82/distro.go
- internal/distro/test/distro.go
In PR#395 we discussed the spelling of archs vs. arches and we agreed to
use arches. This patch only renames the public method `ListArchs`in the
`Distro` interface.
> distro: rename ListArchs to ListArches

- .github/workflows/tests.yml
- codecov.yml
- test/README.md
coveralls doesn't work from GitHub actions. Its "github" service type
uses the GITHUB_TOKEN from the action, which only has read access when
invoked from a forked repository.
codecov gets this right: it validates that an uploaded coverage file
originated from a GitHub action run by asking GitHub, and then uses its
OAuth credentials (through the Marketplace App) to comment and set
status.
Also, coveralls requires a third-party package to convert go's coverage
report to a format it understands. codecov detects the format
server-side. It also handles go's coverage format better: it highlights
lines with "some coverage" in yellow (coveralls has no concept of this).
> .github: switch to codecov.io

- internal/store/store.go
If a compose was interrupted by restarting osbuild-composer it should be
set to failed at startup. This was not working because imgBuild is a
temporary variable, the value stored in ImageBuild needs to be modified
directly.
> store: Fix setting interrupted composes to failed at startup

- tools/test-case-generators/generate-test-case
The line slipped in f945c505 when testing the changes. Let's remove it,
it breaks the script.
> tools: remove accidentally added line in test case generator

- internal/blueprint/customizations_test.go
This is my WIP on `customizations.go`. I have a few questions I'd like to ask.
1. First one is mentioned here: https://github.com/osbuild/osbuild-composer/issues/402
1. Is it ok to use 1 element in arrays for testing or is it better to put at least two in there? Sometimes there are loops going trough that so maybe it would have some benefit but I'm not sure.
1. In the first function `TestCustomizationsHostname` I have actually put the customization into a `Blueprint` and asserted the call from there as well (L24). Is that something we want or is the assert from `Customizations` enough? (L23)
I would also like some general feedback if it looks ok or if I could do something better.
Thank you.
> tests: add coverage for internal/blueprint/customizations.go

- CONTRIBUTING.md
- Makefile
- NEWS.md
- README.md
- docs/osbuild-composer.7.rst
This improves a bit on the documentation all over the place. It mostly follows what we did in *osbuild*, as it looks like everyone liked it so far:
* reformat markdown files in the repo (CONTIRBUTING, README, ..)
* create new osbuild-composer(7) man-page
* minor reshuffling in Makefile
* create a NEWS.md file with changelogs
> Documentation Improvements

- internal/distro/fedora30/distro.go
- internal/distro/fedora31/distro.go
- internal/distro/fedora32/distro.go
- internal/distro/rhel81/distro.go
- internal/distro/rhel82/distro.go
- test/cases/f30-x86_64-ami-boot.json
- test/cases/f30-x86_64-openstack-boot.json
- test/cases/f30-x86_64-partitioned_disk-boot.json
- test/cases/f30-x86_64-vmdk-boot.json
- test/cases/f31-x86_64-ami-boot.json
- test/cases/f31-x86_64-openstack-boot.json
- test/cases/f31-x86_64-partitioned_disk-boot.json
- test/cases/f31-x86_64-vmdk-boot.json
- I added `dracut-config-generic` to Fedora to make initramfs generation host independent
- I clean up its usage in RHEL - it's no longer installed in the build pipeline and in the non-bootable images.
> Make initramfs generation host independent

- .github/workflows/tests.yml
actions/checkout@v1 sometimes fails, bumping the version should fix it. See:
https://github.com/actions/checkout/issues/23
This issue is currently preventing running the checks on #443
> ci/github: bump the checkout action to version 2

- internal/common/helpers.go
- internal/common/helpers_test.go
This also changes the helpers.go to enable mocking all the different architectures.  If you have a better idea for the name of the newly created variable I'll be glad to hear it :)  
The `runtime.GOARCH` is actually a constant that is taken from `sys` package https://golang.org/pkg/runtime/#pkg-constants
Refs #419
> tests: add coverage for common/helpers.go

- internal/common/states_test.go
Asserts look nicer and are easier to read. Functionality should be the same.
Refs #419
> tests: use asserts in states_test.go

- internal/crypt/crypt_test.go
@atodorov could you give me some advice here please? By simply calling the `CryptSHA512` function I get a lot of lines covered which is fine I guess but I am not sure if there's anything else I can do to verify correct functionality of the hash function. I thought about calling it multiple times with the same input and comparing the returned values if they're all unique (each one of them gets random salt). 
But since the actual hashing algorithm is implemented in an external C function I guess simply verifying that this returns a hash value and no errors is enough? What's your opinion on this?
> tests: increase coverage of internal/crypt

- jenkins/run_tests.sh
Let's throw schutz to the wind and add Jenkins to the osbuild-composer
repository. Jenkins will execute the `jenkins/run_tests.sh` script and that
will deploy osbuild, osbuild-composer, and cockpit-composer on Fedora 31
and 32.
We can add extra integration tests gradually after this is merged.
> 🔌 Plug osbuild-composer into Jenkins

- internal/common/types.go
- internal/common/types_test.go
The Alibaba and GCE image types were not used, and they were
causing problems when translated from and to strings as they were
mapping to the same internal image type. The end result was that
AWS jobs were shown as Alibaba or GCE in the UI.
This fixes #369.
> common: drop unused image types

- jenkins/run_tests.sh
Now that Jenkins is hooked up to the repository, let's run the rcm
tests after we deploy all of the services into a VM.
> 🎲 Enable rcm integration tests

- cmd/osbuild-image-tests/aws.go
- cmd/osbuild-image-tests/constants-travis.go
- cmd/osbuild-image-tests/constants.go
- cmd/osbuild-image-tests/context-managers.go
- cmd/osbuild-image-tests/helpers.go
- cmd/osbuild-image-tests/main_test.go
- test/cases/f30-x86_64-ami-boot.json
- test/cases/f31-x86_64-ami-boot.json
- tools/test-case-generators/format-request-map.json
Blocked by #460, without this, the s3 objects won't be deleted.
This PR adds a lot of small cleanups to the image tests and the support for testing the ami images on the actual AWS. The AWS tests won't be run if secrets are not set as environment variables, qemu is used as a fallback in this case.
It should be fairly simple to switch the aws upload to be done by osbuild-composer when we decide to use it in the image tests.
To answer @atodorov 's question, in the end, I decided to use a freshly generated key-pair for each AWS upload. I think it's definitely better for security purposes. I understand that we may have a use-case for debugging the running instance and this will make it hard, but I feel this should be done as a follow-up when we know how do we want to implement this.
I decided …
> tests/image: test ami images on AWS

- tools/test-case-generators/generate-test-case
- tools/test-case-generators/generate-test-cases
The current implementation does not report any errors because it uses
the subprocess.check_output function from Python std library. The
function is convenient to use but it hides all the errors from us which
makes it very inconvenient when the test generation often fails (like
developing support for alternative architecture). This patch introduces
a wrapper around the subprocess.run function which dumps the
subprocess's stdout to stderr in case of failure and forwards it to the
caller in case of success. This way the generation code is still very
straight forward, but the errors are reported properly.
Fixes: #449
> test-case-generators: report errors from child processes

- internal/jobqueue/api.go
- internal/jobqueue/api_test.go
- internal/jobqueue/client.go
- internal/jobqueue/json.go
Make the worker API behave a bit better, especially not returning plain text when advertising `application/json`. See commits messages for details.
> jobqeue: worker API fixups

- cmd/osbuild-dnf-json-tests/main_test.go
- dnf-json
- jenkins/run_tests.sh
While debugging a modularity error on fedora-32, I noticed that it's hard to find out which distro / arch / image type combination failed. This doesn't fix the actual error (@major turned off testing on fedora-32 for now), but might make things simpler in the future.
There's also a commit that fixes `dnf-json` not print python stacktraces in a few additional cases.
See commits for more details.
> dnf-json-tests: split into sub tests

- README.md
- golang-github-osbuild-composer.spec
- osbuild-composer.spec
The newest osbuild is needed for support for aarch64. The aarch64 images
are using GPT which requires stable partuuid which was included in the
latest osbuild release (11). This will be used to produce stable
image-info tests.
> osbuild requirement: bump to version 11

- tools/image-info
The subproces.check_output function hides the output of the subprocess
it runs, using subprocess.run directly enable us to see the errors.
> image-info: report errors from subprocess calls

- tools/test-case-generators/generate-test-case
In PR #400:
https://github.com/osbuild/osbuild-composer/pull/400
we changed the boot type of AWS images from qemu-extract to aws, which
resulted in a bug in the generate-test-case script. It tried to attach
xz archive using qemu-nbd which works just fine from qemu-nbd
perspective but sfdisk and blkid of course failed, because the xz
archive is not a disk image.
This patch makes sure we extract the image before attaching it to
/dev/nbdX.
> test-case-generators: use unxz also for aws

- codecov.yml
Codecov's patch status measures lines covered in a given pull request,
which fails when moving code around.
Adding code with no coverage still fails the codecov/project status,
which fails if coverage has gone down.
> codecov: disable codecov/patch status

- internal/jsondb/db.go
- internal/jsondb/db_private_test.go
- internal/jsondb/db_test.go
- internal/store/store.go
weldr's store is quite complex and handled serialization itself. Move
that part out into a separate package `jsondb`.
This package is more generic than the store needs: it can write an
arbitrary amount of JSON documents while the store only needs one:
state.json. This is in preparation for future work, which introduces a
queue package that builds on top of `jsondb`.
> jsondb: introduce a simple JSON database

- internal/crypt/crypt_test.go
The new crypt tests cannot be run on macOS. Making them conditional for
non-macOS platforms fixes running unit tests in the internal directory
on macOS.
> crypt_test: don't run on macOS

- test/cases/f30-x86_64-ami-boot.json
- test/cases/f30-x86_64-ext4_filesystem-boot.json
- test/cases/f30-x86_64-openstack-boot.json
- test/cases/f30-x86_64-partitioned_disk-boot.json
- test/cases/f30-x86_64-qcow2-boot.json
- test/cases/f30-x86_64-tar-boot.json
- test/cases/f30-x86_64-vhd-boot.json
- test/cases/f30-x86_64-vmdk-boot.json
- test/cases/f31-x86_64-ami-boot.json
- test/cases/f31-x86_64-ext4_filesystem-boot.json
- test/cases/f31-x86_64-openstack-boot.json
- test/cases/f31-x86_64-partitioned_disk-boot.json
- test/cases/f31-x86_64-qcow2-boot.json
- test/cases/f31-x86_64-tar-boot.json
- test/cases/f31-x86_64-vhd-boot.json
- test/cases/f31-x86_64-vmdk-boot.json
We made few changes to the format of the test cases, regenerate them to
reflect the change and also to make sure it still works.
This work will be a base for #472 where I'll regenerate test cases for non-bootable images again to reflect the change.
> test/cases: regenerate fedora test cases for x86_64

- internal/store/store.go
If a user creates a compose with a size of 0, the default image size for the image type should be used. Also, certain image types have requirements for the image size. In order to ensure that the proper image size is stored in the compose object, the compose's ImageBuild object uses ImageType.Size() to get the correct image size for the image type.
> store: use default size in image build

- internal/store/store.go
If you don't set the time it ends up being the default Go time which is
1/1/1 and when you convert that using UnixNano() you get a nice big
negative number (-6795364578871345152) which then eventually shows up in
the queue, finished, and failed output as 'Fri Aug 30 17:47:39 1754'
and since the Time Travel feature is not yet complete this is
impossible.
The fix is to set it when the job is started.
> store: Set JobStarted time when PopJob is called

- internal/distro/fedora30/distro.go
- internal/distro/fedora31/distro.go
- internal/distro/fedora32/distro.go
- test/cases/f30-x86_64-ext4_filesystem-boot.json
- test/cases/f30-x86_64-tar-boot.json
- test/cases/f31-x86_64-ext4_filesystem-boot.json
- test/cases/f31-x86_64-tar-boot.json
- tools/image-info
@larskarlitski , @jgiardino is it ok to change the ext4 image type like this? I'm really unsure about its definition. The image type is declared non-bootable here:
https://github.com/osbuild/osbuild-composer/blob/7dd09443cf22b4cb3a9f15f6fe3d34eb02d8d3ac/internal/distro/fedora31/distro.go#L226
There is no point in having the grub2 stage in pipelines for image types
that are not bootable. The current version is probably a result of
previous refactoring where the member variable was named `IncludeFSTab`.
Moving the grub2 stage into the conditional branch should also fix test
generation on aarch64.
TODO:
> distro: don't include grub2 stage in ext4 images

- .github/workflows/tests.yml
The source of issue here is that our release cycles are synchronized and
if we want to use the latest released osbuild we need to wait for the
bodhi process. It makes sense that we don't want to use latest osbuild
from git master but we should be confident enough in the version we
submit to bodhi.
Using the version from updates-testing therefore fixes the issue with
synchronization and avoids using unreleased versions.
> workflow: enable updates-testing repo when installing osbuild

- internal/upload/awsupload/awsupload.go
us-east-1 seems to very slow these days, some imports can take up to
15 minutes. This commit raises the timeout from 10 to 20 minutes.
> upload/aws: double the timeout for snapshot import

- README.md
- docs/osbuild-composer.7.rst
Cockpit-composer is moving from the weldr github organization to the osbuild organization and its github url has changed. I have updated cockpit-composer's url. 
This PR should not be merged until after cockpit-composer has moved to the osbuild organization.
> Update cockpit-composer urls for organization change

- cmd/osbuild-image-tests/context-managers.go
Speed up the boot tests by allowing qemu to use all of the available
CPUs on the system. Our CI VMs have at least 2 CPUs and this shortens
the time required for a boot test.
> 🐎 Allow qemu to use all available CPUs

- .travis.yml
The tests don't do anything useful currently. This commit disables them
to save some resources and possibly speed up the CI a bit (the free plan
allows us to have only 5 concurrent jobs, so if all slots are full,
PRs have to wait).
> ci/travis: Disable the useless arm64 tests

- jenkins/run_tests.sh
- jenkins/test.yml
- jenkins/test_runner.yml
- jenkins/vars.yml
Convert the bash script to an ansible playbook so we can gracefully
handle testing failures and gather logs reliably. Colorful output
is nice, too.
> 🥊 Resilient testing + log gathering

- tools/prepare-source.sh
go mod works differently in go 1.12 and go 1.13. When someone uses the
prepare-source tool with go >= 1.13, the ci complains because it uses
go 1.12. This commit changes the script to use a well-defined go version.
> tools/prepare-source: use a well-defined go version

- cmd/osbuild-dnf-json-tests/main_test.go
Run multiple dnf-json tests in parallel to speed up execution. The total number of parallel tests is limited by the number of CPUs in the machine that is running the tests.
This reduces dnf-json test runtime in PSI from 14-15 minutes down to 5-6 minutes.
> 🐎 Run dnf-json tests in parallel

- internal/distro/fedora31/distro.go
For some reason, the condition to round up the image size for vhd in `imageType.Size()` wrongly used `imageType.filename` instead of `imageType.file` (only for F31, OK for other distros).
> Fedora31 - fix Size() for vhd

- jenkins/run_tests.sh
- jenkins/test.yml
- jenkins/test_runner_base.yml
- jenkins/test_runner_image.yml
- jenkins/vars.yml
We can speed up test run times by putting base tests and image tests
into two separate jobs in Jenkins. Add support to the testing playbook
for both types of tests and make it easy to add more types later,
especially for image that require booting in the cloud.
> 🐫 Handle base/image test cases

- .github/workflows/tests.yml
- cmd/osbuild-image-tests/main_test.go
- golang-github-osbuild-composer.spec
- internal/distro/fedora30/distro.go
- internal/distro/fedora30/distro_test.go
- internal/distro/fedora31/distro.go
- internal/distro/fedora31/distro_test.go
- internal/distro/fedora32/distro.go
- internal/distro/fedora32/distro_test.go
- internal/distro/rhel81/distro.go
- internal/distro/rhel81/distro_test.go
- internal/distro/rhel82/distro.go
- internal/distro/rhel82/distro_test.go
- internal/distro/rhel83/distro.go
- internal/distro/rhel83/distro_test.go
- internal/upload/awsupload/awsupload.go
- osbuild-composer.spec
- test/cases/fedora_30-aarch64-ami-boot.json
- test/cases/fedora_30-x86_64-ami-boot.json
- test/cases/fedora_31-aarch64-ami-boot.json
- test/cases/fedora_31-x86_64-ami-boot.json
- tools/test-case-generators/format-request-map.json
- tools/test-case-generators/generate-test-case
Prior this commit the ami image type produced raw.xz images. This was bad for
two reasons:
- The upload was broken because AWS doesn't support tar.xz format
- XZ compression is terribly slow
This commit changes the format to vhdx, which is supported by AWS and also
quite quick. See #257
why vhdx was chosen.
The osbuild requirement is bumped to 12, because that's the first version
that supports vhdx.
Also, I removed the code for handling the `raw.xz` images, so cool!
> Change the format of the ami image type to vhdx

- internal/client/integration_test.go
- internal/client/unit_test.go
see internal/client/integration_test.go
> tests: clean up before exiting b/c os.Exit doesn't respect defer

- cmd/osbuild-worker/main.go
- cmd/osbuild-worker/osbuild.go
The commit 2435163f broke sending the logs to osbuild-composer. This was
partly because of unusual error handling in the RunOSBuild function.
This commit fixes that by creating a custom error and properly propagating
the result from it.
> worker: fix missing logs when osbuild fails

- .travis.yml
- test/cases/fedora_32-x86_64-vhd-boot.json
- test/cases/rhel_8.2-x86_64-vhd-boot.json
Jenkins still doesn't run all the image tests as Travis does, so let's add Fedora 32 for now, so we know it's working.
Also, I changed the boot type for f32 and rhel 8.2 to azure, I think they were still set to qemu because of " a merge race condition".
> Enable Travis for Fedora 32

- jenkins/test_runner_image.yml
- jenkins/vars.yml
Enable image tests for Fedora 31 and RHEL 8.2 since we now have the JSON
test case files for all distributions.
> 🤗 Image tests for Fedora 32 + RHEL 8.2

- cmd/osbuild-worker/main.go
I tried fixing this in 181128c5 and forgot to pass the right error at one place. This PR fixes it. I think I tested this properly now, sorry.
> worker: fix passing the result from osbuild when it fails

- internal/osbuild/assembler_test.go
- internal/osbuild/tar_assembler.go
@gicmo mentioned that  when using the https://github.com/osbuild/osbuild/pull/219 PR against the tar test cases an invalid size argument was passed in the assembler options. 
Image size should not be specified for a tar image. When the tar assembler was being created image size was not passed to it. However, the TarAssemblerOptions contained a Size field which would default to 0. This field is removed so that the tar assembler options no longer specify a size. The assembler tests are also updated to reflect this change.
I believe the tar test cases will need to be updated to remove the image size. Can I do this manually or is there a benefit to regenerating the test cases?
> Remove image size from tar assembler options

- test/cases/fedora_30-aarch64-tar-boot.json
- test/cases/fedora_30-x86_64-tar-boot.json
- test/cases/fedora_31-aarch64-tar-boot.json
- test/cases/fedora_31-x86_64-tar-boot.json
- test/cases/fedora_32-x86_64-tar-boot.json
- test/cases/rhel_8.2-x86_64-tar-boot.json
When building a tar image the image size should not be specified. All image size fields are removed from the assembler options in the tar test cases. This is a follow up to #557
> test/cases: remove tar size

- jenkins/test_runner_base.yml
- jenkins/test_runner_image.yml
Hiding logs makes the output prettier, but it is sometimes easier to see
the problem right there in the Ansible output.
> 📔 Remove the no_log for image tests

- internal/worker/client.go
Use https scheme for workers with TLS configuration set.
Fixes #568.
> 🐞 Fix worker https logic

- jenkins/vars.yml
Test the full set of locally-bootable image tests. Cloud based tests
are excluded for now until the infrastructure to boot them is ready.
> Add remaining local image tests

- jenkins/run_tests.sh
- jenkins/test.yml
Jenkins now uses a non-root user for its agent, so we will need to use
sudo for some commands and `become` within the Ansible playbooks.
> Use sudo/become for tests

- cmd/osbuild-image-tests/context-managers.go
Running qemu with -accel accel= results in the following error:
qemu-system-x86_64: -accel accel=kvm:hvf:tcg: Don't use ':' with -accel,
use -M accel=... for now instead
Qemu 4.2 deprecated the -accel accel= argument. When the arg is passed in,
qemu exists status code of 1.
This commit changes the qemu command to use the recommended way of specifying
the acceleration options.
See:
https://github.com/qemu/qemu/commit/3d5e90a50bd4ffa199166e01a365f5c5995534ae
> test/image: fix qemu args on qemu>=4.2

- jenkins/Jenkinsfile
- jenkins/run_tests.sh
By using a small Jenkins pipeline in the repository, we can define
almost all of our testing parameters in the repo itself and not inside
Jenkins. This also allows us to use the GitHub Branch Source plugin and
auto-discover new repositories without `ok to test` bombs in pull
requests.
> 🚽 Use Jenkins pipeline for better flow

- internal/distro/distro_test.go
- internal/distro/distro_test_common/distro_test_common.go
- internal/distro/fedora30/distro_test.go
- internal/distro/fedora31/distro_test.go
- internal/distro/fedora32/distro_test.go
It turned out the paths leading to pipeline JSONs used in TestDistro_Manifest were wrong. This was not obvious before, because this didn't lead to FAILs, so I fixed this problem as well by adding an assert to make sure at least some pipeline files are matched for the test.
> [tests] Fix distro manifest tests pipeline paths

- schutzbot/Jenkinsfile
- schutzbot/run_tests.sh
- schutzbot/test.yml
- schutzbot/test_runner_base.yml
- schutzbot/test_runner_image.yml
- schutzbot/vars.yml
Attempt osbuild-composer testing on the internal Jenkins deployment with
nodes that are destroyed after each use. The internal Jenkins looks for
a Jenkinsfile inside the `schutzbot` directory.
Let's not remove the `jenkins` directory (used by jenkins.osbuild.org)
yet until we know the internal Jenkins is stable and performs well.
> ↔ Parallel testing on internal Jenkins

- codecov.yml
We're using code coverage as additional information, but don't want to
gate pull requests on it.
> codecov: add 5% threshold

- internal/client/integration_test.go
- internal/client/unit_test.go
- internal/client/utils.go
A timeout doesn't make sense on this level, because it is very difficult
to estimate how long downloading rpm metadata takes. Drop it completely
in favor of higher-level timeouts in the test runner.
Fixes #601
> client: drop client timeout in tests

- schutzbot/test_runner_base.yml
- schutzbot/test_runner_image.yml
Use golang's `test.timeout` to set the timeout instead of using
ansible's `async` property. The latter doesn't respect `register` when
running into a timeout, which means there are no logs in that case.
Simplify these playbooks by setting `ignore_errors: true` on the
`command` module, so that it's easier to collect logs.
> schutzbot: use -test.timeout argument

- jenkins/test_runner_base.yml
- jenkins/test_runner_image.yml
This is the same as 6c611b487, but for the jenkins directory
(configuration for Jenkins inside Red Hat's VPN).
Use golang's `test.timeout` to set the timeout instead of using
ansible's `async` property. The latter doesn't respect `register` when
running into a timeout, which means there are no logs in that case.
> jenkins: use -test.timeout argument

- cmd/osbuild-image-tests/constants/constants-travis.go
- cmd/osbuild-image-tests/constants/constants.go
- cmd/osbuild-image-tests/context-managers.go
- cmd/osbuild-image-tests/main_test.go
- cmd/osbuild-worker/main.go
- cmd/osbuild-worker/osbuild.go
- tools/test-case-generators/generate-test-case
Since 2 releases `osbuild` accepts an `--output-directory=DIR` argument
which lets us decide where to place generated artifacts. Switch over to
it, rather than digging into the store, to make sure we will not access
the osbuild store when parallel cleanups are ongoing (which are not yet
a thing, though).
> worker: switch to `--output-diectory=DIR`

- internal/compose/compose.go
- internal/store/store.go
After the queue rework, TestCompose() was the only user of
UpdateImageBuildInCompose() and Compose.UpdateState(). Set all required
fields in TestCompose() directly instead of going through those.
> store: simplify TestCompose

- cmd/osbuild-composer/main.go
- internal/jobqueue/fsjobqueue/fsjobqueue.go
- internal/jobqueue/fsjobqueue/fsjobqueue_test.go
- internal/jobqueue/jobqueue.go
- internal/jobqueue/testjobqueue/testjobqueue.go
- internal/jsondb/db.go
- internal/jsondb/db_test.go
- internal/worker/server.go
This series includes a few follow-up commits for the jobqueue PR. Some is cleaning up, some is refactoring to make it possible to support cancelation (the last commit).
> jobqueue follow ups, including cancelation

- schutzbot/test.yml
- schutzbot/test_runner_image.yml
Make it easier to see progress in Jenkins for image tests and keep their
logs separated for easier diagnosis of problems.
> CI: Split image tests into separate tasks

- internal/distro/fedora30/distro_test.go
- internal/distro/fedora31/distro_test.go
- internal/distro/fedora32/distro_test.go
The asserts should do the same job and also at the same time make sure that the two compared lists are equal. In the original state, the comparison was performed, but the result was thrown away - and actually the result was false, as the two lists were different due to non-equal order of items.
This change originates from a suggestion by @atodorov in #591.
EDIT: I just found out that I could possibly use `assert.ElementsMatch` instead of `assert.Equal` and leave the items order in the list as it was before. What would be the better option?
> [tests] use assert.Equal instead of reflect.DeepEqual in distro_test

- cmd/osbuild-dnf-json-tests/main_test.go
t.Parallel() makes defer weird. This commit moves the temporary dir setup
and teardown to the parallel subtest, so the teardown gets called after
the tests are finished.
See the section "Run a group of tests in parallel":
https://blog.golang.org/subtests
> test/dnf-json: fix cleaning-up the cache after the test is finished

- schutzbot/run_tests.sh
When Jenkins clones a repository for testing, it does the base clone
first and then merges the code from the PR afterwards. This ensures that
the code merges properly and is tested properly, but it also makes a SHA
that only exists inside Jenkins. 😢
Tell ansible-osbuild to use the repository that Jenkins made so that the
SHA is valid.
> CI: Use Jenkins' merged repo for testing

- schutzbot/Jenkinsfile
Ensure that logs are artifacted after a test run. Also, ensure that
these logs are in unique directories so that they are not overwritten by
Jenkins as it builds the final artifact archive.
For example, if two jobs have a `test.log`, Jenkis will only keep one of
those logs. Each log must be named differently or placed in a unique
directory.
> CI: Gather log artifacts

- NEWS.md
We use 8ch indents right now, which causes everything to be interpreted
as `<pre>` (or whatever your favourite equivalent is). Lets use proper
markdown.
While at it, this fixes a set of minor issues:
* Surround markdown syntax with `` to suppress interpretation (like in
the regexp, etc).
* Replace hyphens before dates with proper em-dash.
* Fix indentation in some news-entries, which did not align correctly.
Also see the [rendered](https://github.com/dvdhrm/osbuild-composer/blob/wip/formatnews/NEWS.md) version.
> news: reformat as proper markdown

- cmd/osbuild-tests/main_test.go
This results in better output. Output before this swap can be
seen at https://github.com/osbuild/osbuild-composer/issues/611.
It looks like we wanted a compose to FAIL and it FINISHED instead
which is making the error log confusing.
> tests: swap the places of expected-actual results in asserts

- .travis.yml
- schutzbot/vars.yml
This PR does 2 things:
1) Schutzbot didn't build ami and openstack images, so I added them.
2) Travis is now used to do only image tests with uploading, because that's not currently supported by Schutzbot.
> Remove most of the image tests from Travis

- codecov.yml
d49f0fef4 added a 5% threshold to codecov.yml, so that small fixes don't
turn the CI red.
However, it contained a typo and put the setting in the wrong place in
the file. codecov.io ignores unknown keys instead of throwing an error.
Fix this and validate with:
cat codecov.yml | curl --data-binary @- https://codecov.io/validate
> codevoc: fix threshold

- schutzbot/Jenkinsfile
If a pipeline runs for three hours, stop the pipeline. This can happen
if a network connection breaks down or if jenkins loses control of one
of its agents due to infrastructure issues.
> Add three hour timeout to test pipelines

- internal/upload/awsupload/awsupload.go
- schutzbot/Jenkinsfile
- schutzbot/test.yml
- schutzbot/test_runner_image.yml
- schutzbot/vars.yml
Build an AWS AMI image, upload it to S3, import it into EC2, and boot it.
> CI: Test EC2 import and boot

- .travis.yml
Schutzbot now tests it, no need to do it twice.
> ci/travis: remove ami test

- test/README.md
The image tests are now able to upload images to Azure and boot them there. However, the documentation on how to set up the required resources in Azure was missing. This commit adds it.
Rendered document: https://github.com/ondrejbudai/osbuild-composer/blob/document-azure/test/README.md#setting-up-azure-upload-tests
> test: document the Azure setup process

- cmd/osbuild-tests/main_test.go
- internal/rcm/api.go
- internal/store/store.go
- internal/weldr/api.go
- internal/weldr/compose.go
- internal/worker/server.go
The fix for the logs is here! This grew larger than I thought...
First 11 commits are just a minor refactoring. Basically, the `worker.JobStatus()` method got renamed to `worker.GetJobStatus()` and it now returns also the `JobResult`. In `weldr`, `getComposeState()` is now called `getComposeStatus()` and returns also `JobResult`. `worker.JobResult()` method was dropped because `GetJobStatus()` can be used instead.
Let's explain more in detail why I merged `JobResult()` and `GetJobStatus()` together:
Both methods actually called `jobqueue.GetJobStatus()`, so performance-wise there's no real difference and it feels to me that it makes the code simpler: You don't have to decide which method to call, you just get all the data about a job in one call. We could split those again when we see …
> Fixing the logs once again with some refactorings

- internal/upload/awsupload/awsupload.go
Importing an image into an EBS snapshot can sometimes take a long time.
The customer experience for a timeout is not great.
Allow the import to continue running for as long as needed without
timing out. This allows a customer to monitor the process of their
import until it has a success or failure status.
Fixes osbuild/osbuild-composer#632.
> Remove AWS snapshot import timeout

- distribution/osbuild-composer.conf
- distribution/osbuild-composer.socket
This fixes permission for the weldr socket: allow users in group `weldr`
to access it, but nobody else. Also add this group to the sysusers file.
Keep the job socket accessible by everyone, as it was before. It will
probably be dropped at some point in favor of remote workers.
Fixes #646
> distribution: split weldr and job sockets

- schutzbot/test.yml
- schutzbot/test_runner_base.yml
- schutzbot/test_runner_image.yml
- schutzbot/vars.yml
When we ran into these timeouts, they were always false negatives. It is
hard to find right values for them.
If someone does introduce a bug that hangs one of the tests, we still
have the global timeout.
Fixes #648
> schutzbot: remove all timeouts except the global one

- schutzbot/Jenkinsfile
- schutzbot/test.yml
- schutzbot/vars.yml
Now that EC2 image testing is working well for Fedora 32, enable it for
all of the distros. Also, make it less special and allow it to run with
the other image tests.
Remove the `ami-boot` test from the list of regular image test cases
since it will be thoroughly tested via an import into AWS.
> CI: Run EC2 tests for all instances

- schutzbot/test.yml
The osbuild CI uses the osbuild-composer CI testing playbooks but
there's no need to run the EC2 import for osbuild's CI. Add a check in
the Ansible playbook to look for the AWS_BUCKET environment variable and
skip the EC2 import if the bucker variable is missing.
> CI: Skip AWS test if bucket missing

- .github/workflows/tests.yml
The go test coverage report does not cover other packages unless you
list them with the -coverpkg= argument. This results in an incomplete
coverage report with oddly missing lines.
This commit lists all of the packages so that they will all be included
when running the tests and gathering the results.
> github: Fix go test coverage report

- schutzbot/Jenkinsfile
Now that mock building seems to be stable, let's start building RPMs for
RHEL 8.3 so we can onboard it for base/image testing soon.
> CI: Add mock builds for RHEL 8.3

- internal/weldr/api.go
- internal/weldr/api_test.go
composer-cli expects `msgs`, not `messages`, and throws an exception if
it doesn't exist:
https://github.com/weldr/lorax/blob/master/src/composer/cli/status.py#L52
It is not used anywhere else, so this is a safe change.
> weldr: messages → msgs in status route

- cmd/osbuild-pipeline/main.go
- internal/distro/distro.go
- internal/distro/distro_test_common/distro_test_common.go
- internal/distro/fedora30/distro.go
- internal/distro/fedora31/distro.go
- internal/distro/fedora32/distro.go
- internal/distro/fedora32/distro_test.go
- internal/distro/fedoratest/distro.go
- internal/distro/rhel8/distro.go
- internal/distro/test_distro/distro.go
- internal/osbuild/assembler.go
- internal/osbuild/assembler_test.go
- internal/osbuild/fstab_stage.go
- internal/osbuild/ostree_commit_assembler.go
- internal/osbuild/rpm_ostree_stage.go
- internal/osbuild/stage.go
- internal/osbuild/stage_test.go
- internal/rcm/api.go
- internal/store/json.go
- internal/weldr/api.go
- internal/worker/server_test.go
This adds support for generating Fedora IoT commit tarballs for Fedora 32. See individual commits for details.
I had a short discussion with @jgiardino about this, and she suggested that we could handle the required ostree-specific options in the same way as we handle image size, for now. That is, in the cockpit-composer UI, the user would can specify the parent commit and the ostree ref in the same place they select the image type (where the image size is currently configured).
Does that make sense to you @jkozol?
> Add Fedora IoT support

- cmd/osbuild-composer/main.go
- cmd/osbuild-worker/main.go
- internal/client/unit_test.go
- internal/mocks/rpmmd/fixtures.go
- internal/rcm/api_test.go
- internal/store/store.go
- internal/weldr/api.go
- internal/weldr/api_test.go
- internal/worker/client.go
- internal/worker/server.go
- internal/worker/server_test.go
The `jobs/:job_id/builds/:build_id/image` route was awkward: the
`:jobid` was actually weldr's compose id and `:build_id` was always `0`.
Change it to `jobs/:job_id/artifacts/:name`, where `:job_id` is now a
job id, and `:name` is the name of the artifact to upload. In the
future, it could support uploading more than one artifact.
This allows removing outputs from `store`, which is now back to being a
pure JSON-store. Take care that `weldr` returns (and deletes) images
from the new (or for backwards compatibility, the old) location.
The `org.osbuild.local` target continues to exist as a marker for the
worker to know whether it should upload artifacts.
> worker: introduce job artifact directory

- cmd/osbuild-worker/main.go
- cmd/osbuild-worker/osbuild.go
When fdd7536 added `--output-directory` to the invocation of osbuild,
it also removed `--store`.
This was a mistake: osbuild's default store is `.osbuild`, which is not
what we want. Restore the old behavior of passing a temporary directory.
> worker: dont cache just yet

- internal/worker/json.go
- internal/worker/server.go
- internal/worker/server_test.go
There are times where it would be good to monitor that osbuild-composer
is up and running. Add a very simple status check that always returns
`200 OK`. This can be expanded later to verify that other parts of
osbuild-composer are working properly.
> Add health check at /status

- distribution/osbuild-remote-worker@.service
Setting the cache directory to `/var/cache` causes problems on the
remote worker startup and it needs to be removed.
> Remove CacheDirectory for remote worker

- cmd/osbuild-composer/main.go
- internal/client/unit_test.go
- internal/weldr/api.go
- internal/weldr/api_test.go
- internal/worker/server.go
This allows removing the `artifactsDir` from `weldr.API`. It makes more
sense to deal with that directory in one place only.
This is a follow-up to @teg's [comment](https://github.com/osbuild/osbuild-composer/pull/666#discussion_r430248077) on the job artifact PR.
> worker: add JobArtifact() and DeleteJobArtifacts()

- image-types/rhel8/README.md
- image-types/rhel8/amazon-ec2.md
- image-types/rhel8/kvm-guest-image.md
- image-types/rhel8/microsoft-azure.md
- image-types/rhel8/openstack.md
- image-types/rhel8/vmware.md
Together with https://github.com/osbuild/osbuild-composer/pull/671, all RHEL image types have a documented purpose.
> Document additional RHEL image types

- schutzbot/Jenkinsfile
- schutzbot/mockbuild.sh
- schutzbot/run_tests.sh
- schutzbot/test.yml
Replace RHEL 8.2 nightly images with a RHEL 8 CDN subscribed instance so
we can test with the exact content a customer would have.
> CI: Use RHEL 8 CDN subscribed instance

- internal/client/compose.go
- internal/client/compose_test.go
- internal/store/fixtures.go
- internal/weldr/api.go
- internal/weldr/api_test.go
> Add support for /compose/metadata, /compose/results, as well as tests

- schutzbot/run_tests.sh
This variable is no longer needed since the bash script handles the
cursor.
> CI: Remove journald_cursor play variable

- golang-github-osbuild-composer.spec
- osbuild-composer.spec
RHEL 8 doesn't have golang in the i686 buildroot anymore. Fedora doesn't have
i686 images and kernel anymore. Also, osbuild-composer doesn't have support
for building i686.
Let's exclude i686 for these reasons, it's dead.
See rhbz#1752991
> spec: exclude i686 architecture

- internal/store/store.go
`log` is `nil`, unless we are in verbose mode. Skip logging if no logger
was passed.
Long-term I think we should reconsider how we do our logging, and always
log these type of unexpected errors, and hence always have the logger be
non-nil. For now, fix the immediate problem.
The fact that loading the store from disk fails on upgrade is
unexpected, and should be fixed separately.
Fixes #685.
> store: don't log if no logger was passed

- osbuild-composer.spec
The new functionality that landed in b0cfec767ab3aba7a411e8ae3097f2af59c7a02d
needs this dependency in order to function.
Fixes #689
> osbuild-composer.spec: Add a dependency on osbuild-ostree

- schutzbot/Jenkinsfile
- schutzbot/mockbuild.sh
- schutzbot/run_tests.sh
Store RPMs in object storage based on their SHA rather than the Jenkins
build ID. This allows tests to be re-run without repeating the mock
build step.
> CI: Store RPMs by SHA

- schutzbot/run_tests.sh
- schutzbot/test.yml
Ensure that AWS tests are run if the AWS_BUCKET environment variable is
set.
> Fix the AWS_BUCKET check

- internal/upload/awsupload/awsupload.go
Specifying the image format in the `DiskContainers` part of the snapshot
import process sometimes causes AWS to fail the import due to formatting
issues. However, AWS seems to do a decent job at determining the image
format on its own without specifying the format explicitly.
> Let AWS figure out the image format during import

- internal/weldr/api.go
- internal/weldr/api_test.go
- internal/weldr/compose.go
- internal/weldr/upload.go
Workers don't report status for the osbuild run and the upload targets
separately. Before the move to the jobqueue, we explicitly set the
status of all targets when a compose finished. When I removed that,
the image status broke.
Set the status from what's returned by api.getComposeStatus() to restore
the original behavior.
Fixes #702
> weldr: use compose status for targets as well

- internal/distro/fedora31/distro.go
- internal/distro/fedora32/distro.go
- internal/distro/rhel8/distro.go
- internal/osbuild/grub2_stage.go
- internal/osbuild/stage_test.go
- test/cases/fedora_31-aarch64-ami-boot.json
- test/cases/fedora_31-aarch64-openstack-boot.json
- test/cases/fedora_31-aarch64-qcow2-boot.json
- test/cases/fedora_31-x86_64-ami-boot.json
- test/cases/fedora_31-x86_64-openstack-boot.json
- test/cases/fedora_31-x86_64-qcow2-boot.json
- test/cases/fedora_31-x86_64-vhd-boot.json
- test/cases/fedora_31-x86_64-vmdk-boot.json
- test/cases/fedora_32-x86_64-ami-boot.json
- test/cases/fedora_32-x86_64-openstack-boot.json
- test/cases/fedora_32-x86_64-qcow2-boot.json
- test/cases/fedora_32-x86_64-vhd-boot.json
- test/cases/fedora_32-x86_64-vmdk-boot.json
- test/cases/rhel_8-x86_64-ami-boot.json
- test/cases/rhel_8-x86_64-openstack-boot.json
- test/cases/rhel_8-x86_64-qcow2-boot.json
- test/cases/rhel_8-x86_64-vhd-boot.json
- test/cases/rhel_8-x86_64-vmdk-boot.json
This work is based on previous PRs, namely:
https://github.com/osbuild/osbuild-composer/pull/501
and
https://github.com/osbuild/osbuild/pull/327
The problem here is that we used to treat legacy as a boolean before we
started introducing support for alternative architectures, but now we
need to specify exact strings for the grub2 stage, for example for
ppc64le the legacy parameter looks like this:
```
"legacy": "powerpc-ieee1275"
```
This patch will allow us to introduce support for ppc64le and fix
associated issues:
https://github.com/osbuild/osbuild-composer/issues/693
> osbuild: change legacy type from bool to string

- internal/upload/awsupload/awsupload.go
When ImportSnapshot fails, it goes into the deleted state. However, the code
didn't consider this state as a failure. This commit fixes that.
Fixes #706
> upload/aws: fail ImportSnapshot when the snapshot is deleted

- internal/upload/awsupload/awsupload.go
The AWS API always uses pointers to strings everywhere, rather than
plain strings. The log messages got this wrong and printed the pointers
rather than dereferencing them.
Don't require users to do a memory dump to get at the AMIs, but instead
print the actual strings. Also change to %s from %v to let the linter
warn us in the future. %s accepts only strings, whereas %v prints
whatever you throw at it.
> awsupload: fix printing of IDs

- internal/osbuild/qemu_assembler.go
osbuild takes a "bootloader" object as an option to the qemu assembler:
https://github.com/osbuild/osbuild/blob/3f14ace5c1ac876555aab6e05aa6f0f8dbbe278b/assemblers/org.osbuild.qemu#L43
we don't use it because for x86_64 with enabled legacy support it
defaults to the right value:
https://github.com/osbuild/osbuild/blob/3f14ace5c1ac876555aab6e05aa6f0f8dbbe278b/assemblers/org.osbuild.qemu#L482
but in order to gain support for ppc64le we need to introduce this.
Example usage can be found in samples directory:
https://github.com/osbuild/osbuild/blob/3f14ace5c1ac876555aab6e05aa6f0f8dbbe278b/samples/f30-ppc64le.json#L819
This change itself does not alter osbuild-composer output.
> osbuild: introduce bootloader struct into qemu assembler

- tools/test-case-generators/generate-test-case
Commit 8dd45544919961bf6d5d285a7fb6724ec0404e0f introduced a bug because
the output from osbuild is not captured. The problem is that osbuild
itself writes JSON document to STDOUT so two different JSON documents
are written to STDOUT: osbuild output and generated test case. The
generate-test-cases script then fails because it cannot json.loads() the
test case.
This patch simply supresses the output which fixes the issue.
> tools: fix generate-test-case script

- schutzbot/Jenkinsfile
- schutzbot/mockbuild.sh
Upload artifacts from the mock builds into S3 to allow us to burst into
AWS when needed.
> Use S3 for CI repositories

- internal/osbuild/zipl_stage.go
- internal/osbuild/zipl_stage_test.go
zipl is a z initial program loader used with IBM Z systems. This stage
is required to get support for the s390x architecture.
> osbuild: introduce zipl stage

- cmd/osbuild-tests/main_test.go
qcow2, unlike ami, is guaranteed to exist on all the architectures we
support.
Also, now that we preserve the cache, make two composes, rather than
just one. This verifies that nothing breaks horribly just because the
cache not being cold. The fact that we have a cache at all should make
this tolerably fast.
This should fix #693.
> tests/compose: use qcow2 rather than ami for tests

- tools/image-info
See the individual commits for details, here an excerpt from the main one:
Support analyzing ostree repositories or directory that contain an ostree commit as created by osbuild. Will return the mode of the repository along with the references and their commits. For the first references, the commit is resolved and checked-out to a temp directory. This directory in turn is then analyzed via the existing append_filesystem function. The latter has gained some small ostree specific tweaks.
NB: for the ostree checkout /usr/etc/ is bind mounted to /etc in order to make append_filesystem happy. The rpm verification step is NOT run, because that is not really compatible with ostree.
> Image info: support for analyzing ostree commits

- schutzbot/Jenkinsfile
- schutzbot/run_tests.sh
- test/image-tests/aws.sh
- test/image-tests/qcow2.sh
Add an end-to-end qcow2 test that follows a customer's steps with
`composer-cli`. The image is booted with libvirt to allow the best
virtualization options to be chosen by libvirt. It also uses libvirt's
default network.
> Add native qcow2 boot test

- test/image-tests/aws.sh
The JSON from AWS was not being passed to `jq` and the console
screenshots were empty. 🤦
> AWS: Fix console screenshot retrieval

- schutzbot/Jenkinsfile
Enabling the RHEL 8.3 mock build. More steps/tests can be added after this is merged.
> Re-enable RHEL 8.3 mock build

- schutzbot/run_image_tests.sh
On RHEL, `VERSION_ID` shows up as `8.2` or `8.3`, but we need it to be
just `8`.
Remove the period and everything after it in `$VERSION_ID`.
> Fix image test VERSION_ID

- cmd/osbuild-image-tests/main_test.go
On some environments (like RHEL gating) there's no virtualization available.
This commit adds -disable-local-boot argument to osbuild-image-tests. When
this argument is present, the local booting is skipped. This doesn't affect
the cloud booting, the test binary still tries to do that. If no credentials
are available, the fall back to local booting will be skipped if
-disable-local-boot is given.
I tested this successfully locally.
> image-tests: allow disabling of local booting

- cmd/osbuild-tests/main_test.go
the remaining test for composer-cli compose cancel is part of #759
> tests: composer-cli blueprints undo. Closes #615

- internal/worker/server.go
It is possible for it to end up as nil so it needs to be checked
everywhere it is used.
> worker: Check OSBuildOutput for nil before using it

- cmd/osbuild-worker/main.go
When osbuild crashes (e.g. when cp fails because of the machine running
out of disk space), it doesn't produce a machine-readable result. Due to
our suboptimal handling of the result struct (this is my fault), this can
lead to result == nil. However, composer expects that result != nil in all
cases because it uses the Success flag to assess the compose state. If
result == nil, it just crashes terribly.
> worker: ensure that the reported result is always non-nil

- golang-github-osbuild-composer.spec
- osbuild-composer.spec
The subpackages are not really meant to be used with a different version of
the osbuild-composer package. This commit enforces.the usage of a matching
version in the spec file.
> spec: make the subpackages require a matching version of composer

- test/image-tests/qemu.sh
Fedora's timeout for ssh-keyscan is short by default, but RHEL's is much
longer. Set the timeout to 5 seconds for consistency.
> Set consistent ssh-keyscan timeout

- test/cases/rhel_8.2-aarch64-tar-boot.json
- test/cases/rhel_8.2-ppc64le-tar-boot.json
- test/cases/rhel_8.2-s390x-tar-boot.json
- test/cases/rhel_8.2-x86_64-ami-boot.json
- test/cases/rhel_8.2-x86_64-openstack-boot.json
- test/cases/rhel_8.2-x86_64-qcow2-boot.json
- test/cases/rhel_8.2-x86_64-tar-boot.json
- test/cases/rhel_8.2-x86_64-vhd-boot.json
- test/cases/rhel_8.2-x86_64-vmdk-boot.json
These symlinks are no longer needed now that the testing scripts have
been adjusted.
> Remove 8.2 test case symlinks

- image-types/rhel8/microsoft-azure.md
This patch makes it easier to find the right document describing image
requirements for Linux VM images. It does not link the RHEL page
specifically because it is mainly for RHEL 6 and 7 whereas we build RHEL
8. It instead links documentation for generic Linux distribution.
> image-types: link the Azure requirements

- cmd/osbuild-image-tests/main_test.go
When osbuild fails, osbuild-composer's image tests print the output as
ugly JSON and that makes it difficult to determine why osbuild failed.
Instead, print the json in pretty format. 🌟
Fixes #782.
> Pretty print osbuild JSON on failure

- internal/distro/fedora32/distro.go
- internal/distro/rhel8/distro.go
- test/cases/fedora_32-x86_64-fedora_iot_commit-boot.json
- test/cases/rhel_8-x86_64-rhel_edge_commit-boot.json
How exactly the final file system layout looks like is determined by the installer (anaconda) and thus can not be known at commit creation time. Thus creating an `/etc/fstab` file is unnecessary and the information in it probably wrong. The file wont be used though because it will be overwritten during the installation process.
> distro/{rhel8, fedora32}: no fstab for OSTree

- osbuild-composer.spec
- schutzbot/deploy.sh
in order to catch missing dependencies
Note: I saw this as a comment somewhere in the recent pull requests.
Note2: not sure if related to the `execv()` error I'm seeing internally, more precisely why it doesn't happen in Schutzbot.
> Shutzbot: install only osbuild-composer-tests

- tools/image-info
When extracting the commit tarball as well as doing the ostree commit checkout, use `/var/tmp` instead of `/tmp`, because the latter might be backed by a tmpfs and thus by RAM; this should only be used for small files.
> image-info: use /var/tmp for bigger files/dirs

- cmd/osbuild-worker/main.go
We print messages to the log when the build fails, but we don't print
one when the build is successful.
I really want to celebrate our successes more often, so let's print a
success message when osbuild completes successfully. Since success
doesn't feel like success without an emoji, let's add one of those, too. 🎉
> Print success log line after job is done

- dnf-json
The issue was introduced in 0d3c8329c069dbb8856c6d2fc15ff42a7ff517ea.
The patch correctly changed the base exception class, but it didn't
change the unfortunate use of hardcoded type name. This patch uses
Python's internal `__name__` attribute to get the type (exception) name.
> dnf-json: change confusing error message associated with dnf errors

- cmd/osbuild-tests/main_test.go
builds on top of #642 and tries to add a quick reproducer for #524. We only need the last commit from here.
> Reproducer for 524

- cmd/osbuild-worker/main.go
composer uses the success field to decide whether a build succeeded or failed.
This is bad.
Unfortunately, fixing this requires kinda big code changes. This commit
changes the worker's behaviour to set the osbuild success flag to false
even on errors which weren't caused by osbuild (e.g. an upload error).
This is certainly hacky but I think it's still essential to tell the user
that an error occurred.
Fixes #789
> worker: set the osbuild success to false even on non-osbuild errors

- schutzbot/Jenkinsfile
- schutzbot/ci_details.sh
- schutzbot/mockbuild.sh
Use minimal images when building RPMs via mock on Fedora (PR for RHEL
will come later).
> Switch Fedora mock builds to minimal images

- schutzbot/Jenkinsfile
- schutzbot/deploy.sh
- schutzbot/mockbuild.sh
Now that we have minimal images built by osbuild-compsoer for CI, let's
use those for RHEL mock builds.
This PR depends on osbuild/osbuild-composer#808 to merge first.
> Use minimal images for RHEL mockbuild

- schutzbot/Jenkinsfile
Sometimes dnf has issues downloading RPMs or downloading the repo XML
and this breaks the mock build. Try to run the mock builds three times
before giving up.
> 🔃 Retry mock build up to 3 times

- schutzbot/assets/fedora-branched.tpl
- schutzbot/assets/fedora.repo
- schutzbot/mockbuild.sh
Now that we are using minimal images, we need to bring over the
optimized dnf repositories for Fedora.
> ⏩ Optimize mock build repos for Fedora

- osbuild-composer.spec
Conflicting makes upgrades fail, obsoletes is sufficient.
> spec: do not conflict with lorax-composer

- cmd/osbuild-image-tests/azuretest/azure.go
- cmd/osbuild-image-tests/azuretest/deployment.go
- test/azure-deployment-template.json
Previously, all resources were created with a certain tag. When the cleanup phase came, the Resources - List route\[1\] was used to get all resources with the tag. Then, they were deleted in the right order.
Sadly, the Resources - List API has issues with listing disks. Sometimes, it doesn't return the newly created disks for 15 minutes after they were created. As a result, the disks have been left behind quite often and our bill was higher than necessary.
This PR uses a different method - the Go code now knows all resource names, so it can delete all resources without listing them using the "broken" API route.
\[1\]: https://docs.microsoft.com/en-us/rest/api/resources/resources/list
> Fix azure tests leaking disks

- schutzbot/Jenkinsfile
- schutzbot/ci_details.sh
- schutzbot/mockbuild.sh
As we embark on a CI journey to other architectures, we need to be
explicit about choosing the right architecture for each CI node.
This is a portion of the work required for #834.
> 🤹🏻‍♂️  Prepare for multi-arch support

- schutzbot/Jenkinsfile
Build osbuild/osbuild-composer packages on AWS using aarch64 instances.
Another push towards getting #834  done.
> 🔨 Add aarch64 mock builds

- dnf-json
The time it takes to depsolve a blueprint varies widely depending on
where the job is running and which mirrors are randomly chosen based on
the data returned in the metalink XML.
Use dnf's fastestmirror plugin to choose the fastest mirror for
downloading metadata. This returns consistent results in PSI + AWS and
every depsolve completed in under 60 seconds after 25 tests in each
cloud.
Fixes #845.
(I also added a little flake8 cleanup in an extra patch.) 🧹
> 🏃 Enable fastestmirror in dnf-json

- .travis.yml
- cmd/osbuild-image-tests/constants/constants-travis.go
- cmd/osbuild-image-tests/constants/constants.go
- cmd/osbuild-image-tests/main_test.go
- tools/image-info
I am preparing to remove the usage of `nbd` from `image-info` but wanted to give the code a bit of a cleanup before I started doing that. See the individual commit messages for details.
> image-info: various cleanups and use loop devices instead of nbd

- schutzbot/Jenkinsfile
- schutzbot/deploy.sh
- schutzbot/mockbuild.sh
- test/cloud-init/network-config
- test/image-tests/qemu.sh
Make it easier to handle PSI outages or those times when PSI is overloaded with jobs by allowing base and integration tests to run on PSI OpenStack and AWS.
Also increase the reliability and speed of the integration tests that are booted locally by using a static IP address configuration. Keep checking for the smoke test file repeatedly without messing around with ssh key scanning. This helps when ssh comes up on an instance and then goes back down again.
Fixes #844.
Fixes #847.
> ⛅ Allow base/integration tests to run in PSI + AWS

- schutzbot/run_image_tests.sh
Bugs are being worked out in #798 and we can disable this test until
those bugs are fixed to avoid false failures in CI.
> 🚫 Temporarily disable F32 iot_commit test

- schutzbot/Jenkinsfile
In #842, we verified that our tests run on AWS properly and we should
now let Jenkins decide where to run the tests since they work in both
places.
Remove the hardcoded AWS label and allow tests to run where they please.
> 🤷🏻‍♂️ Allow tests to run on AWS and PSI

- tools/test-case-generators/generate-test-cases
generate-test-cases ignored osbuild failing before.
> generate-test-cases: stop and fail when osbuild fails

- schutzbot/Jenkinsfile
Add base aarch64 tests for Fedora 31/32 and RHEL 8 CDN.
Also restructure the pipeline so that a slow distro or slow architecture
won't hold up the faster-moving tests.
This helps a bit more with #834.
> 🦾 Add aarch64 base tests; restructure stages

- internal/weldr/api.go
- internal/weldr/api_test.go
By default, go's tar archiver uses USTAR header format. Unfortunately, this
format doesn't support sub-second resolution for ModTime. Go solves this by
*rounding* the time. Sometimes, this creates an archive containing a file
with modtime from the future. When such archive is untarred by GNU tar,
the following message is produced:
```
tar: bf548dfd-0a90-40e6-bbf2-dcdd82fcbb4e.json: time stamp 2020-07-13
13:34:31 is 0.356223173 s in the future
```
We have two options here:
1) Use gnu header format that supports sub-second resolution. Unfortunately,
it seems that not all tar archivers support this format (e.g. 7-zip).
2) The other option is to truncate the date (instead of rounding).
I went with option 2.
Also, this commit adds a test to check that the header is not from the future.
Without …
>  api/weldr: bring tars back from the future

- schutzbot/Jenkinsfile
- schutzbot/run_image_tests.sh
Support for uploading was already in, it's just needed to pass the right environment variables.
We should probably add an integration test for this but this is good enough for now and it allows us to get rid of Travis.
> schutzbot: add uploading to Azure

- internal/crypt/crypt.go
- internal/crypt/crypt_impl.go
- internal/crypt/crypt_impl_macos.go
- internal/crypt/crypt_test.go
Currently one would have to pass a `macos` flag explicitly to build on OSX, but if we replace `macos` with `darwin` this happens automatically.
> crypt: add automatic darwin support

- osbuild-composer.spec
The composer-tests use systemd-nspawn, so make sure the `*-tests` RPM
depends on `systemd-container`.
Right now this dependency is recursively fulfilled by the `osbuild`
RPM. However, this might change if we switch to `bubblewrap` as a
sandbox. Furthermore, we should not fulfill our dependencies
recursively, but list them directly.
> spec: pull in systemd-nspawn

- schutzbot/Jenkinsfile
The aarch64 tests are fairly unstable right now and they need work on
out of space issues (#870) and test cases (#861).
> 📤 Temporarily disable aarch64 tests

- schutzbot/Jenkinsfile
Now that we're going about multi-arch testing in a different way, we can
restore some of the old parallelism that we used to have in the pipeline
so it will finish faster.
> 🏇🏻 Speed up pipeline with parallelism (again)

- schutzbot/Jenkinsfile
We've come a long way and we need to triage failures that occur during
CI for the master branch. This will help us find problems with CI as
well as find other issues that could show up in a customer environment.
Also, let's send a happy notification when everything goes well. 💚
🧹 Remove the YAML files from the old Ansible tests since they are no longer needed.
> 💣 Notify via telegram on master CI failure

- internal/distro/distro_test_common/distro_test_common.go
These tests used the image type as test name, which is ambiguous. Use
the file name for the test case instead.
> distro/tests: use test case filename as test name

- internal/distro/fedora31/distro.go
- internal/distro/fedora32/distro.go
- test/cases/fedora_31-aarch64-openstack-boot.json
- test/cases/fedora_31-aarch64-qcow2-boot.json
- test/cases/fedora_31-x86_64-openstack-boot.json
- test/cases/fedora_31-x86_64-qcow2-boot.json
- test/cases/fedora_31-x86_64-qcow2-customize.json
- test/cases/fedora_32-aarch64-openstack-boot.json
- test/cases/fedora_32-aarch64-qcow2-boot.json
- test/cases/fedora_32-x86_64-openstack-boot.json
- test/cases/fedora_32-x86_64-qcow2-boot.json
- test/cases/fedora_32-x86_64-qcow2-customize.json
Previously, cloud-init was installed on qcow and openstack images but was not enabled, preventing a user from logging in to these images. Cloud-init and cloud-config services are enabled in fedora 31 and fedora 32. The image tests have been updated to reflect these changes.
> distro: enable cloud-init services for openstack and qcow2 images for fedora

- schutzbot/Jenkinsfile
- schutzbot/run_image_tests.sh
We want to deliver images directly to OpenStack during the CI tests.
Ensure the credentials are available during those tests and move them to
the proper location to be read by OpenStack tools and SDKs.
This helps with #876.
> 🔐 Add OpenStack credentials for image tests

- schutzbot/Jenkinsfile
- schutzbot/mockbuild.sh
Remove the nightly repos from the RHEL 8.3 jobs and replace them with CDN registration for beta content.
> 🐣 Use RHEL 8.3 beta content from CDN

- schutzbot/Jenkinsfile
The image tests for RHEL 8 still download packages from a server that is only available inside the Red Hat network. 😢
Opened issue #902 for this.
> 🏠 Keep RHEL 8 image tests internal only

- schutzbot/mockbuild.sh
Although rsync works just fine, it would reduce our package list if we
just used `cp` to create the latest repo.
> mockbuild: Remove rsync

- schutzbot/Jenkinsfile
Checking out the code from git during the prepare step is a waste of
time and disk space since we don't need the git repository cloned there.
> 🦘 Skip checkout on prepare

- internal/store/json.go
- internal/store/json_test.go
copy() will not append to a slice, so if the length is 0 nothing will be
copied. Initialize the slice with the length instead of the capacity.
This fixes a problem with blueprint commits vanishing when the server is
restarted.
> store: Fix copy failure when initializing blueprints commit list

- schutzbot/run_image_tests.sh
- test/cases/fedora_32-x86_64-fedora_iot_commit-boot.json
The SELinux bug has been fixed so there is no need to skip it.
> schutzbot: don't skip image test for fedora iot commit

- internal/weldr/api.go
- internal/weldr/api_test.go
The API was crashing if the freeze request was called on a non-existent
blueprint. This changes it to return an empty string, matching
lorax-composer's behavior (since the output is toml it shouldn't return
json).
> weldr: Fix out of range index for missing toml blueprint freeze

- schutzbot/mockbuild.sh
Using `cp` to copy the repo content caused the last part of the path to
be duplicated:
* Current: `master/latest/rhel82_x86_64/rhel82_x86_64/repodata/repomd.xml`
* Desired: `master/latest/rhel82_x86_64/repodata/repomd.xml`
Remove the VERSION_ID/ARCH from the destination to remove the duplicated
path.
> mockbuild: Fix path to latest repo

- schutzbot/Jenkinsfile
- schutzbot/run_image_tests.sh
- test/README.md
- test/cases/fedora_31-x86_64-openstack-boot.json
- test/cases/fedora_32-x86_64-openstack-boot.json
- test/cases/rhel_8-x86_64-openstack-boot.json
- tools/test-case-generators/format-request-map.json
this will cause the images to be uploaded and booted in our OpenStack cluster.
Note: this change is only for x86_64, not added to the aarch64 files.
> tests: Change boot type to openstack. Refs #876

- internal/weldr/api.go
- internal/weldr/api_test.go
Improve the message returned by osbuild-composer when a user asks for
logs of a compose that is still running.
> Add friendly message for logs on running build

- .github/workflows/tests.yml
For reasons unknown, golangci-lint's default 1m0s timeout is *slightly*
too short for CI runs occasionally. Extend it to 5 minutes to ensure the
job always has enough time to run.
> ⏱  Extend golangci-lint timeout to 5m0s

- distribution/osbuild-remote-worker@.service
Although the obuild-remote-worker@.service unit can be started, it can't
be enabled at boot time since the `Install` section is missing in the
unit file.
Add a small `[Install]` section with the same `WantedBy` as
osbuild-composr.service.
Fixes #924.
> Add Install section to remote worker unit file

- internal/upload/awsupload/awsupload.go
Make it easier to tell which snapshot goes with each AMI by labeling
them with a description.
> awsupload: Add description to snapshots

- cmd/osbuild-image-tests/main_test.go
- cmd/osbuild-image-tests/vmwaretest/vmware.go
- cmd/osbuild-worker/main.go
- internal/upload/vmware/vmware.go
Builds on top of #934 and updates the test to use the conversion from the worker.
> Updates around test with streamOptimized vmdk images

- schutzbot/Jenkinsfile
- schutzbot/mockbuild.sh
This branch is where we will base any backports to RHEL8.3. Start off by restricting the testing to only test against the relevant distros.
We also make sure to test against osbuild that has landed in 8.3, rather than the submodule, when we can.
> rhel8.3: restrict testing after branching

- schutzbot/Jenkinsfile
Now that we've reduced how much of our PSI quota we are using so the
OpenStack boot tests will work, we need to use AWS for jobs more often.
This should allow test runs to complete a little sooner by freeing up
PSI resources for the jobs that are only able to run there.
> ⛈  Use AWS more often for testing

- schutzbot/ci_details.sh
We are storing some data in the user's home directory, so let's print
the username so we know what that is.
In particular, this would tell us which user has been authorized to log
in via ssh.
> schutzbot/ci_details: print the username

- internal/weldr/api.go
- internal/weldr/api_test.go
Sources without URL are useless. Make it mandatory.
Fixes: https://github.com/osbuild/osbuild-composer/issues/951
> weldr: make URL mandatory part of a new source

- go.mod
- internal/boot/azuretest/azure.go
- internal/boot/azuretest/deployment.go
In order to run the clean up in a separate binary it is necessary to
refactor the clean up code away from the context manager.
> azuretest: Refactor clean up code to separate functions

- cmd/osbuild-image-tests/main_test.go
- internal/boot/aws.go
- internal/boot/helpers.go
- schutzbot/Jenkinsfile
- schutzbot/run_image_tests.sh
When using random names for artifacts like AWS snapshots, or Azure
images, it becomes hard to clean them up in case of CI failure. See this
issue for more details:
https://github.com/osbuild/osbuild-composer/issues/942
This PR introduces predictable names so that we can easily determine
which artifact belongs to which PR and therefore we can decide to wipe
all resources that are not needed any more.
> image-tests: don't use random names for CI artifacts

- schutzbot/mockbuild.sh
Running mock with verbose enabled made sense a while back when we were
still unsure if things would work, but it's generating a ton of logs now
that eventually clogs Jenkins' disk.
Disable the verbose flag to reduce mock's log output.
> 📜 mockbuild: Reduce log output

- cmd/osbuild-image-tests/main_test.go
as @teg suggests in
https://github.com/osbuild/osbuild-composer/issues/888#issuecomment-662942314
this is ON by default so we can be alerted for missing cloud
credentials in CI!
If you want to disable it then -fail-local-boot=off
> tests: Add option to fail qemu boot. Fix #888

- Makefile
- cmd/osbuild-auth-tests/main_test.go
- cmd/osbuild-composer/main.go
- golang-github-osbuild-composer.spec
- internal/kojiapi/api/api.gen.go
- internal/kojiapi/api/openapi.yml
- internal/kojiapi/server.go
- osbuild-composer.spec
- schutzbot/deploy.sh
- schutzbot/run_base_tests.sh
- test/image-tests/koji.sh
- test/image-tests/osbuild-composer.toml
This PR adds:
- list of allowed domains for both Koji and remote worker APIs. After this change, the server accepts only certificates issued to pre-defined domains.
- tests for this.
- By default, koji and remote worker APIs now use the host's trusted CAs to validate client certificates.
This is configurable in `osbuild-composer.toml` by `koji.ca` and `worker.ca` fields. These accept a path to a certificate that should be used to the validation instead of the default ones. If there's a need for using multiple certificates, it's possible to just append them to one file. (`cat cert1.pem cert2.pem > /etc/osbuild-composer/ca-crt.pem`)
What's still missing:
- wildcards for allowed domains (nice to have)
- SAN certificates for tests. Currently, only certificates with common names are used. This …
> Add domain allowlist to remote worker and Koji APIs

- cmd/osbuild-composer-cloud/main.go
- cmd/osbuild-composer/main.go
- internal/cloudapi/server.go
- internal/kojiapi/server.go
- internal/weldr/api.go
- internal/worker/api/api.gen.go
- internal/worker/api/openapi.yml
- internal/worker/client.go
- internal/worker/json.go
- internal/worker/server.go
- internal/worker/server_test.go
This is an effort to future-proof the worker API. It removes the assumption that all jobs are osbuild jobs and requires a worker to pass both the jobs it can handle and the architecture it runs on.
> worker API: introduce job types and architecture

- schutzbot/deploy.sh
Tom says this shouldn't be started unconditionally because most
of the tests don't need it. In fact it isn't even available in
RHEL trees.
> Start osbuild-composer-koji.socket only if installed

- cmd/osbuild-composer/composer.go
- cmd/osbuild-composer/config.go
- cmd/osbuild-composer/config_test.go
- cmd/osbuild-composer/main.go
- cmd/osbuild-composer/testdata/test.toml
`main.go` was quite unwieldy and hard to see what's going on. This series of patches try to clean it up a bit, mainly by splitting running the actual service into its own file.
This has the additional benefit that it is a step towards running osbuild-composer in an environment different than what systemd sets up (:wave: @major).
> osbuild-composer: cleanup main.go

- golang-github-osbuild-composer.spec
- osbuild-composer.spec
- schutzbot/run_base_tests.sh
- schutzbot/run_image_tests.sh
- test/cmd/aws.sh
- test/cmd/koji.sh
- test/cmd/ostree.sh
- test/cmd/qemu.sh
The -test subpackage should depend on all that it needs, and we should
never need to install anything explicitly from the test scripts.
> test: depend on rpms rather than installing them explicitly

- HACKING.md
- tools/deploy-qemu
- tools/deploy/test/files/run/provision-scripts/deploy.sh
- tools/deploy/test/files/run/provision-scripts/provision.sh
- tools/deploy/test/user-data.yml
- tools/gen-user-data
tools/gen-user-data generates a cloud-init user-data file from a
configuration directory. It is mostly useful to embed files in the
user-data.
tools/deploy-qemu uses above tool to make a user-data file and spins up
a virtual machine with it. This is useful to locally run, test, and
debug osbuild-composer.
A simple user-data directory for running tests locally is included in
tests/deploy-user-data. It expects a repository with osbuild-composer
rpms to be served on the host's port 8000.
> tools: add deploy-qemu and gen-user-data

- schutzbot/deploy.sh
I broke master by merging #1021 - ansible and koji are not in the official
RHEL repositories so we need to enable epel on RHEL to be able to get them.
> test: enable epel on RHEL

- osbuild-composer.spec
Lorax-composer won't be shipped into Fedora 34. To upgrade users from it to osbuild-composer we need to obsolete it in our spec file.
Fixes RHBZ#1886405
> spec: obsolete lorax-composer in Fedora 34

- internal/kojiapi/api/api.gen.go
- internal/kojiapi/api/openapi.yml
- internal/kojiapi/server.go
- tools/koji-compose.py
The kojiapi shouldn't require it as we need to build images from
unsigned packages.
Fixes #985
> kojiapi: make repo gpgkey optional

- test/cmd/ostree.sh
The previously used repo doesn't exist anymore making this test fail with:
Error validating install location: Could not find an installable distribution
at 'http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.3/compose/BaseOS/x86_64/os/':
The URL could not be accessed, maybe you mistyped?
Let's switch to a releng repo that shouldn't be deleted.
> test/ostree: use releng repo instead of nightly for rhel8.3

- internal/kojiapi/server.go
- internal/kojiapi/server_test.go
Add a simple unit test for the koji API.
This adds a Handler() method to the koji.Server struct, which made
writing the test easier. This is a direction we want to go in anyway in
the future.
> kojiapi: add simple test for the /status API

- osbuild-composer.spec
See individual commits.
I would introduce a test building our package in ELN using `mock` but `mock` with ELN target seems to be currently broken. I already asked for help in fedora devel channel.
There's at least a manual ELN scratch build: https://koji.fedoraproject.org/koji/taskinfo?taskID=53369289
Fixes rhbz#1884383
> Fix osbuild-composer in ELN

- cmd/cloud-cleaner/main.go
- cmd/osbuild-image-tests/main_test.go
The issue comes from the fact that the PR introducing it was very old
and meanwhile the variable used for image name creation has changed.
This patch makes sure both functions are the same.
> ci: fix artifact name generation in cloud cleaner

- .gitignore
- Makefile
Currently, we have osbuild-image-tests binary committed in the master branch. IMHO the root cause is that we don't have it in .gitignore. Actually, I think that it is pretty hard to keep .gitignore in sync with the build target.
This commit solves the situation by putting all the built binaries into bin directory and adding this directory into .gitignore. This way, it's much harder to actually commit a new Go binary into the repository.
This commit doesn't remove the binary as #1017 already does that.
We don't want to merge this before #1017
> make: put all binaries into bin directory

- schutzbot/run_cloud_cleaner.sh
`CHANGE_ID` bug strikes for the 3rd time :-/. Hope this is the last one. Recursive grep does not show any other usage:
```
$ rg CHANGE_ID
$
```
> schutzbot/run_cloud_cleaner: pass BRANCH_NAME instead of CHANGE_ID

- HACKING.md
Yesterday, I spent more hours than I would like to admit debugging tests that
was failing because the Fedora cloud base image has only 4 GB disk space.
This commit adds a note for the future me.
> docs/HACKING: add a note about how to grow the image

- DEPLOYING.md
- HACKING.md
- tools/deploy-openstack
Similar to deploy-qemu, but deploys into an OpenStack cluster. It uses
the same logic for user-data.
No downstream testing is necessary for this commit, as it doesn't change *osbuild-composer* itself.
> Add tools/deploy-openstack

- tools/run-koji-container.sh
docker.io has recently introduced a rate limiting on container pulls causing the koji test to fail quite often.
To fix this issue, I created our own postgres mirror\[1\]. This commit switches the Koji test to use it. Note that this change bumps the postgres version from 12 to 13.
\[1\]: https://github.com/osbuild/containers/commit/7db3c6802ebe434129dfc5cd37e7dced329cfe88
> koji/test: use our quay mirror of the postgres container

- test/cases/koji.sh
- test/cases/ostree.sh
We don't install any packages in test cases anymore, therefore we don't need to install EPEL there.
A slightly different explanation:
osbuild-composer-tests depends on packages from EPEL on RHEL. Therefore, you cannot run the test cases without EPEL installed. Therefore, there's no point in installing EPEL there.
> test: don't install epel in test cases

- schutzbot/Jenkinsfile
- test/cases/base_tests.sh
We claim to have self-contained test cases, but the base_tests.sh script
still requires the WORKSPACE environment variable to be set outside of
the script, which is what Jenkins does.
This patch introduces a default value, which makes it possible to use
the script outside of Jenkins.
> base_tests.sh: make the test self-contained

- test/cases/aws.sh
- test/cases/qemu.sh
The integration tests are leaving the composes (which include images) in osbuild-composer. This can lead to exhausting the disk space we have available on our tiny testing machines. This commit adds a removal of the composes after each integration test is finished. This issue is not present in koji.sh and api.sh as they use different osbuild-composer APIs that don't use the artifact feature.
This issue occurred when I worked on enabling the Fedora 33 tests, see:
https://osbuildci.cloud.paas.psi.redhat.com/blue/organizations/jenkins/osbuild%2Fosbuild-composer/detail/PR-1014/23/pipeline
> test/integration: delete composes after we're done

- distribution/osbuild-composer-koji.socket
- osbuild-composer.spec
Remove both the package osbuild-composer-koji, and the only file it
shipped: osbuild-composer-koji.socket.
It's been deprecated since 835b556, but the backwards-compatible
solution in that commit never worked, because osbuild-composer only
checks for "osbuild-composer-api.socket" when starting up.
Since this has been meant to be deprecated for a while, just remove it
outright.
Add an "Obsoletes:" for the package, so that it gets uninstalled on
existing systems.
> distribution: remove osbuild-composer-koji

- schutzbot/mockbuild.sh
Please see individual commits. The main point is to make it easier to use the resulting URLs, without having to look at the log of a previous Jenkins run.
> mockbuild: make repository URLs more predictable

- schutzbot/Jenkinsfile
- schutzbot/deploy.sh
- schutzbot/mockbuild.sh
Now that the repository URLs are predictable, don't use Jenkins' stash
feature to pass the repo file between stages.
Instead, simply create the repo file where it is needed, in deploy.sh.
> schutzbot: don't copy dnf repo file between stages

- .github/workflows/tests.yml
- Makefile
- osbuild-composer.spec
#1070 introduced an `rpmlint` error. This PR fixes it. Also, it fixes a couple of other minor issues and introduces a new Github workflow that runs `rpmlint` against our upstream spec file. This should solve the issue with `rpmlint` errors once and forever.
Fixes #1076
> Fix spec file and introduce rpmlint

- cmd/osbuild-composer/composer.go
- internal/jobqueue/fsjobqueue/fsjobqueue.go
- internal/jobqueue/fsjobqueue/fsjobqueue_test.go
- internal/kojiapi/server_test.go
Soon, we want to begin tagging the jobs with the name of its submitter. The simplest way to add a tag to a job is to put it into its type string. However, as we don't know (and don't want to know) the submitters' names when osbuild-composer is initialized, we need to be able to push arbitrary job types into the jobqueue.
This commit therefore lifts the restriction that a jobqueue accepts only a predefined set of job types. Now, jobqueue clients can push jobs of arbitrary names.
> fsjobqueue: accept jobs of any type

- osbuild-composer.spec
osbuild-composer doesn't actually require osbuild. osbuild-composer-worker does. Let's remove the dependency from osbuild-composer and depend on the right version of osbuild in the worker.
> spec: fix the osbuild dependency

- cmd/osbuild-worker/jobimpl-koji-finalize.go
- cmd/osbuild-worker/jobimpl-koji-init.go
- cmd/osbuild-worker/jobimpl-osbuild-koji.go
- internal/kojiapi/server.go
- internal/kojiapi/server_test.go
- internal/worker/json.go
Serializing an interface does not work, let us simply use the string
representation and treat the empty string as no error. This is
compatible with the current API in the success case, and fixes the
error case, which is currently broken.
Also extend the test matrix for the kojiapi to ensure that all the
different kinds of errors can be serialized correctly and leads to
the correct status being returned.
> workerapi: serialize koji errors as stringss

- Makefile
- schutzbot/mockbuild.sh
Running `make srpm` on the host can have different results from building
the SRPM in mock.
Stop using the Makefile altogether for this, which is meant for
developer convenience only. The interface is clear: a tarball generated
from `git archive` and defining the `commit` variable. Less stuff to
install on the host, too.
Also includes a commit simplifying the way we `make rpm`.
> mockbuild: use mock to build source rpm

- cmd/osbuild-composer/composer.go
- cmd/osbuild-composer/main.go
- distribution/osbuild-composer.service
- distribution/osbuild-composer.socket
- distribution/osbuild-local-worker.socket
- distribution/osbuild-remote-worker.socket
- distribution/osbuild-worker@.service
- osbuild-composer.spec
I think we should be able to ditch the local worker altogether. This is the first step. See the individual comments for details.
> Allow osbuild-composer to run without Weldr API

- .github/workflows/tests.yml
As the team obsessed with immutable test dependencies, how could we use the ubuntu-latest VM which can change at any time?
Speaking of changes to ubuntu-latest... It will soon be updated from ubuntu 18.04 to 20.04 \[1\].
This commit switches our testing pipeline to use ubuntu-20.04 to:
1) make our test dependencies immutable (or at least slightly more immutable)
2) make us prepared for the ubuntu-latest changes.
\[1\]: actions/virtual-environments#1816
>  .github: switch to ubuntu-20.04

- cmd/osbuild-composer/composer.go
- internal/kojiapi/server_test.go
- internal/worker/server.go
- internal/worker/server_test.go
The previous code was smelling a bit (e.g. Server.server field) so I decided
to rewrite it in the style of the much nicer koji server.
Not a functional change.
> worker/server: move it to the style of koji server

- Schutzfile
- schutzbot/Jenkinsfile
- schutzbot/deploy.sh
Now that koji-osbuild pushes rpms for (most) commits in the same format as osbuild and osbuild-composer, it is trivial to add reverse dependency tests for it. 🎈
> Add ability to run reverse dependency tests, and run one for koji-osbuild

- tools/deploy-qemu
- tools/gen-user-data
Also, add a `QEMU_EXTRA_ARGS` environment variable for people to set arguments from their `bashrc` (or similar) that better suit their workflow.
> tools/deploy-qemu: add macOS support 

- internal/cloudapi/openapi.gen.go
- internal/cloudapi/openapi.yml
- internal/cloudapi/server.go
Previously, baseurl was required in openapi.yaml. In order to add support for metalink 
and mirrorlist repos as well, make all optional, since openapi does not support mutually 
exclusive parameters. Instead, enforce this logic in server.go, and if no repo has been 
specified, return a 400 bad request error.
> cloudapi: add support for mirrorlist and metalink repos

- schutzbot/Jenkinsfile
22c9f6a introduced a new environment variable to api.sh,
AWS_API_TEST_SHARE_ACCOUNT, but only set it in the RHEL 8 tests.
Seems like the corresponding branch was not rebased to a version which
already had those 8.4 tests:
https://github.com/osbuild/osbuild-composer/pull/1098
> schutzbot: add required env variable to 8.4 integration test

- Schutzfile
This includes a fix for a recent test failure:
https://github.com/osbuild/koji-osbuild/pull/53
> Schutzfile: bump koji-osbuild reverse dependency

- internal/distro/rhel84/distro.go
- test/data/manifests/rhel_84-x86_64-qcow2-boot.json
- test/data/manifests/rhel_84-x86_64-qcow2-customize.json
The default size of RHEL 8 qcow2 images is 10 GiB, let's align our default.
Related: rhbz#1846087
> distro/rhel8*: change the default size of qcow2 to 10 GiB

- internal/kojiapi/server.go
- internal/worker/server.go
Previously, we had no clue what errors were caught by the default echo's error handler. Thus, in the case of an error, we were basically blind. Let's log all errors so we can investigate them later.
> {koji,worker}/server: log errors returned from handlers

- internal/kojiapi/server.go
Previously, the compose status returned failure as soon as possible. koji-osbuild considers the job as done when its status == failure and proceeds with uploading the logs to koji and marking the job as failed. However, not all osbuild-composer jobs might be done at this point so the logs might be incomplete making the debugging hard.
This commit changes the behaviour: Now, the compose status is pending until ALL jobs belonging to it are finished.
> api/koji: return pending status until all jobs are finished

- .gitmodules
64432c70 promised to remove it but this didn't actually happen. We don't use the submodule anymore so let's indeed drop it this time.
> drop the osbuild submodule

- internal/distro/rhel84/distro.go
- test/data/manifests/rhel_84-x86_64-ami-boot.json
- test/data/manifests/rhel_84-x86_64-openstack-boot.json
- test/data/manifests/rhel_84-x86_64-qcow2-boot.json
- test/data/manifests/rhel_84-x86_64-qcow2-customize.json
- test/data/manifests/rhel_84-x86_64-vhd-boot.json
- test/data/manifests/rhel_84-x86_64-vmdk-boot.json
The RHEL 8.4 specific runner was introduced in osbuild 22, released on the 8th of October 2020. It should by now be in relevant Fedora releases and RHEL 8.4.
> distro/rhel84: use the org.osbuild.rhel84 runner

- internal/distro/rhel84/distro.go
- internal/distro/rhel84/distro_test.go
- test/data/manifests/rhel_84-x86_64-ami-boot.json
- test/data/manifests/rhel_84-x86_64-openstack-boot.json
- test/data/manifests/rhel_84-x86_64-qcow2-boot.json
- test/data/manifests/rhel_84-x86_64-qcow2-customize.json
- test/data/manifests/rhel_84-x86_64-vhd-boot.json
- test/data/manifests/rhel_84-x86_64-vmdk-boot.json
rng-tools is no longer included as a package in the RHEL 8.4 image. This package is both removed from being an included package and also specifically declared as excluded. The test manifests are updated.
I am unsure why rng-tools needs to be explicitly declared as excluded. But, when I just removed it from the included packages list, it was still getting added to the manifest. I tried running `dnf repoquery --whatdepends` to see what might be pulling it in but that didn't reveal anything. If anyone has thoughts on this I'd appreciate the info.
> distro/rhel84: remove rng-tools

- osbuild-composer.spec
Build the `osbuild-composer(7)` man-page as part of the RPM build and include it in the osbuild-composer RPM. Previously the man-page was not shipped at all in any of the produced RPMs. I found out about the problem, because `README.md` refers to the man-page.
> spec: build & install osbuild-composer(7) man-page

- internal/distro/rhel84/distro.go
- test/data/manifests/rhel_84-x86_64-ami-boot.json
- test/data/manifests/rhel_84-x86_64-qcow2-boot.json
- test/data/manifests/rhel_84-x86_64-qcow2-customize.json
The kernel options are updated to remove the read only option "ro" from all image types that had it set. Also, the qcow2's kernel options are updated to only set console=ttyS0 once. It was declared twice which is redundant so now it is set for both tty0 and ttyS0.
> distro/rhel84: update kernel options

- cmd/osbuild-pipeline/main.go
- cmd/osbuild-store-dump/main.go
- internal/cloudapi/server.go
- internal/disk/disk.go
- internal/distro/distro.go
- internal/distro/distro_test_common/distro_test_common.go
- internal/distro/fedora32/distro.go
- internal/distro/fedora33/distro.go
- internal/distro/fedoratest/distro.go
- internal/distro/rhel8/distro.go
- internal/distro/rhel84/distro.go
- internal/distro/test_distro/distro.go
- internal/kojiapi/server.go
- internal/store/fixtures.go
- internal/store/store_test.go
- internal/weldr/api.go
- internal/weldr/api_test.go
- internal/worker/server_test.go
- test/data/manifests/rhel_84-x86_64-ami-boot.json
- test/data/manifests/rhel_84-x86_64-openstack-boot.json
- test/data/manifests/rhel_84-x86_64-qcow2-boot.json
- test/data/manifests/rhel_84-x86_64-qcow2-customize.json
- test/data/manifests/rhel_84-x86_64-vhd-boot.json
- test/data/manifests/rhel_84-x86_64-vmdk-boot.json
Imagine this situation: You have a RHEL system booted from an image produced
by osbuild-composer. On this system, you want to use osbuild-composer to
create another image of RHEL.
However, there's currently something funny with partitions:
All RHEL images built by osbuild-composer contain a root xfs partition. The
interesting bit is that they all share the same xfs partition UUID. This might
sound like a good thing for reproducibility but it has a quirk.
The issue appears when osbuild runs the qemu assembler: it needs to mount all
partitions of the future image to copy the OS tree into it.
Imagine that osbuild-composer is running on a system booted from an image
produced by osbuild-composer. This means that its root xfs partition has this
uuid:
efe8afea-c0a8-45dc-8e6e-499279f6fa5d
When …
> distro/rhel84: use a random uuid for XFS partition

- internal/cloudapi/server.go
- internal/kojiapi/server.go
- internal/weldr/api.go
I thought rand in Go is auto-seeded but I was wrong, see \[1\].
This commit adds seed initialization.
\[1\]: https://golang.org/pkg/math/rand/#Seed
> composer: seed the random number generator

- containers/osbuild-composer/Dockerfile
- containers/osbuild-composer/entrypoint.py
- schutzbot/Jenkinsfile
- schutzbot/containerbuild.sh
Add a Dockerfile that creates a container based on Fedora with
osbuild-composer deployed. Create a suitable entrypoint that runs
osbuild-composer in the container and creates the required sockets
without systemd.
To test this, build the container via:
docker build ./containers/osbuild-composer
Then create your certificates in /etc/osbuild-composer/. Then run
composer with something like:
docker run --rm -v /etc/osbuild-composer:/etc/osbuild-composer <id>
(Where <id> is the container ID returned by `docker build`.)
Note that this container is not yet hooked up to anything. Furthermore,
it might need adjustments to be ready for deployment. This is mostly a
proof-of-concept that shows how to deploy Composer in a container.
> containers: add containerized osbuild-composer

- Schutzfile
- osbuild-composer.spec
- schutzbot/deploy.sh
- tools/provision.sh
koji and ansible are not in RHEL repositories. Depending on them breaks RHEL gating (see OSCI-1541): It tries to build a custom image with -tests package in it but in the build environment there's no EPEL.
This commit makes the RPM independent from EPEL. However, we still need koji and ansible, so the provision script now enables EPEL and installs the packages from there. This is not nice but we have to live with that until OSCI-1541 is solved.
> tests: move the epel dependencies to provisioning

- internal/cloudapi/server.go
- internal/kojiapi/server.go
When rpmmd's Depsolve function is called we need to pass in the image type's excluded packages. These excluded packages are retrieved when we get the packages we include from each image type.
This should fix the issue we've been seeing with brew builds including excluded packages such as firewalld.
Thanks @ondrejbudai for the help figuring this out!!
> kojiapi,cloudapi: exclude packages when depsolving

- tools/deploy-qemu
When the deploy-qemu script is run with less than 2 arguments, it ended
with error, instead of printing usage. This was due to using 'set -u' and
trying to expand unset variables "$1" and "$2" as part of checking if
they were provided. The issue has been fixed by checking number of
provided arguments, instead of their content. The same approach is used
in 'deploy-openstack' script.
> tools: Fix checking of args number in deploy-qemu script

- cmd/osbuild-image-tests/constants/constants.go
- test/README.md
The directory with image-tests test cases has been renamed from `cases`
to `manifests`. This has not been previously reflected in the test/README.md
and osbuild-image-tests code. osbuild-image-tests hardcodes the test
cases directory path and uses it in case no test case are passed
to it on the command line. Since the image_tests.sh CI test case looks
for image-tests test cases in the correct directory and passes the
relevant ones to osbuild-image-tests, the CI didn't detect this issue.
Running osbuild-images-tests without any argument and let it run all
test cases from the default test cases directory as part of CI probably
does not make sense. Due to this reason, I'm not adding any new test.
>  🖼️ test/image: Fix test cases directory path in doc and code

- internal/distro/rhel84/distro.go
- test/data/manifests/rhel_84-x86_64-ami-boot.json
- test/data/manifests/rhel_84-x86_64-openstack-boot.json
- test/data/manifests/rhel_84-x86_64-qcow2-boot.json
- test/data/manifests/rhel_84-x86_64-vhd-boot.json
- test/data/manifests/rhel_84-x86_64-vmdk-boot.json
RHEl 8.4 guest images need to have the default time zone of EST/EDT unless the user specifies one in their blueprint. New York is a major location for this time zone.
> distro/rhel84: use New York as default timezone

- internal/distro/rhel84/distro.go
Our s390x images now use the kernel commandline options set in the image type's declaration.
This should fix the missing kernel cmdline args pointed out by Wei Shi.
> distro/rhel84: fix s390x kernel options

- internal/distro/rhel84/distro.go
RootFsUUID should be the UUID of a root filesystem, not of a root partition.
🤦 sorry!
> rhel84: fix kernel cmdline for s390x

- .github/PULL_REQUEST_TEMPLATE.md
- docs/news/README.md
As we discussed last year. I really liked @ondrejbudai's idea of collecting release note entries for unreleased stuff in `docs/news`.
I've kept the checklist short for now. Suggestions for more items are very welcome :)
> Introduce docs/news and start a checklist in the PR template

- image-types/rhel8/amazon-ec2.md
- image-types/rhel8/kvm-guest-image.md
Updated RHEL-8 KVM and EC2 images information.
Updates in KVM image type:
- Updated the intended use of this image type, based on discussion with Virt PM.
- Added note about the most common way to consume official Red Hat content using this image type.
Updates in EC2 image type:
- Added note about the most common way to consume official Red Hat content using this image type.
> image-types: Updated RHEL-8 KVM and EC2 images information

- schutzbot/Jenkinsfile
With our limited number of machines in OpenStack, we cannot run unlimited jobs
in parallel. When there's a lot of activity in the repository, there's a high
probability that a job must wait for a free VM for quite a long time. In these cases,
tests commonly fail due to the timeout.
I decided to prolong the timeout to 12 hours. This should lower the amount of
these kinds of jobs.
> schutzbot: prolong the timeout to 12 hours

- internal/jobqueue/fsjobqueue/fsjobqueue.go
- internal/jobqueue/fsjobqueue/fsjobqueue_test.go
- internal/jobqueue/jobqueue.go
- internal/kojiapi/api/api.gen.go
- internal/kojiapi/api/openapi.yml
- internal/kojiapi/server.go
- internal/kojiapi/server_test.go
- internal/worker/server.go
- internal/worker/server_test.go
Added an API endpoint that returns the manifest for a given osbuild-koji job.
The Koji API function assumes that the second dependency of the incoming job ID (which should match a Finalize Job) is the first (and perhaps only) Build Job. It retrieves the arguments of the Build Job to extract the Manifest.
The tests cover basic (non-failing) cases for now. More notable is that in all test cases the manifest is empty, which isn't very interesting.
Closes #996.
> Koji: Retrieve the Manifests for a compose job

- docs/news/unreleased/koji-manifests.md
- internal/jobqueue/fsjobqueue/fsjobqueue.go
- internal/jobqueue/fsjobqueue/fsjobqueue_test.go
- internal/jobqueue/jobqueue.go
- internal/kojiapi/server.go
- internal/kojiapi/server_test.go
- internal/worker/server.go
- internal/worker/server_test.go
*Not sure if it's adequate, but it covers some error conditions as well as successful calls.*
This PR replaces the recently introduced `JobArgs()` method of the `JobQueue` interface (see #1155) with a more general `Job()` method that returns all the arguments that were supplied to the `Enqueue()` method: `jobType`, `args`, and `dependencies`.
Having access to the `jobType` makes it possible to validate the type when reading jobs from the queue, which is relevant for the Koji API.
The Koji API now includes convenience methods for reading each job type from the queue, resulting in errors if the ID doesn't match the expected type.  A downside to these functions is that it becomes harder to distinguish between an ID that doesn't exist in the queue and a type …
> Jobqueue: get all job parameters

- internal/upload/awsupload/awsupload.go
- test/cases/aws.sh
Adding the tag called `Name` to the AMI ensures that the name appears in
the *Name* column inside AWS' web console.
Fixes #1171.
> Apply tags to registered AMI

- docs/news/unreleased/timedatex.md
- internal/distro/rhel84/distro.go
- test/data/manifests/rhel_84-x86_64-qcow2-boot.json
- test/data/manifests/rhel_84-x86_64-qcow2-customize.json
timedatex was an exlcuded package due to an selinux-policy issue. This
issue is resolved and timedatex is no longer excluded.
I do not believe this has adequate documentation about the change but I am unsure where I would document our package list.
> distro/rhel84: include timedatex in qcow2 image

- HACKING.md
- distribution/.env
- distribution/Dockerfile-ubi
- distribution/Dockerfile-worker
- distribution/docker-compose.yml
- osbuild-composer.spec
- tools/gen-certs.sh
- tools/provision.sh
Adding *osbuild-composer-worker* Dockerfile (`Dockerfile-worker`) and a `docker-compose.yml` file that makes it straightforward to set up a multi-container environment.  This is a lot faster than building RPMs and installing them in VMs for when you need to do quick compile-debug cycles.
The biggest change to existing tools is the SSL certificate generation script: I've moved the cert generation parts from `tools/provisioning.sh` into a new file (`tools/gen-certs.sh`).  The original workflow that uses this script should be unaffected, but having the cert generation separate makes it easy to quickly create certificates and keys in any directory using the `openssl.cnf` file from any location.
I added a section to HACKING.md that explains how to get the Docker setup up and running.  The …
> Docker-compose and Dockerfile for worker container

- test/README.md
- tools/deploy/gen-test-data/files/run/provision-scripts/deploy.sh
- tools/deploy/gen-test-data/user-data.yml
- tools/test-case-generators/distro-arch-imagetype-map.json
- tools/test-case-generators/generate-all-test-cases
Add the `generate-all-test-cases` tool, which generates all defined image
test cases based on provided "distro x arch x image-type" combination
matrix and CLI arguments. Test cases are generated by running the
`generate-test-cases` tool inside an architecture-specific VM.
The tool requires a qcow2 image to be provided for each requested
architecture. These images are used to create ephemeral VMs used
for test case generation.
There appears to be an issue with entropy on all VMs for other
architecture than the host's one. It makes the generation of the first
test case usually fail due to the `go get` command failing with a "TLS
handshake timeout" error. There is a workaround to retry the generation
of a test case a maximum of 3 times in this case. In the usual case,
the test case …
> [RFC] tools: Add script to generate all test cases in VMs

- docs/news/unreleased/rhel84-differences-fixed.md
- internal/distro/rhel84/distro.go
- test/data/manifests/rhel_84-x86_64-qcow2-boot.json
- test/data/manifests/rhel_84-x86_64-qcow2-customize.json
`rng-tools` was added back into the qcow2 packages by mistake. It should be an excluded package and `rngd.service` should not be enabled. After #1178 `rng-tools` won't need to be an excluded package since it won't be included by `@core` but it is easiest to explicitly exclude it for now.
> distro/rhel84: remove rng-tools from qcow2

- test/data/manifests/fedora_32-x86_64-fedora_iot_commit-boot.json
- test/data/manifests/fedora_33-x86_64-fedora_iot_commit-boot.json
- test/data/manifests/rhel_8-aarch64-rhel_edge_commit-boot.json
- test/data/manifests/rhel_8-x86_64-rhel_edge_commit-boot.json
- tools/image-info
The algorithm from calculating changed in osbuild 24, thus breaking the
testsuite. As the the inputhash is merely a implementation detail, there's
no need to test it in the image tests. Nevertheless, the inputhash is also
tested in the osbuild's testsuite.
This is a minor change of the test suite, both items are not needed imho.
> image-info: do not include inputhash in the report

- cmd/osbuild-worker/jobimpl-osbuild.go
- internal/cloudapi/openapi.gen.go
- internal/cloudapi/openapi.yml
- internal/cloudapi/server.go
- internal/worker/json.go
- test/cases/api.sh
Expose a more detailed job status result - specifically, include upload status alongside
image status. Expand openapi.yml accordingly and add an UploadStatus field to the 
OSBuildJobResult struct. At the moment, only represent the "success" and "failure" states 
of UploadStatus - to differentiate between "pending" and "running" would involve significant 
design decisions and should be addressed in a separate commit.
> cloudapi: expose upload status

- test/data/manifests/fedora_32-x86_64-qcow2-customize.json
- test/data/manifests/fedora_33-x86_64-qcow2-customize.json
- test/data/manifests/rhel_8-x86_64-qcow2-customize.json
- test/data/manifests/rhel_84-x86_64-qcow2-customize.json
- tools/test-case-generators/generate-test-cases
The test case generation script contained a typo in the blueprint
customizations dictionary: "hosname" instead of "hostname".
Fixed typo and regenerated relevant test cases.
> image-tests: fix hostname typo in customizations

- README.md
- Schutzfile
- docs/news/unreleased/osbuild-24.md
- docs/news/unreleased/sysconfig.md
- internal/distro/rhel84/distro.go
- internal/osbuild/sysconfig_stage.go
- internal/osbuild/sysconfig_stage_test.go
- osbuild-composer.spec
- test/data/manifests/rhel_84-x86_64-ami-boot.json
- test/data/manifests/rhel_84-x86_64-openstack-boot.json
- test/data/manifests/rhel_84-x86_64-qcow2-boot.json
- test/data/manifests/rhel_84-x86_64-qcow2-customize.json
- test/data/manifests/rhel_84-x86_64-vhd-boot.json
- test/data/manifests/rhel_84-x86_64-vmdk-boot.json
- tools/image-info
The org.osbuild.sysconfig stage is now supported. Config updates can be made to the kernel and network files. Currently, only the default values are used for all image types in rhel84. The image-info script is updated to allow testing the sysconfig info.
The default values are:
```
kernel:
UPDATEDEFAULT=yes
DEFAULTKERNEL=kernel
network:
NETWORKING=yes
NOZEROCONF=yes
```
> Add sysconfig stage

- .github/workflows/tests.yml
- schutzbot/send_webhook.py
We can now send webhook data to an SQS queue at AWS without signing the
request with credentials. This allows us to trigger Schutzbot from
forks and from branches on the main repository.
> Send webhooks without credentials

- HACKING.md
Small typo spotted in env variable
> HACKING: Minor typo fix

- docs/news/unreleased/cloudapi-packages.md
- internal/cloudapi/openapi.gen.go
- internal/cloudapi/openapi.yml
- internal/cloudapi/server.go
- test/cases/api.sh
Optionally allow a pacakge set to be included in the compose request.
The specified packages are added to the base packages before
depsolving. As the base packages differ between the image types
the package customizations may have different results on the different
images part of the compose request.
> cloudapi: add support for additional packages

- internal/distro/rhel84/distro.go
dbxtool is not available on s390x or ppc64le. So, it cannot be included for now without breaking image builds for these architectures.
It seems that dbxtool will be installed without the explicit declaration since the regenerating the test manifests for x86_64 did not remove it. I am unsure why it was missing in the image-info for the nightly I was comparing the package list for.
> distro/rhel84: remove dbxtool

- docs/news/unreleased/ostree-kernel-append.md
- internal/distro/fedora32/distro.go
- internal/distro/fedora32/distro_test.go
- internal/distro/fedora33/distro.go
- internal/distro/fedora33/distro_test.go
- internal/distro/rhel8/distro.go
- internal/distro/rhel8/distro_test.go
- internal/distro/rhel84/distro.go
- internal/distro/rhel84/distro_test.go
Kernel boot parameters have no effect on ostree type images (Fedora IoT and RHEL for Edge; see #1210).  With this PR, we catch this and fail early in the pipeline creation and communicate the issue to the user.
> Fail early for ostree compose with kernel boot parameters

- test/cases/api.sh
Customizations should be alongside image_requests, not inside of it.
> test: Fix the compose request in the api test case

- test/data/manifests/rhel_84-aarch64-ami-boot.json
- test/data/manifests/rhel_84-aarch64-openstack-boot.json
- test/data/manifests/rhel_84-aarch64-qcow2-boot.json
- test/data/manifests/rhel_84-aarch64-rhel_edge_commit-boot.json
- test/data/manifests/rhel_84-aarch64-tar-boot.json
- test/data/manifests/rhel_84-ppc64le-qcow2-boot.json
- test/data/manifests/rhel_84-ppc64le-tar-boot.json
- test/data/manifests/rhel_84-s390x-qcow2-boot.json
- tools/test-case-generators/distro-arch-imagetype-map.json
- This PR is adding only tests
- This is internal-only change, not visible to user, thus no documentation has been added.
Add RHEL-8.4 image test case manifests for all architectures. The set of
image types per architecture is based on what is currently available for
RHEL-8.3.
The image test case for RHEL-8.4 tar image on s390x is not added yet
because of Issue #1220.
Fixes #1167
> image-tests: Add RHEL-8.4 test cases for all architectures

- internal/weldr/api.go
I didn't include testing or documentation because it's a string meant to be read by the user when trying to freeze a blueprint that doesn't exist.
> weldr: Remove underscores from FreezeHandler error

- .github/workflows/tests.yml
When unit tests succeed, no one cares about them.
When unit tests fail, it's hard to find which one failed. This commit removes
the verbose flag, so it's easy to spot what failed.
Both irrelevant.
> ci: do not run the unit tests with verbose on

- test/cases/api.sh
This is a merge race condition. Sanne added a new variable, I added a new distro.
both irrelevant
> test/api.sh: set the username for centos-8

- schutzbot/Jenkinsfile
Currently, all PRs trigger the daily nightly testing. Let's limit that to just the main branch.
I found this here:
https://stackoverflow.com/questions/39168861/build-periodically-with-a-multi-branch-pipeline-in-jenkins
both irrelevant
> ci: run the nightly test only on the main branch

- schutzbot/Jenkinsfile
https://github.com/osbuild/osbuild-composer/pull/1228 was merged with
a failing Schutzbot's pipeline. The failure is caused because `var` apparently
isn't a right Groovy syntax. Let's use the right word `def` instead.
> schutzbot: fix the pipeline

- cmd/osbuild-worker/jobimpl-osbuild.go
- docs/news/unreleased/vmware-upload-target.md
- internal/target/target.go
- internal/target/vmware_target.go
- internal/upload/vmware/vmware.go
- internal/weldr/upload.go
- schutzbot/Jenkinsfile
- test/cases/vmware.sh
Add upload target for VMWare images to weldr API to allow users to push them directly to their vSphere instance without the need to download and push the image manually.
> Add support for push to VMWare

- Schutzfile
So we can update our production setups.
Not necessary.
> schutzfile: test against osbuild 25 on RHEL 8.3

- internal/distro/rhel84/distro.go
- test/data/ansible/check_ostree.yaml
We aim at shrinking our deps eventually but we need subman for the time
being. This patch basically un-exclude subman which was introduced by
https://github.com/osbuild/osbuild-composer/pull/893
> internal/distro/rhel8: un-exclude subman from edge

- .gitignore
- cmd/osbuild-worker/jobimpl-osbuild-koji.go
- cmd/osbuild-worker/jobimpl-osbuild.go
- cmd/osbuild-worker/main.go
- docs/news/unreleased/weldr-ostree-url.md
- internal/distro/distro.go
- internal/distro/distro_test_common/distro_test_common.go
- internal/distro/fedora32/distro.go
- internal/distro/fedora33/distro.go
- internal/distro/fedoratest/distro.go
- internal/distro/rhel8/distro.go
- internal/distro/rhel84/distro.go
- internal/distro/test_distro/distro.go
- internal/weldr/api.go
- schutzbot/Jenkinsfile
- test/cases/ostree-ng.sh
This introduces an URL parameter to the OSTree image options. This is going to be required for when we introduce the installer image type. For now, we just use it as a convenience to make the parent commit optional in the ostree commit image types.
This will be used by https://github.com/osbuild/cockpit-composer/pull/1232 and https://github.com/weldr/lorax/pull/1115.
Testing is still missing for one of these commits, as well as release notes, so I'm making this a WIP.
cc @jkozol, @bcl, @gicmo and @achilleas-k 
> weldr: add url parametr to ostree image options

- README.md
- Schutzfile
- docs/news/unreleased/rhel84-grub2-saved-entry.md
- internal/blueprint/blueprint.go
- internal/blueprint/customizations.go
- internal/blueprint/customizations_test.go
- internal/distro/fedora32/distro.go
- internal/distro/fedora33/distro.go
- internal/distro/rhel8/distro.go
- internal/distro/rhel84/distro.go
- internal/osbuild/grub2_stage.go
- osbuild-composer.spec
- test/data/manifests/centos_8-x86_64-ami-boot.json
- test/data/manifests/centos_8-x86_64-openstack-boot.json
- test/data/manifests/centos_8-x86_64-qcow2-boot.json
- test/data/manifests/centos_8-x86_64-qcow2-customize.json
- test/data/manifests/centos_8-x86_64-vhd-boot.json
- test/data/manifests/centos_8-x86_64-vmdk-boot.json
- test/data/manifests/rhel_84-aarch64-ami-boot.json
- test/data/manifests/rhel_84-aarch64-openstack-boot.json
- test/data/manifests/rhel_84-aarch64-qcow2-boot.json
- test/data/manifests/rhel_84-ppc64le-qcow2-boot.json
- test/data/manifests/rhel_84-x86_64-ami-boot.json
- test/data/manifests/rhel_84-x86_64-openstack-boot.json
- test/data/manifests/rhel_84-x86_64-qcow2-boot.json
- test/data/manifests/rhel_84-x86_64-qcow2-customize.json
- test/data/manifests/rhel_84-x86_64-vhd-boot.json
- test/data/manifests/rhel_84-x86_64-vmdk-boot.json
Explicitly set the kernel to boot into.
This hooks up the recent changes @gicmo made in osbuild to fix a rhel8.4 regression. No tests yet.
> rhel84/grub2: set saved_entry

- tools/run-koji-container.sh
Use the new tags of the `osbuild/containers` repository. The
infrastructure was simplified a lot and the new tags are much easier to
handle without any conflicts when building other images.
Note that this change uses the `latest` tag of all images. As an
alternative, we can also switch to the `latest-<date>` tags, which would
use a pinned immutable image tagged by the given date. However, these
tags are burried somewhere deep down in the ./tools/ directory and are
easy to forget upgrading. So for now use `latest` until we have better
synchronization infrastructure in place.
However, if these images ever break and we want to get back stable CI
behavior, we can always switch back to older builds by picking those
immutable tags instead of `latest`.
> tools: move to new utility-container builds

- test/data/ansible/check_ostree.yaml
/etc/containers/registries.conf.d/rhel-shortnames.conf shipped in
containers-common-1:1.2.2-1.module+el8.4.0+10073+30e5ea69 has a wrong
shortname for ubi8-minimal:
"ubi8-minimal" = "registry.access.redhat.com/repository/ubi8-minimal"
resulting in `name unknown: Repo not found` when trying to pull the image
via its short name.
Related: rhbz#1931785
> tests: Use full repo name to ubi8-minimal to workaround bug

- cmd/osbuild-worker/jobimpl-osbuild.go
- internal/cloudapi/openapi.gen.go
- internal/cloudapi/openapi.yml
- internal/target/aws_target.go
- internal/target/targetresult.go
- internal/worker/json.go
Extend OSBuildJobResult to contain a TargetResults field, and append 
to it AWS target information like amiID and region. Add TargetResults to 
the UploadStatus struct so that it is exposed on a cloudapi status call.
> cloudapi: expose AWS target information

- cmd/osbuild-worker/jobimpl-osbuild.go
- docs/news/unreleased/cloudapi-upload-status.md
- docs/news/unreleased/rhel84-grub2-saved-entry.md
- internal/cloudapi/openapi.gen.go
- internal/cloudapi/openapi.yml
- internal/cloudapi/server.go
- internal/target/gcp_target.go
- internal/target/targetresult.go
- test/cases/api.sh
- Return GCP-specific target results form the worker, similar as it is done for AWS.
- Extend Cloud API to allow GCP-specific upload Options.
- Modify Cloud API to return UploadOptions as part of the UploadStatus.
- Modify Cloud API integration test to check returned upload Options and upload Type.
- Make formatting of all `case` statements in `api.sh` consistent.
- Add NEWS section describing modifications done to Cloud API
- Added NEWS section.
> cloudapi: implement GCP target results and include UploadOptions

- test/data/ansible/check_ostree.yaml
We found `dmesg` test failed in [this test](https://osbuildci.cloud.paas.psi.redhat.com/blue/organizations/jenkins/osbuild%2Fosbuild-composer/detail/main/143/pipeline/167#step-510-log-52). It's not a "code bug", but test compatibility.
This PR is to improve test compatibility.
> test: Update dmesg test to work with only one failed log

- schutzbot/Jenkinsfile
Move the container build to the same phase as the RPM builds. This does not make a huge difference, but should
shave off about two minutes of total CI runtime.
> Schutzbot: don't block on container build

- schutzbot/Jenkinsfile
because we already have cron jobs on multiple branches!
> Don't check branch name when deciding if build was started by cron

- test/data/ansible/check_ostree.yaml
cherry-picked from main commit 3ed3f2ed951297810282b5ca514452a0921cd7e3
> cherry-pick: Update dmesg test to work with only one failed log

- schutzbot/Jenkinsfile
makes it easier to grab if we need it for manual testing or
in case one needs to download the RPMs from Schutzbot
> tests: Save osbuild-composer.repo file under artifacts

- Makefile
- cmd/osbuild-upload-gcp/main.go
- cmd/osbuild-worker/jobimpl-osbuild.go
- cmd/osbuild-worker/main.go
- internal/upload/gcp/gcp.go
This PR addresses couple of outstanding things, which popped up during the initial GCP PR and later during review of Azure support for Cloud API.
Main changes:
- Moved all logging out of the GCP internal library to the callers (worker and the CLI upload tool), similar as it is done for Azure.
- Made all GCP methods a single purpose and not to do any extra tasks (e.g. cleanup). Rather than cleaning up under the hood, an error is returned and the caller can use provided cleanup methods to delete any unwanted resources. This is true for importing image. If the image upload to Storage fails, there is no need to clean up the object since it has been not created.
- Modified the worker and CLI upload tool code to do all necessary clean up in case of errors 
- Modified worker GCP-related code to …
> GCP refactoring: logging, storage cleanup, worker credentials

- schutzbot/Jenkinsfile
- schutzbot/deploy.sh
- schutzbot/mockbuild.sh
- schutzbot/prepare-rhel-internal.sh
- test/README.md
by defining the COMPOSE_URL environment variable! This will allow
testing more flavors of internal releases.
The rest is renaming files and variables to reflect the fact that
we're running tests against internal trees, not only nightlies.
> Schutzbot: Allow overriding internal RHEL URL

- docs/news/unreleased/rhel83-84-difference-fixed.md
- internal/distro/rhel84/distro.go
- test/data/manifests/centos_8-x86_64-qcow2-boot.json
- test/data/manifests/rhel_84-aarch64-qcow2-boot.json
- test/data/manifests/rhel_84-ppc64le-qcow2-boot.json
- test/data/manifests/rhel_84-s390x-qcow2-boot.json
- test/data/manifests/rhel_84-x86_64-qcow2-boot.json
cloud-init not longer depends on net-tools, so we need to add in the dependency explicitly.
We aimed for the qcow2 to be equivalent to the RHEL8.4 qcow2 produced by imagefactory. However, we missed this unintended change from RHEL8.3.
> distro/rhel84/qcow2: add net-tools

- cmd/osbuild-image-tests/constants/constants.go
- tools/test-case-generators/generate-all-test-cases
- tools/test-case-generators/generate-test-cases
Most build roots for a given distro/arch are identical, so let's checkpoint them to avoid having to regenerate them
all the time.
This risks increasing the disk space usage in the case the build roots do not match, but in practice that should be rare.
> image-tests: checkpoint build root

- schutzbot/Jenkinsfile
By default, a when block is evaluated after an agent is started. I discovered
this randomly: I opened a pipeline and saw that it was stuck on "Prepare EL8 
internal 🤔" stage even though the pipeline should have even run it.
This commit fixes it by adding "beforeAgent true" to all when blocks. It
changes the behaviour to more sane "if when is true, allocate an agent".
See https://www.jenkins.io/doc/book/pipeline/syntax/#evaluating-when-before-entering-agent-in-a-stage
> schutzbot: evaluate the when block before an agent is started

- schutzbot/Jenkinsfile
I think there's currently no reason to run it on PSI.
> schutzbot: run the CS8 integration test on AWS

- cmd/osbuild-upload-gcp/main.go
- cmd/osbuild-worker/jobimpl-osbuild.go
Fix a bug in the worker job implementation and GCP CLI upload tool,
which causes the code to report wrong error instance in case the image
import failed for some reason.
> GCP: Report the right error when image import fails

- .github/workflows/tests.yml
By default, the checkout action checkouts the merge commit. This is different
from what Schutzbot currently does - it runs the test on the PR HEAD commit.
Let's change the GitHub workflows behaviour to the same one as Schutzi
uses.
> github: run workflows on PR head commit

- tools/test-case-generators/generate-test-cases
This slipped in aeddf7e5012e6481c958c528d3965586ff751d88 and
survived 28aaa129ff13d1dc704ea7bdab458d6995013fb2, let's fix it.
> tools/generate-test-cases: fix missing comma

- internal/distro/rhel84/distro_v2.go
- test/cases/ostree-ng.sh
_Duplicate of #1309 for RHEL 8.4.0 branch._
The new image type introduced in #1244 ignores the ostree ref supplied by the user and always uses the default rhel/8/<arch>/edge instead.
This PR fixes the issue by using the user-supplied ref when building the image. It also updates the integration test script to use a non-default ref by prefixing it with test/.
For all distros/image types, the default is only read by the weldr API when a ref isn't specified.
> RHEL 8.4.0: Fix for RHEL for Edge Ref in new image types

- internal/distro/rhel84/distro_v2.go
- test/cases/ostree-ng.sh
The new image type introduced in #1244 ignores the ostree ref supplied by the user and always uses the default `rhel/8/<arch>/edge` instead.
This PR fixes the issue by using the user-supplied ref when building the image.  It also updates the integration test script to use a non-default ref by prefixing it with `test/`.
For all distros/image types, the default is only read by the weldr API when a ref isn't specified.
> Fix for RHEL for Edge Ref in new image types

- cmd/osbuild-worker/jobimpl-osbuild.go
The previous implementation exited before reporting back to the worker
API in few branches. This left the compose status in RUNNING state even
though the worker did not work of the job any more. Refactoring the
API call into the `deref` part makes sure it gets called every time.
Fixes: #1276
- This functionality is already covered by tests. (well not the cases of failure, but we don't have any test cases like that)
- Ideally this change does not affect anyone.
> osbuild-worker: Report job status back to worker API in all cases

- docs/news/unreleased/cloudapi-image_status-status-value.md
- internal/cloudapi/openapi.gen.go
- internal/cloudapi/openapi.yml
- internal/cloudapi/server.go
- test/cases/api.sh
Previously, the Cloud API endpoint `/v1/compose/{id}` return value's `image_status.status` for a running worker job was "running", which didn't comply with the Cloud API specification. Equivalents allowed by the API specification are "building", "uploading" or "registering".
As a result, the Image Builder API also does not comply in this regard to its specification, because it currently just copies the status value string returned by osbuild-composer.
Define the `image_status.status` as a reusable type in the Cloud API specification. This forces openapi to generate an explicit type for it, which can be then explicitly used in the code, instead of plain strings. The name `ImageStatusValue` is probably not ideal, but IMHO something like `ImageStatusStatus` would be even worse...
Return …
> Cloud API: fix `image_status.status` value for running compose

- docs/news/unreleased/ostree-ref-handling.md
- internal/weldr/api.go
- internal/weldr/api_test.go
- test/cases/ostree-ng.sh
Replacing repeated calls to u.Parse() with path.Join() on the URL's path. This method handles certain edge cases differently:
- location not ending in / (http://example.org/repo):
- with the old method, the subsequent parsing of "refs/heads/" would overwrite the path segment of the original URL, resulting in       http://example.org/refs/heads
- with the new method, "refs/heads" is appended to the location and a / is added between the two parts if necessary.
- ref begins with / (location: http://example.org/repo/, ref: /ref):
- with the old method, the final parsing of ref would overwrite the path segment of the URL, resulting in http://example.org/ref
- with the new method, the ref is appended and a / is added between parts where necessary (same as above).
- …
> Improve OSTree ref and URL handling in Weldr API

- schutzbot/Jenkinsfile
- image_tests.sh is already being executed from the osbuild
repository by installing osbuild-composer-tests & calling the
script directly
- in this repo we've got distro_test.go::TestDistro_Manifest() and
distro_test_common.TestDistro_Manifest() which compare the static
manifests stored in this repository with the ones generated
dynamically by the code base. This is executed via `go test` and
runs against all available json files.
The above two items cover the part where we want to make sure that
the resulting content is what we expect.
Additionally the existing integration tests cover the part where
we build images, upload them to a cloud vendor and boot a new VM
from the image.
> tests: Don't execute image tests on PRs. Closes #962

- cmd/cloud-cleaner/main.go
- cmd/osbuild-upload-gcp/main.go
- cmd/osbuild-worker/jobimpl-osbuild.go
- internal/cloud/gcp/cloudbuild.go
- internal/cloud/gcp/cloudbuild_test.go
- internal/cloud/gcp/compute.go
- internal/cloud/gcp/storage.go
- internal/cloudapi/openapi.gen.go
- internal/cloudapi/openapi.yml
- test/cases/api.sh
Modify all relevant methods in the internal GCP library to accept context from the caller.
Modify all places which call the internal GCP library methods to pass the context.
Made it possible to clean up resources after canceled image import:
- Add method to fetch Cloudbuild job log.
- Add method to parse Cloudbuild job log for created resources. Parsing is specific to the Image import Cloudbuild job and its logs format. Add unit tests for the parsing function.
- Add method to clean up all resources (instances, disks, storage objects) after a Cloudbuild job.
- Modify the worker osbuild job implementation and also the GCP upload CLI tool to use the new cleanup method `CloudbuildBuildCleanup()`.
- Keep the `StorageImageImportCleanup()` method, because it is still used by the cloud-cleaner …
> GCP: Allow the caller of the internal library to pass the ctx

- schutzbot/Jenkinsfile
Don't run the nightly test on main. Main currently doesn't match the
osbuild-composer version shipped in any RHEL versions.
We should resume this when we start rebasing again.
Additionally, RHEL 9 test will be never triggered anymore on the nightly test.
> disable nightly tests on main

- .github/PULL_REQUEST_TEMPLATE.md
The template mentioned only "adequate" documentation which can be
interpreted in many ways. Mention the news/unreleased directory and the
guides explicitly and include links for convenience.
> github: mention the guides in the pull request template

- internal/boot/context-managers.go
- osbuild-composer.spec
- tools/deploy-qemu
- tools/libvirt_test.sh
- tools/test-case-generators/generate-all-test-cases
genisoimage might be removed from RHEL 9. The users are advised to switch
to mkisofs tools from the xorriso package. It should be a drop-in replacement.
The same change was recently done by libguestfs:
https://github.com/libguestfs/libguestfs/commit/efb8a766cac4ba8e413594946136bf91e176bb8c
https://github.com/libguestfs/libguestfs/commit/2216ab2e328457ef172d6bfa534272edf2f81a3a
> test: replace genisoimage with mkisofs

- test/cases/ostree-ng.sh
composer-cli-28.14.58 is in nightly compose of RHEL 8.4, it's time to replace API calling with composer-cli
> test: Replace API calling with composer-cli

- Schutzfile
- test/cases/ostree-ng.sh
Since selinux fix has been release in osbuild 27.1 and it's in nightly compose. It's time to remove selinux work around and Schutzfile osbuild pinning
> test: Remove selinux work around and Schutzfile osbuild pinning

- test/cases/ostree-ng.sh
Because test uses 'test/rhel/8/x86_64/edge', building rhel-edge image should include --ref arg
> test: Add --ref for non-default ref

- Schutzfile
- docs/news/unreleased/rhel84-qcow2-compat.md
- internal/distro/rhel84/distro.go
- internal/osbuild1/qemu_assembler.go
- osbuild-composer.spec
- test/data/manifests/centos_8-x86_64-qcow2-boot.json
- test/data/manifests/centos_8-x86_64-qcow2-customize.json
- test/data/manifests/rhel_84-aarch64-qcow2-boot.json
- test/data/manifests/rhel_84-ppc64le-qcow2-boot.json
- test/data/manifests/rhel_84-s390x-qcow2-boot.json
- test/data/manifests/rhel_84-x86_64-qcow2-boot.json
- test/data/manifests/rhel_84-x86_64-qcow2-customize.json
*"backport" from the rhel-8.4.0 branch*
By default, `qemu-img convert` creates qcow2 images usable in qemu 1.1 and
newer. RHEL 8 guest images are meant to be bootable on RHEL 6 though.
Unfortunately, RHEL 6 has qemu 0.12, therefore these images cannot be used
there.
To fix this, we need to use the new qcow2_compat option in qemu assembler
to override the default compat version and make qcow2 images that can be used
in qemu 0.10 and newer.
For this, we need osbuild 28 that is currently only available in RHEL 8.4,
therefore it's being pinned for now in Fedora, CentOS Stream and RHEL 8.3
> distro/rhel84: build qcow2 images with compat=0.10

- internal/distro/fedora32/distro.go
- internal/distro/fedora33/distro.go
- internal/distro/rhel8/distro.go
- internal/distro/rhel84/distro.go
- internal/distro/rhel90/distro.go
The `distribution` struct defined in multiple distributions contained unused `imageTypes` field. Remove it to simplify code.
> distro: remove unused field from `distribution` struct

- test/cases/ostree-ng.sh
According to Ben's suggestion, test has been updated to aligin with customer scenario.
1. Setup ostree prod repo, building installer and edge upgrade will be from prod repo
2. Containers for building installer and edge upgrade will be running as stage repo
3. Before edge system update, prod repo will pull update content from stage repo, make static-delta and summary
> test: Update test to align with customer scenario

- schutzbot/mockbuild.sh
s3cmd sync actually downloads metadata for all objects in a s3 bucket.
We have built a lot of RPMs, thus this takes 5 minutes on AWS and 25 minutes
on my laptop (!!!).
Let's use recursive put instead. This doesn't delete any files on the remote
side. As we upload RPMs only once, this also shouldn't fail on "the
object already exists". Using this method, we should be able to upload the
RPMs in seconds.
> mockbuild: use s3cmd put instead of sync to speed up the RPM upload

- test/cases/ostree-ng.sh
- test/data/ansible/check_ostree.yaml
Update `ostree-ng.sh` to install and run ostree commit on UEFI VM.  `ostree.sh` keeps on BIOS VM. Both of BIOS and UEFI are covered.
`check_ostree.yaml` ansible playbook has to be updated to support both BISO and UEFI.
> test: Install and run ostree commit on UEFI VM

- tools/image-info
After change to image-info [1], which shows the format version for qcow2
images, the `image-format` changed from string to a dictionary. However
the `open_image()` function still compares it with string. This causes
`raw` images to be converted by the script again to `raw` format. This
change fixes the issue, so that `raw` images are not converted, but used
as they are.
[1] https://github.com/osbuild/osbuild-composer/commit/5937b9adca96ea4ffcb0865c75ca3e80c5b9b100
> tools/image-info: don't convert raw images

- test/cases/aws.sh
- test/cases/vmware.sh
- tools/libvirt_test.sh
BZ 1843704 has been fixed and shipped in 8.3. We shouldn't need this
patch anymore!
> tests: Revert a lorax patch

- test/cases/ostree-ng.sh
- test/data/ansible/check_ostree.yaml
According to @teg's suggestion:
> I agree UEFI is the most important to test, and we have now some coverage of both BIOS and UEFI, which is great.
> I wonder, should we also test our installer on BIOS though? Now only the commits are tested on BIOS with the standard installer, but not the one we produce? That would anyway be a separate PR.
This PR will test installer on both BIOS and UEFI VM.
> test: Add installer test on BIOS VM

- internal/cloud/gcp/cloudbuild.go
- internal/cloud/gcp/cloudbuild_test.go
The `cloudbuildResourcesFromBuildLog()` function from the internal GCP
package could cause panic while parsing Build job log which failed early
and didn't create any Compute Engine resources. The function relied on
the `Regexp.FindStringSubmatch()` method to always return a match
while being used on the build log. Accessing a member of a nil slice
would cause a panic in `osbuild-worker`, such as:
```
Stack trace of thread 185316:
#0  0x0000564e5393b5e1 runtime.raise (osbuild-worker)
#1  0x0000564e5391fa1e runtime.sigfwdgo (osbuild-worker)
#2  0x0000564e5391e354 runtime.sigtrampgo (osbuild-worker)
#3  0x0000564e5393b953 runtime.sigtramp (osbuild-worker)
#4  0x00007f37e98e3b20 __restore_rt (libpthread.so.0)
#5  0x0000564e5393b5e1 runtime.raise (osbuild-worker)
#6  0x0000564e5391f5ea …
```
> GCP: Fix panic while parsing a specific build job log

- test/cases/ostree.sh
The `anaconda-34.24.9-1` in fedora 34 requires `inst` prefix.
> test: Update virt-install arg "ks=file:/ks.cfg" to "inst.ks=file:/ks.cfg"

- internal/distro/fedora32/distro.go
- internal/distro/fedora33/distro.go
- internal/distro/rhel8/distro.go
- internal/distro/rhel84/distro.go
- internal/distro/rhel84/distro_v2.go
- internal/distro/rhel90/distro.go
- schutzbot/Jenkinsfile
- test/cases/regression.sh
When a users wants to install a package that itself is excluded or its
dependency is excluded, it fails the build. There is no known workaround
for this shorcoming of our current design.
Therefore, remove a package from the list of excluded if it is
explicitly mentioned in a blueprint. This will not solve the issue with
dependencies, but it will create a possibility of a workaround.
> distro: remove excluded package if explicitly specified in the bp

- osbuild-composer.spec
Not proud of the fix but it should work for now. See the comment in the spec
file for more information and also the upstream PR for more context:
https://github.com/getkin/kin-openapi/pull/351
> spec: fix rpm build on Fedora 34

- test/cases/ostree.sh
Change BOOT_LOCATION to COMPOSE_URL until GA is released.
> tests: change ostree boot location for RHEL 8.4

- osbuild-composer.spec
- schutzbot/prepare-rhel-internal.sh
- test/cases/ostree.sh
- tools/define-compose-url.sh
we don't want this defined multiple times in different places
> tests: Define COMPOSE_URL/COMPOSE_ID in a single place. Fix #1397

- internal/distro/rhel90/distro.go
- test/cases/libvirt.sh
- test/data/manifests/rhel_90-aarch64-qcow2-boot.json
- test/data/manifests/rhel_90-ppc64le-qcow2-boot.json
- test/data/manifests/rhel_90-s390x-qcow2-boot.json
- test/data/manifests/rhel_90-x86_64-qcow2-boot.json
- tools/libvirt_test.sh
RHEL qcow2 images didn't have cloud-init enabled, this PR fixes that. Also, the libvirt test explicitly enabled cloud-init in a blueprint. This behavior was removed so an image without enabled cloud-init will fail the test suite from now on.
Fixes COMPOSER-920
Fixes rhbz#1960309
> enable cloud-init in RHEL 9 qcow2 images

- .gitlab-ci.yml
- schutzbot/Jenkinsfile
- test/cases/regression-include-excluded-packages.sh
- test/cases/regression.sh
Create an entry point for all regression test called "regression.sh" and
run it as part of integration tests for all our distros. This entry
point contains logic for running only the test cases that are
appropriate for a given distribution.
> test/cases: Introduce common "regression" test for all distros

- .github/ISSUE_TEMPLATE/bug_report.md
Create a template to help us with the bug reporting process. This template includes a request for information we usually ask from the reporters. This way, they can include the information upfront.
> github: create issue template

- osbuild-composer.spec
- schutzbot/Jenkinsfile
- test/cases/ostree-ng.sh
Add test case to push/pull rhel for edge container images in quay.io.
The destination quay repository is docker://quay.io/osbuild/testing-rhel-edge-push
Find the repository details and credentials in https://issues.redhat.com/browse/COMPOSER-816
> add test case to push/pull edge container images in quay.io

- schutzbot/Jenkinsfile
Send notifications about successful and failed builds to slack instead of Telegram.
> schutzbot: send notifications to slack

- test/cases/aws.sh
- test/cases/azure.sh
- test/cases/ostree-ng.sh
- test/cases/ostree.sh
- test/cases/vmware.sh
- tools/libvirt_test.sh
This prevents Gitlab CI from getting stuck if something goes wrong with the compose. This can currenly be seen with the azure.sh tests ran here: https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1314689742 
There are other tests that would get stuck in the same way so this should prevent that.
> tests: kill journalctl even if compose fails

- distribution/osbuild-composer-clouddot-template.yml
This will make the job queue persistent over redeployments.
---
Blocked on PersistentVolumeClaim resource usage permission
> distribution: Add PVC to clouddot template

- test/cases/azure.sh
PIPELINE_ID is the same across different jobs running in the same
pipeline while BUILD_ID is unique for every job.
Note: In the case where we have 1 test script/runner
CI_BUILD_ID == CI_JOB_ID
> tests: Use CI_BUILD_ID, not CI_PIPELINE_ID. Fixes #1448

- test/cases/aws.sh
- test/cases/azure.sh
- test/cases/ostree-ng.sh
- test/cases/ostree.sh
- test/cases/vmware.sh
- tools/libvirt_test.sh
3a8c6c8a introduced a new logic for killing journalctl. Unfortunately, it
doesn't work properly. In ostree tests, multiple journalctls are spawned
but there can be only one trap active at a time. This caused all but the last
journalctls to hang indefinitely. Unfortunately, hanging background processes
is something that causes the GitLab CI to hang indefinitely as well.
This commit modifies the logic a bit: The trap is still set. However, there's
also an explicit kill of journalctl after the compose is finished. After the
process is successfully killed, the trap is removed.
> tests: fix journalctl killing once again

- .gitlab-ci.yml
- schutzbot/deploy.sh
> Gitlabci improvements

- .gitlab-ci.yml
- cmd/osbuild-worker/jobimpl-osbuild-koji.go
- cmd/osbuild-worker/jobimpl-osbuild.go
- distribution/Dockerfile-worker
- docs/news/unreleased/hosted-edge-commit.md
- internal/cloudapi/openapi.gen.go
- internal/cloudapi/openapi.yml
- internal/cloudapi/server.go
- internal/kojiapi/server.go
- internal/ostree/ostree.go
- internal/ostree/ostree_test.go
- internal/target/aws_target.go
- internal/target/target.go
- internal/target/targetresult.go
- internal/upload/awsupload/awsupload.go
- internal/weldr/api.go
- internal/weldr/api_test.go
- internal/worker/json.go
- test/cases/api.sh
This PR adds the ability to build edge commits through the Cloud API and upload them to an S3 bucket.  On successful upload, the service returns a [Presigned URL](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html) that can be used to download the object.
Image builder counterpart: https://github.com/osbuild/image-builder/pull/193
One thing to note is the lifetime of the Presigned URL.  It's currently set to 24 hours, but I don't know if that's something we want to expose or adjust.
~~## Draft~~
~~This will remain a draft until #1351 is merged so I can rebase it.  Wanted to open the PR for visibility and to discuss any issues with the approach.~~
~~I'd also like to get the same treatment for the Edge installer image type …
> Hosted edge commit

- distribution/osbuild-composer-clouddot-template.yml
Getting bad gateway errors, missed that I changed the entrypoint to
```
ENTRYPOINT ["python3", "/opt/entrypoint.py", "--remote-worker-api", "--composer-api", "--composer-api-port", "9196"]
```
We could reset it to 443, but since it's http, and not https, let's try to pick something else.
> distribution: The composer-api listens on 9196

- .gitlab-ci.yml
- test/cases/azure.sh
- test/cases/azure_hyperv_gen2.sh
- test/data/azure/deployment-template.json
- test/data/azure/main.tf
Related: rhbz#1896264
Update - a few more questions raised here:
1) Should we drop testing on Gen1 hypervisors or not ? This is being tracked in https://bugzilla.redhat.com/show_bug.cgi?id=1896264
2) How the heck v2 image (hypervisor) works with RHEL 8.3 that is bios-only? (we're not sure if hypervisor can auto-detect which boot mode to use)
> Azure: test on V2 Hyper-V generation

- tools/deploy-qemu
Two fixes for `tools/deploy-qemu`:
- Previously, the temporary directory was created in the script dir. It just
imo created unnecessary and confusing files in my git checkout. Let's just
use the default temporary directory because we don't really have special
needs for it.
- exit is just a helper for the interactive shell, see:
https://stackoverflow.com/questions/6501121/difference-between-exit-and-sys-exit-in-python
> random fixes for tools/deploy-qemu

- .gitlab-ci.yml
Remove Fedora 33 ostree test due to BZ#1975660 (#1496 )
Signed-off-by: Yuxin Sun <yuxisun@redhat.com>
> Remove Fedora 33 ostree test

- schutzbot/run_cloud_cleaner.sh
In 0680214c9b20b76f82c381fb3472d83846ca0c71 the BUILD_ID was changed in azure.sh test but not in cloud_cleaner causing cloud-cleaner to not clean up properly. This fixes that.
I hope this will reduce the ammount of leftover resources in Azure.
> tests: update cloud-cleaner

- cmd/osbuild-upload-aws/main.go
- cmd/osbuild-worker/jobimpl-osbuild.go
- internal/boot/aws.go
- internal/upload/awsupload/awsupload.go
If a user uses a temporary access key for login, a session token is also
needed.
This commit adds support for it to the internal aws library and also
to the osbuild-upload-aws helper. Note that this doesn't affect the main
osbuild-composer executable nor the worker. Everything here should work
as before and session tokens are not supported. Something for a follow up
if anyone needs it.
- our existing test suite covers that this change is backward compatible, no new tests are needed, this just a change to development tools
- just a change of development tools
> upload/aws: add support for session tokens

- test/cases/image_tests.sh
We need to update `image_tests.sh` in order to be able to run it in Gitlab CI for osbuild. Originally we had the cloud credentials in Jenkins as files but that can't be masked in Gitlab CI. I don't know which approach is best here, whether to keep the current implementation and just print the variables one by one to a file to be used by the `TEST_CMD`, print them there one by one or I don't know, I'm open to suggestions.  
> tests: Image tests update for osbuild

- cmd/osbuild-koji-tests/main_test.go
- cmd/osbuild-koji/main.go
- cmd/osbuild-worker/jobimpl-koji-finalize.go
- cmd/osbuild-worker/jobimpl-osbuild.go
- docs/news/unreleased/cloud-api-metadata.md
- internal/cloudapi/openapi.gen.go
- internal/cloudapi/openapi.yml
- internal/cloudapi/server.go
- internal/distro/distro.go
- internal/distro/distro_test.go
- internal/osbuild1/ostree_commit_assembler.go
- internal/osbuild1/result.go
- internal/osbuild1/result_test.go
- internal/osbuild2/ostree_commit_stage.go
- internal/osbuild2/result.go
- internal/osbuild2/rpm_stage.go
- internal/rpmmd/metadata.go
- internal/rpmmd/metadata_test.go
- internal/upload/koji/koji.go
- test/cases/api.sh
_Followup to #1439_
Added a new Cloud API endpoint that returns metadata about a finished build.  Currently the metadata contains full package list (NEVRA) for the built image and, where available, the commit ID (hash) for the created Edge commit.
- Utility functions for extracting and structuring the RPM metadata was moved to an internal package to be reused.
- Added a small utility function that reads the schema version from a raw Manifest.
- Metadata returned from stages was previously only stored for the RPM stage.  Now all metadata from all stages is stored.  Metadata from the `org.osbuild.ostree.commit` stage are also structured.
See individual commit messages for more details.
> Cloud API: compose/id/metadata

- schutzbot/mockbuild.sh
This is apparently not needed anymore, I checked with 20 jobs here:
https://gitlab.com/osbuild/ci/osbuild-composer/-/pipelines/328779200
> ci: remove fedora 34 hack from mockbuild

- .gitlab-ci.yml
- schutzbot/deploy.sh
- schutzbot/mockbuild.sh
EXTRA_REPO_PATH_SEGMENT was needed when both Jenkins and Gitlab CI
were running in parallel (so they don't override their artifacts).
Jenkins is now decommissioned so we can drop the variable.
> ci: remove EXTRA_REPO_PATH_SEGMENT

- .gitlab-ci.yml
- docs/news/unreleased/rhel8.5-edge.md
- internal/distro/rhel85/distro.go
- internal/distro/rhel85/distro_test.go
- internal/distro/rhel85/pipelines.go
- internal/distro/rhel85/stage_inputs.go
- internal/distro/rhel85/stage_options.go
- internal/store/json.go
- schutzbot/mockbuild.sh
- test/cases/ostree-ng.sh
- test/cases/ostree.sh
- test/data/manifests/rhel_85-x86_64-edge_commit-boot.json
- test/data/manifests/rhel_85-x86_64-edge_commit_rt-boot.json
- test/data/manifests/rhel_85-x86_64-edge_container-boot.json
- tools/provision.sh
- tools/test-case-generators/distro-arch-imagetype-map.json
- tools/test-case-generators/format-request-map.json
Adding new distro RHEL 8.5 with support for the three Edge image types: `edge-commit`, `edge-container`, and `edge-installer`.
The definition of the image types differs from older implementations:
- Reusable functions define alternatives to the `pipelines()` function for different image types.  These are bound to the image type instance on creation.  This pattern avoids the frequent conditional branching we ended up having in older pipeline generation functions.  This is especially visible in the definition of the `edge-installer` pipelines that share almost no common components with the other types (only the build pipeline is the same).  Similarly, the other (general) image types will be quite different from the edge image types when they're added, so they can …
> Edge image types for RHEL 8.5

- internal/distro/rhel90/packages.go
A recent update to crypto-policies changed its requirements from:
Recommends: grubby
to:
Recommends: (grubby if kernel)
We don't install kernel in the build pipeline, thus grubby was now no longer
installed. This caused also s390utils-core to not be installed on s390x.
s390utils-core has to be in the build pipeline though because we use
/usr/sbin/zipl from it to install the bootloader to s390x images.
Long story short, images for s390x currently cannot be build because
/usr/sbin/zipl is no longer in the build pipeline. This commit fixes that
by explicitly adding s390utils-core to the package list for s390x.
I verified this fix on an actual s390x machine. The test manifest was
regenerated but it's actually still the same because we use an older
snapshot that doesn't contain the newest …
> distro/rhel90: add s390utils-core to the build pipeline for s390x

- .gitlab-ci.yml
- test/cases/installers.sh
This PR is meant to limit the number of tests run for RHEL 8.5 to just the features and image types that are supported.
- Disable base tests on RHEL 8.5
The unit tests should be passing here but there others depend on image types that aren't supported.
This means that there will be untested features for RHEL 8.5, but that should be fixed soon with the main image types.
> CI: limit testing for RHEL 8.5

- test/data/ansible/check_ostree.yaml
Today, `ostree-ng.sh` failed on dmesg output checking. (https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1397215096). The failed dmesg is not caused by osbuild, but new RT kernel itself(See [bz#1979272](https://bugzilla.redhat.com/show_bug.cgi?id=1979272)). Allow this failed dmesg to make CI happy.
BTW, we have successful test yesterday with rt kernel `kernel-rt-4.18.0-319.rt7.100.el8.x86_64`, but failed today on rt kernel `kernel-rt-4.18.0-320.rt7.101.el8.x86_64`
> test: Allow a failed dmesg imported by new RT kernel

- Schutzfile
We already ship 29 in CentOS Stream 8, eb74ddf2 is 28.
> schutzfile: drop osbuild pin for CentOS Stream 8

- .github/workflows/tests.yml
- README.md
- go.mod
- tools/prepare-source.sh
The oldest distributions that we now support are RHEL 8.4 and Fedora 33.
They both support go 1.15, let's bump.
> bump minimum go version to 1.15

- internal/common/pointers.go
- internal/common/pointers_test.go
- internal/osbuild2/authselect_stage.go
- internal/osbuild2/authselect_stage_test.go
- internal/osbuild2/chrony_stage.go
- internal/osbuild2/chrony_stage_test.go
- internal/osbuild2/cloud_init_stage.go
- internal/osbuild2/cloud_init_stage_test.go
- internal/osbuild2/dracut_conf_stage.go
- internal/osbuild2/dracut_conf_stage_test.go
- internal/osbuild2/keymap_stage.go
- internal/osbuild2/keymap_stage_test.go
- internal/osbuild2/modprobe_stage.go
- internal/osbuild2/modprobe_stage_test.go
- internal/osbuild2/rhsm_stage.go
- internal/osbuild2/stage.go
- internal/osbuild2/stage_test.go
- internal/osbuild2/sysconfig_stage.go
- internal/osbuild2/systemd_logind_stage.go
- internal/osbuild2/systemd_logind_stage_test.go
- internal/osbuild2/systemd_stage.go
- Add two new helper functions `IntToPtr()` and `BoolToPtr()` to the `internal/common` package, which can be used to conveniently set basic type literals in a struct literal, in which pointer to the basic type is expected.
- Add support for the `org.osbuild.modprobe` osbuild stage (osbuild/osbuild#670), which allows one to configure modprobe by creating configuration files.
- Add support for the `org.osbuild.dracut.conf` osbuild stage (osbuild/osbuild#688), which allows one to configure dracut by creating configuration files.
- Add support for the `org.osbuild.systemd-logind` osbuild stage (osbuild/osbuild#668), which allows one to configure systemd-logind by creating configuration drop-ins.
- Add support for the newly added `network-scripts` option in the …
> Add support for newly added / extended osbuild stages required for RHEL AMIs

- docs/news/unreleased/worker-heartbeat.md
- internal/jobqueue/fsjobqueue/fsjobqueue.go
- internal/jobqueue/fsjobqueue/fsjobqueue_test.go
- internal/jobqueue/jobqueue.go
- internal/kojiapi/server_test.go
- internal/worker/server.go
- internal/worker/server_test.go
- test/cases/api.sh
This removes state from the worker server, as it no longer contains the
list of running jobs. Instead only the queue knows if jobs are running
or not.
~~- [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/~~
> worker: Move job tokens to the queue itself

- .gitlab-ci.yml
This is just me trying to run just libvirt tests on Openstack.
There are two reasons for this:
1) TCG is not supported downstream meaning we can't expect booting qcow images without kvm to work.
2) We don't want to move all integration testing to Openstack as it's severely slowing down the CI as can be seen now when we moved Centos stream 8 integration testing.
> tests: Run some libvirt tests in openstack

- test/cases/azure.sh
This package needs to be present otherwise the VM is not
responding. This change makes sure the package is present
in the image.
> tests: make azure.sh easier to run locally

- RELEASING.md
- tools/update-distgit.py
This commit adds RELEASING.md guide describing the process of making a new
upstream release and pushing it into Fedora and CentOS Stream 9.
Additionally, a new helper is added to the repository - update-distgit.py.
The purpose of this helper is to simplify work with the dist-git.
Random thoughts:
I decided to left off RHEL 8 because the guide would be full of internal
URLs and tools. I will probably write a similar guide for it and put it
into internal guides.
I decided to just reference the RHEL Developer Guide for CentOS Stream 9.
It's pretty well written and I didn't feel like duplicating the effort.
We should definitely switch to PR-based approach for Fedora and implement
at least some smoke tests. I believe that the current guide is good enough
and we can iterate later.
**One final …
> docs: document the release process

- schutzbot/update_github_status.sh
> tests: Don't overwrite CI statuses on main for nightly pipelines

- tools/image-info
Some images with ESP, e.g. the `rhel-ec2-aarch64`, have the `/boot` on
a separate partition. `image-info` currently produces traceback on such
images, e.g.:
```
Traceback (most recent call last):
File "/home/thozza/devel/osbuild-composer/./tools/image-info", line 1997, in <module>
main()
File "/home/thozza/devel/osbuild-composer/./tools/image-info", line 1991, in main
report = analyse_image(target)
File "/home/thozza/devel/osbuild-composer/./tools/image-info", line 1863, in analyse_image
append_partitions(report, device, loctl)
File "/home/thozza/devel/osbuild-composer/./tools/image-info", line 1849, in append_partitions
append_filesystem(report, tree)
File "/home/thozza/devel/osbuild-composer/./tools/image-info", line 1809, in append_filesystem
with open(f"{tree}/grub2/grubenv") as f: …
```
> image-info: cover situation when `/boot` is on a separate partition

- cmd/cloud-cleaner/main.go
- internal/cloud/gcp/compute.go
- test/cases/api.sh
The `api.sh` test currently always defaults to `<REGION>-a` zone when creating instance using the built image. The resources in a zone may get exhausted and the solution is to use a different zone. Currently even a CI job retry won't help with mitigation of such error during a CI run.
Modify `api.sh` to pick random GCP zone for a given region when creating a compute instance. Use only GCP zones which are "UP".
The `cloud-cleaner` relied on the behavior of `api.sh` to always choose the "<REGION>-a" zone. Guessing the chosen zone in `cloud-cleaner` is not viable, but thankfully the instance name is by default unique for the whole GCP project. Modify `cloud-cleaner` to iterate over all available zones in the used region and try to delete the specific instance in each of them.
Make …
> Cloud API test: randomize used GCP zone from the region

- docs/news/unreleased/new-osbuild-stages.md
- internal/osbuild2/authselect_stage.go
- internal/osbuild2/chrony_stage.go
- internal/osbuild2/cloud_init_stage.go
- internal/osbuild2/dracut_conf_stage.go
- internal/osbuild2/keymap_stage.go
- internal/osbuild2/stage_test.go
- internal/osbuild2/systemd_logind_stage.go
- Reflect osbuild/osbuild#729 in osbuild-composer.
- Some osbuild stages added as part of #1525 declare unexported types which are complete copies of types with custom MarshalJSON method, to prevent recursion when marshalling to JSON.
- Add news entry for changes merged as part of #1525.
> Fix-ups and missing documentation for PR#1525

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Introduce Dockerfile and devcontainer.json specifying how to build and
run a containerized development environment in VSCode.
The configuration is inspired by the osbuild repo where a similar
configuration directory already exists.
> devcontainer: introduce VSCode dev container

- .gitlab-ci.yml
- test/cases/ostree-ng.sh
- test/cases/ostree.sh
Defined a general purpose artifact save directory where test scripts can add files to be saved for inspecting and troubleshooting builds in CI.
I modified the ostree test scripts to save their compose manifest and logs.
> CI: save compose logs and metadata

- Schutzfile
- schutzbot/deploy.sh
- schutzbot/mockbuild.sh
Let's explain how RPMs for RHEL are built:
We use a subscribed RHEL 8.x machine and mock build these on it. Mock
initializes its own buildroot based on the latest RHEL 8 CDN content, see[1].
This means that the minor version of the buildroot is independent of the minor
version of the host.
However, we currently upload RPMs to a directory whose name consists also of
the minor version of the host. Our hosts are currently running RHEL 8.3 so
the RPMs are uploaded into rhel-8.3 directory despite them being built in the
RHEL 8.4 buildroot (RHEL 8 CDN buildroot specifically). This means that
we cannot guarantee that they are installable on RHEL 8.3 which is weird.
This commit adds a special case for hosts that run on subscribed RHEL and
thus build RPMs in a buildroot constructed from RHEL CDN. …
> ci: upload rpms built in RHEL 8 CDN buildroot into rhel-8-cdn directory

- .gitlab-ci.yml
RHEL 8.4 is GA for a long time so we no longer need 8.4 nightly jobs.
> ci: drop all remaining 8.4 nightly jobs

- internal/osbuild2/cloud_init_stage.go
- internal/osbuild2/cloud_init_stage_test.go
- internal/osbuild2/dracut_conf_stage.go
- internal/osbuild2/dracut_conf_stage_test.go
- internal/osbuild2/modprobe_stage.go
- internal/osbuild2/modprobe_stage_test.go
- internal/osbuild2/stage.go
- internal/osbuild2/stage_test.go
- internal/osbuild2/systemd_logind_stage.go
- internal/osbuild2/systemd_logind_stage_test.go
- internal/osbuild2/systemd_stage.go
- internal/osbuild2/systemd_unit_stage.go
- internal/osbuild2/systemd_unit_stage_test.go
This Pull Request reflects changes made to some osbuild stages before the v30 release (https://github.com/osbuild/osbuild/pull/739):
- change the following stages from creating multiple configuration files to just a single file:
- `cloud-init`
- `modprobe`
- `dracut.conf`
- `systemd-logind`
- the functionality to create Systemd unit drop-ins was extracted from the `systemd` stage to a new `systemd.unit` stage
> Reflect changes made to some osbuild stages before the v30 release

- .gitlab-ci.yml
Previously, all sorts of tests that provided no value were run for RHEL 9.0.
This commit limits its testing to the only test that makes sense: koji.sh.
See #1461 for more details.
Fixes #1461
> ci: run only koji.sh for rhel_90 distro

- internal/client/source_test.go
- internal/store/json.go
- internal/store/store.go
- internal/weldr/api_test.go
- internal/weldr/json.go
The system sources allow specification of the rhsm parameter, but it
isn't available in the sources configured over the Weldr API. This patch
implements support for it.
Fixes: #1445
> weldr: accept rhsm parameter in sources

- internal/distro/rhel85/pipelines.go
- test/data/manifests/rhel_85-aarch64-ami-boot.json
- test/data/manifests/rhel_85-x86_64-ami-boot.json
- test/data/manifests/rhel_85-x86_64-edge_container-boot.json
- test/data/manifests/rhel_85-x86_64-openstack-boot.json
- test/data/manifests/rhel_85-x86_64-qcow2-boot.json
- test/data/manifests/rhel_85-x86_64-tar-boot.json
- test/data/manifests/rhel_85-x86_64-vhd-boot.json
- test/data/manifests/rhel_85-x86_64-vmdk-boot.json
This PR is the result of a short investigation into the differences between the image types in RHEL 8.4 and 8.5, based on the output of the `image-info` tool (as it currently exists in the test manifests).
Elements fixed in this PR:
- AMI package exclude list
~~We (well, mostly @thozza) are working towards updating the AMI definitions to match the official images (https://issues.redhat.com/browse/COMPOSER-837).  The AMI definition I added in #1536 was an initial step towards this, where I updated the package list from the 8.4 definition.  Unfortunately, I neglected to include some packages to the exclusion list.  That's been fixed now.~~
- I reverted the change in the AMI package lists since @thozza is currently working on bringing those up to date separately. …
> Fix differences between 8.4 and 8.5 image definitions

- cmd/osbuild-worker/jobimpl-osbuild.go
To help along with debugging, this commit makes the worker able to print
the status of the different stages with a oneliner for each successfull
stages and a detailed message for failed ones.
Sample output:
Jul 23[..]: Build stages results:
Jul 23[..]: org.osbuild.rpm  success
Jul 23[..]: org.osbuild.selinux  success
Jul 23[..]: Stages results:
Jul 23[..]: org.osbuild.rpm  success
Jul 23[..]: org.osbuild.fix-bls  success
Jul 23[..]: org.osbuild.fstab  success
Jul 23[..]: org.osbuild.grub2  success
Jul 23[..]: org.osbuild.locale  success
Jul 23[..]: org.osbuild.timezone  success
Jul 23[..]: org.osbuild.users failure:
Jul 23[..]:  [/usr/lib/tmpfiles.d/journal-nocow.conf:26] Failed to resolve specifier: uninitialized /etc detected, skipping
Jul 23[..]: All rules containing unresolvable …
> Worker: report stages status after RunOSBuild

- internal/blueprint/customizations.go
- internal/blueprint/customizations_test.go
- internal/client/compose_test.go
- internal/distro/fedora33/distro.go
- internal/distro/fedora33/distro_test.go
- internal/distro/rhel8/distro.go
- internal/distro/rhel8/distro_test.go
- internal/distro/rhel84/distro.go
- internal/distro/rhel84/distro_test.go
- internal/distro/rhel84/distro_v2.go
- internal/distro/rhel85/distro.go
- internal/distro/rhel85/distro_test.go
- internal/distro/rhel90/distro.go
- internal/distro/rhel90/distro_test.go
- internal/distro/test_distro/distro.go
- internal/weldr/api.go
I am extending the weldr api to accept filesystem customisations. Any existing images will only support the `'/'` mountpoint.
Existing images will through structured errors if an unsupported filesystem configuration has been specified.
I have added
* the ability to specify filesystem customisations in blueprints file, with `name`, `mountpoint` and `minSize` parameters
* errors for OSTree types for rhel8 and testing for the rhel8 distro
* errors for unsupported mountpoints on rhel8 (only '/' supported) and added testing
Any feedback on the approach taken, suggestions for improvement would be greatly appreciated. I will then extend the other distro types after this.
> Filesystem config

- osbuild-composer.spec
- test/cases/aws.sh
- test/cases/azure.sh
- test/cases/installers.sh
- test/cases/ostree-ng.sh
- test/cases/ostree.sh
- test/cases/vmware.sh
- tools/gen-ssh.sh
- tools/libvirt_test.sh
Trying the basic functionality just with libvirt test, i'll extend it to the other tests if it works
> replace hard coded ssh keys with generated one

- internal/distro/rhel85/pipelines.go
- test/data/manifests/rhel_85-aarch64-ami-boot.json
- test/data/manifests/rhel_85-aarch64-edge_commit-boot.json
- test/data/manifests/rhel_85-aarch64-openstack-boot.json
- test/data/manifests/rhel_85-aarch64-qcow2-boot.json
- test/data/manifests/rhel_85-aarch64-tar-boot.json
- test/data/manifests/rhel_85-x86_64-ami-boot.json
- test/data/manifests/rhel_85-x86_64-edge_commit-boot.json
- test/data/manifests/rhel_85-x86_64-edge_commit_rt-boot.json
- test/data/manifests/rhel_85-x86_64-openstack-boot.json
- test/data/manifests/rhel_85-x86_64-qcow2-boot.json
- test/data/manifests/rhel_85-x86_64-tar-boot.json
- test/data/manifests/rhel_85-x86_64-vhd-boot.json
- test/data/manifests/rhel_85-x86_64-vmdk-boot.json
This PR fixes up some small (but important) oversights in the image definitions added in #1536.
1. OS image tree pipeline did not define a build root and was instead being built on the host
2. SELinux stage is always the last stage in a pipeline
3. Updated test manifests to reflect 1 & 2
> RHEL 8.5: fixes to image definitions

- cmd/osbuild-composer/config.go
- cmd/osbuild-composer/config_test.go
- cmd/osbuild-composer/testdata/test.toml
- docs/news/unreleased/rhel8.5-support.md
- internal/distro/rhel85/package_sets.go
- internal/osbuild2/files_input.go
- test/data/manifests/rhel_85-aarch64-ami-boot.json
- test/data/manifests/rhel_85-aarch64-ec2-boot.json
- tools/image-info
This is a follow-up to #1607
Notable changes:
- image-info: mount partitions in correct order when analysing image
- composer: don't expose ec2 and ec2-ha RHEL-8.5 images via WeldrAPI
- docs/news: reflect EC2 image changes in the RHEL-8.5 images note
- rhel85: include dracut-config-generic in x86 UEFI boot package set
- unit tests were extended / modified where it was appropriate
- extended an existing NEWS entry related to RHEL-8.5 image types
> [RHEL-8.5] ec2 images followup

- internal/osbuild2/grub2_inst_stage.go
Location property is actually required. If it's omitted from the stage
options, the stage just fails.
Also see: https://github.com/osbuild/osbuild/pull/759
> osbuild2/grub2.inst: always include location in stage options

- test/cases/installers.sh
- test/data/ansible/check_install.yaml
The ansible inventory file in the test uses the group name 'guest'.
Thanks again @henrywang for catching this.
> test: fix host group name in ansible test file

- internal/distro/rhel85/distro.go
- internal/distro/rhel85/distro_test.go
- internal/distro/rhel85/package_sets.go
- internal/store/json.go
- test/cases/installers.sh
- test/data/manifests/rhel_85-x86_64-image_installer-boot.json
- tools/test-case-generators/format-request-map.json
Renamed tar-installer to image-installer.
This is a more appropriate name:
- It disassociates the image type from the "tar" image type. The two  should not be assumed to be connected.
- It's more descriptive. The format of the payload (tar)  isn't relevant to the purpose or role of the image type.
The package set of the payload has changed to be closer to a default RHEL install.
> RHEL 85: Image installer

- internal/disk/disk.go
- internal/distro/rhel85/partition_tables.go
- internal/distro/rhel85/pipelines.go
- internal/distro/rhel85/stage_options.go
- internal/distro/rhel90/partition_tables.go
- internal/distro/rhel90/pipelines.go
- internal/distro/rhel90/stage_options.go
- internal/osbuild2/fix_bls_stage.go
- internal/osbuild2/fix_bls_stage_test.go
- internal/osbuild2/stage_test.go
- test/data/manifests/rhel_85-aarch64-ami-boot.json
- test/data/manifests/rhel_85-aarch64-ec2-boot.json
- test/data/manifests/rhel_90-aarch64-ami-boot.json
This PR includes fixes to RHEL-8.5 and RHEL-9.0 `ami` and `ec2` image definitions on `aarch64`, which caused these images to not boot.
Changes:
- rhel85/90: fix FS type for `/boot` on `ami` and `ec2` images
- rhel85/90: don't use the same part UUID for `/boot` and `/` on `ec2` images
- rhel85/90: use random FS UUID for `/boot` partition on `ec2` and `ami`
- rhel85/90: allow specifying the boot partition for the grub2 stage
- osbuild2: add `prefix` parameter to the `fix-bls` stage
- rhel90: fix a typo in RHBZ number in a comment
- rhel85/90: regenerate aarch64 ami and ec2 image test cases
> RHEL-8.5/9.0: `ami` and `ec2` `aarch64` image fixes

- Makefile
Sometimes you want to build an rpm without the tests and without running
%check
This pull request includes none of these:
> Makefile: Add scratch build target

- osbuild-composer.spec
- test/cases/api.sh
- test/cases/aws.sh
- test/cases/azure.sh
- test/cases/libvirt.sh
- test/cases/ostree-ng.sh
- test/cases/ostree.sh
- tools/define-compose-url.sh
This PR introduces a number of small patches that should simplify the work on enabling RHEL 9 tests. It doesn't enable anything yet but this should move us closer to it.
> Various clean-ups for RHEL 9 tests

- internal/upload/azure/azure.go
Previously, we used RAGRS which means that all our data was always replicated
to at least two regions for increased safety. This is cool but expensive, this PR
switches the API to use LRS that just uses one region.
> upload/azure: use cheaper storage accounts

- .gitlab-ci.yml
- cmd/cloud-cleaner/main.go
- schutzbot/scheduled_cloud_cleaner.sh
- test/cases/api.sh
I'm trying to see if it's possible to trap cloud-cleaner during test execution
> CI: scheduled cloud-cleaner for Azure

- .gitlab-ci.yml
- schutzbot/deploy.sh
- schutzbot/prepare-rhel-internal.sh
Updating rules for Installer and Regression testing and fixing failures
if certain variables are not set.
> ci: minor fixes for nightly testing

- internal/jobqueue/dbjobqueue/dbjobqueue.go
If the transaction is already closed don't log the rollback failure as
an error, it means it was successfully committed.
> dbjobqueue: Reduce error noise in rollback check

- tools/gen-user-data
Since the script adds a `write_files` key in cloud-init user-data, it
should return error if this key already exist in the input file.
> Return error when write_files exists in cloud-init

- internal/distro/rhel85/pipelines.go
- internal/distro/rhel85/stage_options.go
- internal/distro/rhel90/pipelines.go
- internal/distro/rhel90/stage_options.go
- internal/osbuild2/copy_stage.go
- internal/osbuild2/copy_stage_test.go
- internal/osbuild2/device.go
- internal/osbuild2/mkfs_btrfs_stage.go
- internal/osbuild2/mkfs_ext4_stage.go
- internal/osbuild2/mkfs_fat_stage.go
- internal/osbuild2/mkfs_stages_test.go
- internal/osbuild2/mkfs_xfs_stage.go
- internal/osbuild2/mount.go
- internal/osbuild2/sfdisk_stage.go
- internal/osbuild2/sfdisk_stage_test.go
- internal/osbuild2/stage.go
- internal/osbuild2/zipl_inst_stage.go
Simplifying devices and mounts for stages in the osbuild2 package.  This represents the osbuild schema much more closely.  Device and Mount have their own types that aren't tied directly to a Stage type, so stage-specific mounts and devices weren't a good representation.
I also took the opportunity to abstract the creation of some stages that include mounts and devices from their final representation.  This makes the Stage creation a bit more restrictive, to match the schema, while also allowing the use of the Mount and Device interfaces.  For example, `mkfs` stages require only one device labelled by the key `device`, so it makes more sense for the creation function to accept only one device and have that function add the key itself, instead of relying on the caller to assign the key or …
> osbuild: Simplify mounts and devices

- internal/distro/rhel90/stage_options.go
- internal/osbuild2/grub2_stage.go
- test/data/manifests/rhel_90-aarch64-ami-boot.json
- test/data/manifests/rhel_90-aarch64-qcow2-boot.json
Needs https://github.com/osbuild/osbuild/pull/774
Feodra 34 and thus RHEL 9 switched to a unified grub configuration, which means that the main grub config is always located in the same location, /boot/grub2/grub.cfg.[1] osbuild has used this scheme for hybrid boot on x64 but not on pure efi systems like aarch64. The new osbuild option `uefi.unified` was introduced to select that new unified grug cfg scheme also for those, pure efi, systems. Use that.
[1] https://fedoraproject.org/wiki/Changes/UnifyGrubConfig
> rhel90: use unified grub2 layout for pure uefi platforms

- internal/distro/rhel85/pipelines.go
- internal/distro/rhel90/pipelines.go
- test/data/manifests/rhel_85-x86_64-ami-boot.json
- test/data/manifests/rhel_85-x86_64-ec2-boot.json
- test/data/manifests/rhel_85-x86_64-ec2_ha-boot.json
- test/data/manifests/rhel_90-x86_64-ami-boot.json
Change the x86_64-specific dracut configuration of RHEL-8.5 and RHEL-9.0 EC2 and AMI images to not include `xen-netfront` driver and add `nvme` driver, which was previously not included. Since the configuration is no
longer Xen-specific, rename the configuration file to `ec2.conf`.
Justification:
There is no reason to put `xen-netfront` to initramfs as EC2 images don't boot from network root. In addition, add `nvme` driver to handle the case when initramfs is getting forcefully rebuild on a Xen instance (and not able to boot on Nitro after that).
Related to https://issues.redhat.com/browse/COMPOSER-1096.
- image test cases were modified
> RHEL-85/90: modify the x86_64 EC2 images dracut configuration

- internal/distro/rhel85/distro.go
- internal/distro/rhel85/distro_internal_test.go
- test/cases/filesystem.sh
This pull request includes support for the following mount points and sub mounts (as per COMPOSER-1018):
And the following mountpoints (as per COMPOSER-1016):
Additionally, integration filesystem integration test was improved to test the fail case where not allowed mountpoints are set in the blueprint filesystem customizations.
> Filesystem implementation follow up PR

- schutzbot/deploy.sh
- schutzbot/mockbuild.sh
Sometimes CI  gets to an error related to RHSM: https://issues.redhat.com/browse/COMPOSER-1037
This PR intends to solve this issue.
> [CI] remove rhn subscriptions before registering a new one

- schutzbot/deploy.sh
- schutzbot/mockbuild.sh
Sometimes CI gets to an error related to RHSM: https://issues.redhat.com/browse/COMPOSER-1037
After trying to remove all subscriptions from the system (https://github.com/osbuild/osbuild-composer/pull/1657), and realising it didn't solve the issue. Now retry logic is implemented in this PR
> [CI] retry subscribing to RHN

- .github/workflows/trigger-gitlab.yml
Dependabot pushes branches directly to the upstream repository. This causes
double-triggers of gitlab CI. Prevent it by running gitlab CI only for
the main branch.
> ci: do not trigger gitlab CI on pushed to upstream branches

- schutzbot/deploy.sh
This should fix the randomly failing test. See the comment for more
information.
Fixes #1718
> schutzbot: disable /tmp as tmpfs on RHEL 9

- .github/dependabot.yml
schedule checks so they happen at 4:00am UTC. This way gitlab CI doesn't get
blocked during working hours.
> [CI] Schedule dependabot checks

- go.sum
- vendor/github.com/dgrijalva/jwt-go/.gitignore
- vendor/github.com/dgrijalva/jwt-go/.travis.yml
- vendor/github.com/dgrijalva/jwt-go/LICENSE
- vendor/github.com/dgrijalva/jwt-go/MIGRATION_GUIDE.md
- vendor/github.com/dgrijalva/jwt-go/README.md
- vendor/github.com/dgrijalva/jwt-go/VERSION_HISTORY.md
- vendor/github.com/dgrijalva/jwt-go/claims.go
- vendor/github.com/dgrijalva/jwt-go/doc.go
- vendor/github.com/dgrijalva/jwt-go/ecdsa.go
- vendor/github.com/dgrijalva/jwt-go/ecdsa_utils.go
- vendor/github.com/dgrijalva/jwt-go/errors.go
- vendor/github.com/dgrijalva/jwt-go/hmac.go
- vendor/github.com/dgrijalva/jwt-go/map_claims.go
- vendor/github.com/dgrijalva/jwt-go/none.go
- vendor/github.com/dgrijalva/jwt-go/parser.go
- vendor/github.com/dgrijalva/jwt-go/rsa.go
- vendor/github.com/dgrijalva/jwt-go/rsa_pss.go
- vendor/github.com/dgrijalva/jwt-go/rsa_utils.go
- vendor/github.com/dgrijalva/jwt-go/signing_method.go
- vendor/github.com/dgrijalva/jwt-go/token.go
- vendor/modules.txt
#1717 broke the source preparedness check. This was probably caused by the
fact that the PR wasn't rebased on top of the latest main when it was merged.
I guess that some other PR made some incompatible changes in the meantime.
This commit is just a rerun of tools/prepare-source.sh
Merge trains are a nice idea, right?
> go: fix vendoring

- .gitlab-ci.yml
We have limited resources in openstack. We can only run about 40 concurrent VMs.
Previously, the rate limiting was kinda stupid:
All (aws and openstack) jobs were run using the same runner. This runner was
globally limited to 60 concurrent jobs. For openstack, the individual
images were also limited to a certain number of concurrent jobs in
the gitlab-ci-terraform repository so we don't hit the quota. This limit
was applied at runtime - the first thing that an openstack job did was to
wait for a slot. This job counted towards the global limit of jobs (60)
and thus was blocking one slot without doing any useful work.
Applying local limits to please global quota is stupid though. We have much
more demand for rhel-8.5 runner than for e.g. Fedora. It would be much
better to just use global …
> schutzbot: run openstack/* jobs on a dedicated runner

- .gitlab-ci.yml
- test/cases/filesystem.sh
Modifications to the test to work with weldr-client along with and
adding set -euo pipefail which was missing
> tests: enable filesystem test on RHEL-9

- osbuild-composer.spec
- test/cases/ostree-simplified-installer.sh
added test case to test the http boot of simplified installer
> add test case for http boot of simplified installer

- .gitlab-ci.yml
- test/cases/regression-composer-works-behind-satellite.sh
- test/cases/regression-excluded-dependency.sh
- test/cases/regression-include-excluded-packages.sh
> Enable RHEL-9 regression tests

- internal/cloudapi/server.go
- internal/distro/distro.go
- internal/distro/rhel8/distro.go
- internal/distro/rhel84/distro.go
- internal/distro/rhel85/pipelines.go
- internal/distro/rhel90/pipelines.go
Make Organization in the Subscription customization a string
instead of an int.
fixes #1582 
> cloudapi: change Organization customization to a string

- .packit.yaml
As the task is the same for all Fedoras (and creating PRs in rawhide works reasonably well now) I propose we enable packit for all active Fedora releases in order to reduce the manual effort.
I could also imagine doing a second job and pushing to rawhide directly instead of just creating a PR there.
> packit: Propose PRs to all Fedoras

- Schutzfile
- osbuild-composer.spec
- test/cases/regression-composer-works-behind-satellite.sh
Make sure the fallback works when there is no redhat.repo file, but
there is a certificate that can be used to access the repositories.
> regression tests: Introduce test for the RHSM fallback

- osbuild-composer.spec
The golang-github-osbuild-composer package was created by mistake a long
time ago. Stop providing it in Fedora 34 and newer and add a note about
removing the condition when Fedora 33 hits EOL.
> spec: stop providing golang-github-osbuild-composer

- docs/news/unreleased/rhel-ec2-images-rhsm-dnf-plugins.md
- internal/distro/rhel85/pipelines.go
- internal/distro/rhel90/pipelines.go
- test/data/manifests/rhel_85-aarch64-ami-boot.json
- test/data/manifests/rhel_85-aarch64-ec2-boot.json
- test/data/manifests/rhel_85-x86_64-ami-boot.json
- test/data/manifests/rhel_85-x86_64-ec2-boot.json
- test/data/manifests/rhel_85-x86_64-ec2_ha-boot.json
- test/data/manifests/rhel_90-aarch64-ami-boot.json
- test/data/manifests/rhel_90-x86_64-ami-boot.json
The RHSM DNF plugins `product-id` and `subscription-manager` are now
by default enabled on the RHEL-8.5 and RHEL-9.0 `ec2`, `ec2-ha` and
`ami` images.
The desired default state of the RHSM DNF plugins has been decided by
the RHSM team.
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1996670
> RHEL-8.5/9.0: keep RHSM DNF plugins enabled on `ec2`, `ec2-ha` and `ami`

- internal/distro/rhel85/distro.go
- internal/distro/rhel85/distro_test.go
- internal/distro/rhel90/distro.go
- internal/distro/rhel90/distro_test.go
- test/cases/filesystem.sh
Currently the filesystem configuration allows for mount points and their direct sub-directories to be configured as separate partitions (i.e. `/var` & `/var/log`). This pr expands this support to add an additional level to allow for grandchild-directories (i.e. `/var/log/audit`)
> Filesystem submounts fix

- docs/news/unreleased/support-new-osbuild-stages.md
- internal/osbuild2/dnf_config_stage.go
- internal/osbuild2/dnf_config_stage_test.go
- internal/osbuild2/pam_limits_conf_stage.go
- internal/osbuild2/pam_limits_conf_stage_test.go
- internal/osbuild2/selinux_config_stage.go
- internal/osbuild2/selinux_config_stage_test.go
- internal/osbuild2/stage.go
- internal/osbuild2/stage_test.go
- internal/osbuild2/sysctld_stage.go
- internal/osbuild2/sysctld_stage_test.go
- internal/osbuild2/tmpfilesd_stage.go
- internal/osbuild2/tmpfilesd_stage_test.go
- internal/osbuild2/tuned_stage.go
- internal/osbuild2/tuned_stage_test.go
Add support for the following osbuild stages:
- `org.osbuild.selinux.config` - https://github.com/osbuild/osbuild/pull/799
- `org.osbuild.tmpfilesd` - https://github.com/osbuild/osbuild/pull/801
- `org.osbuild.pam.limits.conf` - https://github.com/osbuild/osbuild/pull/802, https://github.com/osbuild/osbuild/pull/807
- `org.osbuild.sysctld` - https://github.com/osbuild/osbuild/pull/804
- `org.osbuild.dnf.config` - https://github.com/osbuild/osbuild/pull/798
- `org.osbuild.tuned` - https://github.com/osbuild/osbuild/pull/797
**The required osbuild version in SPEC file was not updated, because the new stages are not yet used by any image type.**
- added unit tests for all new stages
> Add support for new osbuild stages required for RHEL EC2 SAP image

- tools/test-case-generators/format-request-map.json
- tools/test-case-generators/generate-test-cases
Some image type test cases require additional repositories, which are
not available for all architectures. However, when an image type test
case is specified in the `format-request-map.json`, it is generated on any
architecture.
This behavior is creating issues when generating `*edge-commit` image
type test cases. This is because the `format-request-map.json` contains one
additional definition for `*edge-commit-rt`, which includes `kernel-rt`
package. However repositories with this package are available only for
x86_64. Therefore, when generating image test cases for `*edge-commit`,
the `generate-test-cases` script always generates two test cases,
but the generation of `*edge-commit-rt` always fails on non-x86_64
architectures.
Add a new optional member to the image type test case object …
> generate-test-cases: check `supported_arches` from format-request-map.json`

- internal/weldr/api.go
- internal/weldr/api_test.go
This adds a check to see if the source is valid and returns a 400 error
if it doesn't exist.
> weldr: deleting an unknown source should return an error

- tools/deploy-openstack
Check first parameter and check for a dirty git repo
> tools: improve deploy-openstack script

- tools/test-case-generators/distro-arch-imagetype-map.json
- tools/test-case-generators/format-request-map.json
- tools/test-case-generators/generate-all-test-cases
- tools/test-case-generators/generate-test-cases
Generating image test case with all possible blueprint customizations is supported only for `qcow2` image type. Generating `qcow2` images with customizations was not a lot of fun. One had to use a special CLI option
for this case.
To streamline the generation of image test cases, drop the `--with-customizations` option from the `generate-test-cases` script and move the functionality to `format-request-map.json` by defining a new `qcow2-customize` test case. This is very similar to what `*edge-rt` test case already uses. This mean that when the test case for `qcow2` image type is being generated, actually two test cases will be generated. The filesystem customizations since RHEL-8.5 are handled through distro-specific `overrides`.
In addition:
- Ensure that the `supported_arches` from …
> `generate-test-cases`: small fix and drop `--with-customizations` option

- internal/distro/rhel90/package_sets.go
- test/data/manifests/rhel_90-aarch64-edge_commit-boot.json
- test/data/manifests/rhel_90-x86_64-edge_commit-boot.json
- test/data/manifests/rhel_90-x86_64-edge_commit_rt-boot.json
The `nss-altfiles` package is actually needed for OSTree based systems, since in those the user/groups database is located in the /usr/lib directory (in addition to /etc). It was removed because it was not available in RHEL 9 (rhbz#1916260). This has been fixed, so we need to re-include the package.
> distro/rhel90: re-include nss-altfiles for edge

- HACKING.md
- containers/osbuild-composer/entrypoint.py
- distribution/docker-compose.yml
Minor fixes to the containers to reflect changes to `osbuild-composer` and `osbuild-worker` commands:
- adding the `https://` protocol to the baseurl for the worker container entry point
- updating the log level flag for the `osbuild-composer` entrypoint
- minor doc fix
> Container: minor fixes

- NEWS.md
Make the NEWS.md file more consistent with osbuild's NEWS.md, which
makes it easier to update it in an automated fashion.
This issue was not handled in the release script so far.
> NEWS: Drop title line

- internal/common/constants.go
- internal/weldr/api.go
- osbuild-composer.spec
> internal/common: introduce constants that are set during the build time

- distribution/osbuild-composer.service
- distribution/osbuild-remote-worker@.service
- distribution/osbuild-worker@.service
There is no need for osbuild-composer to wait until the whole multi-user
target is completed. It can be started earlier as it doesn't have any
dependencies in the target.
This can be a problem if there is a unit in the target that is not starting
and still is unrelated to osbuild-composer. There was a bug like this
with Plymouth where the service didn't finish and it was hanging. That
prevented osbuild-composer from starting and the user was left with
working SSH connection and shell, but composer-cli and systemctl start
osbuild-composer.service were both unresponsive.
Replace After=multi-user.target with After=network.target to start
osbuild-composer earlier.
> distribution: Use After=network.target instead of multi-user

- Schutzfile
- internal/distro/rhel85/stage_options.go
- internal/osbuild2/ostree_config_stage.go
- osbuild-composer.spec
Use the new bootloader config for OSTree deployments to set the bootloader backend to `none` since we use grub2 and BLS in all currentlysupported architectures. In fact, not setting it to `none`, will use the default `auto`, which will result in the run of `grub2-mkconfig`, which is not what we want and might even fail for us.
> rhel85: set bootloader to `none` for edge raw images

- internal/blueprint/customizations.go
- internal/disk/customizations.go
@thozza pointed out that `int` is platform dependent which results in a fs size that is too small for 32-bit machines. This pr changes the filesystem custimizations to use `uint64` instead of `int`.
Fix #1832
> Change filesystem minsize from int to uint64 (Fixes #1832)

- internal/distro/rhel90/pipelines.go
- test/data/manifests/rhel_90-aarch64-qcow2-boot.json
- test/data/manifests/rhel_90-aarch64-qcow2-customize.json
- test/data/manifests/rhel_90-ppc64le-qcow2-boot.json
- test/data/manifests/rhel_90-ppc64le-qcow2-customize.json
- test/data/manifests/rhel_90-s390x-qcow2-boot.json
- test/data/manifests/rhel_90-s390x-qcow2-customize.json
- test/data/manifests/rhel_90-x86_64-qcow2-boot.json
- test/data/manifests/rhel_90-x86_64-qcow2-customize.json
There's no reason to use 0.10 since we don't need to support running
this image on RHEL 6 anymore.
See https://bugzilla.redhat.com/show_bug.cgi?id=2008910
> distro/rhel90: use qcow2 compat 1.1 for qcows

- .gitlab-ci.yml
It makes no sesnse to run nightly testing on ga composes. This updates
the regex to exclude ga runners from the scheduled nightly run.
> ci: don't run nightly pipeline on ga releases

- .gitleaks.toml
Adding a gitleaks allowlist for test passwords and keys.
My fork will occasionally get notified of leaks from scanners which identify the hashed passwords in our test scripts.  With the allowlist, I'm hoping this will stop and then we can hopefully start getting alerts for real leaks only.
> Add gitleaks allowlist

- cmd/osbuild-composer/config.go
- cmd/osbuild-composer/config_test.go
- cmd/osbuild-composer/main.go
When the config file doesn't exist, don't return because we need to keep the default and also load from env.
> config: don't fail LoadConfig when file doesn't exist

- dnf-json
Never expiring metadata by default leads to surprising behavior
especially for our long-running services. The overhead of expiration
is small but noticeable, attempt some compromise.
This should all be revisited to make dnf-json handle caches better
and be more performant.
Reported by Adam Miller.
> dnf-json: expire metadata by default

- internal/rpmmd/repository.go
This is a confusing part of the startup process. We have changed the naming
and we also added the cross distro building feature. It is unclear which
files are loaded and from where (if /etc or /usr).
Log the files that are loaded so every user can clearly see what
configuration osbuild-composer uses. This complements the log of loaded
configuration.
> internal/rpmmd: log repository files loaded during composer startup

- README.md
As discussed in our previous "How we work" session I'm proposing to add a "Contributing" section that refers to our developer guide.
See also https://github.com/osbuild/osbuild/pull/839
> README: Add a link to our developer guide

- .gitlab-ci.yml
- test/cases/koji.sh
- tools/provision.sh
I forgot to add the vmware.sh test to .gitlab-ci.yml file when I updated the test and cross-distro.sh should just work as is, so adding both in this commit.
Also fixes #1634
> tests/ci: enable vmware.sh, cross-distro.sh and koji.sh on rhel-9

- test/README.md
- test/data/manifests/centos_8-x86_64-tar-boot.json
- test/data/manifests/rhel_8-aarch64-tar-boot.json
- test/data/manifests/rhel_8-ppc64le-tar-boot.json
- test/data/manifests/rhel_8-s390x-tar-boot.json
- test/data/manifests/rhel_8-x86_64-tar-boot.json
- test/data/manifests/rhel_84-aarch64-tar-boot.json
- test/data/manifests/rhel_84-ppc64le-tar-boot.json
- test/data/manifests/rhel_84-x86_64-tar-boot.json
- test/data/manifests/rhel_85-aarch64-qcow2-boot.json
- test/data/manifests/rhel_85-aarch64-qcow2_customize-boot.json
- test/data/manifests/rhel_85-aarch64-tar-boot.json
- test/data/manifests/rhel_85-ppc64le-qcow2-boot.json
- test/data/manifests/rhel_85-ppc64le-qcow2_customize-boot.json
- test/data/manifests/rhel_85-ppc64le-tar-boot.json
- test/data/manifests/rhel_85-s390x-qcow2-boot.json
- test/data/manifests/rhel_85-s390x-qcow2_customize-boot.json
- test/data/manifests/rhel_85-s390x-tar-boot.json
- test/data/manifests/rhel_85-x86_64-qcow2-boot.json
- test/data/manifests/rhel_85-x86_64-qcow2_customize-boot.json
- test/data/manifests/rhel_85-x86_64-tar-boot.json
- tools/image-info
- tools/test-case-generators/generate-all-test-cases
There have been two main issues with the generated test cases:
1. The `osbuild` used to generate image test cases in F34 repos is too old and does not contain the fix for the qemu stage and qcow compatibility version. Solve this situation by adding a new option `--repofrompath` to `generate-all-test-cases` allowing to specify additional DNF repositories, which will be used on the Runner when installing any packages (such as osbuild).
2. In some cases, e.g. when analysing an extracted `tar` image, it could happen that the tools used by `image-info` to analyse the image could modify its content (e.g. create new files which were originally not on the image). This is especially an issue with `rpm`, which DB backend seemed to create files in `/var/lib/rpm/` when run. Ensure that the analysed …
> Resolve issues found while enabling image test cases in osbuild

- cmd/osbuild-worker/jobimpl-depsolve.go
- cmd/osbuild-worker/main.go
- internal/cloudapi/v2/errors.go
- internal/cloudapi/v2/v2.go
- internal/cloudapi/v2/v2_test.go
- internal/worker/json.go
- internal/worker/server.go
- osbuild-composer.spec
Proof of concept of the simplest way to move depsolving to workers. Do not try this at home unless you are a trained professional.
> api/cloud: Move depsolving to workers

- osbuild-composer.spec
Exclude the `armv7hl` architecture, since osbuild-composer does not
support building images for it.
Tested manually with scratch build on Fedora (https://koji.fedoraproject.org/koji/taskinfo?taskID=76923499)
Fix #1839
> SPEC: Exclude `armv7hl` architecture

- internal/cloudapi/v2/v2_test.go
Bug caused by two consecutive PR merge rebases, one that added a function call and another that changed the signature of the same function.
#1841 added a new test to internal/cloudapi/v2/v2_test.go and
#1814 changed the signature of the newV2Server() in the same file
> cloudapi/v2: fix newV2Server() call in test

- .github/workflows/release.yml
- osbuild-composer.spec
This PR does two things:
- bumps the version ahead of time for the next composer release
- switches over to using schutzbot's personal access token to do the post release version bump.
Related PR for osbuild: https://github.com/osbuild/osbuild/pull/863
> Let schutzbot do the post-release version bump

- templates/dashboards/grafana-dashboard-image-builder-composer-general.configmap.yml
Update the [grafana dashboard](https://grafana.stage.devshift.net/d/cNGfs4Knz_2/image-builder-composer-test?orgId=1&var-datasource=app-sre-stage-01-prometheus&var-interval=6h&var-stability_slo=0.95&var-latency_slo=0.9&from=now-2d&to=now) to include latency metrics and latency error budget burn.
> Grafana latency

- schutzbot/prepare-rhel-internal.sh
A similar change was added in 65e429fc4aa10eed920f77b023c4dae9fc04244e so adding it here as well.
> prepare_rhel_internal: configure s3cmd explicitly

- internal/blueprint/blueprint_test.go
- internal/blueprint/customizations.go
- internal/common/helpers.go
- internal/common/helpers_test.go
> customizations: add support for fs sizes with custom units

- internal/cloudapi/v2/errors.go
Currently error metrics are being recorded forerrors with the exact error code of 500. This
commit enables recording metrics for all 5xx errors.
> cloudapi/v2: 5xx error metrics

- distribution/Dockerfile-worker
Since the depsolving has been moved to the worker, the Dockerfile for the worker needed to have the
dnf-json executable. Additionally there was a missing cache directory.
> distribution: worker dnf-json & cache dir

- osbuild-composer.spec
Fixes #1915
---
[ -d /run/systemd/system ] is used in the systemd rpm macros as well; there's also a check if /usb/bin/systemctl exists in the firstplace, is that needed as well @teg?
> spec: Only run worker preun if systemd is running

- .gitlab-ci.yml
- schutzbot/save_journal.sh
> CI: Journal-log is accessible and encrypted

- cmd/osbuild-composer/composer.go
Also remove metrics from the excludes for the composer api. This
endpoint would not be called via the gateway so it's not relevant here.
> composer: Add worker openapi spec endpoint to auth excludes

- test/cases/ostree-ng.sh
- test/cases/ostree-raw-image.sh
- test/cases/ostree-simplified-installer.sh
- test/cases/ostree.sh
Now the Edge image can be built on multi-distros, such as RHEL 8.x, RHEL 9.x, CentOS Stream 8. CentOS Stream 9 is coming soon. Different distros have different ostree refs.Test script should support ostree ref according to its distro. That's what this PR is doing.
> test: Update ostree test scripts to support different ostree refs

- .packit.yaml
Setting this option enables packit to use the Github upstream release description for the specfile instead of just using all commit messages.
See also: https://packit.dev/docs/configuration/#copy_upstream_release_description
As we're doing good GitHub release notes I hope this will make downstream release notes more consistent with upstream.
Also see the related PR for osbuild: https://github.com/osbuild/osbuild/pull/880
> packit: Use upstream github release description

- internal/osbuild2/sshd_config_stage.go
- internal/osbuild2/sshd_config_stage_test.go
- internal/osbuild2/stage.go
- internal/osbuild2/stage_test.go
This stage was introduced in osbuild 41. Add support into
osbuild-composer and a test using test data from osbuild repo.
> osbuild2: new stage sshd config

- containers/fauxauth/fauxauth.py
- distribution/Dockerfile-fauxauth
- distribution/Dockerfile-worker
Add a mock oauth container to simulate the openshift SSO offline_token
> containers: mock oauth container

- .github/workflows/coverity_scan.yml
https://scan.coverity.com/projects/osbuild-osbuild-composer
> ci: Send results to Coverity Scan daily

- test/cases/ostree-ng.sh
- test/cases/ostree-raw-image.sh
- test/cases/ostree-simplified-installer.sh
- test/cases/ostree.sh
To make Ansible output human-readable, use YAML as output format.
> test: Use YAML as Ansible output format

- cmd/osbuild-composer/composer.go
Mistakenly removed in 4577ac0717c8acfcc96c4917587106258fcd7d86. Composer
itself does the authentication, not the gateway, therefore we do need
the auth exclude.
Added a comment to explain why it's attached to the api socket and not a
separate listener.
> composer: Add metrics endpoint to auth excludes again

- Schutzfile
- osbuild-composer.spec
This will be needed for new stages which are available only in osbuild
41.
> spec: bump osbuild version to 41

- .gitlab-ci.yml
- schutzbot/deploy.sh
- schutzbot/prepare-rhel-internal.sh
- test/cases/ostree.sh
- tools/define-compose-url.sh
- tools/provision.sh
Just some experiments before implementing nightly pipeline for RHEL-9
> ci: split nightly pipeline based on rhel version

- cmd/osbuild-worker/jobimpl-osbuild.go
Running the job in this case is basically undefined, so let's just skip it
in order to not break anything.
> job/osbuild: skip the job if manifest generation failed

- internal/cloudapi/v2/v2.go
- internal/cloudapi/v2/v2_test.go
job dependencies:
depsolve -> manifest -> osbuild
This allows the compose handler to return the osbuild job id
immediately.
> cloudapi/v2: Use manifest-id-only job

- internal/osbuild2/modprobe_stage.go
- internal/osbuild2/modprobe_stage_test.go
- internal/osbuild2/stage_test.go
- osbuild2: support 'install' command in the modprobe stage
- Related to osbuild/osbuild#867
- osbuild2/modprobe: extend and rework stage options validation
-  Related to issue #1785.
> osbuild2: support 'install' command in the modprobe stage and rework data validation

- internal/cloudapi/v1/v1.go
- internal/distro/rhel90/pipelines.go
- internal/distro/rhel90beta/pipelines.go
Removing extraneous error checks (unreachable code).
There's also a fix for some potential nil dereferencing.
Caught by covscan during release.  I decided to fix them immediately instead of bundling them with a feature PR so I wont forget.
> distro/rhel90*: minor code cleanup

- internal/osbuild1/result.go
- internal/osbuild1/result_test.go
- internal/osbuild2/result.go
- internal/osbuild2/result_test.go
Before dereferencing the method receiver in Write(), check if the object is nil.
The result writer in osbuild1 (v1 results) isn't used anymore I think, but we should cover it until it's removed.
Fixes #2002
> osbuild: check if result objects are nil in Write()

- cmd/osbuild-image-tests/main_test.go
We don't have aarch64 machines in Openstack so fallback to qemu when running on aarch64.
> tests: skip Openstack image boot testing on aarch64

- internal/blueprint/customizations.go
- internal/distro/rhel86/distro.go
- internal/distro/rhel90/distro.go
- test/cases/ostree-simplified-installer.sh
Fix https://github.com/osbuild/osbuild-composer/issues/1660
> [8.6/9.0] internal: mandate installation device for the simplified installer

- internal/osbuild2/rhsm_stage.go
- internal/osbuild2/rhsm_stage_test.go
The stage now allows for customizations specific to YUM or DNF. So far
it is just an alias to the same definition, meaning that composer can
use exactly the same structures for both.
Ref: https://github.com/osbuild/osbuild/pull/876
> osbuild2: update rhsm stage

- cmd/osbuild-composer/composer.go
- cmd/osbuild-composer/config.go
- templates/composer.yml
- test/cases/api.sh
By default, pgxpool.Pool has 4 connections (or number of cpus if higher).
Currently, we have 3 replicas, that means max 3*4=12 DB connections.
The dequeue operation is actually blocking - when a worker is waiting for
a job, one connection is blocked. My theory is that with 16 workers, we just
don't have enough connections that causes all sorts of weird slowdowns.
This commit bumps the number of connection from one replica to 10, therefore
we should be at 30 connections in total.
> templates: bump max postgres connections to 10

- templates/composer.yml
We actually need 2 * 16 connections at minimum (one worker waits for two
jobs). Let's bump the maximum connection count even moar.
> template: bump postgres max conns to 20

- .gitlab-ci.yml
- internal/cloudapi/v2/v2.go
We need rhel8.5+ testing.
This reverts commit ac39dacfae8c6e74429da258aed18a788a129c34.
> Revert ".gitlabci.yml: Reduce api test runners"

- .gitlab-ci.yml
- Makefile
- cmd/osbuild-composer-manifest-tests/main_test.go
- internal/distro/distro_test.go
- internal/distro/distro_test_common/distro_test_common.go
- internal/distro/rhel86/package_sets.go
- internal/distro/rhel90/package_sets.go
- osbuild-composer.spec
- test/cases/manifest_tests.sh
- Introduce a new test case checking manifests of all supported combinations of image types against manifests which are part of image test cases, including depsolving of default image's package sets. Depsolving is important to catch unintentional changes in image's package sets. Run the test case in CI. all manifests are verified on a single runner within a single job, because the depsolving should not care about the system distribution. However if needed, the test case could be split to verify manifests of a specific distribution on the same distribution. The single CI job currently take a little over 12 minutes to finish (the test itself takes approximately 419 seconds).
- Fix one issue in the `rhel-86` `image-installer` image type, found by the new test case.
- Fix one issue in the …
> Test all manifests with depsolved package sets 

- internal/osbuild2/selinux_stage.go
- internal/osbuild2/stage_test.go
This was added in osbuild: https://github.com/osbuild/osbuild/pull/875
Introduce the same option in composer and make it optional by specifying
it as a pointer to bool value. It would work the same even if it was
there every time, but as it should be an edge case, don't use it
everywhere. Also osbuild doesn't require it to be present, so it seems
like the right thing to do.
> osbuild2: selinux stage - introduce force_autorelabel option

- internal/distro/rhel90/distro.go
- internal/distro/rhel90/package_sets.go
- test/data/manifests/rhel_90-aarch64-ami-boot.json
- test/data/manifests/rhel_90-aarch64-ec2-boot.json
- test/data/manifests/rhel_90-x86_64-ami-boot.json
- test/data/manifests/rhel_90-x86_64-ec2-boot.json
- test/data/manifests/rhel_90-x86_64-ec2_ha-boot.json
- test/data/manifests/rhel_90-x86_64-ec2_sap-boot.json
Add TuneD package to the base package set for all EC2 image types,
including the `ami` image type. In addition to installing the package,
also enable the service by default. TuneD will by default auto-detect
the environment in which the image is running and set the most
appropriate TuneD profile, with exception of the `ec2-sap` image, which
explicitly sets a specific TuneD profile.
This change affects the `ami`, `ec2`, and `ec2-ha` image types on all
supported architectures.
Regenerate affected image test cases.
Related to RHELPLAN-102615
Fix #1972
> RHEL-9.0: install and enable TuneD by default on all EC2 images

- docs/news/unreleased/centos-8-update.md
- docs/news/unreleased/log-options.md
The doc/news directory has been re-added by some recent PRs, but it is
not used any more since [1]. Clean up the repository of the unused
files.
[1] https://github.com/osbuild/osbuild-composer/pull/1933
> Doc: remove unused doc/news directory

- osbuild-composer.spec
This change was tested by running:
```
$ rpm --eval '
%global noepoch 42
%{?epoch:%epoch:}
'
$ rpm --eval '
%global epoch 42
%{?epoch:%epoch:}
'
42:
```
Fixes #2054
> spec: add epoch to nevra only if it's set

- cmd/osbuild-worker/main.go
- internal/jobqueue/dbjobqueue/dbjobqueue.go
Two logging adjustments:
* worker: normalize job logging
The format is now always 'JOB_ID' (JOB_TYPE). This means that we also know
the job type when a job is finished or when it failed.
* dbjobqueue: don't log when context's deadline was exceeded
This happens rather often as we limit the request job timeout to 20s on the
service.
> Two minor logging improvements

- .gitlab-ci.yml
Jobs that don't interact with clouds can be canceled at any time without
the risk of leaving unused resources in the cloud. This enables the use
of "automatic cancellation of redundant pipelines" which means that if
and update is pushed to an open PR the current running pipeline is
canceled. This is done by adding an "interruptible" flag to the jobs.
Default value is false so only jobs that have it explicitly set to true
will be canceled.
It should help reduce stress on the CI in some cases.
> ci: make some jobs interruptible

- internal/kojiapi/server.go
We have been actually unmarshalling into a wrong datatype for a year, by
fixing this, we should get much more logging in Brew.
> api/koji: fix /compose/log route

- Makefile
- cmd/osbuild-composer-dbjobqueue-tests/main_test.go
- cmd/osbuild-service-maintenance/aws.go
- cmd/osbuild-service-maintenance/config.go
- cmd/osbuild-service-maintenance/gcp.go
- cmd/osbuild-service-maintenance/main.go
- cmd/osbuild-upload-aws/main.go
- cmd/osbuild-worker/jobimpl-osbuild.go
- distribution/Dockerfile-ubi-maintenance
- go.mod
- go.sum
- internal/boot/aws.go
- internal/cloud/awscloud/awscloud.go
- internal/cloud/gcp/compute.go
- internal/cloudapi/v2/v2.go
- internal/jobqueue/dbjobqueue/dbjobqueue.go
- tools/appsre-build-deploy.sh
- vendor/golang.org/x/sync/AUTHORS
- vendor/golang.org/x/sync/CONTRIBUTORS
- vendor/golang.org/x/sync/LICENSE
- vendor/golang.org/x/sync/PATENTS
- vendor/golang.org/x/sync/semaphore/semaphore.go
- vendor/modules.txt
Example (dry) run with modified cutoff so it captured all images and some testing  jobtypes in the queue:
[service-maintenance-dryrun.txt](https://github.com/osbuild/osbuild-composer/files/7619530/service-maintenance-dryrun.txt)
---
Though the DB functions are unit tested, that's pretty much it. I'd like to enable this with dryrun enabled for a while to see how it behaves, and then once we feel confident about it, set dryrun to false. Opinions/thoughts welcomed :)
I wonder if we should make the criteria of selceting images on the target cloud platforms stricter? Like for AWS we check by tag; for GCP I just assume all images in the account are from IB.
> osbuild-service-maintenance: Clean up expired images

- templates/dashboards/grafana-dashboard-image-builder-composer-general.configmap.yml
- [ N/A ] adequate testing for the new functionality or fixed issue
- [ X ] adequate documentation informing people about the change such as
- [ N/A ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/
This PR makes several changes to the Image-Builder-Composer Grafana dashboard:
* Changes the Grafana variable “latency_slo” from 0.9 to 0.95. 
* Adds 0.5 and 0.99 percentiles to the latency panel
* Adds a success vs errors 'compose throughput rate' panel
* Adds a 'slow request rate' panel, tracking the rate of requests with excessive response times
* Changes all prometheus queries to use the variable '$interval' instead of '$__range' (except for the …
> Image Builder Composer - Grafana dashboard Updates

- test/README.md
- tools/test-case-generators/generate-all-test-cases
Add `--build-rpms` option which will make the script build osbuild-composer
RPMs on the remote runner from the sources which were copied over. These
RPMs are then installed on the system, before any image test cases are
generated.
This PR should provide a viable workaround for the necessary transition period when `dnf-json` as a service is merged (PR #2062)
> generate-all-test-cases: add `--build-rpms` option

- internal/jobqueue/dbjobqueue/dbjobqueue.go
- internal/prometheus/job_metrics.go
Add job metrics to track the number of pending/running jobs, the duration of the jobs and how long the jobs spent in
the job queue.
This is based on this commit https://github.com/teg/osbuild-composer/commit/b00451a175508200abcbd1ff1c9e68726b6e24c9 
Edit: Success/Error rate will be done in a follow up PR.
> Job metrics

- osbuild-composer.spec
RHEL gating requires all binaries to be built with PIE.
Just build everything with PIE unconditionally.
Verified with `annocheck`.
> spec: build all binaries with PIE

- test/cases/regression-composer-works-behind-satellite.sh
- test/cases/regression-excluded-dependency.sh
- test/cases/regression-include-excluded-packages.sh
- test/cases/regression-old-worker-new-composer.sh
The biggest fix is that the tests are now cleaning up after themselves which currently blocks RHEL CI.
> Regression test fixes

- .github/workflows/release.yml
Passing the webhook URL is necessary because GH composite actions don't
support handling secrets.
See also https://github.com/osbuild/release-action/pull/3
[skip ci]
> release-action: Send notification to our Slack channel

- schutzbot/scheduled_cloud_cleaner.sh
- test/cases/api.sh
Scheduled cloud cleaner only works in azure and aws. This PR extends this functionality to GCP. To do so, we have to tag every gcp testing resource with "gitlab-ci-test". 
> Extend scheduled cloud cleaner to GCP

- templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
Add an initial dashboard for the job metrics. For now, the dashboard includes graphs and
burn rates for osbuild job duration and depsolve job duration
Temporary dashboard can be found [here](https://grafana.stage.devshift.net/d/y8lhL9hnz_test/image-builder-worker-test?orgId=1&var-datasource=app-sre-stage-01-prometheus&var-interval=1h&var-stability_slo=0.95&var-latency_slo=0.9&from=now-1h&to=now)
> templates: add worker dashboard

- .gitlab-ci.yml
- schutzbot/start_iostats.sh
- schutzbot/stop_iostats.sh
iostat from package sysstat reveales itself quite useful to debug performance issues. I've been using it a lot lately and thought it could be nice to have it enabled by default in the CI.
> Tracing: measure IO during each job

- cmd/osbuild-composer/composer.go
- cmd/osbuild-composer/config.go
- cmd/osbuild-composer/config_test.go
- templates/composer.yml
- test/cases/api.sh
When backed by a DB, composer has no need of a queue or artifact directory.
This also addresses "Error moving artifacts for job" logging noise when using a dbqueue.
> composer: Only set queue and artifact dir for fsqueue

- internal/osbuild2/dnf_automatic_config_stage.go
- internal/osbuild2/dnf_automatic_config_stage_test.go
- internal/osbuild2/pam_limits_conf_stage.go
- internal/osbuild2/sshd_config_stage.go
- internal/osbuild2/sshd_config_stage_test.go
- internal/osbuild2/stage.go
- internal/osbuild2/stage_test.go
- internal/osbuild2/yum_repos_stage.go
- internal/osbuild2/yum_repos_stage_test.go
- osbuild2: support `PermitRootLogin` in sshd.config stage
- osbuild2: support `org.osbuild.yum.repos` stage
- osbuild2: support `org.osbuild.dnf-automatic.config` stage
> Add support for new osbuild stages needed for GCE image

- internal/distro/rhel84/distro_v2.go
- internal/distro/rhel85/pipelines.go
- internal/distro/rhel86/pipelines.go
- internal/distro/rhel90/pipelines.go
- internal/distro/rhel90beta/pipelines.go
- internal/osbuild2/stage_test.go
- internal/osbuild2/sysconfig_stage.go
The `Kernel` and `Network` members of the sysconfig stage options
structure were previously not declared as pointers. As a result, they
always appeared in the resulting JSON object, even though they were
empty. Use pointers to ensure that the members are omitted from the
resulting JSON object, if they were not defined.
> osbuild2: ensure that empty sysconfig options members are omitted

- test/cases/azure.sh
During manual cleanup of unused resources, the storage account can get
removed. The current storage account is not possible to remove
manually, but adding this check to make it more resilient in future
scenarios.
> test: make test more resilient

- internal/jobqueue/dbjobqueue/dbjobqueue.go
> dbjobqueue: fix FinishJob not returning an error if already finished

- cmd/osbuild-auth-tests/certificates.go
These tests can be run only in our CI environment, and not as pure unit tests
launched by go test ./... Let's make sure that all files that belong to these
tests are properly marked with build constraints.
This should fix the following error in Coverity Scan runs:
runtime.main_main·f: function main is undeclared in the main package
Warning:  Build command go build -o bin/ ./... exited with code 2. Please verify that the build completed successfully.
See https://github.com/osbuild/osbuild-composer/runs/4427232580?check_suite_focus=true
> osbuild-auth-tests: add a build constraint also to certificates.go

- tools/test-case-generators/generate-all-test-cases
Use `make scratch` for building RPMs without tests. This fixes the case,
when the RPM build with test fails to build due to changes in image
manifests. The whole reason of running the script is to regenerate image
test cases when the manifest changed, so this was a chicken and egg
problem.
No CI testing is needed, as this is a development tool.
> generate-all-test-cases: use `make scratch` for building RPMs

- internal/osbuild2/tar_stage.go
- internal/osbuild2/tar_stage_test.go
Bring the Tar stage implementation on par with the current osbuild
schema. Specifically add the 'format' and 'root-node' options to the
stage options structure.
Add stage options validation along with appropriate unit tests.
> osbuild2: support 'format' and 'root-node' Tar stage options

- internal/weldr/api.go
Prevents a nil panic, see rhbz#2035956
> weldr: return an error if host distro wasn't found in distro registry

- templates/packer/README.md
- templates/packer/ansible/roles/common/files/worker-initialization-scripts/offline_token.sh
- templates/packer/ansible/roles/common/files/worker-initialization-scripts/set_hostname.sh
- templates/packer/ansible/roles/common/files/worker-initialization-scripts/subscription_manager.sh
- templates/packer/ansible/roles/common/files/worker-initialization-scripts/vector.sh
- templates/packer/ansible/roles/common/files/worker-initialization-scripts/worker_external_creds.sh
- templates/packer/ansible/roles/common/files/worker-initialization-scripts/worker_service.sh
- templates/packer/ansible/roles/common/files/worker-initialization.service
- templates/packer/ansible/roles/common/tasks/main.yml
- templates/packer/ansible/roles/common/tasks/worker-initialization-service.yml
- templates/packer/ansible/roles/common/templates/monitrc.j2
- templates/packer/composer.pkr.hcl
Three commits:
- bump the RHEL version to 8.5
- move configuration scripts from terraform to packer
- remove a broken monit check
The most important is the move of configuration. Previously, we had a huge cloud-init user-data configuration. With this change, all this configuration now lives inside the image and cloud-init must only provide a static file with several values. This should greatly help with testability.
The new image was tested manually and it's awesome. I also added some docs.
> Packer improvements

- test/cases/regression-composer-works-behind-satellite-fallback.sh
- test/cases/regression.sh
The test script regression-composer-works-behind-satellite.sh should be split in two parts to make it more visible and also because it contains two scenarios that are independent.
> test: split test script regression behind satellite

- .gitlab-ci.yml
this test was disabled because it blocked CI, to be solved later. See
[COMPOSER-1118](https://drive.google.com/file/d/10XamNYu7lOpDUcfvBUm8sW51JL3eO_QI/view)
Related [PR](https://github.com/osbuild/osbuild-composer/pull/1758)
> ci: enable zure testing on centos-8

- tools/appsre-build-worker-packer.sh
CI is also defined on appsres infra, and is also true. Use CI_COMMIT_SHA
instead to determine if we're running from a PR or not.
> tools/appsre-build-worker-packer: Use CI_COMMIT_SHA

- internal/distro/image_config.go
- internal/distro/image_config_test.go
- internal/distro/rhel86/distro.go
- internal/distro/rhel86/package_sets.go
- internal/distro/rhel86/pipelines.go
- internal/distro/rhel90/distro.go
- internal/distro/rhel90/package_sets.go
- internal/distro/rhel90/pipelines.go
- test/data/manifests/centos_8-aarch64-ami-boot.json
- test/data/manifests/centos_8-aarch64-qcow2-boot.json
- test/data/manifests/centos_8-aarch64-qcow2_customize-boot.json
- test/data/manifests/centos_8-ppc64le-qcow2-boot.json
- test/data/manifests/centos_8-ppc64le-qcow2_customize-boot.json
- test/data/manifests/centos_8-x86_64-ami-boot.json
- test/data/manifests/centos_8-x86_64-image_installer-boot.json
- test/data/manifests/centos_8-x86_64-qcow2-boot.json
- test/data/manifests/centos_8-x86_64-qcow2_customize-boot.json
- test/data/manifests/rhel_86-aarch64-ami-boot.json
- test/data/manifests/rhel_86-aarch64-ec2-boot.json
- test/data/manifests/rhel_86-x86_64-ami-boot.json
- test/data/manifests/rhel_86-x86_64-ec2-boot.json
- test/data/manifests/rhel_86-x86_64-ec2_ha-boot.json
- test/data/manifests/rhel_86-x86_64-ec2_sap-boot.json
- test/data/manifests/rhel_90-aarch64-ami-boot.json
- test/data/manifests/rhel_90-aarch64-ec2-boot.json
- test/data/manifests/rhel_90-x86_64-ami-boot.json
- test/data/manifests/rhel_90-x86_64-ec2-boot.json
- test/data/manifests/rhel_90-x86_64-ec2_ha-boot.json
- test/data/manifests/rhel_90-x86_64-ec2_sap-boot.json
- Reduce `osPipeline` variants (`ec2BaseTreePipeline`, `osPipeline` and `ostreeTreePipeline`) to a single `osPipeline`, which handles all the potential OS customizations. Nevertheless there are still other pipeline functions which handle pieces of customizations (mostly related to EDGE images).
- Do not hardcode any default configuration values in the `osPipeline` to prevent us from having to introduce yet another variant of the function in case a new image type needs different defaults (e.g. timezone or keyboard layout).
- Introduce a new data structure `ImageConfig`, which holds the default configuration values for a specific image. There are however still some configuration values left in the `imageType` structure, which could be moved to the `ImageConfig` structure.
- The …
> RHEL-86/90: refactoring of `osPipeline` and its variants

- templates/packer/ansible/roles/common/tasks/packages.yml
Lower priority means higher, currently the images built through AppSRE's
infra install the worker from epel.
> templates/packer: Correct priority for worker rpms

- templates/dashboards/grafana-dashboard-image-builder-composer-general.configmap.yml
- templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
This way we get a nice URL `.../d/image-builder-(composer|worker)`.
> templates/dashboards: Fixed grafana uids

- .gitlab-ci.yml
This is executed from osbuild's CI triggers but doesn't run against nightly trees so adding it here.
Note: The issue reference in the comment may be related to this test failing on 9.0. It's been disabled inside the osbuild repository. 
NOTE: needed to verify https://bugzilla.redhat.com/show_bug.cgi?id=2002724#c6
> Add Image Tests to nightly pipelines

- test/cases/filesystem.sh
- the /var/log/audit mountpoint has been added previously to the
blueprint but wasn't explicitly checked
- reordered the list of mountpoints to match the blueprint
(alphabetically)
- added logging of successfull results we that QE can see what has been
tested in the logs and use it for verification purposes.
Related: rhbz#2002727, rhbz#2001891
> tests: Add missing /var/log/audit to explicit checks

- test/cases/koji.sh
> tests: Don't execute koji.sh inside nightly CI pipelines

- cmd/osbuild-worker/jobimpl-osbuild.go
Issues caused by rebase-merge:
- Error handling was changed in one PR
- Errors using the old method were introduced in another
> osbuild-worker: change error handling for OCI upload

- cmd/osbuild-worker/jobimpl-osbuild-koji.go
- internal/kojiapi/server.go
It seems that during the "Worker errors backwards compatibility" work an error check got inverted, leading to `osbuild` not actually being run in the koji job. Sadly this was not uncovered by CI since our overall status reporting was also not complete and ignored build job results with empty `buildResult.OSBuildOutput` fields. See e.g. the CI job [2023038227]( https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/2023038227#L2605): 
```
success
Compose worked!
{"image_statuses":[{"status":"failure"},{"status":"failure"}],"koji_build_id":1,"koji_task_id":0,"status":"success"}
```
> Kojiapi: fix error check in koji job

- .gitlab-ci.yml
- schutzbot/scheduled_cloud_cleaner.sh
- test/cases/vmware.sh
Currently scheduled cloud cleaner only takes care of azure, aws and gcp resources. Extend this functionality to vmware.
To do so, tag every vmware resource with "gitlab-ci-tag". And then remove the old enough ones in scheduled cloud cleaner.
> Extend scheduled cloud cleaner to vmware

- internal/distro/rhel86/partition_tables.go
- test/data/manifests/centos_8-aarch64-ami-boot.json
- test/data/manifests/rhel_86-aarch64-ami-boot.json
- test/data/manifests/rhel_86-aarch64-ec2-boot.json
It should be `1048576` (exactly 512 MiB), like it is for all other distributions. It somehow got mingled in when the distribution was forked off from 8.5/9.0 beta (1048676 to 1048576 strongly suggests a `sed` command was involved, so we blame that).
> distro/rhel86: fix ec2 boot partition for arm64

- cmd/osbuild-mock-openid-provider/main.go
According to (rfc6749)[https://datatracker.ietf.org/doc/html/rfc6749#section-3.3] the `token_type` is required. Additionally, allow setting `expires_in` and `scope`.
> Mock OpenID: add token type, expires in and scope fields

- cmd/osbuild-composer/composer.go
- cmd/osbuild-composer/config.go
- internal/auth/jwt_auth_handler.go
We may need to use several SSO providers, so extend our
configuration to allow that.
Based on PoC from Sanne:
```
package main
import (
"net/http"
"log"
"github.com/openshift-online/ocm-sdk-go/authentication"
"github.com/openshift-online/ocm-sdk-go/logging"
)
type H struct{}
func (h *H) ServeHTTP(w http.ResponseWriter, r *http.Request) {
log.Println("HURRAY")
}
func main() {
logBuilder := logging.NewGoLoggerBuilder()
logger, err := logBuilder.Build()
if err != nil {
panic(err)
}
aH, err := authentication.NewHandler().
KeysURL("https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/certs").
KeysURL("https://identity.api.openshift.com/auth/realms/rhoas/protocol/openid-connect/certs").
Logger(logger).Next(&H{}).Build()
if err != nil {
panic(err)
} …
```
> jwt: support multiple key providers

- internal/distro/rhel90/package_sets.go
- internal/distro/rhel90/stage_options.go
- test/data/manifests/rhel_90-x86_64-image_installer-boot.json
Cherry-picked from @runcom's PR (thank you Antonio).  I think it's better to isolate this change and merge it separately.
Quoting a comment from @nullr0ute that adds relevant context: https://github.com/osbuild/osbuild-composer/pull/1884/commits/c108d7d0a63ed405ab4ba33db17547ec0e1ebd0a#r787575502
> For reference, and this is perfectly fine, the reason the ia32 grub2/shim gets pulled in by default there's been a number of very bad devices that are 64bit but with 32bit firmware and those are needed to boot it and then the kernel runs 64 bit. I doubt we'll need to ever support such a device but I'm adding this comment for reference.
----
> RHEL 9.0: Drop IA32

- .packit.yaml
Fedora Copr has native s390x builders now:
https://lists.fedoraproject.org/archives/list/copr-devel@lists.fedorahosted.org/message/AR3ZDKET3EXZHV3MSU3UHMO7EIKBGAN2/
> packit: re-enable builds for s390x architecture
